// Los quince niveles del modo portales.
//
// LO ESCRIBE armar_mapas.py: no se edita a mano. Cada nivel son 22 por 34
// caracteres y una fila a la que le falte uno corre el mapa entero una columna
// a partir de ahí, sin que se note leyéndolo.
//
//   #  pared por la que SE PUEDE disparar     X  pared negra: rebota el tiro
//   S  dónde aparecen    E  la salida         ^  púas    ~  gelatina
//   =  resorte           o  chatarra          B  placa   D  puerta
export const NIVELES_P = [
  { nombre: "Del otro lado", pista: "Tocá para disparar. Hacen falta los dos portales.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X          #         X",
    "X          #         X",
    "X          #         X",
    "X          #    o    X",
    "X          #         X",
    "X          #         X",
    "X          #         X",
    "X  S       #       E X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "El pozo", pista: "Las púas duelen aunque llegues despacio.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X         ###        X",
    "X         ###        X",
    "X         ###        X",
    "X         ###   o    X",
    "X         ###        X",
    "X         ###        X",
    "X  S      ###      E X",
    "X####^^^^^###^^^^^###X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Impulso", pista: "Caer por un portal conserva la velocidad.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                 ###X",
    "X                 #E#X",
    "X                 ###X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X  S                 X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####     o    #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Techo", pista: "Si tirás al techo de allá, caés de allá.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X  S        #        X",
    "X#####      #        X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #   o    X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #        X",
    "X           #   E    X",
    "X           #########X",
    "X           #        X",
    "X^^^^^^^^^^^#^^^^^^^^X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "El peso de Tito", pista: "La placa se aprieta con peso. Tenés uno colgando.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X         #          X",
    "X         #          X",
    "X         #          X",
    "X         #          X",
    "X         #     o    X",
    "X         #          X",
    "X         #  DDD     X",
    "X  S   B  #  DDD   E X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Gelatina", pista: "Adentro del verde todo va en cámara lenta.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X  S                 X",
    "X#####               X",
    "X          #         X",
    "X          #         X",
    "X      ~~~~#         X",
    "X      ~~~~#         X",
    "X      ~~~~#         X",
    "X      ~~~~#    o    X",
    "X      ~~~~#         X",
    "X          #         X",
    "X          #         X",
    "X          #         X",
    "X          #         X",
    "X          #         X",
    "X          #         X",
    "X          #     E   X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Pared negra", pista: "En lo negro el disparo rebota. Buscá otra cara.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X         XXX        X",
    "X         XXX        X",
    "X         XXX        X",
    "X         XXX   o    X",
    "X         XXX        X",
    "X         ###        X",
    "X         ###        X",
    "X  S      ###      E X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Dos placas", pista: "Las dos a la vez, y sos uno solo.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X        #           X",
    "X        #           X",
    "X        #      o    X",
    "X        #           X",
    "X        #           X",
    "X        #    DDDD   X",
    "X        #    DDDD   X",
    "X  S  B  #  B      E X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "El resorte", pista: "Lo verde te devuelve para arriba.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X  ##                X",
    "X  #E                X",
    "X  ###          o    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X  S                 X",
    "X#######     ========X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Torre", pista: "Para arriba también se puede.", mapa: [
    "X####################X",
    "X               #####X",
    "X               #####X",
    "X  E            #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####     o    #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####          #####X",
    "X#####     S    #####X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Vaivén", pista: "Entrás por una cara y salís por la de al lado.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X     #########      X",
    "X     #########      X",
    "X     #########      X",
    "X     #########      X",
    "X  S  #########      X",
    "X#############       X",
    "X             #      X",
    "X      o      #      X",
    "X             #      X",
    "X             #      X",
    "X             #  E   X",
    "X             #######X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Las dos púas", pista: "No hay piso limpio en el medio.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X       ######       X",
    "X       ######       X",
    "X       ######       X",
    "X       ######  o    X",
    "X       ######       X",
    "X       ######       X",
    "X  S    ######     E X",
    "X###^^^^######^^^^###X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "El desvío", pista: "La placa está en un pozo. Alguien tiene que caer ahí.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X  S                 X",
    "X#########    #######X",
    "X        #    #      X",
    "X        #    #      X",
    "X        #    #      X",
    "X        #    #  o   X",
    "X        #    #      X",
    "X        #    #      X",
    "X        ######      X",
    "X        #    #      X",
    "X   DDD  #    #      X",
    "X   DDD  #  B #      X",
    "X E DDD  ######      X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "Caída larga", pista: "Cuanto más alto entrás, más lejos salís.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X        S           X",
    "X       #####        X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                   #X",
    "X                   #X",
    "X###                #X",
    "X###                #X",
    "X#E                 #X",
    "X###                #X",
    "X###                #X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
  { nombre: "El último puente", pista: "Todo junto. Suerte.", mapa: [
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X              XXXXXXX",
    "X              XXXXXXX",
    "X  S           XXXXXXX",
    "X#######       XXXXXXX",
    "X              XXXXXXX",
    "X      ~~~~    XXXXXXX",
    "X      ~~~~          X",
    "X      ~~~~     o    X",
    "X      ~~~~          X",
    "X              ######X",
    "X              ######X",
    "X   #####      ######X",
    "X   #####      ######X",
    "X   #####   B  ######X",
    "X   #####DDDD########X",
    "X   #####DDDD        X",
    "X   #####        E   X",
    "X####################X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X                    X",
    "X####################X",
  ] },
];
