// ─────────────────────────────────────────────────────────────────────────────
// EL IDIOMA: español o inglés. Todo el juego se escribe en español y se traduce AL DIBUJAR (con
// tr()), así cambiar de idioma en el menú cambia todo al instante, hasta lo que ya está en
// pantalla. Los lemas de los objetos, en inglés, van con el tono del original ("DMG UP",
// "TEARS UP"…). Se recuerda la elección; la primera vez, se usa el idioma del teléfono.
// ─────────────────────────────────────────────────────────────────────────────

let IDIOMA = "es";
try { IDIOMA = localStorage.getItem("shumio-idioma") || ((navigator.language || "es").toLowerCase().startsWith("es") ? "es" : "en"); } catch (e) { /* sin guardar */ }
function cambiarIdioma() {
  IDIOMA = IDIOMA === "es" ? "en" : "es";
  try { localStorage.setItem("shumio-idioma", IDIOMA); } catch (e) { /* sin guardar */ }
}

const EN = {
  // ── los menús ──
  "TOCÁ PARA EMPEZAR": "TAP TO START", "ENTER O CLIC": "PRESS ENTER OR CLICK", "NUEVA PARTIDA": "NEW RUN",
  "PANTALLA COMPLETA": "FULL SCREEN", "SALIR DE PANTALLA COMPLETA": "EXIT FULL SCREEN", "CÓMO SE JUEGA": "HOW TO PLAY",
  "VOLVER": "BACK", "SEGUIR": "RESUME", "SALIR": "QUIT", "OTRA VEZ": "TRY AGAIN", "AL MENÚ": "MAIN MENU", "PAUSA": "PAUSED",
  "PULGAR IZQUIERDO: CAMINAR": "LEFT THUMB: WALK", "PULGAR DERECHO: LLORAR (4 LADOS)": "RIGHT THUMB: CRY (4 WAYS)",
  "BOTÓN GRANDE: BOMBA": "BIG BUTTON: BOMB", "ARRIBA: OBJETO ACTIVO": "TOP: ACTIVE ITEM", "AL LADO: CÁPSULA": "NEXT TO IT: PILL",
  "WASD: CAMINAR": "WASD: WALK", "FLECHAS: LLORAR": "ARROWS: CRY", "E: BOMBA   Q: CÁPSULA": "E: BOMB   Q: PILL",
  "ESPACIO: OBJETO ACTIVO": "SPACE: ACTIVE ITEM", "ESC: PAUSA": "ESC: PAUSE",
  "LIMPIÁ LAS SALAS, BAJÁ 4 PISOS Y": "CLEAR THE ROOMS, GO DOWN 4 FLOORS", "HACÉ QUE MICELIA DEJE DE LLORAR.": "AND MAKE MICELIA STOP CRYING.",
  "MI ÚLTIMA VOLUNTAD": "MY LAST WILL", "POR CULPA DE:": "KILLED BY:", "LA HUMEDAD": "THE DAMP",
  "Y LE DEJO MIS COSAS A MI HONGO:": "MY STUFF GOES TO MY MUSHROOM:", "(NO TENÍA NADA)": "(I HAD NOTHING)",
  "¡LO LOGRASTE!": "YOU DID IT!", "MICELIA YA NO LLORA.": "MICELIA CRIES NO MORE.", "SHUMIO TAMPOCO.": "NEITHER DOES SHUMIO.",
  "GIRÁ EL TELÉFONO": "TURN YOUR PHONE", "SHUMIO": "SHUMIO",
  // el tutorial dibujado en el piso
  "MOVERSE": "MOVE", "LLORAR": "CRY", "BOMBA": "BOMB", "OBJETO": "ITEM", "ESPACIO": "SPACE", "IZQUIERDA": "LEFT", "DERECHA": "RIGHT",
  // mensajes del juego
  "¡OTRA VIDA!": "EXTRA LIFE!", "¡MICELIA CAYÓ!": "MICELIA HAS FALLEN!", "Abrí el cofre": "Open the chest", "UNA CÁPSULA": "A PILL",
  // ── los pisos, las maldiciones, los jefes y los bichos (también son "la causa" de la muerte) ──
  "SÓTANO HÚMEDO I": "DAMP BASEMENT I", "SÓTANO HÚMEDO II": "DAMP BASEMENT II", "LAS RAÍCES I": "THE ROOTS I", "LAS RAÍCES II": "THE ROOTS II",
  "¡Maldición del ciego!": "Curse of the Blind!", "¡Maldición de la oscuridad!": "Curse of Darkness!", "¡Maldición del extraviado!": "Curse of the Lost!", "¡Maldición de lo desconocido!": "Curse of the Unknown!",
  "MADRE BABOSA": "MOTHER SLUG", "REY MOSQUÍN": "GNAT KING", "GUSANO ANILLADO": "RINGED WORM", "MICELIA": "MICELIA",
  "LA MADRE BABOSA": "THE MOTHER SLUG", "EL REY MOSQUÍN": "THE GNAT KING", "EL GUSANO ANILLADO": "THE RINGED WORM",
  "UN MOSQUÍN": "A GNAT", "UN MOSQUÍN ROJO": "A RED GNAT", "UN HONGÓN": "A FUNGOON", "UNA BABOSA": "A SLUG", "UN ESCUPIDOR": "A SPITTER",
  "UN SALTARÍN": "A HOPPER", "UN GUSANO": "A WORM", "UN BULBO": "A BULB", "UNA ARAÑITA": "A LITTLE SPIDER", "UN GRUMO": "A CLOT",
  "UNOS PINCHOS": "SOME SPIKES", "LA BABA": "THE SLIME", "EL FUEGO": "THE FIRE", "UNA BOMBA": "A BOMB", "UNA LÁGRIMA MALA": "AN EVIL TEAR",
  "TU PROPIA EXPLOSIÓN": "YOUR OWN EXPLOSION", "UN COFRE CON PINCHOS": "A SPIKED CHEST",
  // ── los objetos: nombre y lema ──
  "SOMBRERO ROJO": "RED CAP", "DAÑO ARRIBA": "DMG UP", "SETA PICANTE": "HOT MUSHROOM", "CAFÉ DE RAÍZ": "ROOT COFFEE", "LÁGRIMAS ARRIBA": "TEARS UP",
  "CEBOLLA TRISTE": "SAD ONION", "ZAPATILLAS": "SNEAKERS", "VELOCIDAD ARRIBA": "SPEED UP", "LUPA": "MAGNIFYING GLASS", "LÁGRIMAS GRANDES": "BIG TEARS",
  "TRÉBOL": "CLOVER", "SUERTE ARRIBA": "LUCK UP", "CORAZÓN DE PIEDRA": "STONE HEART", "VIDA ARRIBA": "HP UP", "RAÍZ VIEJA": "OLD ROOT",
  "OJO DE VIDRIO": "GLASS EYE", "ALCANCE ARRIBA": "RANGE UP", "LÁGRIMA DE PLOMO": "LEAD TEAR", "PESADA Y DOLOROSA": "HEAVY AND PAINFUL",
  "LENTE DE SANGRE": "BLOOD LENS", "DAÑO Y ALCANCE": "DMG + RANGE UP", "CAPARAZÓN": "SHELL", "TODO UN POCO ARRIBA": "A LITTLE BIT OF EVERYTHING UP",
  "MEDIA LUNA": "HALF MOON", "LÁGRIMAS Y SUERTE": "TEARS + LUCK UP", "HONGO GIGANTE": "GIANT MUSHROOM", "¡TODO ARRIBA!": "ALL STATS UP!",
  "HONGO AZUL": "BLUE CAP", "VIDA Y LÁGRIMAS": "HP + TEARS UP", "HONGUITO": "TINY SHROOM", "CHIQUITO Y VELOZ": "SMALL AND FAST",
  "HONGO RARO": "ODD MUSHROOM", "LÁGRIMAS ARRIBA, DAÑO ABAJO": "TEARS UP, DMG DOWN", "HONGO DE LA VIDA": "LIFE MUSHROOM", "UNA VIDA MÁS": "ONE MORE LIFE",
  "HORMONAS": "HORMONES", "DAÑO Y VELOCIDAD": "DMG + SPEED UP", "BOLA VELOZ": "SPEED BALL", "CABEZA DE GRILLO": "CRICKET'S HEAD",
  "DAÑO POR UNO Y MEDIO": "DMG TIMES 1.5", "PACTO DE SANGRE": "BLOOD PACT", "CUERNO": "HORN", "DAÑO MUCHO ARRIBA": "DMG WAY UP",
  "PENTAGRAMA": "PENTAGRAM", "LA MARCA": "THE MARK", "EL PACTO": "THE PACT", "DAÑO Y LÁGRIMAS": "DMG + TEARS UP", "SANGRE DEL MÁRTIR": "MARTYR'S BLOOD",
  "LA AUREOLA": "THE HALO", "TODO ARRIBA": "ALL STATS UP", "ROSARIO": "ROSARY", "FE Y LÁGRIMAS": "FAITH AND TEARS",
  "CORAZÓN SAGRADO": "SACRED HEART", "LÁGRIMAS BENDITAS QUE BUSCAN": "BLESSED HOMING TEARS",
  "LLANTO DE AZUFRE": "SULFUR SOBS", "¡RAYO DE SANGRE!": "BLOOD LASER!", "OJO MECÁNICO": "MECHANICAL EYE", "LÁGRIMAS LÁSER": "LASER TEARS",
  "ARO DE LUZ": "RING OF LIGHT", "ANILLOS LÁSER QUE SE CARGAN": "CHARGED LASER RINGS", "EMBRIÓN DE PÓLVORA": "GUNPOWDER EMBRYO", "¡LLORÁS BOMBAS!": "YOU CRY BOMBS!",
  "FETO DEL CIELO": "FETUS FROM ABOVE", "BOMBARDEO A DEMANDA": "ON-DEMAND AIRSTRIKE", "LÁGRIMA MANSA": "TAME TEAR", "UNA LÁGRIMA QUE OBEDECE": "A TEAR THAT OBEYS",
  "CUCHILLO DE LA ABUELA": "GRANDMA'S KNIFE", "FILOSO Y FIEL": "SHARP AND LOYAL", "TERCER OJO": "THIRD EYE", "TRES LÁGRIMAS": "TRIPLE SHOT",
  "ARAÑA MUTANTE": "MUTANT SPIDER", "CUATRO LÁGRIMAS": "QUAD SHOT", "LENTES BIFOCALES": "BIFOCALS", "LLANTO DOBLE": "DOUBLE SHOT",
  "OJO DE CÍCLOPE": "CYCLOPS EYE", "UNA LÁGRIMA ENORME": "ONE HUGE TEAR", "LECHE DE SOJA": "SOY MILK", "LLANTO SIN FIN": "ENDLESS CRYING",
  "LECHE DE ALMENDRA": "ALMOND MILK", "LLANTO SIN FIN, CON GUSANOS": "ENDLESS CRYING, WITH WORMS", "LECHE CHOCOLATADA": "CHOCOLATE MILK",
  "LÁGRIMAS QUE SE CARGAN": "CHARGE SHOTS", "PULMÓN DE BABOSA": "SLUG LUNG", "RÁFAGA CARGADA": "CHARGED BURST", "JARABE AMARGO": "BITTER SYRUP",
  "LÁGRIMAS QUE EXPLOTAN": "EXPLOSIVE TEARS", "COÁGULO": "CLOT", "REVIENTA EN PEDAZOS": "BURSTS TO PIECES", "OJOS SALTONES": "BULGING EYES",
  "DE CERCA DUELE MÁS": "HURTS MORE UP CLOSE", "TROZO DE CARBÓN": "LUMP OF COAL", "DE LEJOS DUELE MÁS": "HURTS MORE FROM AFAR",
  "OJO MUERTO": "DEAD EYE", "CADA ACIERTO SUMA": "EVERY HIT COUNTS", "OJO CAZADOR": "HUNTER EYE", "LÁGRIMAS QUE BUSCAN": "HOMING TEARS",
  "VELO": "VEIL", "LÁGRIMAS FANTASMA": "SPECTRAL TEARS", "FLECHA DE AMOR": "LOVE ARROW", "ATRAVIESA TODO": "PIERCING SHOTS",
  "GOMA ELÁSTICA": "RUBBER BAND", "LÁGRIMAS QUE REBOTAN": "BOUNCING TEARS", "PLANETITA": "TINY PLANET", "LÁGRIMAS EN ÓRBITA": "ORBITING TEARS",
  "MI REFLEJO": "MY REFLECTION", "LÁGRIMAS QUE VUELVEN": "BOOMERANG TEARS", "BUCLE": "LOOP", "LÁGRIMAS QUE DAN LA VUELTA": "WRAP-AROUND TEARS",
  "ANTIGRAVEDAD": "ANTI-GRAVITY", "LÁGRIMAS QUE ESPERAN": "TEARS THAT WAIT", "CUERPO DE GRILLO": "CRICKET'S BODY", "LÁGRIMAS QUE SE PARTEN": "SPLITTING TEARS",
  "PARÁSITO": "PARASITE", "LÁGRIMAS QUE SE DIVIDEN": "DIVIDING TEARS", "FRACTURA EXPUESTA": "COMPOUND FRACTURE", "LÁGRIMAS DE HUESO": "BONE TEARS",
  "ESPORA PEGAJOSA": "STICKY SPORE", "SE PEGA Y EXPLOTA": "STICKS AND EXPLODES", "RAÍZ ELÉCTRICA": "ELECTRIC ROOT", "LÁGRIMAS CON CHISPA": "SPARKING TEARS",
  "LUZ SANTA": "HOLY LIGHT", "RAYOS DEL CIELO": "LIGHT FROM ABOVE", "AMOR DURO": "TOUGH LOVE", "LÁGRIMAS CON DIENTES": "TOOTH TEARS",
  "EUTANASIA": "EUTHANASIA", "AGUJAS MORTALES": "DEADLY NEEDLES", "ESPORAS TÓXICAS": "TOXIC SPORES", "LÁGRIMAS VENENOSAS": "POISON TEARS",
  "PICADURA DE ARAÑA": "SPIDER BITE", "LÁGRIMAS QUE FRENAN": "SLOWING TEARS", "ESCARCHA": "FROST", "LÁGRIMAS DE HIELO": "ICE TEARS",
  "CHISPA": "SPARK", "LÁGRIMAS QUE QUEMAN": "BURNING TEARS", "MATERIA OSCURA": "DARK MATTER", "DAÑO Y MIEDO": "DMG UP + FEAR",
  "LENTES DE LA ABUELA": "GRANDMA'S GLASSES", "MIRADA DE PIEDRA": "STONE GAZE", "PERFUME DE LA ABUELA": "GRANDMA'S PERFUME", "LÁGRIMAS Y MIEDO": "TEARS UP + FEAR",
  "LABIAL DE LA ABUELA": "GRANDMA'S LIPSTICK", "ALCANCE Y AMOR": "RANGE AND LOVE", "TACOS DE LA ABUELA": "GRANDMA'S HEELS", "PISOTONES": "STOMP STOMP",
  "LÍQUIDO MISTERIOSO": "MYSTERIOUS LIQUID", "LÁGRIMAS QUE DEJAN BABA": "SLIMY TEARS", "CABEZA DEL TENDERO": "SHOPKEEPER'S HEAD", "LÁGRIMAS DE PLATA": "MONEY TEARS",
  "ATRACTOR EXTRAÑO": "STRANGE ATTRACTOR", "TODO VA A TUS LÁGRIMAS": "EVERYTHING COMES TO YOUR TEARS", "PISCIS": "PISCES", "LÁGRIMAS QUE EMPUJAN": "KNOCKBACK TEARS",
  "OJO DE BELIAL": "EYE OF BELIAL", "ATRAVIESA Y SE ENOJA": "PIERCES AND GETS ANGRY", "CABEZA DIVINA": "DIVINE HEAD", "LÁGRIMAS DIVINAS": "DIVINE TEARS",
  "EL VIRUS": "THE VIRUS", "TOCAR ES ENVENENAR": "TOUCH TO POISON", "ALAS DE POLILLA": "MOTH WINGS", "¡A VOLAR!": "YOU CAN FLY!",
  "PALOMA MUERTA": "DEAD DOVE", "VUELO Y LÁGRIMAS FANTASMA": "FLIGHT + SPECTRAL TEARS", "ESPÍRITU NOCTURNO": "NIGHT SPIRIT",
  "IMÁN": "MAGNET", "TODO VIENE A VOS": "EVERYTHING COMES TO YOU", "BRÚJULA": "COMPASS", "EL MAPA SE REVELA": "THE MAP IS REVEALED",
  "CASCO DE ESPORAS": "SPORE HELMET", "DOS CORAZONES DE ESPORA": "TWO SPORE HEARTS", "BOMBA GORDA": "FAT BOMB", "CINCO BOMBAS GRANDES": "FIVE BIG BOMBS",
  "MALDICIÓN PODRIDA": "ROTTEN CURSE", "BOMBAS VENENOSAS": "POISON BOMBS", "BOLSA DE MONEDAS": "BAG OF COINS", "VEINTICINCO MONEDAS": "TWENTY-FIVE COINS",
  "LLAVERO": "KEY RING", "CUATRO LLAVES": "FOUR KEYS", "COLA DE GATO": "CAT TAIL", "MÁS COFRES": "MORE CHESTS", "GATO MUERTO": "DEAD CAT",
  "NUEVE VIDAS": "NINE LIVES", "PÁJARO MUERTO": "DEAD BIRD", "VENGANZA ALADA": "WINGED REVENGE", "BEBÉ ARAÑA": "SPIDER BABY",
  "LA VENGANZA DE LAS ARAÑAS": "SPIDER REVENGE", "MOSCA AMIGA": "FRIENDLY FLY", "TE CUIDA LAS ESPALDAS": "HAS YOUR BACK", "ADMIRADORA": "ADMIRER",
  "UNA MOSCA QUE MUERDE": "A FLY THAT BITES", "CORONA DE MOSCAS": "CROWN OF FLIES", "ESCUDO ZUMBADOR": "BUZZING SHIELD", "ÁNGEL GUARDIÁN": "GUARDIAN ANGEL",
  "TE PROTEGE": "WATCHES OVER YOU", "BOLA DE PELOS": "HAIRBALL", "GIRA Y PEGA": "SPINS AND HITS", "HERMANITO": "LITTLE BROTHER",
  "UN AMIGUITO QUE LLORA": "A CRYING BUDDY", "HERMANITA": "LITTLE SISTER", "LLORA MÁS FUERTE": "CRIES HARDER", "BEBÉ DEMONIO": "DEMON BABY",
  "DISPARA SOLO": "SHOOTS ON ITS OWN", "ROBO-BEBÉ": "ROBO-BABY", "UN AMIGUITO CON LÁSER": "A BUDDY WITH A LASER", "ÍNCUBO": "INCUBUS",
  "COPIA TUS LÁGRIMAS": "COPIES YOUR TEARS", "GORDITO": "CHUBBY", "SE LANZA DE PANZA": "BELLY FLOP", "CEREBRO PODRIDO": "ROTTEN BRAIN",
  "IDEAS EXPLOSIVAS": "EXPLOSIVE IDEAS", "SANGUIJUELA": "LEECH", "CHUPA Y CURA": "SUCKS AND HEALS", "BOLSA DE CENTAVOS": "SACK OF PENNIES",
  "MONEDAS DE REGALO": "FREE MONEY", "LIBRO DE SETAS": "BOOK OF MUSHROOMS", "PODER PARA LA SALA": "POWER FOR THE ROOM", "DADO VIEJO": "OLD DIE",
  "REHACE EL DESTINO": "REROLL YOUR DESTINY", "FRASCO DE MOSQUINES": "JAR OF GNATS", "MOSCAS DE TU LADO": "FLIES ON YOUR SIDE", "LINTERNA": "LANTERN",
  "UNA LUZ QUE QUEMA": "A BURNING LIGHT", "MECHA ETERNA": "ETERNAL FUSE", "UNA BOMBA GRATIS": "A FREE BOMB", "GOTA DE ROCÍO": "DEWDROP",
  "CURA UN CORAZÓN": "HEALS ONE HEART", "NECRONOMICÓN": "NECRONOMICON", "LA MUERTE PARA TODOS": "DEATH TO ALL", "LIBRO DE LA REVELACIÓN": "BOOK OF REVELATIONS",
  "PROTECCIÓN REVELADA": "REVEALED PROTECTION", "LIBRO DE LAS SOMBRAS": "BOOK OF SHADOWS", "ESCUDO TEMPORAL": "TEMPORARY SHIELD", "LIBRO SANTO": "HOLY BOOK",
  "VUELO POR UN RATO": "FLIGHT FOR A WHILE", "TELEPATÍA PARA TONTOS": "TELEPATHY FOR DUMMIES", "LÁGRIMAS QUE PIENSAN": "THINKING TEARS",
  "MANUAL DEL ANARQUISTA": "ANARCHIST'S MANUAL", "BOMBAS PARA TODOS": "BOMBS FOR EVERYONE", "¡AAAAAH!": "AAAAAH!", "GRITO DE AZUFRE": "SULFUR SCREAM",
  "CONTROL REMOTO": "REMOTE CONTROL", "UN MISIL A PEDIDO": "A MISSILE ON DEMAND", "¡KAMIKAZE!": "KAMIKAZE!", "BOOM (A VOS NO)": "BOOM, BUT NOT ON YOU",
  "RELOJ DE ARENA": "HOURGLASS", "EL TIEMPO SE FRENA": "TIME SLOWS DOWN", "UNICORNIO CHIQUITO": "TINY UNICORN", "¡INVENCIBLE!": "INVINCIBLE!",
  "CABEZA DE TAMMY": "TAMMY'S HEAD", "LLANTO EN REDONDO": "CRYING ALL AROUND", "CABEZA DE GATO": "CAT HEAD", "MOSCAS AMIGAS": "FRIENDLY FLIES",
  "PATITA DE GATO": "CAT PAW", "CARNE POR ALMA": "FLESH FOR SOUL", "CABEZA PODRIDA": "ROTTEN HEAD", "TIRALA": "THROW IT",
  "CAJA DE ARAÑAS": "BOX OF SPIDERS", "ARAÑITAS AMIGAS": "FRIENDLY SPIDERS",
  // las baratijas
  "GUSANO ONDULADO": "WIGGLE WORM", "LÁGRIMAS EN ONDA": "WAVY TEARS", "GUSANO ANILLO": "RING WORM", "LÁGRIMAS EN ESPIRAL": "SPIRAL TEARS",
  "GUSANO GANCHO": "HOOK WORM", "LÁGRIMAS EN ZIGZAG": "ZIGZAG TEARS", "GUSANO PULSO": "PULSE WORM", "LÁGRIMAS QUE LATEN": "PULSING TEARS",
  "GUSANO CHATO": "FLAT WORM", "LÁGRIMAS ANCHAS": "WIDE TEARS", "OJITO ROSA": "PINKY EYE", "CLIP": "PAPER CLIP", "ABRE COFRES DORADOS": "OPENS GOLDEN CHESTS",
  "DEDO DE LA SUERTE": "LUCKY FINGER", "MÁS PREMIOS": "MORE REWARDS", "TENEDOR": "FORK", "COMÉ ALGO": "EAT SOMETHING", "GARRAPATA": "TICK",
  "LOS JEFES, MÁS DÉBILES": "WEAKER BOSSES", "PÁGINA PERDIDA": "MISSING PAGE", "EL DOLOR SE CONTAGIA": "PAIN IS CONTAGIOUS", "MONEDA TRAGADA": "SWALLOWED COIN",
  "DOLOR QUE PAGA": "PAIN THAT PAYS",
  // las transformaciones
  "¡HONGAZO!": "FUN GUY!", "Más hongo que nunca": "More mushroom than ever", "¡SERAFÍN!": "SERAPHIM!", "Alas y fe": "Wings and faith",
  "¡LEVIATÁN!": "LEVIATHAN!", "Alas oscuras": "Dark wings", "¡MISHI!": "KITTY!", "Nueve vidas de moscas": "Nine lives of flies",
  "¡BELCEBÚ!": "BEELZEBUB!", "El señor de las moscas": "Lord of the flies", "¡PODRIDO!": "ROTTEN!", "Dejás baba venenosa": "You leave poison slime",
  "¡PINCHADO!": "SPUN!", "Daño y velocidad": "Damage and speed", "¿SÍ, ABUELA?": "YES, GRANDMA?", "Un cuchillo te sigue": "A knife follows you",
  "¡SIAMÉS!": "CONJOINED!", "Lágrimas en diagonal": "Diagonal tears", "¡RATÓN DE BIBLIOTECA!": "BOOKWORM!", "A veces, doble": "Sometimes double",
  "¡BEBÉ ARAÑA!": "SPIDER BABY!", "Una araña amiga": "A friendly spider",
  // las cápsulas
  "¡LÁGRIMAS ARRIBA!": "TEARS UP!", "LÁGRIMAS ABAJO": "TEARS DOWN", "¡VELOCIDAD ARRIBA!": "SPEED UP!", "VELOCIDAD ABAJO": "SPEED DOWN",
  "¡ALCANCE ARRIBA!": "RANGE UP!", "ALCANCE ABAJO": "RANGE DOWN", "¡SALUD TOTAL!": "FULL HEALTH!", "MAL VIAJE": "BAD TRIP",
  "¡SUERTE ARRIBA!": "LUCK UP!", "SUERTE ABAJO": "LUCK DOWN", "BOMBAS POR LLAVES": "BOMBS ARE KEYS", "¡ESPORAS DE VIDA!": "SPORES OF LIFE!", "¡DAÑO ARRIBA!": "DMG UP!",
};
/** Los que empiezan igual y siguen con un número o un nombre ("TIEMPO 1:23", "ME MORÍ EN SÓTANO…"). */
const EN_PREFIJOS = [["MÚSICA ", "MUSIC "], ["EFECTOS ", "SOUND FX "], ["TIEMPO ", "TIME "], ["PARTIDAS ", "RUNS "], ["GANADAS ", "WINS "],
  ["PISO ", "FLOOR "], ["ME MORÍ EN ", "I DIED IN "], ["Te quedan ", "Lives left: "]];
const EN_SUFIJOS = [[" BICHOS", " CRITTERS"]];
/** Traduce un texto del juego al idioma elegido (si no está en el diccionario, queda como está). */
function tr(s) {
  if (IDIOMA === "es" || s == null) return s;
  s = String(s);
  if (EN[s] != null) return EN[s];
  for (const [a, b] of EN_PREFIJOS) if (s.startsWith(a)) return b + tr(s.slice(a.length));
  for (const [a, b] of EN_SUFIJOS) if (s.endsWith(a)) return tr(s.slice(0, -a.length)) + b;
  return s;
}
