// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Experimental.Rendering
{
    public partial class GraphicsFormatUtility
    {
        public static global::UnityEngine.Experimental.Rendering.GraphicsFormat GetGraphicsFormat(global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite) { global::Porteo.Falta.Llamada("UnityEngine.Experimental.Rendering.GraphicsFormatUtility::GetGraphicsFormat"); return default; }
        public static bool HasAlphaChannel(global::UnityEngine.Experimental.Rendering.GraphicsFormat format) { global::Porteo.Falta.Llamada("UnityEngine.Experimental.Rendering.GraphicsFormatUtility::HasAlphaChannel"); return default; }
        public static bool IsCrunchFormat(global::UnityEngine.TextureFormat format) { global::Porteo.Falta.Llamada("UnityEngine.Experimental.Rendering.GraphicsFormatUtility::IsCrunchFormat"); return default; }
    }
}
