// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Sprites
{
    public sealed partial class DataUtility
    {
        public static global::UnityEngine.Vector4 GetInnerUV(global::UnityEngine.Sprite sprite) { global::Porteo.Falta.Llamada("UnityEngine.Sprites.DataUtility::GetInnerUV"); return default; }
        public static global::UnityEngine.Vector4 GetOuterUV(global::UnityEngine.Sprite sprite) { global::Porteo.Falta.Llamada("UnityEngine.Sprites.DataUtility::GetOuterUV"); return default; }
        public static global::UnityEngine.Vector4 GetPadding(global::UnityEngine.Sprite sprite) { global::Porteo.Falta.Llamada("UnityEngine.Sprites.DataUtility::GetPadding"); return default; }
        public static global::UnityEngine.Vector2 GetMinSize(global::UnityEngine.Sprite sprite) { global::Porteo.Falta.Llamada("UnityEngine.Sprites.DataUtility::GetMinSize"); return default; }
    }
}
