// <auto-generated> porteo: generar</auto-generated>
namespace Porteo
{
    // Lo que el motor todavía no hace: avisa una vez por miembro y sigue con el valor por defecto.
    public static class Falta
    {
        static readonly System.Collections.Generic.HashSet<string> vistos = new System.Collections.Generic.HashSet<string>();
        public static void Llamada(string quien)
        {
            if (vistos.Add(quien)) System.Console.WriteLine("porteo: falta " + quien);
        }
        public static System.Collections.Generic.IEnumerable<string> Vistos => vistos;
    }
}
