// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial interface IPlayable
    {
        global::UnityEngine.Playables.PlayableHandle GetHandle();
    }
}
