// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct PlayableHandle : global::System.IEquatable<global::UnityEngine.Playables.PlayableHandle>
    {
        public global::System.IntPtr m_Handle;
        public uint m_Version;
        public bool Equals(global::UnityEngine.Playables.PlayableHandle other) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableHandle::Equals"); return default; }
    }
}
