// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimationPlayableOutput : global::UnityEngine.Playables.IPlayableOutput
    {
        public global::UnityEngine.Playables.PlayableOutputHandle m_Handle;
        public global::UnityEngine.Playables.PlayableOutputHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationPlayableOutput::GetHandle"); return default; }
        public static explicit operator global::UnityEngine.Animations.AnimationPlayableOutput(global::UnityEngine.Playables.PlayableOutput output) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationPlayableOutput::op_Explicit"); return default; }
        public global::UnityEngine.Animator GetTarget() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationPlayableOutput::GetTarget"); return default; }
    }
}
