// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimationOffsetPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Animations.AnimationOffsetPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Animations.AnimationOffsetPlayable Create(global::UnityEngine.Playables.PlayableGraph graph, global::UnityEngine.Vector3 position, global::UnityEngine.Quaternion rotation, int inputCount) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationOffsetPlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationOffsetPlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Animations.AnimationOffsetPlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationOffsetPlayable::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Animations.AnimationOffsetPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationOffsetPlayable::Equals"); return default; }
    }
}
