// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimationMotionXToDeltaPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Animations.AnimationMotionXToDeltaPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Animations.AnimationMotionXToDeltaPlayable Create(global::UnityEngine.Playables.PlayableGraph graph) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMotionXToDeltaPlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMotionXToDeltaPlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Animations.AnimationMotionXToDeltaPlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMotionXToDeltaPlayable::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Animations.AnimationMotionXToDeltaPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMotionXToDeltaPlayable::Equals"); return default; }
        public void SetAbsoluteMotion(bool value) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMotionXToDeltaPlayable::SetAbsoluteMotion"); }
    }
}
