// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public static partial class AnimationPlayableExtensions
    {
        public static void SetAnimatedProperties<U>(U playable, global::UnityEngine.AnimationClip clip) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationPlayableExtensions::SetAnimatedProperties"); }
    }
}
