// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimationClipPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Animations.AnimationClipPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Animations.AnimationClipPlayable Create(global::UnityEngine.Playables.PlayableGraph graph, global::UnityEngine.AnimationClip clip) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Animations.AnimationClipPlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Animations.AnimationClipPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::Equals"); return default; }
        public void SetApplyFootIK(bool value) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::SetApplyFootIK"); }
        public void SetRemoveStartOffset(bool value) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::SetRemoveStartOffset"); }
        public void SetOverrideLoopTime(bool value) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::SetOverrideLoopTime"); }
        public void SetLoopTime(bool value) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationClipPlayable::SetLoopTime"); }
    }
}
