// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimationRemoveScalePlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Animations.AnimationRemoveScalePlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Animations.AnimationRemoveScalePlayable Create(global::UnityEngine.Playables.PlayableGraph graph, int inputCount) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationRemoveScalePlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationRemoveScalePlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Animations.AnimationRemoveScalePlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationRemoveScalePlayable::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Animations.AnimationRemoveScalePlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationRemoveScalePlayable::Equals"); return default; }
    }
}
