// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimationMixerPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Animations.AnimationMixerPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Animations.AnimationMixerPlayable Create(global::UnityEngine.Playables.PlayableGraph graph, int inputCount = 0) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMixerPlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMixerPlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Animations.AnimationMixerPlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMixerPlayable::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Animations.AnimationMixerPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationMixerPlayable::Equals"); return default; }
    }
}
