// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimatorControllerPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Animations.AnimatorControllerPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimatorControllerPlayable::GetHandle"); return default; }
        public bool Equals(global::UnityEngine.Animations.AnimatorControllerPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimatorControllerPlayable::Equals"); return default; }
    }
}
