// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial struct AnimationLayerMixerPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Animations.AnimationLayerMixerPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Animations.AnimationLayerMixerPlayable Create(global::UnityEngine.Playables.PlayableGraph graph, int inputCount, bool singleLayerOptimization) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationLayerMixerPlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationLayerMixerPlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Animations.AnimationLayerMixerPlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationLayerMixerPlayable::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Animations.AnimationLayerMixerPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationLayerMixerPlayable::Equals"); return default; }
        public void SetLayerMaskFromAvatarMask(uint layerIndex, global::UnityEngine.AvatarMask mask) { global::Porteo.Falta.Llamada("UnityEngine.Animations.AnimationLayerMixerPlayable::SetLayerMaskFromAvatarMask"); }
    }
}
