// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    [System.Flags]
    public enum Axis : int
    {
        None = 0,
        X = 1,
        Y = 2,
        Z = 4,
    }
}
