// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Animations
{
    public partial interface IAnimationWindowPreview
    {
        void StartPreview();
        void StopPreview();
        void UpdatePreviewGraph(global::UnityEngine.Playables.PlayableGraph graph);
        global::UnityEngine.Playables.Playable BuildPreviewGraph(global::UnityEngine.Playables.PlayableGraph graph, global::UnityEngine.Playables.Playable inputPlayable);
    }
}
