// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.SpriteShapeModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.U2D.SpriteShapeRenderer))]
