// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Profiling
{
    public sealed partial class CustomSampler : global::UnityEngine.Profiling.Sampler
    {
    }
}
