#!/usr/bin/env python3
"""Compila PhysX 4.1.1 para WebAssembly con el emscripten que trae .NET y arma una biblioteca
estática (libporteo_fisica.a) con PhysX y la capa en C que usa el motor (fisica.cpp).

    python3 -I compilar-physx.py SALIDA [--emsdk DIR] [--crate ARCHIVO.crate]

El código de PhysX sale del crate physx-sys 0.8.2 de crates.io (Embark Studios lo publica con
el código de PhysX 4.1.1 adentro; licencias BSD-3 de NVIDIA y MIT/Apache de Embark). Se baja,
se verifica con el checksum del índice de crates.io y se compila: Unity 2018.4 usa PhysX 3.4, y
la 4.1 es la misma familia (mismo solver por defecto, mismo controlador de personaje).

La biblioteca se enlaza en el .wasm del motor (Web.csproj, NativeFileReference): todo queda en
un solo módulo y C# llama a fisica.cpp con DllImport, sin pasar por JavaScript.
"""
import argparse
import hashlib
import io
import json
import os
import re
import subprocess
import sys
import tarfile
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

CRATE = "physx-sys"
VERSION = "0.8.2"
SHA256 = "35bb4bf1bfa71baa5c2574ee6323734dac9f1a046310535532f30b30f6585419"
AQUI = Path(__file__).resolve().parent


def log(*a):
    print(*a, file=sys.stderr, flush=True)


def bajar_crate(destino: Path) -> Path:
    """El crate, verificado; se extrae una sola vez."""
    raiz = destino / f"{CRATE}-{VERSION}"
    if (raiz / "PhysX").is_dir():
        return raiz
    destino.mkdir(parents=True, exist_ok=True)
    archivo = destino / f"{CRATE}-{VERSION}.crate"
    if not archivo.exists():
        url = f"https://static.crates.io/crates/{CRATE}/{CRATE}-{VERSION}.crate"
        log("bajando", url)
        with urllib.request.urlopen(url, timeout=300) as r:
            archivo.write_bytes(r.read())
    datos = archivo.read_bytes()
    h = hashlib.sha256(datos).hexdigest()
    if h != SHA256:
        raise SystemExit(f"el crate no coincide con el índice de crates.io: {h}")
    with tarfile.open(fileobj=io.BytesIO(datos), mode="r:gz") as t:
        t.extractall(destino, filter="data")
    return raiz


# Arreglos al código de PhysX 4.1.1 para emscripten: (archivo, texto viejo, texto nuevo).
PARCHES = [
    # la rama de emscripten tiene una llave de más que cierra el namespace antes de tiempo
    ("PhysX/physx/source/foundation/include/unix/sse2/PsUnixSse2InlineAoS.h",
     "const PX_ALIGN(16, PxU32 gMaskXYZ[4]) = { 0xffffffff, 0xffffffff, 0xffffffff, 0 }; }",
     "const PX_ALIGN(16, PxU32 gMaskXYZ[4]) = { 0xffffffff, 0xffffffff, 0xffffffff, 0 };"),
    # en wasm32 size_t es unsigned long, distinto de uint32_t: hace falta su hash (como en Apple)
    ("PhysX/physx/source/foundation/include/PsHash.h",
     "#if PX_APPLE_FAMILY\n// hash for size_t",
     "#if PX_APPLE_FAMILY || PX_EMSCRIPTEN\n// hash for size_t"),
]


def parchear(raiz: Path):
    for rel, viejo, nuevo in PARCHES:
        f = raiz / rel
        t = f.read_text(errors="surrogateescape")
        if viejo in t:
            f.write_text(t.replace(viejo, nuevo), errors="surrogateescape")
            log("parche:", rel)
        elif nuevo not in t:
            raise SystemExit(f"el parche no aplica: {rel}")


def lista(raiz: Path, nombre: str):
    """Los archivos de sources/NOMBRE (un arreglo de Rust con nombres sin extensión)."""
    texto = (raiz / "sources" / nombre).read_text()
    return re.findall(r'"([^"]+)"', texto)


def fuentes_e_includes(raiz: Path):
    px = raiz / "PhysX" / "physx"
    fuentes, inc = [], []

    def comp(nombre, lista_nombre=None):
        src = px / "source" / nombre / "src"
        fuentes.extend(src / (f + ".cpp") for f in lista(raiz, lista_nombre or nombre))
        inc.extend([src, px / "source" / nombre / "include"])

    def carpeta(rel, lista_nombre):
        d = px / rel
        fuentes.extend(d / (f + ".cpp") for f in lista(raiz, lista_nombre))
        inc.append(d)

    comp("fastxml")
    comp("task")
    comp("foundation")
    carpeta("source/foundation/src/unix", "foundation_unix")
    # lowlevel
    fuentes.append(px / "source/lowlevel/api/src/px_globals.cpp")
    carpeta("source/lowlevel/common/src/pipeline", "lowlevel_pipeline")
    carpeta("source/lowlevel/software/src", "lowlevel_software")
    inc.extend(px / "source/lowlevel" / d for d in ["api/include", "common/include/collision", "common/include/pipeline",
                                                     "common/include/utils", "software/include"])
    comp("lowlevelaabb")
    comp("lowleveldynamics")
    # extensions (las juntas, el despachador, los filtros) con su serialización
    comp("physxextensions", "extensions")
    fuentes.append(px / "source/physxmetadata/extensions/src/PxExtensionAutoGeneratedMetaDataObjects.cpp")
    inc.append(px / "source/physxmetadata/extensions/include")
    carpeta("source/physxextensions/src/serialization", "extensions_serialization")
    inc.append(px / "source/physxextensions/src/serialization/File")
    carpeta("source/physxextensions/src/serialization/Xml", "extensions_xml")
    carpeta("source/physxextensions/src/serialization/Binary", "extensions_binary")
    comp("physxcharacterkinematic")
    comp("common")
    # geomutils
    carpeta("source/geomutils/src", "geomutils")
    inc.append(px / "source/geomutils/include")
    for sub in ["ccd", "common", "contact", "convex", "distance", "gjk", "hf", "intersection", "mesh", "pcm", "sweep"]:
        carpeta(f"source/geomutils/src/{sub}", f"geomutils_{sub}")
    # cooking (mallas de colisión y convexos a partir de los vértices de Unity)
    carpeta("source/physxcooking/src", "cooking")
    carpeta("source/physxcooking/src/mesh", "cooking_mesh")
    carpeta("source/physxcooking/src/convex", "cooking_convex")
    inc.append(px / "include/cooking")
    # physx
    fuentes.extend(px / "source/physxmetadata/core/src" / (f + ".cpp") for f in ["PxAutoGeneratedMetaDataObjects", "PxMetaDataObjects"])
    inc.append(px / "source/physxmetadata/core/include")
    fuentes.append(px / "source/immediatemode/src/NpImmediateMode.cpp")
    carpeta("source/physx/src/buffering", "buffering")
    carpeta("source/physx/src", "core")
    comp("scenequery")
    comp("simulationcontroller")
    # pvd: los encabezados hacen falta aunque no se compile (PX_SUPPORT_PVD=0)
    inc.extend([px / "source/pvd/include", px / "source/filebuf/include", px / "source/foundation/include",
                px / "source/common/src", px / "include", raiz / "PhysX/pxshared/include"])
    vistos, unicos = set(), []
    for d in inc:
        if d not in vistos:
            vistos.add(d)
            unicos.append(d)
    return fuentes, unicos


def entorno(emsdk: Path):
    e = dict(os.environ)
    herramientas = emsdk / "tools"
    paquetes = emsdk.parent.parent
    nodo = next(paquetes.glob("Microsoft.NET.Runtime.Emscripten.*.Node.*/*/tools/bin/node"))
    cache = next(paquetes.glob("Microsoft.NET.Runtime.Emscripten.*.Cache.*/*/tools/emscripten/cache"))
    e.update({
        "EMSDK_PATH": str(herramientas),
        "DOTNET_EMSCRIPTEN_LLVM_ROOT": str(herramientas / "bin"),
        "DOTNET_EMSCRIPTEN_BINARYEN_ROOT": str(herramientas),
        "DOTNET_EMSCRIPTEN_NODE_JS": str(nodo),
        "EM_CONFIG": str(herramientas / "emscripten/.emscripten"),
        "EM_CACHE": str(cache),
        "EM_FROZEN_CACHE": "1",
    })
    return e, herramientas / "emscripten"


BANDERAS = [
    "-std=c++14", "-O3", "-fno-exceptions", "-fno-rtti", "-msimd128", "-msse", "-msse2",
    "-Wno-everything", "-ffp-contract=off",
    "-DPX_PHYSX_STATIC_LIB", "-DDISABLE_CUDA_PHYSX", "-DNDEBUG=1", "-DPX_SUPPORT_PVD=0", "-DPX_COOKING",
]


# para la prueba en consola (.NET de escritorio): la misma física como biblioteca compartida
BANDERAS_NATIVO = [b for b in BANDERAS if b not in ("-msimd128", "-msse", "-msse2")] + ["-fPIC", "-msse2"]


def compilar(args):
    em, e, inc, fuente, objeto, nativo = args
    if objeto.exists() and objeto.stat().st_mtime > fuente.stat().st_mtime:
        return None
    objeto.parent.mkdir(parents=True, exist_ok=True)
    compilador = "clang++" if nativo else str(em / "em++")
    cmd = [compilador, *(BANDERAS_NATIVO if nativo else BANDERAS), *[f"-I{d}" for d in inc], "-c", str(fuente), "-o", str(objeto)]
    r = subprocess.run(cmd, env=e, capture_output=True, text=True)
    if r.returncode != 0:
        return f"{fuente}:\n{r.stderr[-4000:]}"
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("salida")
    ap.add_argument("--emsdk", default="/tmp/claude-0/slime/dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Sdk.linux-x64/10.0.12")
    ap.add_argument("--hilos", type=int, default=os.cpu_count() or 4)
    ap.add_argument("--nativo", action="store_true", help="libporteo.so para la prueba en consola")
    a = ap.parse_args()
    salida = Path(a.salida).resolve()
    raiz = bajar_crate(salida / "fuente")
    parchear(raiz)
    fuentes, inc = fuentes_e_includes(raiz)
    fuentes.append(AQUI / "fisica.cpp")
    e, em = entorno(Path(a.emsdk))
    objs = salida / ("obj-nativo" if a.nativo else "obj")
    trabajos = []
    for f in fuentes:
        rel = f.relative_to(raiz) if raiz in f.parents else Path("porteo") / f.name
        trabajos.append((em, e, inc, f, objs / rel.with_suffix(".o"), a.nativo))
    log(f"compilando {len(trabajos)} archivos con {a.hilos} hilos")
    errores = []
    with ThreadPoolExecutor(a.hilos) as ex:
        for i, r in enumerate(ex.map(compilar, trabajos)):
            if r:
                errores.append(r)
                log(r)
    if errores:
        raise SystemExit(f"{len(errores)} archivos no compilan")
    if a.nativo:
        lib = salida / "libporteo.so"
        subprocess.run(["clang++", "-shared", "-o", str(lib), *[str(t[4]) for t in trabajos], "-lpthread", "-ldl"], check=True)
        log(f"listo: {lib} ({lib.stat().st_size / 1e6:.1f} MB)")
        return
    lib = salida / "libporteo_fisica.a"
    if lib.exists():
        lib.unlink()
    subprocess.run([str(em / "emar"), "rcs", str(lib), *[str(t[4]) for t in trabajos]], env=e, check=True)
    log(f"listo: {lib} ({lib.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
