plugins { id 'com.android.application' version '8.7.3' }
android {
    namespace 'ai.peakcode'
    compileSdk 34
    defaultConfig {
        applicationId "ai.peakcode"
        minSdk 24
        targetSdk 34
        versionCode 10
        versionName "1.0"
    }
    buildTypes { debug { } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
