// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.U2D
{
    public partial class SpriteAtlasManager
    {
        public static event global::System.Action<global::UnityEngine.U2D.SpriteAtlas> atlasRegistered { add { global::Porteo.Falta.Llamada("UnityEngine.U2D.SpriteAtlasManager::atlasRegistered+"); } remove { } }
    }
}
