/* ============================================================================
   aeroplaza/js/textos.js — todo lo que se lee, en castellano, inglés y
   portugués. t('clave', {n: 3}) reemplaza {n}. Si falta una traducción se usa
   el castellano (y en la consola avisa, para encontrarla).
   ========================================================================== */
const T = {
  es: {
    prob_ojos: 'Ojos', prob_cabeza: 'Cabeza', prob_degrade: 'Degradé', mot_igual: 'Igual que el cuerpo', ojo_ovalos: 'Óvalos', ojo_redondos: 'Redondos', ojo_felices: 'Felices', ojo_ninguno: 'Sin ojos',
    jugar: 'Jugar', canal_estilo: 'Estilo retro', estilo_titulo: 'Estilo retro', estilo_ajuste: 'Ajuste fino', estilo_ps1: 'Temblor PS1', estilo_paleta: 'Paleta', paleta_no: 'Libre', paleta_gb: 'Game Boy', paleta_8: '8 bits',
    est_normal: 'Normal', est_normal_d: 'Nítido, con brillo y reflejos.', est_pixel: 'Pixel', est_pixel_d: '270 líneas, 16 tonos y tramado. Va más rápido.', est_ps1: 'PS1', est_ps1_d: 'Vértices que tiemblan, 200 líneas, color de 15 bits.',
    est_tubo: 'Tele de tubo', est_tubo_d: 'Pantalla curva, líneas y colores corridos.', est_gameboy: 'Game Boy', est_gameboy_d: 'Cuatro verdes y 144 líneas.', est_ochobits: '8 bits', est_ochobits_d: '16 colores de consola de fantasía.', est_vhs: 'VHS', est_vhs_d: 'Cinta vieja: tiembla, raya y ruido.',
    est_rapido: 'Va rápido', error_titulo: 'Uy, algo falló', error_texto: 'El juego sigue andando. Si se traba, probá la calidad baja o el estilo Pixel (es el más liviano).', error_baja: 'Calidad baja', error_recargar: 'Recargar', sin_webgl: 'Este navegador no puede dibujar en 3D (WebGL). Abrí el archivo con Chrome, Edge, Firefox o Safari.', contexto_perdido: 'La placa de video se reinició. Tocá para seguir en calidad baja.',
    lento_pixel: 'Va lento en este aparato: probá el estilo Pixel (👾), es muchísimo más rápido', subio_calidad: 'Calidad: {n}',
    tuto_mover: 'Movete con WASD o las flechas · en el celu, con la palanca', tuto_mover_dedo: 'Movete con la palanca de la izquierda', tuto_saltar: 'Saltá con Espacio (dos veces: doble salto)', tuto_saltar_dedo: 'Saltá con ⤒ (dos veces: doble salto)', tuto_camara: 'Arrastrá para mirar alrededor', tuto_hablar: 'Hablale a Brújula, al lado del mapa: apretá E', tuto_hablar_dedo: 'Hablale a Brújula, al lado del mapa: tocá ✋', tuto_listo: '¡Listo! Explorá, juntá orbes y tomá el tren 🚆',
    consejo_1: 'Consejo: el tren de la estación lleva a los otros reinos', consejo_2: 'Consejo: con 👾 cambiás a estilo Pixel, PS1, Game Boy o VHS', consejo_3: 'Consejo: las frutas de la huerta te agrandan, te achican o te pintan', consejo_4: 'Consejo: en la fuente de la plaza hay burbujas para volar',
    idioma_titulo: 'Elegí tu idioma', aviso_titulo: '¡Hola!', aviso_texto: 'AEROPLAZA es un lugar para pasear con gente de todo el mundo. Sé amable en el chat, tomate un descanso cada tanto y tomá agua.',
    aviso_seguir: 'Tocá la pantalla para seguir', aviso_seguir_pc: 'Hacé clic o apretá una tecla para seguir',
    canal_plaza: 'Plaza', canal_probador: 'Probador', canal_salas: 'Salas', canal_opciones: 'Opciones', canal_controles: 'Controles', canal_creditos: 'Créditos', canal_discos: 'Discos', canal_casa: 'Mi casa',
    empezar: 'Empezar', menu: 'Menú', volver: 'Volver', listo: 'Listo', cerrar: 'Cerrar', si: 'Sí', no: 'No', aceptar: 'Aceptar', despues: 'Después', seguir: 'Seguir', comprar: 'Comprar', salir: 'Salir',
    plaza_desc: 'Una isla con lago, cascada y gente de todo el mundo. Paseá, juntá orbes, hablá con los vecinos y tomate el tren a los otros reinos.',
    en_linea: 'en línea', conectando: 'conectando…', sin_red: 'sin conexión', solo: 'jugando solo', sala: 'Sala', jugadores: '{n} acá', total_linea: '{n} en línea',
    reino_plaza: 'Plaza', reino_aqua: 'Aqua', reino_aurora: 'Aurora', reino_jardin: 'Jardín de géiseres', reino_tienda: 'Aero·Mart', reino_casa: 'Mi casa', reino_casa_de: 'Casa de {n}',
    reino_aqua_d: 'Mar abierto, hotel en la playa, delfines para montar y la carrera de aros.', reino_aurora_d: 'Noche eterna, aurora, estrellas que caen y el sueño de todos.', reino_jardin_d: 'Lotos, nenúfares, géiseres y flores gigantes que rebotan.', reino_plaza_d: 'La isla del centro, con el lago y la cascada.', reino_casa_d: 'Tu isla flotante: poné muebles y recibí visitas.',
    viajar: 'Viajar', a_donde: '¿A dónde vamos?', viajando: 'Viajando a {n}…', casas_abiertas: 'Casas con gente', ninguna_casa: 'Todavía no hay casas abiertas',
    accion_viajar: 'Viajar', accion_entrar_tienda: 'Entrar', accion_mi_casa: 'Ir a mi casa', accion_salir_tienda: 'Salir', accion_probador: 'Probador', accion_burbuja: 'Subir a una burbuja', accion_hablar: 'Hablar', accion_fruta: 'Comer', accion_montar: 'Montar', accion_comprar: 'Ver', accion_disco: 'Agarrar', accion_construir: 'Construir', accion_sueno: 'Soñar', accion_bajar: 'Bajar',
    hot_burbujero: 'Burbujero', hot_gestos: 'Gestos', hot_discos: 'Música', hot_foto: 'Foto', hot_mapa: 'Mapa',
    op_cam_auto: 'Cámara que sigue', op_t_sonido: 'Sonido', op_t_imagen: 'Imagen', op_t_juego: 'Juego', op_t_datos: 'Datos', op_aparato: 'Este aparato: calidad {q}', op_nucleos: 'núcleos', op_misiones: 'misiones', op_cosas: 'cosas', ctl_botones: 'Botones', prob_cuerpo: 'Cuerpo', prob_cosas: 'Cosas',
    gesto_saludar: 'Saludar', gesto_festejar: 'Festejar', gesto_sentarse: 'Sentarse', gesto_bailar1: 'Baile 1', gesto_bailar2: 'Baile 2', gesto_bailar3: 'Baile 3', gesto_aplaudir: 'Aplaudir', gesto_saltito: 'Saltito', gesto_voltereta: 'Voltereta', gesto_pensar: 'Pensar',
    chat_poner: 'Escribí y apretá Enter…', chat_enviar: 'Enviar', se_unio: '{n} llegó', se_fue: '{n} se fue',
    orbes: 'orbes', mas_orbes: '+{n} orbes', espuma: 'Espuma', reventaste: '¡Pop! Volvés a la estación', te_pego: '{n} te tiró una burbuja',
    pausa: 'Pausa', salir_menu: 'Salir al menú', guardado: 'Guardado',
    op_musica: 'Música', op_efectos: 'Efectos', op_calidad: 'Calidad', cal_auto: 'Automática', cal_alta: 'Alta', cal_media: 'Media', cal_baja: 'Baja',
    op_retro: 'Efectos retro', op_pix: 'Pixelado', op_trama: 'Tramado', op_niveles: 'Colores', op_barrido: 'Líneas de TV', op_tubo: 'Tubo', op_aberracion: 'Aberración', op_ninguno: 'No', op_camara: 'Sensibilidad de cámara', op_invertir: 'Invertir cámara', op_nombres: 'Nombres arriba', op_idioma: 'Idioma', op_borrar: 'Borrar partida', op_borrar_seguro: '¿Borrar todo? Se pierden orbes, ropa y casa.', op_reloj: 'Reloj de 24 h', op_giro: 'Con el celu parado', giro_auto: 'Girar solo', giro_normal: 'Girar ⟳', giro_reves: 'Girar ⟲', giro_no: 'No girar',
    ctl_titulo: 'Controles', ctl_teclado: 'Teclado y mouse', ctl_mando: 'Mando', ctl_dedos: 'En pantalla', ctl_editar: 'Mover y agrandar botones', ctl_tam: 'Tamaño', ctl_opacidad: 'Transparencia', ctl_palanca: 'Palanca', ctl_fija: 'Fija', ctl_flotante: 'Donde apoyo el dedo', ctl_zurdo: 'Para zurdos', ctl_vibra: 'Vibrar', ctl_restablecer: 'Como venía', ctl_elegi: 'Tocá un botón para elegirlo y arrastralo',
    ctl_teclas: 'WASD / flechas: caminar · Mayús: correr · Espacio: saltar (dos veces: doble salto) · E: usar · C: bajar o bucear · F: burbujero · T: chat · 1-5: barra · V: foto · Esc: pausa · Arrastrar: cámara · Rueda: acercar',
    ctl_mando_txt: 'Palanca izquierda: caminar · derecha: cámara · A: saltar · X/B: usar · Y: burbujero · gatillos: correr y bajar · Start: pausa',
    prob_titulo: 'Probador', prob_color: 'Color', prob_color2: 'Brillo', prob_motivo: 'Motivo', prob_cubre: 'Cuánto cubre', prob_material: 'Material', prob_sombrero: 'Sombrero', prob_pelo: 'Pelo', prob_color_pelo: 'Color del pelo', prob_anteojos: 'Anteojos', prob_espalda: 'Espalda', prob_particulas: 'Partículas', prob_nombre: 'Nombre', prob_azar: 'Al azar', prob_precio: '{n} orbes', prob_comprar: '¿Comprar {q} por {n} orbes?', prob_faltan: 'Te faltan {n} orbes', prob_comprado: '¡Es tuyo!', prob_bloq_mision: 'Se gana con una misión',
    mat_gelatina: 'Gelatina', mat_vidrio: 'Vidrio', mat_perla: 'Perla', mat_cromo: 'Cromo', mat_mate: 'Mate', mat_neon: 'Neón',
    mot_ninguno: 'Liso', mot_agua: 'Agua', mot_nubes: 'Nubes', mot_tierra: 'Tierra', mot_galaxia: 'Galaxia', mot_hojas: 'Hojas', mot_burbujas: 'Burbujas', mot_flores: 'Flores', mot_aurora: 'Aurora',
    som_ninguno: 'Nada', som_conico: 'Sombrero de paja', som_gorro: 'Gorro', som_galera: 'Galera', som_corona: 'Corona', som_flor: 'Flor', som_auriculares: 'Auriculares', som_casco: 'Casco de vidrio', som_aureola: 'Aureola', som_brote: 'Brote', som_gorra: 'Gorra', som_explorador: 'Sombrero de explorador', som_hongo: 'Sombrero hongo', som_capitan: 'Gorra de capitán',
    ant_ninguno: 'Nada', ant_sol: 'De sol', ant_redondos: 'Redondos', ant_visor: 'Visor',
    esp_ninguno: 'Nada', esp_alas: 'Alas', esp_mochila: 'Mochila burbuja', esp_aleta: 'Aleta', esp_molinete: 'Molinete',
    pei_ninguno: 'Pelado', pei_mechon: 'Mechón', pei_rulos: 'Rulos', pei_pinches: 'Pinches', pei_melena: 'Melena', pei_rodete: 'Rodete', pei_colitas: 'Colitas', pei_cresta: 'Cresta', pei_nube: 'Nube',
    par_ninguna: 'Nada', par_burbujas: 'Burbujas', par_estrellas: 'Estrellas', par_hojas: 'Hojitas', par_notas: 'Notas',
    mis_titulo: 'Misiones', mis_nueva: '¡Misión nueva!', mis_lista: '¡Listo! Volvé con {n}', mis_hecha: '¡Misión cumplida!', mis_premio: 'Premio: {p}',
    disco_nuevo: '¡Disco nuevo! «{n}»', discos_titulo: 'Discos', disco_bloq: 'Encontralo en algún reino', disco_sonando: 'Sonando',
    can_titulo: 'Iniciar sesión', can_colina: 'La colina', can_playa: 'Playa del faro', can_bosque: 'Bosque de hongos', can_arrecife: 'Arrecife', can_ciudad: 'Ciudad de vidrio', can_cielo: 'Cielo', can_aurora: 'Aurora', can_plano: 'Pitido',
    fruta_grande: '¡Sos gigante!', fruta_azul: '¡Te pusiste azul!', fruta_chico: '¡Sos chiquito!', fruta_brillo: '¡Brillás!', fruta_liviano: '¡Sos liviano como una pluma!',
    carrera_empieza: '¡Carrera! Pasá por los aros', carrera_aro: 'Aro {n}/{t}', carrera_fin: '¡Llegaste! {s} s', carrera_record: '¡Récord! {s} s',
    sueno_falta: 'El sueño necesita más estrellas: {n}/{t}', sueno_empieza: '¡Sueño colectivo!', estrella: '+1 estrella',
    casa_construir: 'Construir', casa_mover: 'Mover', casa_girar: 'Girar', casa_quitar: 'Quitar', casa_listo: 'Listo', casa_catalogo: 'Muebles', casa_visitas: 'Tu casa está abierta: quien viaje en tren la puede visitar',
    foto_lista: 'Foto guardada', foto_ayuda: 'Modo foto: V o 📷 para sacar', mapa_titulo: 'Mapa',
    creditos_txt: 'Hecho con three.js. Arte de Rezona. Música propia sintetizada. Multijugador por MQTT sin servidor.', creditos_inspira: 'Inspirado en los juegos sociales de estética Frutiger Aero.',
    cargando: 'Cargando…', tocar_para_empezar: 'Tocá para empezar',
    burbuja_bajar: 'E: salir de la burbuja · Espacio: subir · C: bajar', dedo_burbuja: '✋ salir · ⤒ subir · ⤓ bajar',
    npc_nimbo: 'Nimbo', npc_lima: 'Lima', npc_burbu: 'Burbu', npc_vendedora: 'Menta', npc_coral: 'Coral', npc_estela: 'Estela', npc_loto: 'Loto', npc_guia: 'Guía', npc_brujula: 'Brújula', npc_brisa: 'Brisa', npc_musgo: 'Musgo', npc_marea: 'Marea',
  },
  en: {
    prob_ojos: 'Eyes', prob_cabeza: 'Head', prob_degrade: 'Gradient', mot_igual: 'Same as body', ojo_ovalos: 'Ovals', ojo_redondos: 'Round', ojo_felices: 'Happy', ojo_ninguno: 'No eyes',
    jugar: 'Play', canal_estilo: 'Retro style', estilo_titulo: 'Retro style', estilo_ajuste: 'Fine tuning', estilo_ps1: 'PS1 wobble', estilo_paleta: 'Palette', paleta_no: 'Free', paleta_gb: 'Game Boy', paleta_8: '8-bit',
    est_normal: 'Normal', est_normal_d: 'Sharp, with glow and reflections.', est_pixel: 'Pixel', est_pixel_d: '270 lines, 16 tones and dithering. Runs faster.', est_ps1: 'PS1', est_ps1_d: 'Wobbly vertices, 200 lines, 15-bit colour.',
    est_tubo: 'CRT TV', est_tubo_d: 'Curved screen, scanlines and colour fringing.', est_gameboy: 'Game Boy', est_gameboy_d: 'Four greens and 144 lines.', est_ochobits: '8-bit', est_ochobits_d: '16 fantasy-console colours.', est_vhs: 'VHS', est_vhs_d: 'Old tape: wobble, tracking and noise.',
    est_rapido: 'Fast', error_titulo: 'Oops, something went wrong', error_texto: 'The game keeps running. If it gets stuck, try low quality or the Pixel style (the lightest).', error_baja: 'Low quality', error_recargar: 'Reload', sin_webgl: 'This browser cannot draw 3D (WebGL). Open the file in Chrome, Edge, Firefox or Safari.', contexto_perdido: 'The graphics card restarted. Tap to continue in low quality.',
    lento_pixel: "It's slow on this device: try the Pixel style (👾), it's much faster", subio_calidad: 'Quality: {n}',
    tuto_mover: 'Move with WASD or the arrows · on phones, with the stick', tuto_mover_dedo: 'Move with the stick on the left', tuto_saltar: 'Jump with Space (twice: double jump)', tuto_saltar_dedo: 'Jump with ⤒ (twice: double jump)', tuto_camara: 'Drag to look around', tuto_hablar: 'Talk to Compass, next to the map: press E', tuto_hablar_dedo: 'Talk to Compass, next to the map: tap ✋', tuto_listo: 'All set! Explore, collect orbs and take the train 🚆',
    consejo_1: 'Tip: the station train goes to the other realms', consejo_2: 'Tip: with 👾 you switch to Pixel, PS1, Game Boy or VHS style', consejo_3: 'Tip: orchard fruit makes you big, small or paints you', consejo_4: 'Tip: the plaza fountain has bubbles to fly in',
    idioma_titulo: 'Choose your language', aviso_titulo: 'Hi there!', aviso_texto: 'AEROPLAZA is a place to hang out with people from all over the world. Be kind in the chat, take a break now and then, and drink some water.',
    aviso_seguir: 'Tap the screen to continue', aviso_seguir_pc: 'Click or press a key to continue',
    canal_plaza: 'Plaza', canal_probador: 'Dressing room', canal_salas: 'Rooms', canal_opciones: 'Settings', canal_controles: 'Controls', canal_creditos: 'Credits', canal_discos: 'Discs', canal_casa: 'My home',
    empezar: 'Start', menu: 'Menu', volver: 'Back', listo: 'Done', cerrar: 'Close', si: 'Yes', no: 'No', aceptar: 'Accept', despues: 'Later', seguir: 'Continue', comprar: 'Buy', salir: 'Exit',
    plaza_desc: 'An island with a lake, a waterfall and people from everywhere. Wander around, collect orbs, chat with the neighbours and take the train to the other realms.',
    en_linea: 'online', conectando: 'connecting…', sin_red: 'offline', solo: 'playing solo', sala: 'Room', jugadores: '{n} here', total_linea: '{n} online',
    reino_plaza: 'Plaza', reino_aqua: 'Aqua', reino_aurora: 'Aurora', reino_jardin: 'Geyser Garden', reino_tienda: 'Aero·Mart', reino_casa: 'My home', reino_casa_de: "{n}'s home",
    reino_aqua_d: 'Open sea, a beach hotel, dolphins to ride and the ring race.', reino_aurora_d: 'Endless night, auroras, falling stars and everyone’s dream.', reino_jardin_d: 'Lotus, lily pads, geysers and giant bouncy flowers.', reino_plaza_d: 'The central island, with the lake and the waterfall.', reino_casa_d: 'Your floating island: place furniture and get visitors.',
    viajar: 'Travel', a_donde: 'Where to?', viajando: 'Travelling to {n}…', casas_abiertas: 'Homes with people', ninguna_casa: 'No open homes yet',
    accion_viajar: 'Travel', accion_entrar_tienda: 'Enter', accion_mi_casa: 'Go home', accion_salir_tienda: 'Leave', accion_probador: 'Dressing room', accion_burbuja: 'Hop into a bubble', accion_hablar: 'Talk', accion_fruta: 'Eat', accion_montar: 'Ride', accion_comprar: 'Look', accion_disco: 'Pick up', accion_construir: 'Build', accion_sueno: 'Dream', accion_bajar: 'Get off',
    hot_burbujero: 'Bubbler', hot_gestos: 'Emotes', hot_discos: 'Music', hot_foto: 'Photo', hot_mapa: 'Map',
    op_cam_auto: 'Camera follows', op_t_sonido: 'Sound', op_t_imagen: 'Graphics', op_t_juego: 'Game', op_t_datos: 'Data', op_aparato: 'This device: {q} quality', op_nucleos: 'cores', op_misiones: 'quests', op_cosas: 'items', ctl_botones: 'Buttons', prob_cuerpo: 'Body', prob_cosas: 'Items',
    gesto_saludar: 'Wave', gesto_festejar: 'Cheer', gesto_sentarse: 'Sit', gesto_bailar1: 'Dance 1', gesto_bailar2: 'Dance 2', gesto_bailar3: 'Dance 3', gesto_aplaudir: 'Clap', gesto_saltito: 'Hop', gesto_voltereta: 'Flip', gesto_pensar: 'Think',
    chat_poner: 'Type and press Enter…', chat_enviar: 'Send', se_unio: '{n} arrived', se_fue: '{n} left',
    orbes: 'orbs', mas_orbes: '+{n} orbs', espuma: 'Foam', reventaste: 'Pop! Back to the station', te_pego: '{n} hit you with a bubble',
    pausa: 'Pause', salir_menu: 'Back to menu', guardado: 'Saved',
    op_musica: 'Music', op_efectos: 'Sound effects', op_calidad: 'Quality', cal_auto: 'Automatic', cal_alta: 'High', cal_media: 'Medium', cal_baja: 'Low',
    op_retro: 'Retro effects', op_pix: 'Pixelation', op_trama: 'Dithering', op_niveles: 'Colours', op_barrido: 'Scanlines', op_tubo: 'CRT', op_aberracion: 'Aberration', op_ninguno: 'Off', op_camara: 'Camera sensitivity', op_invertir: 'Invert camera', op_nombres: 'Name tags', op_idioma: 'Language', op_borrar: 'Delete save', op_borrar_seguro: 'Delete everything? You lose orbs, clothes and home.', op_reloj: '24-hour clock', op_giro: 'Phone held upright', giro_auto: 'Auto-rotate', giro_normal: 'Rotate ⟳', giro_reves: 'Rotate ⟲', giro_no: "Don't rotate",
    ctl_titulo: 'Controls', ctl_teclado: 'Keyboard and mouse', ctl_mando: 'Gamepad', ctl_dedos: 'On screen', ctl_editar: 'Move and resize buttons', ctl_tam: 'Size', ctl_opacidad: 'Opacity', ctl_palanca: 'Stick', ctl_fija: 'Fixed', ctl_flotante: 'Where my finger lands', ctl_zurdo: 'Left-handed', ctl_vibra: 'Vibrate', ctl_restablecer: 'Reset', ctl_elegi: 'Tap a button to pick it and drag it',
    ctl_teclas: 'WASD / arrows: walk · Shift: run · Space: jump (twice: double jump) · E: use · C: down or dive · F: bubbler · T: chat · 1-5: hotbar · V: photo · Esc: pause · Drag: camera · Wheel: zoom',
    ctl_mando_txt: 'Left stick: walk · right: camera · A: jump · X/B: use · Y: bubbler · triggers: run and down · Start: pause',
    prob_titulo: 'Dressing room', prob_color: 'Colour', prob_color2: 'Glow', prob_motivo: 'Pattern', prob_cubre: 'Coverage', prob_material: 'Material', prob_sombrero: 'Hat', prob_pelo: 'Hair', prob_color_pelo: 'Hair colour', prob_anteojos: 'Glasses', prob_espalda: 'Back', prob_particulas: 'Particles', prob_nombre: 'Name', prob_azar: 'Random', prob_precio: '{n} orbs', prob_comprar: 'Buy {q} for {n} orbs?', prob_faltan: 'You need {n} more orbs', prob_comprado: "It's yours!", prob_bloq_mision: 'Earned with a quest',
    mat_gelatina: 'Jelly', mat_vidrio: 'Glass', mat_perla: 'Pearl', mat_cromo: 'Chrome', mat_mate: 'Matte', mat_neon: 'Neon',
    mot_ninguno: 'Plain', mot_agua: 'Water', mot_nubes: 'Clouds', mot_tierra: 'Earth', mot_galaxia: 'Galaxy', mot_hojas: 'Leaves', mot_burbujas: 'Bubbles', mot_flores: 'Flowers', mot_aurora: 'Aurora',
    som_ninguno: 'None', som_conico: 'Straw hat', som_gorro: 'Beanie', som_galera: 'Top hat', som_corona: 'Crown', som_flor: 'Flower', som_auriculares: 'Headphones', som_casco: 'Glass helmet', som_aureola: 'Halo', som_brote: 'Sprout', som_gorra: 'Cap', som_explorador: 'Explorer hat', som_hongo: 'Mushroom hat', som_capitan: 'Captain cap',
    ant_ninguno: 'None', ant_sol: 'Sunglasses', ant_redondos: 'Round', ant_visor: 'Visor',
    esp_ninguno: 'None', esp_alas: 'Wings', esp_mochila: 'Bubble backpack', esp_aleta: 'Fin', esp_molinete: 'Pinwheel',
    pei_ninguno: 'Bald', pei_mechon: 'Tuft', pei_rulos: 'Curls', pei_pinches: 'Spikes', pei_melena: 'Long hair', pei_rodete: 'Bun', pei_colitas: 'Pigtails', pei_cresta: 'Mohawk', pei_nube: 'Cloud',
    par_ninguna: 'None', par_burbujas: 'Bubbles', par_estrellas: 'Stars', par_hojas: 'Leaves', par_notas: 'Notes',
    mis_titulo: 'Quests', mis_nueva: 'New quest!', mis_lista: 'Done! Go back to {n}', mis_hecha: 'Quest complete!', mis_premio: 'Reward: {p}',
    disco_nuevo: 'New disc! “{n}”', discos_titulo: 'Discs', disco_bloq: 'Find it in some realm', disco_sonando: 'Playing',
    can_titulo: 'Sign in', can_colina: 'The hill', can_playa: 'Lighthouse beach', can_bosque: 'Mushroom forest', can_arrecife: 'Reef', can_ciudad: 'Glass city', can_cielo: 'Sky', can_aurora: 'Aurora', can_plano: 'Beep',
    fruta_grande: "You're huge!", fruta_azul: 'You turned blue!', fruta_chico: "You're tiny!", fruta_brillo: "You're glowing!", fruta_liviano: 'Light as a feather!',
    carrera_empieza: 'Race! Go through the rings', carrera_aro: 'Ring {n}/{t}', carrera_fin: 'Finished! {s} s', carrera_record: 'New record! {s} s',
    sueno_falta: 'The dream needs more stars: {n}/{t}', sueno_empieza: 'Collective dream!', estrella: '+1 star',
    casa_construir: 'Build', casa_mover: 'Move', casa_girar: 'Rotate', casa_quitar: 'Remove', casa_listo: 'Done', casa_catalogo: 'Furniture', casa_visitas: 'Your home is open: anyone travelling by train can visit',
    foto_lista: 'Photo saved', foto_ayuda: 'Photo mode: V or 📷 to take it', mapa_titulo: 'Map',
    creditos_txt: 'Made with three.js. Art by Rezona. Original synthesized music. Serverless multiplayer over MQTT.', creditos_inspira: 'Inspired by Frutiger Aero social games.',
    cargando: 'Loading…', tocar_para_empezar: 'Tap to start',
    burbuja_bajar: 'E: leave the bubble · Space: up · C: down', dedo_burbuja: '✋ leave · ⤒ up · ⤓ down',
    npc_nimbo: 'Nimbo', npc_lima: 'Lime', npc_burbu: 'Bubs', npc_vendedora: 'Mint', npc_coral: 'Coral', npc_estela: 'Stella', npc_loto: 'Lotus', npc_guia: 'Guide', npc_brujula: 'Compass', npc_brisa: 'Breeze', npc_musgo: 'Moss', npc_marea: 'Tide',
  },
  pt: {
    prob_ojos: 'Olhos', prob_cabeza: 'Cabeça', prob_degrade: 'Degradê', mot_igual: 'Igual ao corpo', ojo_ovalos: 'Ovais', ojo_redondos: 'Redondos', ojo_felices: 'Felizes', ojo_ninguno: 'Sem olhos',
    jugar: 'Jogar', canal_estilo: 'Estilo retrô', estilo_titulo: 'Estilo retrô', estilo_ajuste: 'Ajuste fino', estilo_ps1: 'Tremor de PS1', estilo_paleta: 'Paleta', paleta_no: 'Livre', paleta_gb: 'Game Boy', paleta_8: '8 bits',
    est_normal: 'Normal', est_normal_d: 'Nítido, com brilho e reflexos.', est_pixel: 'Pixel', est_pixel_d: '270 linhas, 16 tons e pontilhado. Mais rápido.', est_ps1: 'PS1', est_ps1_d: 'Vértices que tremem, 200 linhas, cor de 15 bits.',
    est_tubo: 'TV de tubo', est_tubo_d: 'Tela curva, linhas e cores borradas.', est_gameboy: 'Game Boy', est_gameboy_d: 'Quatro verdes e 144 linhas.', est_ochobits: '8 bits', est_ochobits_d: '16 cores de console de fantasia.', est_vhs: 'VHS', est_vhs_d: 'Fita velha: tremida, riscos e ruído.',
    est_rapido: 'Rápido', error_titulo: 'Ops, algo falhou', error_texto: 'O jogo continua. Se travar, tente a qualidade baixa ou o estilo Pixel (o mais leve).', error_baja: 'Qualidade baixa', error_recargar: 'Recarregar', sin_webgl: 'Este navegador não desenha em 3D (WebGL). Abra o arquivo no Chrome, Edge, Firefox ou Safari.', contexto_perdido: 'A placa de vídeo reiniciou. Toque para continuar em qualidade baixa.',
    lento_pixel: 'Está lento neste aparelho: tente o estilo Pixel (👾), é muito mais rápido', subio_calidad: 'Qualidade: {n}',
    tuto_mover: 'Ande com WASD ou as setas · no celular, com a alavanca', tuto_mover_dedo: 'Ande com a alavanca da esquerda', tuto_saltar: 'Pule com Espaço (duas vezes: pulo duplo)', tuto_saltar_dedo: 'Pule com ⤒ (duas vezes: pulo duplo)', tuto_camara: 'Arraste para olhar em volta', tuto_hablar: 'Fale com a Bússola, ao lado do mapa: aperte E', tuto_hablar_dedo: 'Fale com a Bússola, ao lado do mapa: toque ✋', tuto_listo: 'Pronto! Explore, junte orbes e pegue o trem 🚆',
    consejo_1: 'Dica: o trem da estação leva aos outros reinos', consejo_2: 'Dica: com 👾 você muda para Pixel, PS1, Game Boy ou VHS', consejo_3: 'Dica: as frutas do pomar te aumentam, diminuem ou pintam', consejo_4: 'Dica: na fonte da praça tem bolhas para voar',
    idioma_titulo: 'Escolha seu idioma', aviso_titulo: 'Olá!', aviso_texto: 'AEROPLAZA é um lugar para passear com gente do mundo todo. Seja gentil no chat, faça uma pausa de vez em quando e beba água.',
    aviso_seguir: 'Toque na tela para continuar', aviso_seguir_pc: 'Clique ou aperte uma tecla para continuar',
    canal_plaza: 'Praça', canal_probador: 'Provador', canal_salas: 'Salas', canal_opciones: 'Opções', canal_controles: 'Controles', canal_creditos: 'Créditos', canal_discos: 'Discos', canal_casa: 'Minha casa',
    empezar: 'Começar', menu: 'Menu', volver: 'Voltar', listo: 'Pronto', cerrar: 'Fechar', si: 'Sim', no: 'Não', aceptar: 'Aceitar', despues: 'Depois', seguir: 'Continuar', comprar: 'Comprar', salir: 'Sair',
    plaza_desc: 'Uma ilha com lago, cachoeira e gente de todo lugar. Passeie, junte orbes, converse com os vizinhos e pegue o trem para os outros reinos.',
    en_linea: 'online', conectando: 'conectando…', sin_red: 'sem conexão', solo: 'jogando sozinho', sala: 'Sala', jugadores: '{n} aqui', total_linea: '{n} online',
    reino_plaza: 'Praça', reino_aqua: 'Aqua', reino_aurora: 'Aurora', reino_jardin: 'Jardim de gêiseres', reino_tienda: 'Aero·Mart', reino_casa: 'Minha casa', reino_casa_de: 'Casa de {n}',
    reino_aqua_d: 'Mar aberto, hotel na praia, golfinhos para montar e a corrida de aros.', reino_aurora_d: 'Noite eterna, aurora, estrelas cadentes e o sonho de todos.', reino_jardin_d: 'Lótus, vitórias-régias, gêiseres e flores gigantes que quicam.', reino_plaza_d: 'A ilha do centro, com o lago e a cachoeira.', reino_casa_d: 'Sua ilha flutuante: coloque móveis e receba visitas.',
    viajar: 'Viajar', a_donde: 'Para onde vamos?', viajando: 'Viajando para {n}…', casas_abiertas: 'Casas com gente', ninguna_casa: 'Ainda não há casas abertas',
    accion_viajar: 'Viajar', accion_entrar_tienda: 'Entrar', accion_mi_casa: 'Ir pra minha casa', accion_salir_tienda: 'Sair', accion_probador: 'Provador', accion_burbuja: 'Entrar numa bolha', accion_hablar: 'Falar', accion_fruta: 'Comer', accion_montar: 'Montar', accion_comprar: 'Ver', accion_disco: 'Pegar', accion_construir: 'Construir', accion_sueno: 'Sonhar', accion_bajar: 'Descer',
    hot_burbujero: 'Bolheiro', hot_gestos: 'Gestos', hot_discos: 'Música', hot_foto: 'Foto', hot_mapa: 'Mapa',
    op_cam_auto: 'Câmera que segue', op_t_sonido: 'Som', op_t_imagen: 'Imagem', op_t_juego: 'Jogo', op_t_datos: 'Dados', op_aparato: 'Este aparelho: qualidade {q}', op_nucleos: 'núcleos', op_misiones: 'missões', op_cosas: 'itens', ctl_botones: 'Botões', prob_cuerpo: 'Corpo', prob_cosas: 'Itens',
    gesto_saludar: 'Acenar', gesto_festejar: 'Comemorar', gesto_sentarse: 'Sentar', gesto_bailar1: 'Dança 1', gesto_bailar2: 'Dança 2', gesto_bailar3: 'Dança 3', gesto_aplaudir: 'Aplaudir', gesto_saltito: 'Pulinho', gesto_voltereta: 'Cambalhota', gesto_pensar: 'Pensar',
    chat_poner: 'Escreva e aperte Enter…', chat_enviar: 'Enviar', se_unio: '{n} chegou', se_fue: '{n} saiu',
    orbes: 'orbes', mas_orbes: '+{n} orbes', espuma: 'Espuma', reventaste: 'Pop! De volta à estação', te_pego: '{n} jogou uma bolha em você',
    pausa: 'Pausa', salir_menu: 'Voltar ao menu', guardado: 'Salvo',
    op_musica: 'Música', op_efectos: 'Efeitos', op_calidad: 'Qualidade', cal_auto: 'Automática', cal_alta: 'Alta', cal_media: 'Média', cal_baja: 'Baixa',
    op_retro: 'Efeitos retrô', op_pix: 'Pixelado', op_trama: 'Pontilhado', op_niveles: 'Cores', op_barrido: 'Linhas de TV', op_tubo: 'Tubo', op_aberracion: 'Aberração', op_ninguno: 'Não', op_camara: 'Sensibilidade da câmera', op_invertir: 'Inverter câmera', op_nombres: 'Nomes em cima', op_idioma: 'Idioma', op_borrar: 'Apagar jogo', op_borrar_seguro: 'Apagar tudo? Você perde orbes, roupas e casa.', op_reloj: 'Relógio de 24 h', op_giro: 'Com o celular em pé', giro_auto: 'Girar sozinho', giro_normal: 'Girar ⟳', giro_reves: 'Girar ⟲', giro_no: 'Não girar',
    ctl_titulo: 'Controles', ctl_teclado: 'Teclado e mouse', ctl_mando: 'Controle', ctl_dedos: 'Na tela', ctl_editar: 'Mover e aumentar botões', ctl_tam: 'Tamanho', ctl_opacidad: 'Transparência', ctl_palanca: 'Alavanca', ctl_fija: 'Fixa', ctl_flotante: 'Onde apoio o dedo', ctl_zurdo: 'Para canhotos', ctl_vibra: 'Vibrar', ctl_restablecer: 'Como era', ctl_elegi: 'Toque num botão para escolher e arraste',
    ctl_teclas: 'WASD / setas: andar · Shift: correr · Espaço: pular (duas vezes: pulo duplo) · E: usar · C: descer ou mergulhar · F: bolheiro · T: chat · 1-5: barra · V: foto · Esc: pausa · Arrastar: câmera · Roda: zoom',
    ctl_mando_txt: 'Alavanca esquerda: andar · direita: câmera · A: pular · X/B: usar · Y: bolheiro · gatilhos: correr e descer · Start: pausa',
    prob_titulo: 'Provador', prob_color: 'Cor', prob_color2: 'Brilho', prob_motivo: 'Estampa', prob_cubre: 'Quanto cobre', prob_material: 'Material', prob_sombrero: 'Chapéu', prob_pelo: 'Cabelo', prob_color_pelo: 'Cor do cabelo', prob_anteojos: 'Óculos', prob_espalda: 'Costas', prob_particulas: 'Partículas', prob_nombre: 'Nome', prob_azar: 'Aleatório', prob_precio: '{n} orbes', prob_comprar: 'Comprar {q} por {n} orbes?', prob_faltan: 'Faltam {n} orbes', prob_comprado: 'É seu!', prob_bloq_mision: 'Ganha-se com uma missão',
    mat_gelatina: 'Gelatina', mat_vidrio: 'Vidro', mat_perla: 'Pérola', mat_cromo: 'Cromo', mat_mate: 'Fosco', mat_neon: 'Neon',
    mot_ninguno: 'Liso', mot_agua: 'Água', mot_nubes: 'Nuvens', mot_tierra: 'Terra', mot_galaxia: 'Galáxia', mot_hojas: 'Folhas', mot_burbujas: 'Bolhas', mot_flores: 'Flores', mot_aurora: 'Aurora',
    som_ninguno: 'Nada', som_conico: 'Chapéu de palha', som_gorro: 'Gorro', som_galera: 'Cartola', som_corona: 'Coroa', som_flor: 'Flor', som_auriculares: 'Fones', som_casco: 'Capacete de vidro', som_aureola: 'Auréola', som_brote: 'Broto', som_gorra: 'Boné', som_explorador: 'Chapéu de explorador', som_hongo: 'Chapéu cogumelo', som_capitan: 'Quepe de capitão',
    ant_ninguno: 'Nada', ant_sol: 'De sol', ant_redondos: 'Redondos', ant_visor: 'Viseira',
    esp_ninguno: 'Nada', esp_alas: 'Asas', esp_mochila: 'Mochila bolha', esp_aleta: 'Barbatana', esp_molinete: 'Cata-vento',
    pei_ninguno: 'Careca', pei_mechon: 'Topete', pei_rulos: 'Cachos', pei_pinches: 'Espetado', pei_melena: 'Cabelão', pei_rodete: 'Coque', pei_colitas: 'Maria-chiquinha', pei_cresta: 'Moicano', pei_nube: 'Nuvem',
    par_ninguna: 'Nada', par_burbujas: 'Bolhas', par_estrellas: 'Estrelas', par_hojas: 'Folhinhas', par_notas: 'Notas',
    mis_titulo: 'Missões', mis_nueva: 'Missão nova!', mis_lista: 'Pronto! Volte a {n}', mis_hecha: 'Missão cumprida!', mis_premio: 'Prêmio: {p}',
    disco_nuevo: 'Disco novo! «{n}»', discos_titulo: 'Discos', disco_bloq: 'Encontre em algum reino', disco_sonando: 'Tocando',
    can_titulo: 'Iniciar sessão', can_colina: 'A colina', can_playa: 'Praia do farol', can_bosque: 'Bosque dos cogumelos', can_arrecife: 'Recife', can_ciudad: 'Cidade de vidro', can_cielo: 'Céu', can_aurora: 'Aurora', can_plano: 'Bipe',
    fruta_grande: 'Você é gigante!', fruta_azul: 'Você ficou azul!', fruta_chico: 'Você é pequenininho!', fruta_brillo: 'Você brilha!', fruta_liviano: 'Leve como uma pena!',
    carrera_empieza: 'Corrida! Passe pelos aros', carrera_aro: 'Aro {n}/{t}', carrera_fin: 'Chegou! {s} s', carrera_record: 'Recorde! {s} s',
    sueno_falta: 'O sonho precisa de mais estrelas: {n}/{t}', sueno_empieza: 'Sonho coletivo!', estrella: '+1 estrela',
    casa_construir: 'Construir', casa_mover: 'Mover', casa_girar: 'Girar', casa_quitar: 'Tirar', casa_listo: 'Pronto', casa_catalogo: 'Móveis', casa_visitas: 'Sua casa está aberta: quem viajar de trem pode visitar',
    foto_lista: 'Foto salva', foto_ayuda: 'Modo foto: V ou 📷 para tirar', mapa_titulo: 'Mapa',
    creditos_txt: 'Feito com three.js. Arte da Rezona. Música própria sintetizada. Multijogador por MQTT sem servidor.', creditos_inspira: 'Inspirado nos jogos sociais de estética Frutiger Aero.',
    cargando: 'Carregando…', tocar_para_empezar: 'Toque para começar',
    burbuja_bajar: 'E: sair da bolha · Espaço: subir · C: descer', dedo_burbuja: '✋ sair · ⤒ subir · ⤓ descer',
    npc_nimbo: 'Nimbo', npc_lima: 'Lima', npc_burbu: 'Bolhinha', npc_vendedora: 'Menta', npc_coral: 'Coral', npc_estela: 'Estela', npc_loto: 'Lótus', npc_guia: 'Guia', npc_brujula: 'Bússola', npc_brisa: 'Brisa', npc_musgo: 'Musgo', npc_marea: 'Maré',
  },
};
export const IDIOMAS = ['es', 'en', 'pt'];
let actual = 'es';
export function ponerIdioma(i) { actual = T[i] ? i : 'es'; document.documentElement.lang = actual; }
export function idioma() { return actual; }
export function t(k, v = {}) {
  let s = T[actual][k] ?? T.es[k];
  if (s == null) { console.warn('falta el texto', k); return k; }
  for (const [a, b] of Object.entries(v)) s = s.replaceAll('{' + a + '}', b);
  return s;
}
/* los textos largos de las misiones y los NPC (se agregan desde misiones.js) */
export function sumar(dic) { for (const i of IDIOMAS) Object.assign(T[i], dic[i] || {}); }
