/* ============================================================================
   TAJO — los idiomas que se sumaron el 08/10 (la lista está en
   motor2d/idiomas.js). El de México es el mismo español con tuteo; Egipto,
   Irak y Arabia Saudita usan el árabe estándar. Lo que falte cae en inglés.
   ========================================================================== */

TXT['es-MX'] = Object.assign({}, TXT.es, {
  idioma: 'ELIGE TU IDIOMA', elegir: 'CORTA UNA FRUTA PARA EMPEZAR', clasicoD: 'TRES FALLAS · CUIDADO CON LAS BOMBAS', otra: 'OTRA VEZ', seguir: 'CONTINUAR',
  ayuda: 'DESLIZA EL DEDO PARA CORTAR LA FRUTA. NO TOQUES LAS BOMBAS.', ayudaFalla: 'SI UNA FRUTA CAE SIN CORTAR, ES UNA FALLA.',
  faltan: 'CORTA {0} MÁS', proba: 'PRUEBA AQUÍ', tocar: 'TOCA PARA CONTINUAR',
});

Object.assign(TXT, {
  ar: {
    idioma: 'اختر لغتك', subtitulo: 'طريق النصل', elegir: 'اقطع فاكهة لتبدأ',
    clasico: 'كلاسيكي', clasicoD: 'ثلاثة أخطاء · احذر القنابل', zen: 'زِن', zenD: '90 ثانية بلا قنابل', tormenta: 'عاصفة', tormentaD: '60 ثانية مع قوى خاصة',
    diario: 'تحدي اليوم', diarioD: 'نفس الفاكهة للجميع', dojo: 'دوجو', controles: 'التحكم', idiomaBtn: 'اللغة', record: 'أفضل نتيجة', hoyRec: 'اليوم {0}',
    combo: 'كومبو ×{0}', fin: 'نهاية الطريق', bomba: 'قنبلة!', tiempo: 'انتهى الوقت!', otra: 'مرة أخرى', menu: 'القائمة', pausa: 'إيقاف مؤقت', seguir: 'متابعة',
    reiniciar: 'إعادة', musica: 'الموسيقى', sonido: 'الصوت', si: 'نعم', no: 'لا', nuevoRecord: 'رقم قياسي جديد!', volver: 'رجوع',
    ayuda: 'اسحب إصبعك لتقطع الفاكهة. لا تلمس القنابل.', ayudaFalla: 'إذا سقطت فاكهة دون أن تقطعها فهذا خطأ.', cortadas: 'المقطوعة', mejorCombo: 'أفضل كومبو',
    hielo: 'تجميد', frenesi: 'جنون', doble: 'مضاعف', filos: 'النصال', usar: 'استخدام', enUso: 'مستخدم', faltan: 'اقطع {0} أخرى', nuevoFilo: 'نصل جديد: {0}!',
    grosor: 'سُمك الأثر', sensib: 'الحساسية', alcance: 'مدى القطع', tamPausa: 'زر الإيقاف', zurdo: 'أعسر', vibrar: 'الاهتزاز', proba: 'جرّب هنا',
    restablecer: 'الإعدادات الأصلية', listo: 'تم', baja: 'منخفضة', media: 'متوسطة', alta: 'عالية', fino: 'رفيع', medio: 'متوسط', grueso: 'سميك', chico: 'صغير', grande: 'كبير',
    tocar: 'المس للمتابعة', menos10: '−10', puntos: 'نقاط', todas: 'كل النصال',
    nombresFilo: ['فرشاة', 'قرمزي', 'يَشْم', 'نيلي', 'ورق الذهب'],
  },
  id: {
    idioma: 'PILIH BAHASAMU', subtitulo: 'JALAN SANG PEDANG', elegir: 'POTONG BUAH UNTUK MULAI',
    clasico: 'KLASIK', clasicoD: 'TIGA KESALAHAN · AWAS BOM', zen: 'ZEN', zenD: '90 DETIK TANPA BOM', tormenta: 'BADAI', tormentaD: '60 DETIK DENGAN KEKUATAN',
    diario: 'HARIAN', diarioD: 'BUAH YANG SAMA UNTUK SEMUA', dojo: 'DOJO', controles: 'KONTROL', idiomaBtn: 'BAHASA', record: 'REKOR', hoyRec: 'HARI INI {0}',
    combo: 'KOMBO ×{0}', fin: 'AKHIR PERJALANAN', bomba: 'BOM!', tiempo: 'WAKTU HABIS!', otra: 'LAGI', menu: 'MENU', pausa: 'JEDA', seguir: 'LANJUT',
    reiniciar: 'ULANGI', musica: 'MUSIK', sonido: 'SUARA', si: 'YA', no: 'TIDAK', nuevoRecord: 'REKOR BARU!', volver: 'KEMBALI',
    ayuda: 'GESER JARIMU UNTUK MEMOTONG BUAH. JANGAN SENTUH BOM.', ayudaFalla: 'JIKA BUAH JATUH TANPA DIPOTONG, ITU KESALAHAN.', cortadas: 'TERPOTONG', mejorCombo: 'KOMBO TERBAIK',
    hielo: 'BEKU', frenesi: 'AMUK', doble: 'GANDA', filos: 'PEDANG', usar: 'PAKAI', enUso: 'DIPAKAI', faltan: 'POTONG {0} LAGI', nuevoFilo: 'PEDANG BARU: {0}!',
    grosor: 'TEBAL JEJAK', sensib: 'SENSITIVITAS', alcance: 'JANGKAUAN POTONG', tamPausa: 'TOMBOL JEDA', zurdo: 'KIDAL', vibrar: 'GETAR', proba: 'COBA DI SINI',
    restablecer: 'ATUR ULANG', listo: 'SELESAI', baja: 'RENDAH', media: 'SEDANG', alta: 'TINGGI', fino: 'TIPIS', medio: 'SEDANG', grueso: 'TEBAL', chico: 'KECIL', grande: 'BESAR',
    tocar: 'KETUK UNTUK LANJUT', menos10: '−10', puntos: 'POIN', todas: 'SEMUA PEDANG',
    nombresFilo: ['KUAS', 'MERAH KESUMBA', 'GIOK', 'NILA', 'DAUN EMAS'],
  },
  ms: {
    idioma: 'PILIH BAHASA ANDA', subtitulo: 'JALAN PEDANG', elegir: 'POTONG BUAH UNTUK MULA',
    clasico: 'KLASIK', clasicoD: 'TIGA KESILAPAN · AWAS BOM', zen: 'ZEN', zenD: '90 SAAT TANPA BOM', tormenta: 'RIBUT', tormentaD: '60 SAAT DENGAN KUASA',
    diario: 'HARIAN', diarioD: 'BUAH YANG SAMA UNTUK SEMUA', dojo: 'DOJO', controles: 'KAWALAN', idiomaBtn: 'BAHASA', record: 'REKOD', hoyRec: 'HARI INI {0}',
    combo: 'KOMBO ×{0}', fin: 'PENGHUJUNG JALAN', bomba: 'BOM!', tiempo: 'MASA TAMAT!', otra: 'LAGI', menu: 'MENU', pausa: 'JEDA', seguir: 'SAMBUNG',
    reiniciar: 'MULA SEMULA', musica: 'MUZIK', sonido: 'BUNYI', si: 'YA', no: 'TIDAK', nuevoRecord: 'REKOD BAHARU!', volver: 'KEMBALI',
    ayuda: 'LERETKAN JARI UNTUK MEMOTONG BUAH. JANGAN SENTUH BOM.', ayudaFalla: 'JIKA BUAH JATUH TANPA DIPOTONG, ITU SATU KESILAPAN.', cortadas: 'DIPOTONG', mejorCombo: 'KOMBO TERBAIK',
    hielo: 'BEKU', frenesi: 'AMUKAN', doble: 'GANDA', filos: 'PEDANG', usar: 'GUNA', enUso: 'DIGUNAKAN', faltan: 'POTONG {0} LAGI', nuevoFilo: 'PEDANG BAHARU: {0}!',
    grosor: 'KETEBALAN JEJAK', sensib: 'KEPEKAAN', alcance: 'JANGKAUAN POTONG', tamPausa: 'BUTANG JEDA', zurdo: 'KIDAL', vibrar: 'GETAR', proba: 'CUBA DI SINI',
    restablecer: 'TETAP SEMULA', listo: 'SIAP', baja: 'RENDAH', media: 'SEDERHANA', alta: 'TINGGI', fino: 'NIPIS', medio: 'SEDERHANA', grueso: 'TEBAL', chico: 'KECIL', grande: 'BESAR',
    tocar: 'KETIK UNTUK SAMBUNG', menos10: '−10', puntos: 'MATA', todas: 'SEMUA PEDANG',
    nombresFilo: ['BERUS', 'MERAH SAGA', 'JED', 'NILA', 'DAUN EMAS'],
  },
  fil: {
    idioma: 'PUMILI NG WIKA', subtitulo: 'ANG DAAN NG TALIM', elegir: 'HUMIWA NG PRUTAS PARA MAGSIMULA',
    clasico: 'KLASIKO', clasicoD: 'TATLONG MINTIS · INGAT SA BOMBA', zen: 'ZEN', zenD: '90 SEGUNDONG WALANG BOMBA', tormenta: 'BAGYO', tormentaD: '60 SEGUNDONG MAY KAPANGYARIHAN',
    diario: 'ARAW-ARAW', diarioD: 'PAREHONG PRUTAS PARA SA LAHAT', dojo: 'DOJO', controles: 'KONTROL', idiomaBtn: 'WIKA', record: 'REKORD', hoyRec: 'NGAYON {0}',
    combo: 'COMBO ×{0}', fin: 'DULO NG DAAN', bomba: 'BOMBA!', tiempo: 'UBOS NA ANG ORAS!', otra: 'ULIT', menu: 'MENU', pausa: 'HINTO', seguir: 'ITULOY',
    reiniciar: 'SIMULAN ULIT', musica: 'MUSIKA', sonido: 'TUNOG', si: 'OO', no: 'HINDI', nuevoRecord: 'BAGONG REKORD!', volver: 'BUMALIK',
    ayuda: 'I-SWIPE ANG DALIRI PARA HIWAIN ANG PRUTAS. HUWAG HAWAKAN ANG BOMBA.', ayudaFalla: 'KAPAG NAHULOG ANG PRUTAS NANG HINDI NAHIWA, MINTIS IYON.', cortadas: 'NAHIWA', mejorCombo: 'PINAKAMAHUSAY NA COMBO',
    hielo: 'YELO', frenesi: 'SIKLAB', doble: 'DOBLE', filos: 'MGA TALIM', usar: 'GAMITIN', enUso: 'GINAGAMIT', faltan: 'HUMIWA PA NG {0}', nuevoFilo: 'BAGONG TALIM: {0}!',
    grosor: 'KAPAL NG GUHIT', sensib: 'SENSITIBIDAD', alcance: 'ABOT NG HIWA', tamPausa: 'PINDUTANG HINTO', zurdo: 'KALIWETE', vibrar: 'VIBRATE', proba: 'SUBUKAN DITO',
    restablecer: 'I-RESET', listo: 'TAPOS', baja: 'MABABA', media: 'KATAMTAMAN', alta: 'MATAAS', fino: 'MANIPIS', medio: 'KATAMTAMAN', grueso: 'MAKAPAL', chico: 'MALIIT', grande: 'MALAKI',
    tocar: 'I-TAP PARA ITULOY', menos10: '−10', puntos: 'PUNTOS', todas: 'LAHAT NG TALIM',
    nombresFilo: ['PINSEL', 'BERMILYON', 'JADE', 'INDIGO', 'DAHONG GINTO'],
  },
  tr: {
    idioma: 'DİLİNİ SEÇ', subtitulo: 'KILICIN YOLU', elegir: 'BAŞLAMAK İÇİN BİR MEYVE KES',
    clasico: 'KLASİK', clasicoD: 'ÜÇ HATA · BOMBALARA DİKKAT', zen: 'ZEN', zenD: 'BOMBASIZ 90 SANİYE', tormenta: 'FIRTINA', tormentaD: 'GÜÇLERLE 60 SANİYE',
    diario: 'GÜNLÜK', diarioD: 'HERKES İÇİN AYNI MEYVELER', dojo: 'DOJO', controles: 'KONTROLLER', idiomaBtn: 'DİL', record: 'REKOR', hoyRec: 'BUGÜN {0}',
    combo: 'KOMBO ×{0}', fin: 'YOLUN SONU', bomba: 'BOMBA!', tiempo: 'SÜRE DOLDU!', otra: 'TEKRAR', menu: 'MENÜ', pausa: 'DURAKLAT', seguir: 'DEVAM',
    reiniciar: 'YENİDEN BAŞLAT', musica: 'MÜZİK', sonido: 'SES', si: 'AÇIK', no: 'KAPALI', nuevoRecord: 'YENİ REKOR!', volver: 'GERİ',
    ayuda: 'MEYVEYİ KESMEK İÇİN PARMAĞINI KAYDIR. BOMBALARA DOKUNMA.', ayudaFalla: 'BİR MEYVE KESİLMEDEN DÜŞERSE HATA SAYILIR.', cortadas: 'KESİLEN', mejorCombo: 'EN İYİ KOMBO',
    hielo: 'BUZ', frenesi: 'ÇILGINLIK', doble: 'ÇİFT', filos: 'BIÇAKLAR', usar: 'KULLAN', enUso: 'KULLANIMDA', faltan: '{0} TANE DAHA KES', nuevoFilo: 'YENİ BIÇAK: {0}!',
    grosor: 'İZ KALINLIĞI', sensib: 'HASSASİYET', alcance: 'KESİM MENZİLİ', tamPausa: 'DURAKLATMA DÜĞMESİ', zurdo: 'SOLAK', vibrar: 'TİTREŞİM', proba: 'BURADA DENE',
    restablecer: 'SIFIRLA', listo: 'TAMAM', baja: 'DÜŞÜK', media: 'ORTA', alta: 'YÜKSEK', fino: 'İNCE', medio: 'ORTA', grueso: 'KALIN', chico: 'KÜÇÜK', grande: 'BÜYÜK',
    tocar: 'DEVAM İÇİN DOKUN', menos10: '−10', puntos: 'PUAN', todas: 'TÜM BIÇAKLAR',
    nombresFilo: ['FIRÇA', 'ZİNCİFRE', 'YEŞİM', 'ÇİVİT', 'ALTIN VARAK'],
  },
  ur: {
    idioma: 'اپنی زبان منتخب کریں', subtitulo: 'دھار کا راستہ', elegir: 'شروع کرنے کے لیے کوئی پھل کاٹیں',
    clasico: 'کلاسک', clasicoD: 'تین غلطیاں · بموں سے بچیں', zen: 'زین', zenD: 'بموں کے بغیر 90 سیکنڈ', tormenta: 'طوفان', tormentaD: 'طاقتوں کے ساتھ 60 سیکنڈ',
    diario: 'آج کا چیلنج', diarioD: 'سب کے لیے ایک جیسے پھل', dojo: 'ڈوجو', controles: 'کنٹرولز', idiomaBtn: 'زبان', record: 'ریکارڈ', hoyRec: 'آج {0}',
    combo: 'کومبو ×{0}', fin: 'راستے کا اختتام', bomba: 'بم!', tiempo: 'وقت ختم!', otra: 'دوبارہ', menu: 'مینیو', pausa: 'وقفہ', seguir: 'جاری رکھیں',
    reiniciar: 'دوبارہ شروع', musica: 'موسیقی', sonido: 'آواز', si: 'ہاں', no: 'نہیں', nuevoRecord: 'نیا ریکارڈ!', volver: 'واپس',
    ayuda: 'پھل کاٹنے کے لیے انگلی پھیریں۔ بموں کو مت چھوئیں۔', ayudaFalla: 'اگر کوئی پھل کٹے بغیر گر جائے تو یہ غلطی ہے۔', cortadas: 'کٹے ہوئے', mejorCombo: 'بہترین کومبو',
    hielo: 'برف', frenesi: 'جنون', doble: 'دگنا', filos: 'دھاریں', usar: 'استعمال کریں', enUso: 'استعمال میں', faltan: 'مزید {0} کاٹیں', nuevoFilo: 'نئی دھار: {0}!',
    grosor: 'لکیر کی موٹائی', sensib: 'حساسیت', alcance: 'کاٹ کی پہنچ', tamPausa: 'وقفے کا بٹن', zurdo: 'بائیں ہاتھ والا', vibrar: 'تھرتھراہٹ', proba: 'یہاں آزمائیں',
    restablecer: 'اصل ترتیب', listo: 'ٹھیک ہے', baja: 'کم', media: 'درمیانی', alta: 'زیادہ', fino: 'باریک', medio: 'درمیانہ', grueso: 'موٹا', chico: 'چھوٹا', grande: 'بڑا',
    tocar: 'جاری رکھنے کے لیے ٹیپ کریں', menos10: '−10', puntos: 'پوائنٹس', todas: 'تمام دھاریں',
    nombresFilo: ['برش', 'شنگرفی', 'یشب', 'نیلا', 'سونے کا ورق'],
  },
  th: {
    idioma: 'เลือกภาษา', subtitulo: 'วิถีแห่งคมดาบ', elegir: 'ฟันผลไม้เพื่อเริ่ม',
    clasico: 'คลาสสิก', clasicoD: 'พลาดได้ 3 ครั้ง · ระวังระเบิด', zen: 'เซน', zenD: '90 วินาที ไม่มีระเบิด', tormenta: 'พายุ', tormentaD: '60 วินาที พร้อมพลังพิเศษ',
    diario: 'รายวัน', diarioD: 'ผลไม้ชุดเดียวกันสำหรับทุกคน', dojo: 'โดโจ', controles: 'การควบคุม', idiomaBtn: 'ภาษา', record: 'สถิติ', hoyRec: 'วันนี้ {0}',
    combo: 'คอมโบ ×{0}', fin: 'สุดทาง', bomba: 'ระเบิด!', tiempo: 'หมดเวลา!', otra: 'อีกครั้ง', menu: 'เมนู', pausa: 'หยุดชั่วคราว', seguir: 'เล่นต่อ',
    reiniciar: 'เริ่มใหม่', musica: 'เพลง', sonido: 'เสียง', si: 'เปิด', no: 'ปิด', nuevoRecord: 'สถิติใหม่!', volver: 'กลับ',
    ayuda: 'ลากนิ้วเพื่อฟันผลไม้ อย่าแตะระเบิด', ayudaFalla: 'ถ้าผลไม้ตกลงไปโดยไม่ถูกฟัน จะนับเป็นการพลาด', cortadas: 'ฟันได้', mejorCombo: 'คอมโบสูงสุด',
    hielo: 'แช่แข็ง', frenesi: 'บ้าคลั่ง', doble: 'สองเท่า', filos: 'ใบมีด', usar: 'ใช้', enUso: 'กำลังใช้', faltan: 'ฟันอีก {0} ลูก', nuevoFilo: 'ใบมีดใหม่: {0}!',
    grosor: 'ความหนาของรอย', sensib: 'ความไว', alcance: 'ระยะฟัน', tamPausa: 'ปุ่มหยุด', zurdo: 'ถนัดซ้าย', vibrar: 'สั่น', proba: 'ลองที่นี่',
    restablecer: 'คืนค่าเดิม', listo: 'เสร็จ', baja: 'ต่ำ', media: 'กลาง', alta: 'สูง', fino: 'บาง', medio: 'กลาง', grueso: 'หนา', chico: 'เล็ก', grande: 'ใหญ่',
    tocar: 'แตะเพื่อเล่นต่อ', menos10: '−10', puntos: 'คะแนน', todas: 'ใบมีดทั้งหมด',
    nombresFilo: ['พู่กัน', 'ชาด', 'หยก', 'คราม', 'ทองคำเปลว'],
  },
  my: {
    idioma: 'ဘာသာစကား ရွေးပါ', subtitulo: 'ဓားသွား၏ လမ်း', elegir: 'စတင်ရန် အသီးတစ်လုံး ခုတ်ပါ',
    clasico: 'ဂန္ထဝင်', clasicoD: 'အမှား 3 ကြိမ် · ဗုံးကို သတိထားပါ', zen: 'ဇင်', zenD: 'ဗုံးမပါ 90 စက္ကန့်', tormenta: 'မုန်တိုင်း', tormentaD: 'စွမ်းအားများနှင့် 60 စက္ကန့်',
    diario: 'နေ့စဉ်', diarioD: 'လူတိုင်းအတွက် အသီးတူတူ', dojo: 'ဒိုဂျို', controles: 'ထိန်းချုပ်မှု', idiomaBtn: 'ဘာသာစကား', record: 'စံချိန်', hoyRec: 'ယနေ့ {0}',
    combo: 'ကွန်ဘို ×{0}', fin: 'လမ်းဆုံး', bomba: 'ဗုံး!', tiempo: 'အချိန်ကုန်ပြီ!', otra: 'ထပ်ကစား', menu: 'မီနူး', pausa: 'ခဏရပ်', seguir: 'ဆက်ကစား',
    reiniciar: 'ပြန်စ', musica: 'ဂီတ', sonido: 'အသံ', si: 'ဖွင့်', no: 'ပိတ်', nuevoRecord: 'စံချိန်သစ်!', volver: 'နောက်သို့',
    ayuda: 'အသီးကို ခုတ်ရန် လက်ချောင်းကို ပွတ်ဆွဲပါ။ ဗုံးကို မထိပါနှင့်။', ayudaFalla: 'အသီးကို မခုတ်ဘဲ ကျသွားလျှင် အမှားတစ်ခု ဖြစ်သည်။', cortadas: 'ခုတ်ပြီး', mejorCombo: 'အကောင်းဆုံး ကွန်ဘို',
    hielo: 'အေးခဲ', frenesi: 'ရူးသွပ်', doble: 'နှစ်ဆ', filos: 'ဓားသွားများ', usar: 'သုံးမည်', enUso: 'သုံးနေသည်', faltan: 'နောက်ထပ် {0} လုံး ခုတ်ပါ', nuevoFilo: 'ဓားသွားသစ်: {0}!',
    grosor: 'အစင်းအထူ', sensib: 'အာရုံခံနိုင်မှု', alcance: 'ခုတ်နိုင်သည့်အကွာ', tamPausa: 'ရပ်ခလုတ်', zurdo: 'ဘယ်သန်', vibrar: 'တုန်ခါမှု', proba: 'ဒီမှာ စမ်းပါ',
    restablecer: 'မူလအတိုင်း', listo: 'ပြီးပြီ', baja: 'နိမ့်', media: 'အလယ်', alta: 'မြင့်', fino: 'ပါး', medio: 'အလယ်', grueso: 'ထူ', chico: 'သေး', grande: 'ကြီး',
    tocar: 'ဆက်ရန် နှိပ်ပါ', menos10: '−10', puntos: 'ရမှတ်', todas: 'ဓားသွားအားလုံး',
    nombresFilo: ['စုတ်တံ', 'ဟင်္သပဒါး', 'ကျောက်စိမ်း', 'မဲနယ်', 'ရွှေဆိုင်း'],
  },
  ja: {
    idioma: '言語を選択', subtitulo: '刃の道', elegir: 'フルーツを斬ってスタート',
    clasico: 'クラシック', clasicoD: 'ミス3回まで・爆弾に注意', zen: '禅', zenD: '爆弾なしの90秒', tormenta: '嵐', tormentaD: 'パワーありの60秒',
    diario: 'デイリー', diarioD: 'みんな同じフルーツ', dojo: '道場', controles: '操作設定', idiomaBtn: '言語', record: 'ベスト', hoyRec: '今日 {0}',
    combo: 'コンボ ×{0}', fin: '道の終わり', bomba: '爆弾！', tiempo: 'タイムアップ！', otra: 'もう一度', menu: 'メニュー', pausa: 'ポーズ', seguir: '再開',
    reiniciar: 'やり直す', musica: '音楽', sonido: '効果音', si: 'オン', no: 'オフ', nuevoRecord: '新記録！', volver: '戻る',
    ayuda: '指をスワイプしてフルーツを斬ろう。爆弾には触れないで。', ayudaFalla: '斬らずにフルーツを落とすとミスになる。', cortadas: '斬った数', mejorCombo: '最高コンボ',
    hielo: '氷結', frenesi: '乱舞', doble: '2倍', filos: '刃', usar: '使う', enUso: '使用中', faltan: 'あと{0}個斬ろう', nuevoFilo: '新しい刃：{0}！',
    grosor: '軌跡の太さ', sensib: '感度', alcance: '斬る範囲', tamPausa: 'ポーズボタン', zurdo: '左利き', vibrar: '振動', proba: 'ここで試す',
    restablecer: '初期設定に戻す', listo: '完了', baja: '低', media: '中', alta: '高', fino: '細い', medio: '普通', grueso: '太い', chico: '小', grande: '大',
    tocar: 'タップして続ける', menos10: '−10', puntos: 'ポイント', todas: 'すべての刃',
    nombresFilo: ['筆', '朱', '翡翠', '藍', '金箔'],
  },
});
