/* ============================================================================
   FILETE — los idiomas que se sumaron el 08/10 (la lista está en
   motor2d/idiomas.js). El de México es el mismo español con tuteo; Egipto,
   Irak y Arabia Saudita usan el árabe estándar. Lo que falte cae en inglés.
   Los barrios (San Telmo, La Boca…) quedan con su nombre, como en el cartel.
   ========================================================================== */

TXT['es-MX'] = Object.assign({}, TXT.es, {
  idioma: 'ELIGE TU IDIOMA', aventuraD: 'JUNTA LAS FLORES', seguirPartida: 'CONTINUAR LA PARTIDA', seguir: 'CONTINUAR', otra: 'OTRA VEZ',
  elogios: ['¡BONITO!', '¡CHIDO!', '¡GENIAL!', '¡DE PELÍCULA!', '¡UNA OBRA DE ARTE!'], bloqueado: 'JUNTA {0}', proba: 'PRUEBA AQUÍ',
  ayuda: 'ARRASTRA LAS PIEZAS AL TABLERO. LLENA FILAS O COLUMNAS PARA BORRARLAS.', ayudaFlores: 'BORRA LAS FILAS O COLUMNAS DONDE ESTÁN LAS FLORES PARA JUNTARLAS.',
  tocar: 'TOCA PARA CONTINUAR',
});

Object.assign(TXT, {
  ar: {
    idioma: 'اختر لغتك', subtitulo: 'لغز بوينس آيرس',
    clasico: 'كلاسيكي', clasicoD: 'إلى أبعد ما تستطيع', aventura: 'الأحياء', aventuraD: 'اجمع الزهور', diario: 'تحدي اليوم',
    controles: 'التحكم', idiomaBtn: 'اللغة', record: 'أفضل نتيجة', hoyRec: 'اليوم {0}', seguirPartida: 'متابعة اللعبة',
    elogios: ['جميل!', 'رائع!', 'مذهل!', 'كالأفلام!', 'تحفة فنية!'], limpio: 'لوحة نظيفة!', combo: 'كومبو',
    fin: 'انتهى العرض', sinLugar: 'لا مكان بعد الآن', otra: 'مرة أخرى', menu: 'القائمة', pausa: 'إيقاف مؤقت', seguir: 'متابعة', reiniciar: 'إعادة',
    musica: 'الموسيقى', sonido: 'الصوت', si: 'تشغيل', no: 'إيقاف', cambio: 'تبديل', nivel: 'المستوى {0}', flores: 'الزهور', puntos: 'النقاط',
    ganaste: 'يا له من فن!', nivelHecho: 'اكتمل المستوى', siguiente: 'التالي', reintentar: 'حاول مجددًا', bloqueado: 'اجمع {0}',
    altura: 'ارتفاع القطعة', velocidad: 'سرعة الإصبع', bandeja: 'حجم منطقة القطع', guia: 'دليل الوضع', zurdo: 'أعسر', vibrar: 'الاهتزاز',
    proba: 'جرّب هنا', restablecer: 'الإعدادات الأصلية', listo: 'تم', nuevoRecord: 'رقم قياسي جديد!', volver: 'رجوع',
    ayuda: 'اسحب القطع إلى اللوحة. املأ صفوفًا أو أعمدة لمسحها.', ayudaFlores: 'امسح الصفوف أو الأعمدة التي فيها الزهور لتجمعها.',
    tocar: 'المس للمتابعة', cambioD: 'يبدّل القطع الثلاث',
  },
  id: {
    idioma: 'PILIH BAHASAMU', subtitulo: 'TEKA-TEKI BUENOS AIRES',
    clasico: 'KLASIK', clasicoD: 'SEJAUH YANG KAMU BISA', aventura: 'KAWASAN', aventuraD: 'KUMPULKAN BUNGA', diario: 'TANTANGAN HARIAN',
    controles: 'KONTROL', idiomaBtn: 'BAHASA', record: 'REKOR', hoyRec: 'HARI INI {0}', seguirPartida: 'LANJUTKAN PERMAINAN',
    elogios: ['BAGUS!', 'HEBAT!', 'KEREN!', 'LUAR BIASA!', 'KARYA SENI!'], limpio: 'PAPAN BERSIH!', combo: 'KOMBO',
    fin: 'PERTUNJUKAN SELESAI', sinLugar: 'TIDAK ADA TEMPAT LAGI', otra: 'LAGI', menu: 'MENU', pausa: 'JEDA', seguir: 'LANJUT', reiniciar: 'ULANGI',
    musica: 'MUSIK', sonido: 'SUARA', si: 'NYALA', no: 'MATI', cambio: 'TUKAR', nivel: 'LEVEL {0}', flores: 'BUNGA', puntos: 'POIN',
    ganaste: 'SENI SEKALI!', nivelHecho: 'LEVEL SELESAI', siguiente: 'BERIKUTNYA', reintentar: 'COBA LAGI', bloqueado: 'KUMPULKAN {0}',
    altura: 'TINGGI KEPINGAN', velocidad: 'KECEPATAN JARI', bandeja: 'UKURAN BAKI', guia: 'PANDUAN LETAK', zurdo: 'KIDAL', vibrar: 'GETAR',
    proba: 'COBA DI SINI', restablecer: 'ATUR ULANG', listo: 'SELESAI', nuevoRecord: 'REKOR BARU!', volver: 'KEMBALI',
    ayuda: 'SERET KEPINGAN KE PAPAN. PENUHI BARIS ATAU KOLOM UNTUK MENGHAPUSNYA.', ayudaFlores: 'HAPUS BARIS ATAU KOLOM TEMPAT BUNGA BERADA UNTUK MENGUMPULKANNYA.',
    tocar: 'SENTUH UNTUK LANJUT', cambioD: 'MENUKAR KETIGA KEPINGAN',
  },
  ms: {
    idioma: 'PILIH BAHASA ANDA', subtitulo: 'TEKA-TEKI BUENOS AIRES',
    clasico: 'KLASIK', clasicoD: 'SEJAUH YANG ANDA MAMPU', aventura: 'KAWASAN', aventuraD: 'KUMPUL BUNGA', diario: 'CABARAN HARIAN',
    controles: 'KAWALAN', idiomaBtn: 'BAHASA', record: 'REKOD', hoyRec: 'HARI INI {0}', seguirPartida: 'SAMBUNG PERMAINAN',
    elogios: ['BAGUS!', 'HEBAT!', 'MANTAP!', 'LUAR BIASA!', 'KARYA SENI!'], limpio: 'PAPAN BERSIH!', combo: 'KOMBO',
    fin: 'PERSEMBAHAN TAMAT', sinLugar: 'TIADA RUANG LAGI', otra: 'LAGI', menu: 'MENU', pausa: 'JEDA', seguir: 'SAMBUNG', reiniciar: 'MULA SEMULA',
    musica: 'MUZIK', sonido: 'BUNYI', si: 'HIDUP', no: 'MATI', cambio: 'TUKAR', nivel: 'TAHAP {0}', flores: 'BUNGA', puntos: 'MATA',
    ganaste: 'SUNGGUH SENI!', nivelHecho: 'TAHAP SELESAI', siguiente: 'SETERUSNYA', reintentar: 'CUBA LAGI', bloqueado: 'KUMPUL {0}',
    altura: 'TINGGI KEPINGAN', velocidad: 'KELAJUAN JARI', bandeja: 'SAIZ DULANG', guia: 'PANDUAN LETAK', zurdo: 'KIDAL', vibrar: 'GETARAN',
    proba: 'CUBA DI SINI', restablecer: 'TETAP SEMULA', listo: 'SIAP', nuevoRecord: 'REKOD BARU!', volver: 'KEMBALI',
    ayuda: 'SERET KEPINGAN KE PAPAN. PENUHKAN BARIS ATAU LAJUR UNTUK MEMADAMNYA.', ayudaFlores: 'PADAM BARIS ATAU LAJUR YANG ADA BUNGA UNTUK MENGUMPULNYA.',
    tocar: 'SENTUH UNTUK SAMBUNG', cambioD: 'MENUKAR KETIGA-TIGA KEPINGAN',
  },
  fil: {
    idioma: 'PUMILI NG WIKA', subtitulo: 'ANG PALAISIPAN NG BUENOS AIRES',
    clasico: 'KLASIKO', clasicoD: 'HANGGANG SAAN KA AABOT', aventura: 'MGA BARYO', aventuraD: 'IPUNIN ANG MGA BULAKLAK', diario: 'HAMON NGAYONG ARAW',
    controles: 'KONTROL', idiomaBtn: 'WIKA', record: 'PINAKAMATAAS', hoyRec: 'NGAYON {0}', seguirPartida: 'ITULOY ANG LARO',
    elogios: ['AYOS!', 'GALING!', 'ASTIG!', 'PANG-PELIKULA!', 'OBRA MAESTRA!'], limpio: 'MALINIS NA ANG BOARD!', combo: 'COMBO',
    fin: 'TAPOS ANG PALABAS', sinLugar: 'WALA NANG PUWANG', otra: 'ULIT', menu: 'MENU', pausa: 'HINTO', seguir: 'ITULOY', reiniciar: 'ULITIN',
    musica: 'MUSIKA', sonido: 'TUNOG', si: 'BUKAS', no: 'SARADO', cambio: 'PALIT', nivel: 'LEVEL {0}', flores: 'BULAKLAK', puntos: 'PUNTOS',
    ganaste: 'NAPAKAGANDA!', nivelHecho: 'TAPOS ANG LEVEL', siguiente: 'SUSUNOD', reintentar: 'SUBUKAN ULIT', bloqueado: 'KAILANGAN {0}',
    altura: 'TAAS NG PIRASO', velocidad: 'BILIS NG DALIRI', bandeja: 'LAKI NG TRAY', guia: 'GABAY SA PAGLAGAY', zurdo: 'KALIWETE', vibrar: 'VIBRATE',
    proba: 'SUBUKAN DITO', restablecer: 'I-RESET', listo: 'TAPOS', nuevoRecord: 'BAGONG RECORD!', volver: 'BUMALIK',
    ayuda: 'I-DRAG ANG MGA PIRASO SA BOARD. PUNUIN ANG MGA HANAY O KOLUM PARA MABURA.', ayudaFlores: 'BURAHIN ANG MGA HANAY O KOLUM NA MAY BULAKLAK PARA MAIPON ITO.',
    tocar: 'PINDUTIN PARA ITULOY', cambioD: 'PINAPALITAN ANG TATLONG PIRASO',
  },
  tr: {
    idioma: 'DİLİNİ SEÇ', subtitulo: 'BUENOS AIRES BULMACASI',
    clasico: 'KLASİK', clasicoD: 'GİDEBİLDİĞİN YERE KADAR', aventura: 'MAHALLELER', aventuraD: 'ÇİÇEKLERİ TOPLA', diario: 'GÜNÜN GÖREVİ',
    controles: 'KONTROLLER', idiomaBtn: 'DİL', record: 'REKOR', hoyRec: 'BUGÜN {0}', seguirPartida: 'OYUNA DEVAM ET',
    elogios: ['GÜZEL!', 'SÜPER!', 'HARİKA!', 'MUHTEŞEM!', 'BİR SANAT ESERİ!'], limpio: 'TAHTA TERTEMİZ!', combo: 'KOMBO',
    fin: 'GÖSTERİ BİTTİ', sinLugar: 'YER KALMADI', otra: 'TEKRAR', menu: 'MENÜ', pausa: 'DURAKLAT', seguir: 'DEVAM', reiniciar: 'YENİDEN BAŞLAT',
    musica: 'MÜZİK', sonido: 'SES', si: 'AÇIK', no: 'KAPALI', cambio: 'DEĞİŞ', nivel: 'SEVİYE {0}', flores: 'ÇİÇEKLER', puntos: 'PUAN',
    ganaste: 'NE SANAT AMA!', nivelHecho: 'SEVİYE TAMAM', siguiente: 'SIRADAKİ', reintentar: 'TEKRAR DENE', bloqueado: '{0} TOPLA',
    altura: 'PARÇA YÜKSEKLİĞİ', velocidad: 'PARMAK HIZI', bandeja: 'TEPSİ BOYUTU', guia: 'YERLEŞTİRME KILAVUZU', zurdo: 'SOLAK', vibrar: 'TİTREŞİM',
    proba: 'BURADA DENE', restablecer: 'SIFIRLA', listo: 'TAMAM', nuevoRecord: 'YENİ REKOR!', volver: 'GERİ',
    ayuda: 'PARÇALARI TAHTAYA SÜRÜKLE. SATIR YA DA SÜTUNLARI DOLDURUP SİL.', ayudaFlores: 'ÇİÇEKLERİ TOPLAMAK İÇİN ONLARIN OLDUĞU SATIR YA DA SÜTUNLARI SİL.',
    tocar: 'DEVAM İÇİN DOKUN', cambioD: 'ÜÇ PARÇAYI DEĞİŞTİRİR',
  },
  ur: {
    idioma: 'اپنی زبان چنیں', subtitulo: 'بیونس آئرس کی پہیلی',
    clasico: 'کلاسک', clasicoD: 'جہاں تک پہنچ سکیں', aventura: 'محلے', aventuraD: 'پھول جمع کریں', diario: 'آج کا چیلنج',
    controles: 'کنٹرولز', idiomaBtn: 'زبان', record: 'بہترین', hoyRec: 'آج {0}', seguirPartida: 'کھیل جاری رکھیں',
    elogios: ['خوب!', 'زبردست!', 'شاندار!', 'کمال!', 'فن کا شاہکار!'], limpio: 'بورڈ صاف!', combo: 'کومبو',
    fin: 'تماشا ختم', sinLugar: 'مزید جگہ نہیں', otra: 'دوبارہ', menu: 'مینو', pausa: 'وقفہ', seguir: 'جاری رکھیں', reiniciar: 'دوبارہ شروع',
    musica: 'موسیقی', sonido: 'آواز', si: 'آن', no: 'آف', cambio: 'تبدیل', nivel: 'لیول {0}', flores: 'پھول', puntos: 'پوائنٹس',
    ganaste: 'کیا فن ہے!', nivelHecho: 'لیول مکمل', siguiente: 'اگلا', reintentar: 'دوبارہ کوشش', bloqueado: '{0} جمع کریں',
    altura: 'ٹکڑے کی اونچائی', velocidad: 'انگلی کی رفتار', bandeja: 'ٹرے کا سائز', guia: 'رکھنے کی رہنمائی', zurdo: 'بائیں ہاتھ والا', vibrar: 'تھرتھراہٹ',
    proba: 'یہاں آزمائیں', restablecer: 'ری سیٹ', listo: 'ہو گیا', nuevoRecord: 'نیا ریکارڈ!', volver: 'واپس',
    ayuda: 'ٹکڑوں کو بورڈ پر گھسیٹیں۔ قطاریں یا کالم بھر کر انہیں مٹائیں۔', ayudaFlores: 'پھول جمع کرنے کے لیے وہ قطاریں یا کالم مٹائیں جن میں پھول ہیں۔',
    tocar: 'جاری رکھنے کے لیے چھوئیں', cambioD: 'تینوں ٹکڑے بدل دیتا ہے',
  },
  th: {
    idioma: 'เลือกภาษาของคุณ', subtitulo: 'ปริศนาแห่งบัวโนสไอเรส',
    clasico: 'คลาสสิก', clasicoD: 'ไปให้ไกลที่สุด', aventura: 'ย่านต่างๆ', aventuraD: 'เก็บดอกไม้', diario: 'ภารกิจประจำวัน',
    controles: 'การควบคุม', idiomaBtn: 'ภาษา', record: 'สถิติ', hoyRec: 'วันนี้ {0}', seguirPartida: 'เล่นต่อจากเดิม',
    elogios: ['ดี!', 'เยี่ยม!', 'สุดยอด!', 'อย่างกับหนัง!', 'งานศิลปะชัดๆ!'], limpio: 'กระดานโล่ง!', combo: 'คอมโบ',
    fin: 'จบการแสดง', sinLugar: 'ไม่มีที่ว่างแล้ว', otra: 'อีกครั้ง', menu: 'เมนู', pausa: 'หยุดชั่วคราว', seguir: 'เล่นต่อ', reiniciar: 'เริ่มใหม่',
    musica: 'ดนตรี', sonido: 'เสียง', si: 'เปิด', no: 'ปิด', cambio: 'สลับ', nivel: 'ด่าน {0}', flores: 'ดอกไม้', puntos: 'คะแนน',
    ganaste: 'ศิลปะสุดๆ!', nivelHecho: 'ผ่านด่าน', siguiente: 'ถัดไป', reintentar: 'ลองอีกครั้ง', bloqueado: 'เก็บ {0}',
    altura: 'ความสูงของชิ้น', velocidad: 'ความเร็วนิ้ว', bandeja: 'ขนาดถาด', guia: 'ตัวช่วยวาง', zurdo: 'ถนัดซ้าย', vibrar: 'สั่น',
    proba: 'ลองตรงนี้', restablecer: 'คืนค่าเดิม', listo: 'เสร็จ', nuevoRecord: 'สถิติใหม่!', volver: 'กลับ',
    ayuda: 'ลากชิ้นส่วนลงบนกระดาน เติมแถวหรือคอลัมน์ให้เต็มเพื่อลบออก', ayudaFlores: 'ลบแถวหรือคอลัมน์ที่มีดอกไม้เพื่อเก็บดอกไม้',
    tocar: 'แตะเพื่อเล่นต่อ', cambioD: 'สลับชิ้นทั้งสาม',
  },
  my: {
    idioma: 'ဘာသာစကား ရွေးပါ', subtitulo: 'ဘွန်နိုအဲရီး ပဟေဠိ',
    clasico: 'ဂန္ထဝင်', clasicoD: 'ရောက်နိုင်သလောက်', aventura: 'ရပ်ကွက်များ', aventuraD: 'ပန်းများ စုဆောင်းပါ', diario: 'ယနေ့ စိန်ခေါ်မှု',
    controles: 'ထိန်းချုပ်မှု', idiomaBtn: 'ဘာသာစကား', record: 'အမြင့်ဆုံး', hoyRec: 'ယနေ့ {0}', seguirPartida: 'ဆက်ကစားမည်',
    elogios: ['ကောင်းတယ်!', 'တော်တယ်!', 'အံ့ဩစရာ!', 'ရုပ်ရှင်လိုပဲ!', 'အနုပညာလက်ရာ!'], limpio: 'ဘုတ် ရှင်းသွားပြီ!', combo: 'ကွန်ဘို',
    fin: 'ပွဲပြီးပြီ', sinLugar: 'နေရာ မကျန်တော့ပါ', otra: 'ထပ်ကစား', menu: 'မီနူး', pausa: 'ခဏရပ်', seguir: 'ဆက်ရန်', reiniciar: 'အစမှ ပြန်စ',
    musica: 'ဂီတ', sonido: 'အသံ', si: 'ဖွင့်', no: 'ပိတ်', cambio: 'လဲရန်', nivel: 'အဆင့် {0}', flores: 'ပန်းများ', puntos: 'ရမှတ်',
    ganaste: 'အနုပညာပဲ!', nivelHecho: 'အဆင့် ပြီးပြီ', siguiente: 'နောက်တစ်ဆင့်', reintentar: 'ထပ်ကြိုးစား', bloqueado: '{0} စုပါ',
    altura: 'အပိုင်းအမြင့်', velocidad: 'လက်ချောင်းအမြန်', bandeja: 'ဗန်းအရွယ်', guia: 'နေရာချ လမ်းညွှန်', zurdo: 'ဘယ်သန်', vibrar: 'တုန်ခါမှု',
    proba: 'ဒီမှာ စမ်းကြည့်ပါ', restablecer: 'မူလအတိုင်း', listo: 'ပြီးပြီ', nuevoRecord: 'စံချိန်သစ်!', volver: 'နောက်သို့',
    ayuda: 'အပိုင်းများကို ဘုတ်ပေါ်သို့ ဆွဲပါ။ အတန်း သို့မဟုတ် ကော်လံ ပြည့်လျှင် ပျက်သွားမည်။', ayudaFlores: 'ပန်းများကို စုရန် ပန်းရှိသော အတန်း သို့မဟုတ် ကော်လံကို ဖျက်ပါ။',
    tocar: 'ဆက်ရန် ထိပါ', cambioD: 'အပိုင်း သုံးခုလုံးကို လဲပေးသည်',
  },
  ja: {
    idioma: '言語を選択', subtitulo: 'ブエノスアイレスのパズル',
    clasico: 'クラシック', clasicoD: 'どこまで行けるか', aventura: '街めぐり', aventuraD: '花を集めよう', diario: '今日のチャレンジ',
    controles: '操作設定', idiomaBtn: '言語', record: 'ベスト', hoyRec: '今日 {0}', seguirPartida: '続きから遊ぶ',
    elogios: ['いいね！', 'すごい！', '見事！', '映画みたい！', 'まさに芸術！'], limpio: '盤面クリア！', combo: 'コンボ',
    fin: '幕引き', sinLugar: 'もう置けない', otra: 'もう一回', menu: 'メニュー', pausa: 'ポーズ', seguir: '再開', reiniciar: 'やり直す',
    musica: '音楽', sonido: '効果音', si: 'オン', no: 'オフ', cambio: '交換', nivel: 'レベル {0}', flores: '花', puntos: 'ポイント',
    ganaste: '芸術的！', nivelHecho: 'レベルクリア', siguiente: 'つぎへ', reintentar: 'もう一度', bloqueado: '{0}個集めよう',
    altura: 'ピースの高さ', velocidad: '指の速さ', bandeja: 'トレイの大きさ', guia: '配置ガイド', zurdo: '左きき', vibrar: '振動',
    proba: 'ここで試そう', restablecer: '初期設定に戻す', listo: '完了', nuevoRecord: '新記録！', volver: '戻る',
    ayuda: 'ピースを盤面にドラッグ。縦か横の列をそろえると消えるよ。', ayudaFlores: '花のある列を消すと花を集められるよ。',
    tocar: 'タップで続ける', cambioD: '3つのピースを入れ替える',
  },
});
