/* ============================================================================
   SALAMANCA — los idiomas que se sumaron el 08/10 (la lista está en
   motor2d/idiomas.js). El de México es el mismo español con tuteo (y el pilón
   en vez de la yapa); Egipto, Irak y Arabia Saudita usan el árabe estándar.
   Las cartas y el altar traen su tabla [nombre, descripción] por idioma; lo
   que falte cae en inglés. Mandinga, Pombero y copla quedan con su nombre.
   ========================================================================== */

TXT['es-MX'] = Object.assign({}, TXT.es, {
  idioma: 'ELIGE TU IDIOMA', seguir: 'CONTINUAR', yapa: 'EL PILÓN', tocaCarta: 'TOCA UNA CARTA', tocar: 'TOCA PARA CONTINUAR',
  historia: ['EL MANDINGA SE LLEVÓ LAS ALMAS DEL PUEBLO A SU SALAMANCA.', 'BAJA CON EL FAROL DE LA ABUELA Y TRÁELAS DE VUELTA.'],
  ayuda: 'MUÉVETE PARA ESQUIVAR. QUÉDATE QUIETO PARA DISPARAR.', arrastra: 'ARRASTRA LA PALANCA Y EL BOTÓN',
});

Object.assign(TXT, {
  ar: {
    idioma: 'اختر لغتك', subtitulo: 'كهف الشيطان',
    jugar: 'العب', diario: 'تحدي اليوم', altar: 'المذبح', controles: 'التحكم', idiomaBtn: 'اللغة',
    record: 'الأفضل {0}', hoyRec: 'اليوم {0}', almas: 'الأرواح',
    historia: ['أخذ الشيطان أرواح أهل القرية إلى كهفه.', 'انزل بفانوس الجدة وأعد الأرواح إلى ديارها.'],
    ayuda: 'تحرّك لتتفادى. قف ساكنًا لتطلق النار.', ayudaPC: 'WASD أو الأسهم · المسافة: الأغنية · ESC: إيقاف',
    pisos: ['المدخل', 'المياه السوداء', 'الجمر', 'القاعة'], piso: 'الطابق {0}',
    nivel: 'ارتفع مستواك!', elegir: 'اختر', tocaCarta: 'المس بطاقة', yapa: 'هدية البداية',
    fogon: 'نار المخيم', fogonTxt: 'البومبيرو يعرض عليك صفقة.', descansar: 'استرح', descansarD: '+40% من الصحة',
    trato: 'صفقة', tratoD: 'بطاقة ملحمية مقابل 15% من الصحة القصوى',
    pausa: 'إيقاف مؤقت', seguir: 'متابعة', salir: 'الخروج إلى القائمة', musica: 'الموسيقى', sonido: 'الصوت', si: 'تشغيل', no: 'إيقاف', tusCartas: 'بطاقاتك',
    muerte: 'أمسك بك الكهف', llegaste: 'وصلت إلى {0}', nuevoRecord: 'رقم قياسي جديد!', otraVez: 'مرة أخرى', menu: 'القائمة',
    victoria: 'حرّرت الأرواح!', victoriaTxt: 'هرب الشيطان إلى الأعمق...', seguirBajando: 'واصل النزول',
    enemigos: 'الأعداء', nv: 'مستوى', revivir: 'حياة أخرى!', copla: 'الأغنية', limpio: 'نظيف!',
    palanca: 'العصا', flotante: 'عائمة', fija: 'ثابتة', tamPal: 'حجم العصا', tamBtn: 'حجم الزر', opac: 'الشفافية',
    zurdo: 'أعسر', vibrar: 'الاهتزاز', arrastra: 'اسحب العصا والزر', restablecer: 'الإعدادات الأصلية', listo: 'تم',
    comprar: 'شراء', max: 'الأقصى', mejorar: 'تحسينات دائمة', ganadas: '+{0} روح', nivelAlcanzado: 'المستوى {0}', muertos: '{0} عدو',
    jefes: ['الضفدع الملك', 'الأرملة', 'المستذئب', 'ماندينغا'], tocar: 'المس للمتابعة', nuevo: 'جديد', volver: 'رجوع',
  },
  id: {
    idioma: 'PILIH BAHASAMU', subtitulo: 'GUA SANG IBLIS',
    jugar: 'MAIN', diario: 'TANTANGAN HARIAN', altar: 'ALTAR', controles: 'KONTROL', idiomaBtn: 'BAHASA',
    record: 'REKOR {0}', hoyRec: 'HARI INI {0}', almas: 'JIWA',
    historia: ['IBLIS MEMBAWA JIWA-JIWA DESA KE GUANYA.', 'TURUNLAH DENGAN LENTERA NENEK DAN BAWA MEREKA PULANG.'],
    ayuda: 'BERGERAK UNTUK MENGHINDAR. DIAM UNTUK MENEMBAK.', ayudaPC: 'WASD ATAU PANAH · SPASI: COPLA · ESC: JEDA',
    pisos: ['MULUT GUA', 'AIR HITAM', 'BARA', 'AULA'], piso: 'LANTAI {0}',
    nivel: 'NAIK LEVEL!', elegir: 'PILIH', tocaCarta: 'SENTUH SEBUAH KARTU', yapa: 'BONUS AWAL',
    fogon: 'API UNGGUN', fogonTxt: 'POMBERO MENAWARKAN SEBUAH KESEPAKATAN.', descansar: 'ISTIRAHAT', descansarD: '+40% NYAWA',
    trato: 'KESEPAKATAN', tratoD: 'KARTU EPIK DITUKAR 15% NYAWA MAKS',
    pausa: 'JEDA', seguir: 'LANJUT', salir: 'KELUAR KE MENU', musica: 'MUSIK', sonido: 'SUARA', si: 'NYALA', no: 'MATI', tusCartas: 'KARTUMU',
    muerte: 'GUA ITU MENANGKAPMU', llegaste: 'KAMU MENCAPAI {0}', nuevoRecord: 'REKOR BARU!', otraVez: 'LAGI', menu: 'MENU',
    victoria: 'KAMU MEMBEBASKAN JIWA-JIWA!', victoriaTxt: 'IBLIS KABUR LEBIH DALAM...', seguirBajando: 'TERUS TURUN',
    enemigos: 'MUSUH', nv: 'LV', revivir: 'NYAWA KEDUA!', copla: 'COPLA', limpio: 'BERSIH!',
    palanca: 'STIK', flotante: 'MENGAMBANG', fija: 'TETAP', tamPal: 'UKURAN STIK', tamBtn: 'UKURAN TOMBOL', opac: 'TRANSPARANSI',
    zurdo: 'KIDAL', vibrar: 'GETAR', arrastra: 'SERET STIK DAN TOMBOLNYA', restablecer: 'ATUR ULANG', listo: 'SELESAI',
    comprar: 'BELI', max: 'MAKS', mejorar: 'PENINGKATAN PERMANEN', ganadas: '+{0} JIWA', nivelAlcanzado: 'LEVEL {0}', muertos: '{0} MUSUH',
    jefes: ['RAJA KODOK', 'SANG JANDA', 'MANUSIA SERIGALA', 'MANDINGA'], tocar: 'SENTUH UNTUK LANJUT', nuevo: 'BARU', volver: 'KEMBALI',
  },
  ms: {
    idioma: 'PILIH BAHASA ANDA', subtitulo: 'GUA SI IBLIS',
    jugar: 'MAIN', diario: 'CABARAN HARIAN', altar: 'ALTAR', controles: 'KAWALAN', idiomaBtn: 'BAHASA',
    record: 'REKOD {0}', hoyRec: 'HARI INI {0}', almas: 'JIWA',
    historia: ['IBLIS MEMBAWA JIWA PENDUDUK KAMPUNG KE GUANYA.', 'TURUN DENGAN PELITA NENEK DAN BAWA MEREKA PULANG.'],
    ayuda: 'BERGERAK UNTUK MENGELAK. BERDIRI DIAM UNTUK MENEMBAK.', ayudaPC: 'WASD ATAU ANAK PANAH · SPACE: COPLA · ESC: JEDA',
    pisos: ['MULUT GUA', 'AIR HITAM', 'BARA', 'DEWAN'], piso: 'TINGKAT {0}',
    nivel: 'NAIK TAHAP!', elegir: 'PILIH', tocaCarta: 'SENTUH SEKEPING KAD', yapa: 'BONUS MULA',
    fogon: 'UNGGUN API', fogonTxt: 'POMBERO MENAWARKAN SATU PERJANJIAN.', descansar: 'REHAT', descansarD: '+40% NYAWA',
    trato: 'PERJANJIAN', tratoD: 'KAD EPIK DENGAN 15% NYAWA MAKS',
    pausa: 'JEDA', seguir: 'SAMBUNG', salir: 'KELUAR KE MENU', musica: 'MUZIK', sonido: 'BUNYI', si: 'HIDUP', no: 'MATI', tusCartas: 'KAD ANDA',
    muerte: 'GUA ITU MENANGKAP ANDA', llegaste: 'ANDA SAMPAI KE {0}', nuevoRecord: 'REKOD BARU!', otraVez: 'LAGI', menu: 'MENU',
    victoria: 'ANDA MEMBEBASKAN JIWA-JIWA!', victoriaTxt: 'IBLIS LARI LEBIH DALAM...', seguirBajando: 'TERUS TURUN',
    enemigos: 'MUSUH', nv: 'TP', revivir: 'NYAWA KEDUA!', copla: 'COPLA', limpio: 'BERSIH!',
    palanca: 'KAYU BEDIK', flotante: 'TERAPUNG', fija: 'TETAP', tamPal: 'SAIZ KAYU BEDIK', tamBtn: 'SAIZ BUTANG', opac: 'KELUTSINARAN',
    zurdo: 'KIDAL', vibrar: 'GETARAN', arrastra: 'SERET KAYU BEDIK DAN BUTANG', restablecer: 'TETAP SEMULA', listo: 'SIAP',
    comprar: 'BELI', max: 'MAKS', mejorar: 'PENINGKATAN KEKAL', ganadas: '+{0} JIWA', nivelAlcanzado: 'TAHAP {0}', muertos: '{0} MUSUH',
    jefes: ['RAJA KATAK', 'SI BALU', 'SERIGALA JADIAN', 'MANDINGA'], tocar: 'SENTUH UNTUK SAMBUNG', nuevo: 'BAHARU', volver: 'KEMBALI',
  },
  fil: {
    idioma: 'PUMILI NG WIKA', subtitulo: 'ANG KUWEBA NG DEMONYO',
    jugar: 'MAGLARO', diario: 'HAMON NGAYONG ARAW', altar: 'ALTAR', controles: 'KONTROL', idiomaBtn: 'WIKA',
    record: 'REKORD {0}', hoyRec: 'NGAYON {0}', almas: 'KALULUWA',
    historia: ['DINALA NG DEMONYO ANG MGA KALULUWA NG BAYAN SA KANYANG KUWEBA.', 'BUMABA DALA ANG PAROL NI LOLA AT IBALIK SILA.'],
    ayuda: 'GUMALAW PARA UMIWAS. TUMIGIL PARA BUMARIL.', ayudaPC: 'WASD O ARROWS · SPACE: COPLA · ESC: HINTO',
    pisos: ['BUNGANGA', 'ITIM NA TUBIG', 'MGA BAGA', 'ANG BULWAGAN'], piso: 'PALAPAG {0}',
    nivel: 'LEVEL UP!', elegir: 'PUMILI', tocaCarta: 'PUMILI NG BARAHA', yapa: 'PAUNANG BONUS',
    fogon: 'ANG SIGA', fogonTxt: 'NAG-AALOK ANG POMBERO NG ISANG KASUNDUAN.', descansar: 'MAGPAHINGA', descansarD: '+40% BUHAY',
    trato: 'KASUNDUAN', tratoD: 'EPIKONG BARAHA KAPALIT NG 15% MAX NA BUHAY',
    pausa: 'HINTO', seguir: 'ITULOY', salir: 'BUMALIK SA MENU', musica: 'MUSIKA', sonido: 'TUNOG', si: 'BUKAS', no: 'SARADO', tusCartas: 'IYONG MGA BARAHA',
    muerte: 'NAHULI KA NG KUWEBA', llegaste: 'NARATING MO ANG {0}', nuevoRecord: 'BAGONG REKORD!', otraVez: 'ULIT', menu: 'MENU',
    victoria: 'NAPALAYA MO ANG MGA KALULUWA!', victoriaTxt: 'TUMAKAS ANG DEMONYO PABABA PA...', seguirBajando: 'BUMABA PA',
    enemigos: 'KALABAN', nv: 'LV', revivir: 'IKALAWANG BUHAY!', copla: 'COPLA', limpio: 'MALINIS!',
    palanca: 'STICK', flotante: 'LUMULUTANG', fija: 'NAKAPIRMI', tamPal: 'LAKI NG STICK', tamBtn: 'LAKI NG BUTONES', opac: 'LINAW',
    zurdo: 'KALIWETE', vibrar: 'VIBRATE', arrastra: 'I-DRAG ANG STICK AT BUTONES', restablecer: 'I-RESET', listo: 'TAPOS',
    comprar: 'BILHIN', max: 'MAX', mejorar: 'PANGHABAMBUHAY NA UPGRADE', ganadas: '+{0} KALULUWA', nivelAlcanzado: 'LEVEL {0}', muertos: '{0} KALABAN',
    jefes: ['HARING PALAKA', 'ANG BALO', 'ASWANG', 'MANDINGA'], tocar: 'PINDUTIN PARA ITULOY', nuevo: 'BAGO', volver: 'BUMALIK',
  },
  tr: {
    idioma: 'DİLİNİ SEÇ', subtitulo: 'ŞEYTANIN MAĞARASI',
    jugar: 'OYNA', diario: 'GÜNÜN GÖREVİ', altar: 'SUNAK', controles: 'KONTROLLER', idiomaBtn: 'DİL',
    record: 'REKOR {0}', hoyRec: 'BUGÜN {0}', almas: 'RUH',
    historia: ['ŞEYTAN KÖYÜN RUHLARINI MAĞARASINA GÖTÜRDÜ.', 'NİNENİN FENERİYLE AŞAĞI İN VE ONLARI GERİ GETİR.'],
    ayuda: 'KAÇMAK İÇİN HAREKET ET. ATEŞ ETMEK İÇİN DUR.', ayudaPC: 'WASD YA DA OKLAR · BOŞLUK: COPLA · ESC: DURAKLAT',
    pisos: ['AĞIZ', 'KARA SULAR', 'KORLAR', 'SALON'], piso: 'KAT {0}',
    nivel: 'SEVİYE ATLADIN!', elegir: 'SEÇ', tocaCarta: 'BİR KART SEÇ', yapa: 'BAŞLANGIÇ HEDİYESİ',
    fogon: 'KAMP ATEŞİ', fogonTxt: 'POMBERO SANA BİR ANLAŞMA ÖNERİYOR.', descansar: 'DİNLEN', descansarD: '+%40 CAN',
    trato: 'ANLAŞMA', tratoD: '%15 AZAMİ CAN KARŞILIĞINDA EPİK KART',
    pausa: 'DURAKLAT', seguir: 'DEVAM', salir: 'MENÜYE DÖN', musica: 'MÜZİK', sonido: 'SES', si: 'AÇIK', no: 'KAPALI', tusCartas: 'KARTLARIN',
    muerte: 'MAĞARA SENİ YAKALADI', llegaste: 'ULAŞTIĞIN YER: {0}', nuevoRecord: 'YENİ REKOR!', otraVez: 'TEKRAR', menu: 'MENÜ',
    victoria: 'RUHLARI KURTARDIN!', victoriaTxt: 'ŞEYTAN DAHA DERİNE KAÇTI...', seguirBajando: 'İNMEYE DEVAM ET',
    enemigos: 'DÜŞMAN', nv: 'SV', revivir: 'İKİNCİ CAN!', copla: 'COPLA', limpio: 'TEMİZ!',
    palanca: 'ÇUBUK', flotante: 'SERBEST', fija: 'SABİT', tamPal: 'ÇUBUK BOYUTU', tamBtn: 'DÜĞME BOYUTU', opac: 'SAYDAMLIK',
    zurdo: 'SOLAK', vibrar: 'TİTREŞİM', arrastra: 'ÇUBUĞU VE DÜĞMEYİ SÜRÜKLE', restablecer: 'SIFIRLA', listo: 'TAMAM',
    comprar: 'AL', max: 'MAKS', mejorar: 'KALICI GELİŞTİRMELER', ganadas: '+{0} RUH', nivelAlcanzado: 'SEVİYE {0}', muertos: '{0} DÜŞMAN',
    jefes: ['KURBAĞA KRAL', 'DUL KADIN', 'KURT ADAM', 'MANDINGA'], tocar: 'DEVAM İÇİN DOKUN', nuevo: 'YENİ', volver: 'GERİ',
  },
  ur: {
    idioma: 'اپنی زبان چنیں', subtitulo: 'شیطان کا غار',
    jugar: 'کھیلیں', diario: 'آج کا چیلنج', altar: 'قربان گاہ', controles: 'کنٹرولز', idiomaBtn: 'زبان',
    record: 'بہترین {0}', hoyRec: 'آج {0}', almas: 'روحیں',
    historia: ['شیطان گاؤں کی روحیں اپنے غار میں لے گیا۔', 'دادی کی لالٹین لے کر نیچے اتریں اور انہیں واپس لائیں۔'],
    ayuda: 'بچنے کے لیے حرکت کریں۔ گولی چلانے کے لیے رک جائیں۔', ayudaPC: 'WASD یا تیر · اسپیس: کوپلا · ESC: وقفہ',
    pisos: ['دہانہ', 'کالے پانی', 'انگارے', 'بڑا ہال'], piso: 'منزل {0}',
    nivel: 'لیول اپ!', elegir: 'چنیں', tocaCarta: 'ایک کارڈ چنیں', yapa: 'آغاز کا تحفہ',
    fogon: 'الاؤ', fogonTxt: 'پومبیرو آپ کو ایک سودا پیش کرتا ہے۔', descansar: 'آرام', descansarD: '+40% صحت',
    trato: 'سودا', tratoD: 'زیادہ سے زیادہ صحت کے 15% کے بدلے شاندار کارڈ',
    pausa: 'وقفہ', seguir: 'جاری رکھیں', salir: 'مینو پر جائیں', musica: 'موسیقی', sonido: 'آواز', si: 'آن', no: 'آف', tusCartas: 'آپ کے کارڈ',
    muerte: 'غار نے آپ کو پکڑ لیا', llegaste: 'آپ {0} تک پہنچے', nuevoRecord: 'نیا ریکارڈ!', otraVez: 'دوبارہ', menu: 'مینو',
    victoria: 'آپ نے روحیں آزاد کر دیں!', victoriaTxt: 'شیطان مزید گہرائی میں بھاگ گیا...', seguirBajando: 'نیچے اترتے رہیں',
    enemigos: 'دشمن', nv: 'لیول', revivir: 'ایک اور زندگی!', copla: 'کوپلا', limpio: 'صاف!',
    palanca: 'اسٹک', flotante: 'تیرتی', fija: 'ٹھہری', tamPal: 'اسٹک کا سائز', tamBtn: 'بٹن کا سائز', opac: 'شفافیت',
    zurdo: 'بائیں ہاتھ والا', vibrar: 'تھرتھراہٹ', arrastra: 'اسٹک اور بٹن کو گھسیٹیں', restablecer: 'ری سیٹ', listo: 'ہو گیا',
    comprar: 'خریدیں', max: 'مکمل', mejorar: 'ہمیشہ کی بہتری', ganadas: '+{0} روحیں', nivelAlcanzado: 'لیول {0}', muertos: '{0} دشمن',
    jefes: ['مینڈک بادشاہ', 'بیوہ', 'بھیڑیا آدمی', 'مانڈنگا'], tocar: 'جاری رکھنے کے لیے چھوئیں', nuevo: 'نیا', volver: 'واپس',
  },
  th: {
    idioma: 'เลือกภาษาของคุณ', subtitulo: 'ถ้ำของปีศาจ',
    jugar: 'เล่น', diario: 'ภารกิจประจำวัน', altar: 'แท่นบูชา', controles: 'การควบคุม', idiomaBtn: 'ภาษา',
    record: 'สถิติ {0}', hoyRec: 'วันนี้ {0}', almas: 'วิญญาณ',
    historia: ['ปีศาจพาวิญญาณของชาวบ้านลงไปในถ้ำของมัน', 'ถือตะเกียงของยายลงไป แล้วพาพวกเขากลับมา'],
    ayuda: 'เคลื่อนที่เพื่อหลบ หยุดนิ่งเพื่อยิง', ayudaPC: 'WASD หรือลูกศร · SPACE: COPLA · ESC: หยุด',
    pisos: ['ปากถ้ำ', 'น้ำดำ', 'ถ่านไฟ', 'โถงใหญ่'], piso: 'ชั้น {0}',
    nivel: 'เลเวลอัป!', elegir: 'เลือก', tocaCarta: 'แตะการ์ดหนึ่งใบ', yapa: 'ของแถมตอนเริ่ม',
    fogon: 'กองไฟ', fogonTxt: 'ปอมเบโรเสนอข้อตกลงให้คุณ', descansar: 'พักผ่อน', descansarD: '+40% พลังชีวิต',
    trato: 'ข้อตกลง', tratoD: 'การ์ดระดับตำนาน แลกกับพลังชีวิตสูงสุด 15%',
    pausa: 'หยุดชั่วคราว', seguir: 'เล่นต่อ', salir: 'ออกไปเมนู', musica: 'ดนตรี', sonido: 'เสียง', si: 'เปิด', no: 'ปิด', tusCartas: 'การ์ดของคุณ',
    muerte: 'ถ้ำจับตัวคุณไว้แล้ว', llegaste: 'คุณไปถึง {0}', nuevoRecord: 'สถิติใหม่!', otraVez: 'อีกครั้ง', menu: 'เมนู',
    victoria: 'คุณปลดปล่อยวิญญาณแล้ว!', victoriaTxt: 'ปีศาจหนีลึกลงไปอีก...', seguirBajando: 'ลงต่อไป',
    enemigos: 'ศัตรู', nv: 'LV', revivir: 'ชีวิตที่สอง!', copla: 'โกปลา', limpio: 'เคลียร์!',
    palanca: 'จอยสติ๊ก', flotante: 'ลอยตาม', fija: 'คงที่', tamPal: 'ขนาดจอย', tamBtn: 'ขนาดปุ่ม', opac: 'ความโปร่งใส',
    zurdo: 'ถนัดซ้าย', vibrar: 'สั่น', arrastra: 'ลากจอยและปุ่มได้เลย', restablecer: 'คืนค่าเดิม', listo: 'เสร็จ',
    comprar: 'ซื้อ', max: 'สูงสุด', mejorar: 'อัปเกรดถาวร', ganadas: '+{0} วิญญาณ', nivelAlcanzado: 'เลเวล {0}', muertos: 'ศัตรู {0} ตัว',
    jefes: ['ราชากบ', 'แม่ม่าย', 'มนุษย์หมาป่า', 'มานดิงกา'], tocar: 'แตะเพื่อไปต่อ', nuevo: 'ใหม่', volver: 'กลับ',
  },
  my: {
    idioma: 'ဘာသာစကား ရွေးပါ', subtitulo: 'မာရ်နတ်၏ ဂူ',
    jugar: 'ကစားမည်', diario: 'ယနေ့ စိန်ခေါ်မှု', altar: 'ယဇ်ပလ္လင်', controles: 'ထိန်းချုပ်မှု', idiomaBtn: 'ဘာသာစကား',
    record: 'အမြင့်ဆုံး {0}', hoyRec: 'ယနေ့ {0}', almas: 'ဝိညာဉ်',
    historia: ['မာရ်နတ်က ရွာသားတို့၏ ဝိညာဉ်များကို သူ့ဂူထဲ ခေါ်သွားသည်။', 'အဖွား၏ မီးအိမ်ကို ကိုင်ပြီး ဆင်းကာ သူတို့ကို ပြန်ခေါ်ခဲ့ပါ။'],
    ayuda: 'ရှောင်ရန် ရွှေ့ပါ။ ပစ်ရန် ငြိမ်ငြိမ်နေပါ။', ayudaPC: 'WASD သို့ မြှား · SPACE: COPLA · ESC: ခဏရပ်',
    pisos: ['ဂူဝ', 'ရေနက်', 'မီးကျီး', 'ခန်းမ'], piso: 'အထပ် {0}',
    nivel: 'အဆင့်တက်ပြီ!', elegir: 'ရွေးမည်', tocaCarta: 'ကတ်တစ်ချပ် ထိပါ', yapa: 'အစ လက်ဆောင်',
    fogon: 'မီးပုံ', fogonTxt: 'ပွန်ဘယ်ရိုက သင့်ကို အပေးအယူ တစ်ခု ကမ်းလှမ်းသည်။', descansar: 'အနားယူ', descansarD: '+40% အသက်',
    trato: 'အပေးအယူ', tratoD: 'အမြင့်ဆုံးအသက် 15% ဖြင့် ရှားပါးကတ်',
    pausa: 'ခဏရပ်', seguir: 'ဆက်ရန်', salir: 'မီနူးသို့', musica: 'ဂီတ', sonido: 'အသံ', si: 'ဖွင့်', no: 'ပိတ်', tusCartas: 'သင့်ကတ်များ',
    muerte: 'ဂူက သင့်ကို ဖမ်းမိသွားပြီ', llegaste: '{0} အထိ ရောက်ခဲ့သည်', nuevoRecord: 'စံချိန်သစ်!', otraVez: 'ထပ်ကစား', menu: 'မီနူး',
    victoria: 'ဝိညာဉ်များကို လွတ်မြောက်စေပြီ!', victoriaTxt: 'မာရ်နတ် ပိုနက်ရာသို့ ထွက်ပြေးသွားသည်...', seguirBajando: 'ဆက်ဆင်းမည်',
    enemigos: 'ရန်သူ', nv: 'LV', revivir: 'နောက်ထပ်အသက်!', copla: 'ကိုပလာ', limpio: 'ရှင်းပြီ!',
    palanca: 'ဂျွိုင်စတစ်', flotante: 'လွင့်', fija: 'ပုံသေ', tamPal: 'ဂျွိုင်စတစ် အရွယ်', tamBtn: 'ခလုတ် အရွယ်', opac: 'ဖောက်ထွင်းမြင်မှု',
    zurdo: 'ဘယ်သန်', vibrar: 'တုန်ခါမှု', arrastra: 'ဂျွိုင်စတစ်နှင့် ခလုတ်ကို ဆွဲရွှေ့ပါ', restablecer: 'မူလအတိုင်း', listo: 'ပြီးပြီ',
    comprar: 'ဝယ်မည်', max: 'အပြည့်', mejorar: 'အမြဲတမ်း အဆင့်မြှင့်', ganadas: '+{0} ဝိညာဉ်', nivelAlcanzado: 'အဆင့် {0}', muertos: 'ရန်သူ {0}',
    jefes: ['ဖားဘုရင်', 'မုဆိုးမ', 'ဝံပုလွေလူ', 'မန်ဒင်ဂါ'], tocar: 'ဆက်ရန် ထိပါ', nuevo: 'အသစ်', volver: 'နောက်သို့',
  },
  ja: {
    idioma: '言語を選択', subtitulo: '悪魔の洞くつ',
    jugar: 'プレイ', diario: '今日のチャレンジ', altar: '祭壇', controles: '操作設定', idiomaBtn: '言語',
    record: 'ベスト {0}', hoyRec: '今日 {0}', almas: '魂',
    historia: ['悪魔が村の魂を自分の洞くつへ連れ去った。', 'おばあちゃんのランタンを持って下り、魂を取り戻そう。'],
    ayuda: '動いてよける。止まると撃つ。', ayudaPC: 'WASDか矢印・スペース：コプラ・ESC：ポーズ',
    pisos: ['洞くつの口', '黒い水', '残り火', '大広間'], piso: '{0}階',
    nivel: 'レベルアップ！', elegir: '選ぶ', tocaCarta: 'カードを選ぼう', yapa: 'おまけ',
    fogon: 'たき火', fogonTxt: 'ポンベロが取引を持ちかけてきた。', descansar: '休む', descansarD: '体力+40%',
    trato: '取引', tratoD: '最大体力15%でエピックカード',
    pausa: 'ポーズ', seguir: '再開', salir: 'メニューへ', musica: '音楽', sonido: '効果音', si: 'オン', no: 'オフ', tusCartas: '手持ちのカード',
    muerte: '洞くつに捕まった', llegaste: '{0}まで到達', nuevoRecord: '新記録！', otraVez: 'もう一回', menu: 'メニュー',
    victoria: '魂を解放した！', victoriaTxt: '悪魔はさらに奥へ逃げた…', seguirBajando: 'さらに下りる',
    enemigos: '敵', nv: 'LV', revivir: 'もう一つの命！', copla: 'コプラ', limpio: 'クリア！',
    palanca: 'スティック', flotante: 'フリー', fija: '固定', tamPal: 'スティックの大きさ', tamBtn: 'ボタンの大きさ', opac: '透明度',
    zurdo: '左きき', vibrar: '振動', arrastra: 'スティックとボタンをドラッグ', restablecer: '初期設定に戻す', listo: '完了',
    comprar: '買う', max: '最大', mejorar: '永久アップグレード', ganadas: '魂+{0}', nivelAlcanzado: 'レベル {0}', muertos: '敵 {0}体',
    jefes: ['カエルの王', '未亡人', '狼男', 'マンディンガ'], tocar: 'タップで続ける', nuevo: 'NEW', volver: '戻る',
  },
});

/* las cartas: [nombre, descripción] (null = el de la lista original) */
const CARTAS_IDIOMA = {
  'es-MX': {
    seguido: [null, 'DISPARAS OTRA VEZ AL INSTANTE.'], iman: [null, 'JUNTAS TODO DESDE MÁS LEJOS.'],
    compa: [null, 'UN ESPÍRITU DISPARA CONTIGO, AUNQUE CORRAS.'],
  },
  ar: {
    frontal: ['طلقة مزدوجة', '+1 طلقة إلى الأمام.'], seguido: ['رشقة', 'تطلق مرة أخرى فورًا.'], diagonal: ['مروحة', '+2 طلقات قطرية.'],
    lateral: ['الجانبان', '+2 طلقات إلى الجانبين.'], trasero: ['الظهر', '+1 طلقة إلى الخلف.'], rebote: ['ارتداد', 'ترتد الطلقات عن الجدران.'],
    atraviesa: ['اختراق', 'تخترق الطلقات الأعداء.'], salto: ['قفزة', 'تقفز الطلقة إلى عدو آخر.'], danio: ['حدّ', '+25% من الضرر.'],
    cadencia: ['نبض', '+18% من سرعة الإطلاق.'], critico: ['العين الشريرة', '+12% فرصة الضربة الحرجة وضربات أقوى.'], fuego: ['جمرة', 'الطلقات تحرق.'],
    hielo: ['صقيع', 'تبطئ وأحيانًا تجمّد.'], rayo: ['برق', 'كل ضربة تصعق عدوين قريبين.'], veneno: ['سمّ', 'يسمّم. السم يتراكم.'],
    vida: ['قلب', '+25% من الصحة القصوى.'], robo: ['عطش', 'كل عدو يسقط يشفيك قليلًا.'], curar: ['متّة', 'يشفي نصف صحتك.'],
    escudo: ['الضوء الشرير', 'أضواء تدور وتحرق وتصدّ الرصاص.'], compa: ['روح', 'روح تطلق معك حتى وأنت تجري.'], velocidad: ['صنادل', '+12% من السرعة.'],
    iman: ['مغناطيس', 'تلتقط كل شيء من بعيد.'], explosion: ['انفجار', 'ينفجر الأعداء عند سقوطهم.'], esquive: ['ظل', '+10% فرصة تفادي الضربات.'],
    copla: ['غيتار', 'الأغنية تُشحن أسرع.'],
  },
  id: {
    frontal: ['TEMBAKAN GANDA', '+1 TEMBAKAN KE DEPAN.'], seguido: ['BERONDONG', 'MENEMBAK LAGI SEKETIKA.'], diagonal: ['KIPAS', '+2 TEMBAKAN DIAGONAL.'],
    lateral: ['SAMPING', '+2 TEMBAKAN KE SAMPING.'], trasero: ['BELAKANG', '+1 TEMBAKAN KE BELAKANG.'], rebote: ['PANTUL', 'TEMBAKAN MEMANTUL DI DINDING.'],
    atraviesa: ['TEMBUS', 'TEMBAKAN MENEMBUS MUSUH.'], salto: ['LONCAT', 'TEMBAKAN MELONCAT KE MUSUH LAIN.'], danio: ['TAJAM', '+25% KERUSAKAN.'],
    cadencia: ['DENYUT', '+18% KECEPATAN TEMBAK.'], critico: ['MATA JAHAT', '+12% PELUANG KRITIS DAN KRITIS LEBIH KUAT.'], fuego: ['BARA', 'TEMBAKAN MEMBAKAR.'],
    hielo: ['EMBUN BEKU', 'MEMPERLAMBAT DAN KADANG MEMBEKUKAN.'], rayo: ['PETIR', 'TIAP SERANGAN MENYAMBAR DUA MUSUH TERDEKAT.'], veneno: ['BISA', 'MERACUNI. RACUN MENUMPUK.'],
    vida: ['JANTUNG', '+25% NYAWA MAKS.'], robo: ['HAUS', 'TIAP MUSUH YANG JATUH SEDIKIT MEMULIHKANMU.'], curar: ['TEH MATE', 'MEMULIHKAN SETENGAH NYAWAMU.'],
    escudo: ['CAHAYA JAHAT', 'CAHAYA BERPUTAR YANG MEMBAKAR DAN MENAHAN PELURU.'], compa: ['ARWAH', 'ARWAH MENEMBAK BERSAMAMU, BAHKAN SAAT BERLARI.'], velocidad: ['SANDAL', '+12% KECEPATAN GERAK.'],
    iman: ['MAGNET', 'MENGAMBIL BARANG DARI JAUH.'], explosion: ['LEDAKAN', 'MUSUH MELEDAK SAAT MATI.'], esquive: ['BAYANGAN', '+10% PELUANG MENGHINDARI SERANGAN.'],
    copla: ['GITAR', 'COPLA TERISI LEBIH CEPAT.'],
  },
  ms: {
    frontal: ['TEMBAKAN BERGANDA', '+1 TEMBAKAN KE DEPAN.'], seguido: ['DERAS', 'MENEMBAK LAGI SERTA-MERTA.'], diagonal: ['KIPAS', '+2 TEMBAKAN PEPENJURU.'],
    lateral: ['SISI', '+2 TEMBAKAN KE SISI.'], trasero: ['BELAKANG', '+1 TEMBAKAN KE BELAKANG.'], rebote: ['LANTUN', 'TEMBAKAN MELANTUN DI DINDING.'],
    atraviesa: ['TEMBUS', 'TEMBAKAN MENEMBUSI MUSUH.'], salto: ['LOMPAT', 'TEMBAKAN MELOMPAT KE MUSUH LAIN.'], danio: ['TAJAM', '+25% KEROSAKAN.'],
    cadencia: ['NADI', '+18% KADAR TEMBAKAN.'], critico: ['MATA JAHAT', '+12% PELUANG KRITIKAL DAN KRITIKAL LEBIH KUAT.'], fuego: ['BARA', 'TEMBAKAN MEMBAKAR.'],
    hielo: ['FROS', 'MELAMBATKAN DAN KADANG-KADANG MEMBEKUKAN.'], rayo: ['PETIR', 'SETIAP SERANGAN MENYAMBAR DUA MUSUH BERHAMPIRAN.'], veneno: ['BISA', 'MERACUN. RACUN BERTIMBUN.'],
    vida: ['JANTUNG', '+25% NYAWA MAKS.'], robo: ['DAHAGA', 'SETIAP MUSUH YANG TUMBANG MEMULIHKAN ANDA SEDIKIT.'], curar: ['TEH MATE', 'MEMULIHKAN SEPARUH NYAWA ANDA.'],
    escudo: ['CAHAYA JAHAT', 'CAHAYA BERPUSING YANG MEMBAKAR DAN MENAHAN PELURU.'], compa: ['ROH', 'ROH MENEMBAK BERSAMA ANDA, WALAUPUN BERLARI.'], velocidad: ['SELIPAR', '+12% KELAJUAN.'],
    iman: ['MAGNET', 'MENGUTIP SEMUA DARI JAUH.'], explosion: ['LETUPAN', 'MUSUH MELETUP APABILA TUMBANG.'], esquive: ['BAYANG', '+10% PELUANG MENGELAK.'],
    copla: ['GITAR', 'COPLA DICAS LEBIH PANTAS.'],
  },
  fil: {
    frontal: ['DOBLENG PUTOK', '+1 PUTOK PAHARAP.'], seguido: ['RATSADA', 'BUMARIL ULIT AGAD.'], diagonal: ['PAMAYPAY', '+2 PAHILIS NA PUTOK.'],
    lateral: ['GILID', '+2 PUTOK SA MGA GILID.'], trasero: ['LIKOD', '+1 PUTOK PATALIKOD.'], rebote: ['TALBOG', 'TUMATALBOG ANG PUTOK SA PADER.'],
    atraviesa: ['TAGOS', 'TUMATAGOS ANG PUTOK SA KALABAN.'], salto: ['LUKSO', 'LUMULUKSO ANG PUTOK SA IBANG KALABAN.'], danio: ['TALIM', '+25% PINSALA.'],
    cadencia: ['PULSO', '+18% BILIS NG PAGBARIL.'], critico: ['MASAMANG MATA', '+12% TSANSA NG CRITICAL AT MAS MALAKAS NA CRITICAL.'], fuego: ['BAGA', 'NAKAKASUNOG ANG PUTOK.'],
    hielo: ['YELO', 'NAGPAPABAGAL AT MINSANG NAGPAPATIGAS.'], rayo: ['KIDLAT', 'BAWAT TAMA AY KUMIKIDLAT SA DALAWANG MALAPIT.'], veneno: ['LASON', 'NAGLALASON. NAIIPON ANG LASON.'],
    vida: ['PUSO', '+25% MAX NA BUHAY.'], robo: ['UHAW', 'BAWAT KALABANG BUMAGSAK AY MEDYO NAGPAPAGALING SA IYO.'], curar: ['MATE', 'PINAPAGALING ANG KALAHATI NG BUHAY MO.'],
    escudo: ['MASAMANG ILAW', 'UMIIKOT NA ILAW NA NANUNUNOG AT HUMAHARANG NG BALA.'], compa: ['ESPIRITU', 'MAY ESPIRITUNG BUMABARIL KASAMA MO, KAHIT TUMATAKBO.'], velocidad: ['TSINELAS', '+12% BILIS.'],
    iman: ['MAGNET', 'NAKAKAPULOT KAHIT MALAYO.'], explosion: ['PAGSABOG', 'SUMASABOG ANG KALABAN PAGBAGSAK.'], esquive: ['ANINO', '+10% TSANSANG UMIWAS.'],
    copla: ['GITARA', 'MAS MABILIS MAPUNO ANG COPLA.'],
  },
  tr: {
    frontal: ['ÇİFT ATIŞ', '+1 İLERİ ATIŞ.'], seguido: ['SERİ', 'ANINDA BİR KEZ DAHA ATEŞ EDERSİN.'], diagonal: ['YELPAZE', '+2 ÇAPRAZ ATIŞ.'],
    lateral: ['YANLAR', '+2 YANA ATIŞ.'], trasero: ['SIRT', '+1 GERİYE ATIŞ.'], rebote: ['SEKME', 'ATIŞLAR DUVARLARDAN SEKER.'],
    atraviesa: ['DELİCİ', 'ATIŞLAR DÜŞMANLARI DELİP GEÇER.'], salto: ['SIÇRAMA', 'ATIŞ BAŞKA BİR DÜŞMANA SIÇRAR.'], danio: ['KESKİNLİK', '+%25 HASAR.'],
    cadencia: ['NABIZ', '+%18 ATIŞ HIZI.'], critico: ['NAZAR', '+%12 KRİTİK ŞANSI VE DAHA GÜÇLÜ KRİTİK.'], fuego: ['KOR', 'ATIŞLAR YAKAR.'],
    hielo: ['AYAZ', 'YAVAŞLATIR, BAZEN DONDURUR.'], rayo: ['YILDIRIM', 'HER VURUŞ YAKINDAKİ İKİ DÜŞMANA ÇARPAR.'], veneno: ['ZEHİR', 'ZEHİRLER. ZEHİR BİRİKİR.'],
    vida: ['YÜREK', '+%25 AZAMİ CAN.'], robo: ['SUSUZLUK', 'DÜŞEN HER DÜŞMAN SENİ BİRAZ İYİLEŞTİRİR.'], curar: ['MATE ÇAYI', 'CANININ YARISINI YENİLER.'],
    escudo: ['KÖTÜ IŞIK', 'DÖNEN IŞIKLAR YAKAR VE MERMİ DURDURUR.'], compa: ['RUH', 'BİR RUH SENİNLE ATEŞ EDER, KOŞARKEN BİLE.'], velocidad: ['ESPADRİL', '+%12 HIZ.'],
    iman: ['MIKNATIS', 'HER ŞEYİ DAHA UZAKTAN TOPLARSIN.'], explosion: ['PATLAMA', 'DÜŞMANLAR ÖLÜNCE PATLAR.'], esquive: ['GÖLGE', '+%10 KAÇINMA ŞANSI.'],
    copla: ['GİTAR', 'COPLA DAHA HIZLI DOLAR.'],
  },
  ur: {
    frontal: ['دوہرا وار', '+1 سامنے کی طرف گولی۔'], seguido: ['بوچھاڑ', 'فوراً دوبارہ گولی چلائیں۔'], diagonal: ['پنکھا', '+2 ترچھی گولیاں۔'],
    lateral: ['پہلو', '+2 اطراف میں گولیاں۔'], trasero: ['پیٹھ', '+1 پیچھے کی طرف گولی۔'], rebote: ['اچھال', 'گولیاں دیواروں سے اچھلتی ہیں۔'],
    atraviesa: ['آر پار', 'گولیاں دشمنوں کے آر پار جاتی ہیں۔'], salto: ['چھلانگ', 'گولی دوسرے دشمن پر کودتی ہے۔'], danio: ['دھار', '+25% نقصان۔'],
    cadencia: ['نبض', '+18% گولی کی رفتار۔'], critico: ['بری نظر', '+12% کریٹیکل موقع اور زیادہ طاقتور وار۔'], fuego: ['انگارہ', 'گولیاں جلاتی ہیں۔'],
    hielo: ['پالا', 'سست کرتی ہیں اور کبھی جما دیتی ہیں۔'], rayo: ['بجلی', 'ہر وار قریب کے دو دشمنوں پر بجلی گراتا ہے۔'], veneno: ['زہر', 'زہر دیتا ہے۔ زہر جمع ہوتا ہے۔'],
    vida: ['دل', '+25% زیادہ سے زیادہ صحت۔'], robo: ['پیاس', 'ہر گرتا دشمن آپ کو تھوڑا ٹھیک کرتا ہے۔'], curar: ['ماتے چائے', 'آدھی صحت بحال کرتی ہے۔'],
    escudo: ['آسیبی روشنی', 'گھومتی روشنیاں جلاتی ہیں اور گولیاں روکتی ہیں۔'], compa: ['روح', 'ایک روح آپ کے ساتھ گولی چلاتی ہے، دوڑتے ہوئے بھی۔'], velocidad: ['چپل', '+12% رفتار۔'],
    iman: ['مقناطیس', 'دور سے سب کچھ اٹھائیں۔'], explosion: ['دھماکا', 'دشمن گرتے ہی پھٹ جاتے ہیں۔'], esquive: ['سایہ', '+10% وار سے بچنے کا موقع۔'],
    copla: ['گٹار', 'کوپلا جلدی بھرتا ہے۔'],
  },
  th: {
    frontal: ['ยิงคู่', '+1 นัดยิงไปข้างหน้า'], seguido: ['รัวยิง', 'ยิงซ้ำได้ทันที'], diagonal: ['พัด', '+2 นัดยิงทแยง'],
    lateral: ['ด้านข้าง', '+2 นัดยิงออกด้านข้าง'], trasero: ['ด้านหลัง', '+1 นัดยิงไปข้างหลัง'], rebote: ['สะท้อน', 'กระสุนสะท้อนกำแพง'],
    atraviesa: ['ทะลุ', 'กระสุนทะลุศัตรู'], salto: ['กระโดด', 'กระสุนกระโดดไปหาศัตรูตัวอื่น'], danio: ['คม', '+25% ความเสียหาย'],
    cadencia: ['ชีพจร', '+18% อัตรายิง'], critico: ['ตาร้าย', '+12% โอกาสคริติคอล และคริติคอลแรงขึ้น'], fuego: ['ถ่านไฟ', 'กระสุนเผาไหม้'],
    hielo: ['น้ำค้างแข็ง', 'ทำให้ช้า และบางครั้งแช่แข็ง'], rayo: ['สายฟ้า', 'ทุกการโจมตีปล่อยสายฟ้าใส่ศัตรูใกล้ๆ สองตัว'], veneno: ['พิษ', 'ติดพิษ พิษสะสมได้'],
    vida: ['หัวใจ', '+25% พลังชีวิตสูงสุด'], robo: ['กระหาย', 'ศัตรูทุกตัวที่ล้มช่วยฟื้นพลังเล็กน้อย'], curar: ['ชามาเต', 'ฟื้นพลังชีวิตครึ่งหนึ่ง'],
    escudo: ['แสงผี', 'แสงวนรอบตัวที่เผาศัตรูและกันกระสุน'], compa: ['วิญญาณ', 'วิญญาณยิงไปกับคุณ แม้ตอนวิ่ง'], velocidad: ['รองเท้าสาน', '+12% ความเร็ว'],
    iman: ['แม่เหล็ก', 'เก็บของได้จากไกลขึ้น'], explosion: ['ระเบิด', 'ศัตรูระเบิดเมื่อตาย'], esquive: ['เงา', '+10% โอกาสหลบการโจมตี'],
    copla: ['กีตาร์', 'โกปลาชาร์จเร็วขึ้น'],
  },
  my: {
    frontal: ['နှစ်ချက်ပစ်', 'ရှေ့သို့ +1 ချက်။'], seguido: ['ဆက်တိုက်', 'ချက်ချင်း ထပ်ပစ်သည်။'], diagonal: ['ယပ်တောင်', 'ထောင့်ဖြတ် +2 ချက်။'],
    lateral: ['ဘေး', 'ဘေးသို့ +2 ချက်။'], trasero: ['ကျော', 'နောက်သို့ +1 ချက်။'], rebote: ['ပြန်ကန်', 'ကျည်များ နံရံမှ ပြန်ကန်သည်။'],
    atraviesa: ['ဖောက်ထွင်း', 'ကျည်များ ရန်သူကို ဖောက်သွားသည်။'], salto: ['ခုန်', 'ကျည် အခြားရန်သူဆီ ခုန်သွားသည်။'], danio: ['အသွား', '+25% ထိခိုက်မှု။'],
    cadencia: ['သွေးခုန်', '+18% ပစ်နှုန်း။'], critico: ['မျက်စိဆိုး', '+12% ကရစ်တီကယ် အခွင့်နှင့် ပိုပြင်း။'], fuego: ['မီးကျီး', 'ကျည်များ လောင်ကျွမ်းစေသည်။'],
    hielo: ['နှင်းခဲ', 'နှေးစေပြီး တခါတရံ ခဲစေသည်။'], rayo: ['မိုးကြိုး', 'ထိတိုင်း အနီးရှိ ရန်သူနှစ်ယောက်ကို လျှပ်စီးပစ်သည်။'], veneno: ['အဆိပ်', 'အဆိပ်သင့်စေသည်။ အဆိပ် စုပုံသည်။'],
    vida: ['နှလုံး', '+25% အမြင့်ဆုံးအသက်။'], robo: ['ရေငတ်', 'ရန်သူ ကျတိုင်း အနည်းငယ် ပြန်ကောင်းသည်။'], curar: ['မာတေ', 'အသက်တစ်ဝက် ပြန်ကောင်းစေသည်။'],
    escudo: ['ဆိုးသောအလင်း', 'လှည့်ပတ်နေသော အလင်းများက လောင်ပြီး ကျည်တားသည်။'], compa: ['ဝိညာဉ်', 'ဝိညာဉ်တစ်ခု သင်နှင့်အတူ ပစ်သည်၊ ပြေးနေစဉ်ပင်။'], velocidad: ['ဖိနပ်', '+12% အမြန်နှုန်း။'],
    iman: ['သံလိုက်', 'အဝေးမှ အားလုံး ကောက်ယူသည်။'], explosion: ['ပေါက်ကွဲ', 'ရန်သူများ ကျလျှင် ပေါက်ကွဲသည်။'], esquive: ['အရိပ်', '+10% ရှောင်နိုင်ခွင့်။'],
    copla: ['ဂစ်တာ', 'ကိုပလာ ပိုမြန်စွာ အားပြည့်သည်။'],
  },
  ja: {
    frontal: ['ダブルショット', '前方への弾+1。'], seguido: ['連射', 'すぐにもう一度撃つ。'], diagonal: ['扇', '斜めの弾+2。'],
    lateral: ['左右', '横への弾+2。'], trasero: ['背中', '後ろへの弾+1。'], rebote: ['跳弾', '弾が壁で跳ね返る。'],
    atraviesa: ['貫通', '弾が敵を貫く。'], salto: ['跳躍', '弾が別の敵へ跳ぶ。'], danio: ['刃', 'ダメージ+25%。'],
    cadencia: ['鼓動', '連射速度+18%。'], critico: ['邪視', '会心率+12%、会心がより強力に。'], fuego: ['燠火', '弾が燃やす。'],
    hielo: ['霜', '遅くし、時々凍らせる。'], rayo: ['雷', '命中ごとに近くの2体へ雷が飛ぶ。'], veneno: ['毒', '毒を与える。毒は重なる。'],
    vida: ['心臓', '最大体力+25%。'], robo: ['渇き', '敵を倒すたびに少し回復。'], curar: ['マテ茶', '体力の半分を回復。'],
    escudo: ['鬼火', '回る光が敵を焼き、弾を防ぐ。'], compa: ['精霊', '走っていても精霊が一緒に撃つ。'], velocidad: ['サンダル', '移動速度+12%。'],
    iman: ['磁石', '遠くの物も拾える。'], explosion: ['爆発', '倒した敵が爆発する。'], esquive: ['影', '回避率+10%。'],
    copla: ['ギター', 'コプラのチャージが速くなる。'],
  },
};

/* el altar: [nombre, descripción]; cortas, que van al lado del botón de comprar */
const ALTAR_IDIOMA = {
  'es-MX': { yapa: ['PILÓN', null], revivir: [null, 'REVIVES UNA VEZ'] },
  ar: { vida: ['الصحة', '+10% صحة'], danio: ['القوة', '+8% ضرر'], cadencia: ['اليد', '+6% سرعة إطلاق'], suerte: ['الحظ', 'بطاقات أندر'], yapa: ['هدية', 'بطاقة عند البدء'], revivir: ['حياة أخرى', 'تعود للحياة مرة'] },
  id: { vida: ['NYAWA', '+10% NYAWA'], danio: ['KEKUATAN', '+8% KERUSAKAN'], cadencia: ['TANGAN', '+6% LAJU TEMBAK'], suerte: ['HOKI', 'KARTU LANGKA'], yapa: ['BONUS', 'KARTU AWAL'], revivir: ['NYAWA KEDUA', 'BANGKIT SEKALI'] },
  ms: { vida: ['NYAWA', '+10% NYAWA'], danio: ['KUASA', '+8% KEROSAKAN'], cadencia: ['TANGAN', '+6% KADAR TEMBAK'], suerte: ['TUAH', 'KAD JARANG'], yapa: ['BONUS', 'KAD AWAL'], revivir: ['NYAWA KEDUA', 'BANGKIT SEKALI'] },
  fil: { vida: ['BUHAY', '+10% BUHAY'], danio: ['LAKAS', '+8% PINSALA'], cadencia: ['KAMAY', '+6% BILIS BARIL'], suerte: ['SUWERTE', 'BIHIRANG BARAHA'], yapa: ['BONUS', 'BARAHA SA SIMULA'], revivir: ['IKALAWANG BUHAY', 'MABUBUHAY ULIT'] },
  tr: { vida: ['CAN', '+%10 CAN'], danio: ['GÜÇ', '+%8 HASAR'], cadencia: ['EL', '+%6 ATIŞ HIZI'], suerte: ['ŞANS', 'NADİR KARTLAR'], yapa: ['HEDİYE', 'BAŞLARKEN KART'], revivir: ['İKİNCİ CAN', 'BİR KEZ DİRİL'] },
  ur: { vida: ['صحت', '+10% صحت'], danio: ['طاقت', '+8% نقصان'], cadencia: ['ہاتھ', '+6% گولی کی رفتار'], suerte: ['قسمت', 'نایاب کارڈ'], yapa: ['تحفہ', 'شروع میں کارڈ'], revivir: ['ایک اور زندگی', 'ایک بار جی اٹھیں'] },
  th: { vida: ['พลังชีวิต', '+10% พลังชีวิต'], danio: ['พลัง', '+8% ความเสียหาย'], cadencia: ['มือ', '+6% อัตรายิง'], suerte: ['โชค', 'การ์ดหายากขึ้น'], yapa: ['ของแถม', 'การ์ดตอนเริ่ม'], revivir: ['ชีวิตที่สอง', 'ฟื้นคืนชีพหนึ่งครั้ง'] },
  my: { vida: ['အသက်', '+10% အသက်'], danio: ['ခွန်အား', '+8% ထိခိုက်မှု'], cadencia: ['လက်', '+6% ပစ်နှုန်း'], suerte: ['ကံ', 'ပိုရှားသော ကတ်'], yapa: ['လက်ဆောင်', 'စစချင်း ကတ်'], revivir: ['နောက်ထပ်အသက်', 'တစ်ကြိမ် ပြန်ရှင်'] },
  ja: { vida: ['体力', '体力+10%'], danio: ['力', 'ダメージ+8%'], cadencia: ['手', '連射+6%'], suerte: ['運', 'レアカード増'], yapa: ['おまけ', '開始時にカード'], revivir: ['もう一つの命', '一度だけ復活'] },
};
