// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.AssetBundleModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.AssetBundle))]
