/* ============================================================================
   ruta40/js/textos.js — todo lo que se lee, en castellano, inglés y portugués.
   t('clave', {n: 3}) reemplaza {n}. Lo que falta en un idioma cae al castellano.
   ========================================================================== */
const ES = {
  titulo: 'RUTA 40', sub: 'De la Puna al Glaciar',
  elegirIdioma: 'Elegí el idioma', idiomaNombre: 'ESPAÑOL',
  cargando: 'Cargando la chata…', tocar: 'Tocá para arrancar', teclas: 'Flechas o A/D para manejar · P pausa',
  viajar: 'VIAJAR', picadas: 'PICADAS', gomeria: 'GOMERÍA', ajustes: 'AJUSTES', historia: 'HISTORIA',
  volver: 'Volver', listo: 'Listo', si: 'Sí', no: 'No', cerrar: 'Cerrar', seguir: 'Seguir', saltar: 'Saltar ›',
  // el mapa
  mapa: 'La Ruta 40', km: 'km', record: 'Récord', sinRecord: 'Sin récord', bloqueado: 'Llegá a {n} m en {lugar} para abrirlo',
  llegaste: 'Llegaste', viajarA: 'VIAJAR', picadaA: 'PICADA',
  // los tramos
  t_puna: 'Puna', t_quebrada: 'Quebrada de Humahuaca', t_salinas: 'Salinas Grandes', t_valles: 'Valles Calchaquíes',
  t_cuyo: 'Cuyo', t_patagonia: 'Patagonia', t_glaciar: 'Los Glaciares',
  p_puna: 'A 3.500 metros el aire es finito y el motor tose. Las vicuñas no se apuran por nadie.',
  p_quebrada: 'El Cerro de los Siete Colores: cada franja es otro tiempo de la tierra. Ojo con las cuestas.',
  p_salinas: 'Doce mil hectáreas de sal. Plano como una mesa, y la mesa está puesta para volar.',
  p_valles: 'Entre Cafayate y Cachi: ripio, torrontés y cerros colorados. Los puentes de madera crujen.',
  p_cuyo: 'Viñedos, álamos y el Aconcagua mirando. Las bajadas son largas: la Difunta Correa te cuida.',
  p_patagonia: 'El viento sopla de frente todo el año. Acá el que no aprieta, no llega.',
  p_glaciar: 'El hielo cruje y la ruta patina. Al final te espera la Rosa con el mate.',
  // la historia
  h1: 'Don Tito arregla gomas en La Quiaca, en la punta de arriba de la Ruta 40.',
  h2: 'Un día le llega una carta desde El Calafate: «Vení a tomar unos mates, que te extraño. — Rosa».',
  h3: 'Son cinco mil kilómetros de ripio, cuestas y viento. Tito carga la chata y sale.',
  fin1: 'Tito llega al glaciar con la chata llena de tierra.',
  fin2: '—¡Tardaste! —le dice Rosa, con el mate listo.',
  fin3: '—Es que la ruta es larga, hermana. Pero qué linda que es.',
  creditos: 'Hecho con física propia, arte de Rezona y música sintetizada. Gracias por manejar.',
  // manejando
  m: 'm', nafta: 'NAFTA', naftaBaja: '¡NAFTA!', sinNafta: '¡Sin nafta!', cabeza: '¡Se dio la cabeza!', volco: '¡Volcaste!',
  llegada: '¡LLEGASTE!', nuevoRecord: '¡NUEVO RÉCORD!', mojon: 'MOJÓN {n}', vuelo: 'VUELO {n}s', vueltaAtras: 'VUELTA ATRÁS', vueltaAdelante: 'VUELTA ADELANTE',
  doble: '×{n}', willy: 'WILLY {n}s', limpio: 'ATERRIZAJE LIMPIO', combo: 'COMBO ×{n}', casi: '¡CASI!',
  tutoGas: 'Pedal derecho: acelerar', tutoFreno: 'Pedal izquierdo: frenar y marcha atrás', tutoAire: 'En el aire: acelerar gira para atrás, frenar para adelante', tutoCabeza: 'Que no toque la cabeza',
  tutoTeclas: '→ acelerar · ← frenar', pausa: 'PARE', reiniciar: 'Reiniciar', salir: 'Salir',
  // el resultado
  resultado: 'Fin del viaje', distancia: 'Distancia', monedas: 'Monedas', trucos: 'Trucos', mojones: 'Mojones', total: 'Total',
  otraVez: 'OTRA VEZ', alMapa: 'MAPA', abriste: '¡Se abrió {lugar}!',
  // la gomería
  g_titulo: 'Gomería "El Tito"', usar: 'USAR', elegido: 'EN USO', comprar: 'COMPRAR', maximo: 'AL MÁXIMO', faltan: 'Te faltan {n}',
  v_chata: 'La Chata', v_escarabajo: 'El Fitito', v_colectivo: 'El Colectivo', v_cuatro: 'La 4x4', v_tractor: 'El Tractor',
  d_chata: 'La camioneta de campo. Pareja en todo, como un buen mate.',
  d_escarabajo: 'Livianito y gasolero: vuela en las rampas, sufre en las cuestas.',
  d_colectivo: 'Largo, pesado y fileteado. No hay loma que lo vuelque; tanque de viaje.',
  d_cuatro: 'Tracción en las cuatro y cubiertas de barro. Trepa paredes.',
  d_tractor: 'Lento y terco. Con esa rueda de atrás sube lo que le pongas.',
  mj_motor: 'Motor', mj_llantas: 'Cubiertas', mj_susp: 'Suspensión', mj_tanque: 'Tanque', mj_aire: 'Vuelo',
  e_vel: 'Velocidad', e_agarre: 'Agarre', e_trepa: 'Trepada', e_nafta: 'Nafta',
  // las picadas
  pc_titulo: 'Picadas', pc_sub: 'Mil doscientos metros contra tres. Sin nafta que cuidar.', pc_nivel: ['Del barrio', 'Del pueblo', 'De la provincia'],
  pc_premio: 'Premio', pc_ganaste: '¡GANASTE LA PICADA!', pc_puesto: 'Llegaste {n}º', pc_largada: 'LARGADA', pc_meta: 'META',
  pc_rivales: 'Rivales', pc_ganada: 'Ganada', pc_correr: 'CORRER',
  // ajustes
  a_titulo: 'Ajustes', a_musica: 'Música', a_motor: 'Motor', a_efectos: 'Efectos', a_radio: 'Radio en la ruta', a_idioma: 'Idioma',
  a_controles: 'Controles', a_vibrar: 'Vibrar', a_calidad: 'Calidad', a_alta: 'Alta', a_media: 'Media', a_baja: 'Baja',
  a_giro: 'Pantalla girada', a_auto: 'Automática', a_normal: 'Normal', a_reves: 'Al revés', a_borrar: 'Borrar la partida', a_borrarSeguro: '¿Seguro? Se pierde todo.',
  a_estilo: 'Música', a_estiloFolk: 'Folclore', a_estilo16: '16 bits',
  // los controles
  c_titulo: 'Controles', c_ayuda: 'Arrastrá los pedales adonde te queden cómodos', c_tam: 'Tamaño', c_alfa: 'Transparencia',
  c_lado: 'Cambiar de lado', c_modo: 'Modo', c_pedales: 'Pedales', c_mitades: 'Mitades de pantalla', c_reset: 'Como estaba', c_freno: 'FRENO', c_gas: 'GAS',
  moneda: '$',
};
const EN = {
  titulo: 'ROUTE 40', sub: 'From the Puna to the Glacier',
  elegirIdioma: 'Choose your language', idiomaNombre: 'ENGLISH',
  cargando: 'Loading the pickup…', tocar: 'Tap to start', teclas: 'Arrows or A/D to drive · P pause',
  viajar: 'DRIVE', picadas: 'RACES', gomeria: 'GARAGE', ajustes: 'SETTINGS', historia: 'STORY',
  volver: 'Back', listo: 'Done', si: 'Yes', no: 'No', cerrar: 'Close', seguir: 'Continue', saltar: 'Skip ›',
  mapa: 'Route 40', km: 'km', record: 'Best', sinRecord: 'No record', bloqueado: 'Reach {n} m in {lugar} to open it',
  llegaste: 'Finished', viajarA: 'DRIVE', picadaA: 'RACE',
  t_puna: 'Puna', t_quebrada: 'Humahuaca Gorge', t_salinas: 'Great Salt Flats', t_valles: 'Calchaquí Valleys',
  t_cuyo: 'Cuyo', t_patagonia: 'Patagonia', t_glaciar: 'The Glaciers',
  p_puna: 'At 3,500 metres the air is thin and the engine coughs. Vicuñas hurry for no one.',
  p_quebrada: 'The Hill of Seven Colours: every stripe is another age of the earth. Mind the climbs.',
  p_salinas: 'Twelve thousand hectares of salt. Flat as a table, and the table is set for flying.',
  p_valles: 'Between Cafayate and Cachi: gravel, torrontés wine and red hills. The wooden bridges creak.',
  p_cuyo: 'Vineyards, poplars and Aconcagua watching. The descents are long: the Difunta Correa looks after you.',
  p_patagonia: 'The wind blows head-on all year round. Out here, if you don\'t push, you don\'t arrive.',
  p_glaciar: 'The ice cracks and the road slides. At the end, Rosa is waiting with the mate.',
  h1: 'Don Tito fixes tyres in La Quiaca, at the very top of Route 40.',
  h2: 'One day a letter arrives from El Calafate: "Come have some mate, I miss you. — Rosa".',
  h3: 'Five thousand kilometres of gravel, climbs and wind. Tito loads the pickup and hits the road.',
  fin1: 'Tito reaches the glacier with the pickup covered in dust.',
  fin2: '"You took your time!" says Rosa, mate ready.',
  fin3: '"The road is long, sister. But it\'s so beautiful."',
  creditos: 'Made with home-grown physics, art from Rezona and synthesized music. Thanks for driving.',
  m: 'm', nafta: 'FUEL', naftaBaja: 'FUEL!', sinNafta: 'Out of fuel!', cabeza: 'Bumped his head!', volco: 'You flipped!',
  llegada: 'YOU MADE IT!', nuevoRecord: 'NEW RECORD!', mojon: 'MILESTONE {n}', vuelo: 'AIR {n}s', vueltaAtras: 'BACKFLIP', vueltaAdelante: 'FRONTFLIP',
  doble: '×{n}', willy: 'WHEELIE {n}s', limpio: 'CLEAN LANDING', combo: 'COMBO ×{n}', casi: 'CLOSE ONE!',
  tutoGas: 'Right pedal: gas', tutoFreno: 'Left pedal: brake and reverse', tutoAire: 'In the air: gas tilts back, brake tilts forward', tutoCabeza: 'Don\'t let his head touch the ground',
  tutoTeclas: '→ gas · ← brake', pausa: 'STOP', reiniciar: 'Restart', salir: 'Quit',
  resultado: 'End of the trip', distancia: 'Distance', monedas: 'Coins', trucos: 'Tricks', mojones: 'Milestones', total: 'Total',
  otraVez: 'AGAIN', alMapa: 'MAP', abriste: '{lugar} is open!',
  g_titulo: '"El Tito" Tyre Shop', usar: 'USE', elegido: 'IN USE', comprar: 'BUY', maximo: 'MAXED', faltan: 'You need {n} more',
  v_chata: 'The Pickup', v_escarabajo: 'The Fitito', v_colectivo: 'The Bus', v_cuatro: 'The 4x4', v_tractor: 'The Tractor',
  d_chata: 'The old farm pickup. Good at everything, like a good mate.',
  d_escarabajo: 'Light and thrifty: flies off the ramps, struggles on the climbs.',
  d_colectivo: 'Long, heavy and hand-painted. No hill can flip it; a road-trip tank.',
  d_cuatro: 'Four-wheel drive and mud tyres. Climbs walls.',
  d_tractor: 'Slow and stubborn. With that back wheel it climbs anything.',
  mj_motor: 'Engine', mj_llantas: 'Tyres', mj_susp: 'Suspension', mj_tanque: 'Fuel tank', mj_aire: 'Air control',
  e_vel: 'Speed', e_agarre: 'Grip', e_trepa: 'Climbing', e_nafta: 'Fuel',
  pc_titulo: 'Races', pc_sub: 'Twelve hundred metres against three rivals. No fuel to worry about.', pc_nivel: ['Neighbourhood', 'Town', 'Province'],
  pc_premio: 'Prize', pc_ganaste: 'YOU WON THE RACE!', pc_puesto: 'You finished {n}', pc_largada: 'START', pc_meta: 'FINISH',
  pc_rivales: 'Rivals', pc_ganada: 'Won', pc_correr: 'RACE',
  a_titulo: 'Settings', a_musica: 'Music', a_motor: 'Engine', a_efectos: 'Effects', a_radio: 'Radio while driving', a_idioma: 'Language',
  a_controles: 'Controls', a_vibrar: 'Vibration', a_calidad: 'Quality', a_alta: 'High', a_media: 'Medium', a_baja: 'Low',
  a_giro: 'Rotated screen', a_auto: 'Automatic', a_normal: 'Normal', a_reves: 'Upside down', a_borrar: 'Erase save', a_borrarSeguro: 'Sure? Everything will be lost.',
  a_estilo: 'Music', a_estiloFolk: 'Folk', a_estilo16: '16-bit',
  c_titulo: 'Controls', c_ayuda: 'Drag the pedals wherever feels comfortable', c_tam: 'Size', c_alfa: 'Opacity',
  c_lado: 'Swap sides', c_modo: 'Mode', c_pedales: 'Pedals', c_mitades: 'Screen halves', c_reset: 'Reset', c_freno: 'BRAKE', c_gas: 'GAS',
  moneda: '$',
};
const PT = {
  titulo: 'ROTA 40', sub: 'Da Puna à Geleira',
  elegirIdioma: 'Escolha o idioma', idiomaNombre: 'PORTUGUÊS',
  cargando: 'Carregando a caminhonete…', tocar: 'Toque para começar', teclas: 'Setas ou A/D para dirigir · P pausa',
  viajar: 'VIAJAR', picadas: 'RACHAS', gomeria: 'BORRACHARIA', ajustes: 'AJUSTES', historia: 'HISTÓRIA',
  volver: 'Voltar', listo: 'Pronto', si: 'Sim', no: 'Não', cerrar: 'Fechar', seguir: 'Continuar', saltar: 'Pular ›',
  mapa: 'A Rota 40', km: 'km', record: 'Recorde', sinRecord: 'Sem recorde', bloqueado: 'Chegue a {n} m em {lugar} para abrir',
  llegaste: 'Chegou', viajarA: 'VIAJAR', picadaA: 'RACHA',
  t_puna: 'Puna', t_quebrada: 'Quebrada de Humahuaca', t_salinas: 'Salinas Grandes', t_valles: 'Vales Calchaquíes',
  t_cuyo: 'Cuyo', t_patagonia: 'Patagônia', t_glaciar: 'As Geleiras',
  p_puna: 'A 3.500 metros o ar é rarefeito e o motor tosse. As vicunhas não têm pressa.',
  p_quebrada: 'O Morro das Sete Cores: cada faixa é outra era da terra. Cuidado com as subidas.',
  p_salinas: 'Doze mil hectares de sal. Plano como uma mesa, e a mesa está posta para voar.',
  p_valles: 'Entre Cafayate e Cachi: cascalho, vinho torrontés e morros vermelhos. As pontes de madeira rangem.',
  p_cuyo: 'Vinhedos, álamos e o Aconcágua olhando. As descidas são longas: a Difunta Correa te protege.',
  p_patagonia: 'O vento sopra de frente o ano todo. Aqui, quem não acelera não chega.',
  p_glaciar: 'O gelo estala e a estrada escorrega. No fim, a Rosa te espera com o chimarrão.',
  h1: 'Seu Tito conserta pneus em La Quiaca, lá no alto da Rota 40.',
  h2: 'Um dia chega uma carta de El Calafate: «Vem tomar um chimarrão, estou com saudade. — Rosa».',
  h3: 'São cinco mil quilômetros de cascalho, subidas e vento. Tito carrega a caminhonete e parte.',
  fin1: 'Tito chega à geleira com a caminhonete cheia de poeira.',
  fin2: '—Demorou, hein! —diz Rosa, com o chimarrão pronto.',
  fin3: '—É que a estrada é longa, irmã. Mas como é bonita.',
  creditos: 'Feito com física própria, arte da Rezona e música sintetizada. Obrigado por dirigir.',
  m: 'm', nafta: 'GASOLINA', naftaBaja: 'GASOLINA!', sinNafta: 'Sem gasolina!', cabeza: 'Bateu a cabeça!', volco: 'Capotou!',
  llegada: 'VOCÊ CHEGOU!', nuevoRecord: 'NOVO RECORDE!', mojon: 'MARCO {n}', vuelo: 'VOO {n}s', vueltaAtras: 'MORTAL PARA TRÁS', vueltaAdelante: 'MORTAL PARA FRENTE',
  doble: '×{n}', willy: 'EMPINADA {n}s', limpio: 'POUSO LIMPO', combo: 'COMBO ×{n}', casi: 'POR POUCO!',
  tutoGas: 'Pedal direito: acelerar', tutoFreno: 'Pedal esquerdo: frear e ré', tutoAire: 'No ar: acelerar gira para trás, frear gira para frente', tutoCabeza: 'Não deixe a cabeça tocar o chão',
  tutoTeclas: '→ acelerar · ← frear', pausa: 'PARE', reiniciar: 'Reiniciar', salir: 'Sair',
  resultado: 'Fim da viagem', distancia: 'Distância', monedas: 'Moedas', trucos: 'Manobras', mojones: 'Marcos', total: 'Total',
  otraVez: 'DE NOVO', alMapa: 'MAPA', abriste: '{lugar} foi liberado!',
  g_titulo: 'Borracharia "El Tito"', usar: 'USAR', elegido: 'EM USO', comprar: 'COMPRAR', maximo: 'NO MÁXIMO', faltan: 'Faltam {n}',
  v_chata: 'A Caminhonete', v_escarabajo: 'O Fitito', v_colectivo: 'O Ônibus', v_cuatro: 'O 4x4', v_tractor: 'O Trator',
  d_chata: 'A caminhonete da roça. Boa em tudo, como um bom chimarrão.',
  d_escarabajo: 'Levinho e econômico: voa nas rampas, sofre nas subidas.',
  d_colectivo: 'Comprido, pesado e pintado à mão. Nenhum morro o capota; tanque de viagem.',
  d_cuatro: 'Tração nas quatro e pneus de lama. Sobe parede.',
  d_tractor: 'Lento e teimoso. Com essa roda traseira sobe qualquer coisa.',
  mj_motor: 'Motor', mj_llantas: 'Pneus', mj_susp: 'Suspensão', mj_tanque: 'Tanque', mj_aire: 'Voo',
  e_vel: 'Velocidade', e_agarre: 'Aderência', e_trepa: 'Subida', e_nafta: 'Gasolina',
  pc_titulo: 'Rachas', pc_sub: 'Mil e duzentos metros contra três. Sem gasolina para economizar.', pc_nivel: ['Do bairro', 'Da cidade', 'Da província'],
  pc_premio: 'Prêmio', pc_ganaste: 'VOCÊ VENCEU O RACHA!', pc_puesto: 'Você chegou em {n}º', pc_largada: 'LARGADA', pc_meta: 'CHEGADA',
  pc_rivales: 'Rivais', pc_ganada: 'Vencida', pc_correr: 'CORRER',
  a_titulo: 'Ajustes', a_musica: 'Música', a_motor: 'Motor', a_efectos: 'Efeitos', a_radio: 'Rádio na estrada', a_idioma: 'Idioma',
  a_controles: 'Controles', a_vibrar: 'Vibrar', a_calidad: 'Qualidade', a_alta: 'Alta', a_media: 'Média', a_baja: 'Baixa',
  a_giro: 'Tela girada', a_auto: 'Automática', a_normal: 'Normal', a_reves: 'Invertida', a_borrar: 'Apagar o progresso', a_borrarSeguro: 'Certeza? Tudo será perdido.',
  a_estilo: 'Música', a_estiloFolk: 'Folclore', a_estilo16: '16 bits',
  c_titulo: 'Controles', c_ayuda: 'Arraste os pedais para onde ficar confortável', c_tam: 'Tamanho', c_alfa: 'Transparência',
  c_lado: 'Trocar de lado', c_modo: 'Modo', c_pedales: 'Pedais', c_mitades: 'Metades da tela', c_reset: 'Restaurar', c_freno: 'FREIO', c_gas: 'GÁS',
  moneda: '$',
};
export const IDIOMAS = { es: ES, en: EN, pt: PT };
let actual = 'es';
export function ponerIdioma(i) { actual = IDIOMAS[i] ? i : 'es'; document.documentElement.lang = actual; }
export const idioma = () => actual;
export function t(k, v) {
  let s = IDIOMAS[actual][k] ?? ES[k] ?? k;
  if (v && typeof s === 'string') for (const [a, b] of Object.entries(v)) s = s.replaceAll('{' + a + '}', b);
  return s;
}
/* números con separador de miles de cada idioma */
export const num = (n) => Math.round(n).toLocaleString(actual === 'en' ? 'en-US' : actual === 'pt' ? 'pt-BR' : 'es-AR');
