// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum BuiltinShaderMode : int
    {
        Disabled = 0,
        UseBuiltin = 1,
        UseCustom = 2,
    }
}
