// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public partial class CommandBuffer : global::System.IDisposable
    {
        public string name { set { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::name="); } }
        public void Clear() { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::Clear"); }
        public void SetViewport(global::UnityEngine.Rect pixelRect) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetViewport"); }
        public void GetTemporaryRT(int nameID, int width, int height, int depthBuffer, global::UnityEngine.FilterMode filter, global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite, int antiAliasing, bool enableRandomWrite, global::UnityEngine.RenderTextureMemoryless memorylessMode, bool useDynamicScale) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::GetTemporaryRT"); }
        public void GetTemporaryRT(int nameID, int width, int height, int depthBuffer, global::UnityEngine.FilterMode filter, global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite, int antiAliasing, bool enableRandomWrite) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::GetTemporaryRT"); }
        public void GetTemporaryRT(int nameID, int width, int height, int depthBuffer, global::UnityEngine.FilterMode filter, global::UnityEngine.RenderTextureFormat format) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::GetTemporaryRT"); }
        public void GetTemporaryRT(int nameID, global::UnityEngine.RenderTextureDescriptor desc, global::UnityEngine.FilterMode filter) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::GetTemporaryRT"); }
        public void ReleaseTemporaryRT(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::ReleaseTemporaryRT"); }
        public void ClearRenderTarget(bool clearDepth, bool clearColor, global::UnityEngine.Color backgroundColor) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::ClearRenderTarget"); }
        public void SetGlobalFloat(int nameID, float value) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetGlobalFloat"); }
        public void SetGlobalVector(int nameID, global::UnityEngine.Vector4 value) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetGlobalVector"); }
        public void EnableShaderKeyword(string keyword) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::EnableShaderKeyword"); }
        public void DisableShaderKeyword(string keyword) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::DisableShaderKeyword"); }
        public void BeginSample(string name) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::BeginSample"); }
        public void EndSample(string name) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::EndSample"); }
        public void SetRenderTarget(global::UnityEngine.Rendering.RenderTargetIdentifier rt, global::UnityEngine.Rendering.RenderBufferLoadAction loadAction, global::UnityEngine.Rendering.RenderBufferStoreAction storeAction) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetRenderTarget"); }
        public void SetRenderTarget(global::UnityEngine.Rendering.RenderTargetIdentifier rt, global::UnityEngine.Rendering.RenderBufferLoadAction colorLoadAction, global::UnityEngine.Rendering.RenderBufferStoreAction colorStoreAction, global::UnityEngine.Rendering.RenderBufferLoadAction depthLoadAction, global::UnityEngine.Rendering.RenderBufferStoreAction depthStoreAction) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetRenderTarget"); }
        public void SetRenderTarget(global::UnityEngine.Rendering.RenderTargetIdentifier rt, int mipLevel, global::UnityEngine.CubemapFace cubemapFace, int depthSlice) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetRenderTarget"); }
        public void SetRenderTarget(global::UnityEngine.Rendering.RenderTargetIdentifier color, global::UnityEngine.Rendering.RenderBufferLoadAction colorLoadAction, global::UnityEngine.Rendering.RenderBufferStoreAction colorStoreAction, global::UnityEngine.Rendering.RenderTargetIdentifier depth, global::UnityEngine.Rendering.RenderBufferLoadAction depthLoadAction, global::UnityEngine.Rendering.RenderBufferStoreAction depthStoreAction) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetRenderTarget"); }
        public void SetRenderTarget(global::UnityEngine.Rendering.RenderTargetIdentifier[] colors, global::UnityEngine.Rendering.RenderTargetIdentifier depth) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetRenderTarget"); }
        public void Dispose() { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::Dispose"); }
        public CommandBuffer() { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::.ctor"); }
        public void SetComputeVectorParam(global::UnityEngine.ComputeShader computeShader, string name, global::UnityEngine.Vector4 val) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetComputeVectorParam"); }
        public void SetComputeFloatParams(global::UnityEngine.ComputeShader computeShader, string name, params float[] values) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetComputeFloatParams"); }
        public void SetComputeTextureParam(global::UnityEngine.ComputeShader computeShader, int kernelIndex, string name, global::UnityEngine.Rendering.RenderTargetIdentifier rt) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetComputeTextureParam"); }
        public void SetComputeBufferParam(global::UnityEngine.ComputeShader computeShader, int kernelIndex, string name, global::UnityEngine.ComputeBuffer buffer) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetComputeBufferParam"); }
        public void DispatchCompute(global::UnityEngine.ComputeShader computeShader, int kernelIndex, int threadGroupsX, int threadGroupsY, int threadGroupsZ) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::DispatchCompute"); }
        public void DrawMesh(global::UnityEngine.Mesh mesh, global::UnityEngine.Matrix4x4 matrix, global::UnityEngine.Material material, int submeshIndex, int shaderPass, global::UnityEngine.MaterialPropertyBlock properties) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::DrawMesh"); }
        public void DrawMesh(global::UnityEngine.Mesh mesh, global::UnityEngine.Matrix4x4 matrix, global::UnityEngine.Material material, int submeshIndex, int shaderPass) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::DrawMesh"); }
        public void CopyTexture(global::UnityEngine.Rendering.RenderTargetIdentifier src, global::UnityEngine.Rendering.RenderTargetIdentifier dst) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::CopyTexture"); }
        public void CopyTexture(global::UnityEngine.Rendering.RenderTargetIdentifier src, int srcElement, int srcMip, global::UnityEngine.Rendering.RenderTargetIdentifier dst, int dstElement, int dstMip) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::CopyTexture"); }
        public void Blit(global::UnityEngine.Texture source, global::UnityEngine.Rendering.RenderTargetIdentifier dest) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::Blit"); }
        public void Blit(global::UnityEngine.Rendering.RenderTargetIdentifier source, global::UnityEngine.Rendering.RenderTargetIdentifier dest) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::Blit"); }
        public void Blit(global::UnityEngine.Rendering.RenderTargetIdentifier source, global::UnityEngine.Rendering.RenderTargetIdentifier dest, global::UnityEngine.Material mat, int pass) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::Blit"); }
        public void SetGlobalTexture(string name, global::UnityEngine.Rendering.RenderTargetIdentifier value) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetGlobalTexture"); }
        public void SetGlobalTexture(int nameID, global::UnityEngine.Rendering.RenderTargetIdentifier value) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetGlobalTexture"); }
        public void SetSinglePassStereo(global::UnityEngine.Rendering.SinglePassStereoMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.CommandBuffer::SetSinglePassStereo"); }
    }
}
