// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public partial struct GlobalKeyword
    {
        public string m_Name;
        public uint m_Index;
    }
}
