// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public partial struct LocalKeywordSpace : global::System.IEquatable<global::UnityEngine.Rendering.LocalKeywordSpace>
    {
        public global::System.IntPtr m_KeywordSpace;
        public bool Equals(global::UnityEngine.Rendering.LocalKeywordSpace rhs) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.LocalKeywordSpace::Equals"); return default; }
    }
}
