// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public partial struct LocalKeyword : global::System.IEquatable<global::UnityEngine.Rendering.LocalKeyword>
    {
        public global::UnityEngine.Rendering.LocalKeywordSpace m_SpaceInfo;
        public string m_Name;
        public uint m_Index;
        public bool Equals(global::UnityEngine.Rendering.LocalKeyword rhs) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.LocalKeyword::Equals"); return default; }
    }
}
