// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum ReflectionProbeClearFlags : int
    {
        Skybox = 1,
        SolidColor = 2,
    }
}
