// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum ReflectionProbeType : int
    {
        Cube = 0,
        Card = 1,
    }
}
