// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum ReflectionProbeMode : int
    {
        Baked = 0,
        Realtime = 1,
        Custom = 2,
    }
}
