// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum RenderTextureSubElement : int
    {
        Color = 0,
        Depth = 1,
        Stencil = 2,
        Default = 3,
    }
}
