// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public partial struct RenderTargetIdentifier : global::System.IEquatable<global::UnityEngine.Rendering.RenderTargetIdentifier>
    {
        public global::UnityEngine.Rendering.BuiltinRenderTextureType m_Type;
        public int m_NameID;
        public int m_InstanceID;
        public global::System.IntPtr m_BufferPointer;
        public int m_MipLevel;
        public global::UnityEngine.CubemapFace m_CubeFace;
        public int m_DepthSlice;
        public RenderTargetIdentifier(global::UnityEngine.Rendering.BuiltinRenderTextureType type) { this = default; }
        public RenderTargetIdentifier(int nameID) { this = default; }
        public RenderTargetIdentifier(global::UnityEngine.Texture tex) { this = default; }
        public static implicit operator global::UnityEngine.Rendering.RenderTargetIdentifier(global::UnityEngine.Rendering.BuiltinRenderTextureType type) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.RenderTargetIdentifier::op_Implicit"); return default; }
        public static implicit operator global::UnityEngine.Rendering.RenderTargetIdentifier(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.RenderTargetIdentifier::op_Implicit"); return default; }
        public static implicit operator global::UnityEngine.Rendering.RenderTargetIdentifier(global::UnityEngine.Texture tex) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.RenderTargetIdentifier::op_Implicit"); return default; }
        public static implicit operator global::UnityEngine.Rendering.RenderTargetIdentifier(global::UnityEngine.RenderBuffer buf) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.RenderTargetIdentifier::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Rendering.RenderTargetIdentifier rhs) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.RenderTargetIdentifier::Equals"); return default; }
    }
}
