// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public abstract partial class RenderPipelineAsset : global::UnityEngine.ScriptableObject
    {
        protected abstract global::UnityEngine.Rendering.RenderPipeline CreatePipeline();
        protected virtual void OnDisable() { global::Porteo.Falta.Llamada("UnityEngine.Rendering.RenderPipelineAsset::OnDisable"); }
    }
}
