// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public abstract partial class RenderPipeline
    {
        protected abstract void Render(global::UnityEngine.Rendering.ScriptableRenderContext context, global::UnityEngine.Camera[] cameras);
    }
}
