// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public partial struct RenderTargetBinding
    {
        public global::UnityEngine.Rendering.RenderTargetIdentifier[] m_ColorRenderTargets;
        public global::UnityEngine.Rendering.RenderTargetIdentifier m_DepthRenderTarget;
        public global::UnityEngine.Rendering.RenderBufferLoadAction[] m_ColorLoadActions;
        public global::UnityEngine.Rendering.RenderBufferStoreAction[] m_ColorStoreActions;
        public global::UnityEngine.Rendering.RenderBufferLoadAction m_DepthLoadAction;
        public global::UnityEngine.Rendering.RenderBufferStoreAction m_DepthStoreAction;
        public global::UnityEngine.Rendering.RenderTargetFlags m_Flags;
    }
}
