// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum RenderBufferStoreAction : int
    {
        Store = 0,
        Resolve = 1,
        StoreAndResolve = 2,
        DontCare = 3,
    }
}
