// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public partial struct ScriptableRenderContext : global::System.IEquatable<global::UnityEngine.Rendering.ScriptableRenderContext>
    {
        public global::System.IntPtr m_Ptr;
        public bool Equals(global::UnityEngine.Rendering.ScriptableRenderContext other) { global::Porteo.Falta.Llamada("UnityEngine.Rendering.ScriptableRenderContext::Equals"); return default; }
    }
}
