// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum ShadowSamplingMode : int
    {
        CompareDepths = 0,
        RawDepth = 1,
        None = 2,
    }
}
