// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Rendering
{
    public enum SinglePassStereoMode : int
    {
        None = 0,
        SideBySide = 1,
        Instancing = 2,
        Multiview = 3,
    }
}
