// Los textos en tres idiomas y en una sola tabla, como en ritmo/ y paraguas/.
//
// El castellano es el original. Lo que falta en otro idioma cae al inglés, y
// si tampoco está, al castellano: se nota, que es la idea (un hueco callado no
// se arregla nunca). Los nombres de los ítems en castellano viven en items.js
// junto al resto de sus datos; acá están sus traducciones ('it.' y 'd.').
//
// Las marcas {así} se reemplazan con t(clave, { así: valor }). Las que no se
// pasan quedan como están: la notificación "+{n} Madera" completa su {n} más
// tarde, cuando suma lo que va juntando.
export const IDIOMAS = { es: 'Español', en: 'English', pt: 'Português' };
const LOCALES = { es: 'es-AR', en: 'en-US', pt: 'pt-BR' };
let actual = 'es';

export function idioma() { return actual; }
export function locale() { return LOCALES[actual]; }
export function ponerIdioma(c) {
  if (!IDIOMAS[c]) return false;
  actual = c;
  document.documentElement.lang = c;
  return true;
}
export function detectarIdioma() {
  for (const l of navigator.languages || [navigator.language || 'es']) {
    const c = String(l).slice(0, 2).toLowerCase();
    if (IDIOMAS[c]) return c;
  }
  return 'en';
}
export function t(clave, v = null, def = undefined) {
  let s = T[actual][clave] ?? (actual === 'es' ? undefined : T.en[clave]) ?? def ?? T.es[clave] ?? clave;
  if (v) s = s.replace(/\{(\w+)\}/g, (m, k) => (k in v ? v[k] : m));
  return s;
}

const T = {
  es: {
    'doc.titulo': 'La Isla',
    'menu.la': 'LA', 'menu.isla': 'ISLA',
    'menu.jugar': 'JUGAR', 'menu.ajustes': 'AJUSTES', 'menu.creditos': 'CRÉDITOS',
    'menu.continuar': 'CONTINUAR', 'menu.nueva': 'NUEVA PARTIDA', 'menu.volver': '← VOLVER',
    'menu.deNuevo1': '¿DE', 'menu.deNuevo2': 'NUEVO?', 'menu.siBorrar': 'SÍ, BORRAR LA ISLA', 'menu.no': '← NO',
    'menu.pausa': 'PAUSA', 'menu.salir': 'SALIR AL MENÚ',
    'menu.pie': 'La isla de @vfx843, rehecha en HTML · Menú al estilo de @brutu_scripts',
    'menu.pieBorrar': 'Se borra lo guardado: el terreno, lo construido y lo juntado.',
    'menu.pieCartel': 'Tocá los botones del cartel',
    'menu.pieGuarda': 'La isla se guarda sola',
    'menu.pieIdioma': 'Elegí tu idioma · Choose your language · Escolha seu idioma',
    'menu.guardada': 'Guardada el {fecha} a las {hora} · Día {dia}',
    'aj.titulo': 'AJUSTES', 'aj.musica': 'MÚSICA', 'aj.efectos': 'EFECTOS', 'aj.ambiente': 'AMBIENTE',
    'aj.mirar': 'MIRAR', 'aj.calidad': 'CALIDAD', 'aj.baja': 'BAJA', 'aj.media': 'MEDIA', 'aj.alta': 'ALTA',
    'aj.pixel': 'PÍXEL', 'aj.auto': 'AUTO', 'aj.idioma': 'IDIOMA',
    'cr.titulo': 'CRÉDITOS',
    'cr.1': 'La isla de Phoenix Baker (@vfx843)', 'cr.2': 'rehecha en HTML a partir de sus videos.',
    'cr.3': 'Menú: la idea de @brutu_scripts', 'cr.4': 'cámara que se mece y vuela a los carteles.',
    'cr.5': 'Todo hecho con código', 'cr.6': 'texturas, modelos, música y sonidos:', 'cr.7': 'ni una imagen ni un audio de archivo.',
    'hud.dia': 'Día {n} · {hora}', 'hud.objetivo': 'OBJETIVO',
    'v.mochila': 'Mochila', 'v.mesa': 'Mesa', 'v.cofre': 'Cofre', 'v.coleccion': 'Colección',
    'v.fabricarMano': 'Fabricar a mano', 'v.mesaTitulo': 'Mesa de trabajo', 'v.mesaLejos': 'Mesa de trabajo — acercate a una para fabricar',
    'v.barra': 'Barra', 'v.mesaCerca': 'Hay una mesa cerca: {n} recetas más en la pestaña Mesa.',
    'v.mesaFalta': 'Con una mesa de trabajo cerca se desbloquean {n} recetas más.', 'v.hacer': 'Hacer',
    'v.coleccionTitulo': 'Colección — {a} de {b}', 'v.patrimonio': 'Patrimonio: <b>{p}</b> · Día {d}',
    'v.stats': 'Palmeras taladas: {a} · Rocas picadas: {b} · Peces: {c} · Bloques puestos: {d}',
    'tip.desconocido': 'Todavía no lo encontraste.', 'tip.cu': '{p} c/u · {t}', 'tip.comida': 'Se come (F): +{n} de hambre',
    'pincel.titulo': '{nombre} (R cambia)',
    'pincel.subir': 'Subir', 'pincel.bajar': 'Bajar', 'pincel.aplanar': 'Aplanar', 'pincel.suavizar': 'Suavizar', 'pincel.arena': 'Arena', 'pincel.pasto': 'Pasto',
    'a.clic': 'Hacé clic para jugar', 'a.juntar': 'Juntar {n}', 'a.mina': 'Bajar a la mina', 'a.subir': 'Subir a la isla',
    'a.descansar': 'Descansar hasta el amanecer', 'a.mesa': 'Mesa de trabajo', 'a.cofre': 'Abrir cofre',
    'a.picoHierro': 'Necesitás un pico de hierro', 'a.aca': 'Acá no: está la choza o el muelle', 'a.piedra': 'Para subir el piso hace falta piedra',
    'n.llena': 'La mochila está llena', 'n.mina': 'La mina: más adentro, vetas más raras', 'n.farol': 'Sin farol no se ve casi nada…',
    'n.dia': 'Día {n}. ¡Buen día!', 'n.sinHambre': 'No tenés hambre', 'n.veta': 'Esta veta necesita un pico de hierro',
    'n.estrella': '¡Cayó una estrella cerca!', 'n.nuevo': '¡Nuevo! {nombre} {e}', 'n.junta': '+{n} {nombre}', 'n.hiciste': 'Hiciste: {nombre}',
    'n.hambre': 'Tenés hambre: comé algo (F)', 'n.desmayo': 'Te desmayaste y despertaste en la choza',
    'o.1': 'Juntá ramas y piedras del piso: caminá por encima o apretá E',
    'o.2': 'Abrí la mochila (Tab) y hacé un hacha de piedra',
    'o.3': 'Con el hacha en la mano, talá una palmera (clic)',
    'o.4': 'Con 4 de madera hacé una mesa de trabajo y ponela (clic derecho)',
    'o.5': 'En la mesa (E): hacé un pico de piedra',
    'o.6': 'Picá rocas: de a pedazos salen piedra, carbón y a veces hierro',
    'o.7': 'Con hierro, carbón y madera, hacé un farol en la mesa',
    'o.8': 'Bajá a la mina: la boca está en la ladera del cerro',
    'o.9': 'Lo raro está lejos de la escalera y pide pico de hierro',
    'o.10': 'Llená la colección: pescá, minerá y mirá el cielo de noche',
    'b.pausa': 'Pausa', 'b.cerrar': 'Cerrar', 'b.saltar': 'Saltar', 'b.usar': 'Usar', 'b.poner': 'Poner', 'b.e': 'Interactuar', 'b.inv': 'Inventario',
  },
  en: {
    'doc.titulo': 'The Island',
    'menu.la': 'THE', 'menu.isla': 'ISLAND',
    'menu.jugar': 'PLAY', 'menu.ajustes': 'SETTINGS', 'menu.creditos': 'CREDITS',
    'menu.continuar': 'CONTINUE', 'menu.nueva': 'NEW GAME', 'menu.volver': '← BACK',
    'menu.deNuevo1': 'START', 'menu.deNuevo2': 'OVER?', 'menu.siBorrar': 'YES, ERASE THE ISLAND', 'menu.no': '← NO',
    'menu.pausa': 'PAUSED', 'menu.salir': 'QUIT TO MENU',
    'menu.pie': "@vfx843's island, remade in HTML · Menu in the style of @brutu_scripts",
    'menu.pieBorrar': 'Everything saved is erased: the terrain, what you built and what you collected.',
    'menu.pieCartel': 'Press the buttons on the sign',
    'menu.pieGuarda': 'The island saves itself',
    'menu.guardada': 'Saved on {fecha} at {hora} · Day {dia}',
    'aj.titulo': 'SETTINGS', 'aj.musica': 'MUSIC', 'aj.efectos': 'SOUNDS', 'aj.ambiente': 'AMBIENCE',
    'aj.mirar': 'LOOK', 'aj.calidad': 'QUALITY', 'aj.baja': 'LOW', 'aj.media': 'MED', 'aj.alta': 'HIGH',
    'aj.pixel': 'PIXEL', 'aj.auto': 'AUTO', 'aj.idioma': 'LANGUAGE',
    'cr.titulo': 'CREDITS',
    'cr.1': 'The island by Phoenix Baker (@vfx843)', 'cr.2': 'remade in HTML from the videos.',
    'cr.3': 'Menu: the idea by @brutu_scripts', 'cr.4': 'a camera that sways and flies to the signs.',
    'cr.5': 'All made with code', 'cr.6': 'textures, models, music and sounds:', 'cr.7': 'not a single image or audio file.',
    'hud.dia': 'Day {n} · {hora}', 'hud.objetivo': 'GOAL',
    'v.mochila': 'Backpack', 'v.mesa': 'Workbench', 'v.cofre': 'Chest', 'v.coleccion': 'Collection',
    'v.fabricarMano': 'Craft by hand', 'v.mesaTitulo': 'Workbench', 'v.mesaLejos': 'Workbench — get close to one to craft',
    'v.barra': 'Hotbar', 'v.mesaCerca': 'There is a workbench nearby: {n} more recipes in the Workbench tab.',
    'v.mesaFalta': 'Near a workbench, {n} more recipes unlock.', 'v.hacer': 'Craft',
    'v.coleccionTitulo': 'Collection — {a} of {b}', 'v.patrimonio': 'Net worth: <b>{p}</b> · Day {d}',
    'v.stats': 'Palms felled: {a} · Rocks mined: {b} · Fish: {c} · Blocks placed: {d}',
    'tip.desconocido': "You haven't found it yet.", 'tip.cu': '{p} each · {t}', 'tip.comida': 'Edible (F): +{n} food',
    'pincel.titulo': '{nombre} (R to switch)',
    'pincel.subir': 'Raise', 'pincel.bajar': 'Lower', 'pincel.aplanar': 'Flatten', 'pincel.suavizar': 'Smooth', 'pincel.arena': 'Sand', 'pincel.pasto': 'Grass',
    'a.clic': 'Click to play', 'a.juntar': 'Pick up {n}', 'a.mina': 'Go down into the mine', 'a.subir': 'Climb up to the island',
    'a.descansar': 'Rest until dawn', 'a.mesa': 'Workbench', 'a.cofre': 'Open chest',
    'a.picoHierro': 'You need an iron pickaxe', 'a.aca': 'Not here: the hut or the dock is in the way', 'a.piedra': 'Raising the ground takes stone',
    'n.llena': 'Your backpack is full', 'n.mina': 'The mine: the deeper, the rarer the veins', 'n.farol': 'Without a lantern you can barely see…',
    'n.dia': 'Day {n}. Good morning!', 'n.sinHambre': "You're not hungry", 'n.veta': 'This vein needs an iron pickaxe',
    'n.estrella': 'A star fell nearby!', 'n.nuevo': 'New! {nombre} {e}', 'n.junta': '+{n} {nombre}', 'n.hiciste': 'You made: {nombre}',
    'n.hambre': "You're hungry: eat something (F)", 'n.desmayo': 'You passed out and woke up at the hut',
    'o.1': 'Pick up sticks and stones: walk over them or press E',
    'o.2': 'Open your backpack (Tab) and craft a stone axe',
    'o.3': 'With the axe in hand, chop down a palm tree (click)',
    'o.4': 'With 4 wood, craft a workbench and place it (right click)',
    'o.5': 'At the workbench (E): craft a stone pickaxe',
    'o.6': 'Mine rocks: chunk by chunk you get stone, coal and sometimes iron',
    'o.7': 'With iron, coal and wood, craft a lantern at the workbench',
    'o.8': 'Go down into the mine: the entrance is on the hillside',
    'o.9': 'Rare things are far from the ladder and need an iron pickaxe',
    'o.10': 'Fill the collection: fish, mine and watch the night sky',
    'b.pausa': 'Pause', 'b.cerrar': 'Close', 'b.saltar': 'Jump', 'b.usar': 'Use', 'b.poner': 'Place', 'b.e': 'Interact', 'b.inv': 'Inventory',
    'it.rama': 'Stick', 'it.piedra': 'Stone', 'it.madera': 'Wood', 'it.fibra': 'Fiber', 'it.coco': 'Coconut', 'it.carbon': 'Coal',
    'it.hierro': 'Iron', 'it.pirita': 'Pyrite', 'it.oro': 'Gold', 'it.cuarzo': 'Quartz', 'it.citrino': 'Citrine', 'it.amatista': 'Amethyst',
    'it.esmeralda': 'Emerald', 'it.rubi': 'Ruby', 'it.zafiro': 'Sapphire', 'it.lapislazuli': 'Lapis lazuli', 'it.malaquita': 'Malachite',
    'it.aguamarina': 'Phosphophyllite', 'it.tanzanita': 'Tanzanite', 'it.opalo': 'Opal', 'it.bismuto': 'Bismuth', 'it.estrella': 'Fallen star',
    'it.cielo': 'Sky shard', 'it.uranio': 'Uranium', 'it.gravinita': 'Gravinite', 'it.antimateria': 'Antimatter', 'it.quarks': 'Quark cluster',
    'it.atun': 'Tuna', 'it.payaso': 'Clownfish', 'it.calamar': 'Squid', 'it.abisal': 'Anglerfish', 'it.botella': 'Message in a bottle',
    'it.moneda': 'Ancient coin', 'it.hachaPiedra': 'Stone axe', 'it.picoPiedra': 'Stone pickaxe', 'it.pala': 'Shovel', 'it.guadana': 'Scythe',
    'it.cana': 'Fishing rod', 'it.canaBuena': 'Golden rod', 'it.farol': 'Lantern', 'it.picoHierro': 'Iron pickaxe', 'it.hachaHierro': 'Iron axe',
    'it.picoAmatista': 'Amethyst pickaxe', 'it.mesa': 'Workbench', 'it.cofre': 'Chest', 'it.bloqueMadera': 'Wood block', 'it.tablon': 'Plank',
    'it.bloquePiedra': 'Stone block', 'it.farolPie': 'Standing lantern',
    'd.pirita': "Fool's gold: shines the same, worth little.", 'd.lapislazuli': "It had to be here: it's in Minecraft.",
    'd.estrella': 'Gives off its own light. They fall at night.',
    'd.cielo': 'Literally a piece of the sky: it always shows the sky, wherever you are.',
    'd.uranio': 'Radioactive, of course.', 'd.gravinita': 'Lets you see the spacetime around it.',
    'd.antimateria': 'Looking inside is looking at the universe.', 'd.quarks': 'Particles that pop in and out of existence.',
    'd.abisal': "It shouldn't be this close to shore. It's a game.",
  },
  pt: {
    'doc.titulo': 'A Ilha',
    'menu.la': 'A', 'menu.isla': 'ILHA',
    'menu.jugar': 'JOGAR', 'menu.ajustes': 'AJUSTES', 'menu.creditos': 'CRÉDITOS',
    'menu.continuar': 'CONTINUAR', 'menu.nueva': 'NOVO JOGO', 'menu.volver': '← VOLTAR',
    'menu.deNuevo1': 'COMEÇAR', 'menu.deNuevo2': 'DE NOVO?', 'menu.siBorrar': 'SIM, APAGAR A ILHA', 'menu.no': '← NÃO',
    'menu.pausa': 'PAUSA', 'menu.salir': 'SAIR PARA O MENU',
    'menu.pie': 'A ilha de @vfx843, refeita em HTML · Menu no estilo de @brutu_scripts',
    'menu.pieBorrar': 'Tudo o que foi salvo é apagado: o terreno, o que você construiu e o que juntou.',
    'menu.pieCartel': 'Toque nos botões da placa',
    'menu.pieGuarda': 'A ilha se salva sozinha',
    'menu.guardada': 'Salva em {fecha} às {hora} · Dia {dia}',
    'aj.titulo': 'AJUSTES', 'aj.musica': 'MÚSICA', 'aj.efectos': 'EFEITOS', 'aj.ambiente': 'AMBIENTE',
    'aj.mirar': 'OLHAR', 'aj.calidad': 'QUALIDADE', 'aj.baja': 'BAIXA', 'aj.media': 'MÉDIA', 'aj.alta': 'ALTA',
    'aj.pixel': 'PIXEL', 'aj.auto': 'AUTO', 'aj.idioma': 'IDIOMA',
    'cr.titulo': 'CRÉDITOS',
    'cr.1': 'A ilha de Phoenix Baker (@vfx843)', 'cr.2': 'refeita em HTML a partir dos vídeos.',
    'cr.3': 'Menu: a ideia de @brutu_scripts', 'cr.4': 'câmera que balança e voa até as placas.',
    'cr.5': 'Tudo feito com código', 'cr.6': 'texturas, modelos, música e sons:', 'cr.7': 'nenhuma imagem nem áudio de arquivo.',
    'hud.dia': 'Dia {n} · {hora}', 'hud.objetivo': 'OBJETIVO',
    'v.mochila': 'Mochila', 'v.mesa': 'Bancada', 'v.cofre': 'Baú', 'v.coleccion': 'Coleção',
    'v.fabricarMano': 'Fabricar à mão', 'v.mesaTitulo': 'Bancada', 'v.mesaLejos': 'Bancada — chegue perto de uma para fabricar',
    'v.barra': 'Barra', 'v.mesaCerca': 'Tem uma bancada perto: mais {n} receitas na aba Bancada.',
    'v.mesaFalta': 'Perto de uma bancada, mais {n} receitas são liberadas.', 'v.hacer': 'Fazer',
    'v.coleccionTitulo': 'Coleção — {a} de {b}', 'v.patrimonio': 'Patrimônio: <b>{p}</b> · Dia {d}',
    'v.stats': 'Palmeiras derrubadas: {a} · Rochas quebradas: {b} · Peixes: {c} · Blocos colocados: {d}',
    'tip.desconocido': 'Você ainda não encontrou.', 'tip.cu': '{p} cada · {t}', 'tip.comida': 'Comestível (F): +{n} de fome',
    'pincel.titulo': '{nombre} (R troca)',
    'pincel.subir': 'Elevar', 'pincel.bajar': 'Baixar', 'pincel.aplanar': 'Aplanar', 'pincel.suavizar': 'Suavizar', 'pincel.arena': 'Areia', 'pincel.pasto': 'Grama',
    'a.clic': 'Clique para jogar', 'a.juntar': 'Pegar {n}', 'a.mina': 'Descer para a mina', 'a.subir': 'Subir para a ilha',
    'a.descansar': 'Descansar até o amanhecer', 'a.mesa': 'Bancada', 'a.cofre': 'Abrir baú',
    'a.picoHierro': 'Você precisa de uma picareta de ferro', 'a.aca': 'Aqui não: a cabana ou o píer está no caminho', 'a.piedra': 'Para elevar o chão é preciso pedra',
    'n.llena': 'A mochila está cheia', 'n.mina': 'A mina: quanto mais fundo, mais raros os veios', 'n.farol': 'Sem lanterna quase não se vê nada…',
    'n.dia': 'Dia {n}. Bom dia!', 'n.sinHambre': 'Você não está com fome', 'n.veta': 'Este veio precisa de uma picareta de ferro',
    'n.estrella': 'Uma estrela caiu por perto!', 'n.nuevo': 'Novo! {nombre} {e}', 'n.junta': '+{n} {nombre}', 'n.hiciste': 'Você fez: {nombre}',
    'n.hambre': 'Você está com fome: coma algo (F)', 'n.desmayo': 'Você desmaiou e acordou na cabana',
    'o.1': 'Pegue gravetos e pedras do chão: passe por cima ou aperte E',
    'o.2': 'Abra a mochila (Tab) e faça um machado de pedra',
    'o.3': 'Com o machado na mão, derrube uma palmeira (clique)',
    'o.4': 'Com 4 de madeira, faça uma bancada e coloque no chão (clique direito)',
    'o.5': 'Na bancada (E): faça uma picareta de pedra',
    'o.6': 'Quebre rochas: pedaço por pedaço saem pedra, carvão e às vezes ferro',
    'o.7': 'Com ferro, carvão e madeira, faça uma lanterna na bancada',
    'o.8': 'Desça para a mina: a entrada fica na encosta do morro',
    'o.9': 'O raro fica longe da escada e pede picareta de ferro',
    'o.10': 'Complete a coleção: pesque, minere e olhe o céu à noite',
    'b.pausa': 'Pausa', 'b.cerrar': 'Fechar', 'b.saltar': 'Pular', 'b.usar': 'Usar', 'b.poner': 'Colocar', 'b.e': 'Interagir', 'b.inv': 'Inventário',
    'it.rama': 'Graveto', 'it.piedra': 'Pedra', 'it.madera': 'Madeira', 'it.fibra': 'Fibra', 'it.coco': 'Coco', 'it.carbon': 'Carvão',
    'it.hierro': 'Ferro', 'it.pirita': 'Pirita', 'it.oro': 'Ouro', 'it.cuarzo': 'Quartzo', 'it.citrino': 'Citrino', 'it.amatista': 'Ametista',
    'it.esmeralda': 'Esmeralda', 'it.rubi': 'Rubi', 'it.zafiro': 'Safira', 'it.lapislazuli': 'Lápis-lazúli', 'it.malaquita': 'Malaquita',
    'it.aguamarina': 'Fosfofilita', 'it.tanzanita': 'Tanzanita', 'it.opalo': 'Opala', 'it.bismuto': 'Bismuto', 'it.estrella': 'Estrela caída',
    'it.cielo': 'Fragmento de céu', 'it.uranio': 'Urânio', 'it.gravinita': 'Gravinita', 'it.antimateria': 'Antimatéria', 'it.quarks': 'Aglomerado de quarks',
    'it.atun': 'Atum', 'it.payaso': 'Peixe-palhaço', 'it.calamar': 'Lula', 'it.abisal': 'Peixe-abissal', 'it.botella': 'Mensagem na garrafa',
    'it.moneda': 'Moeda antiga', 'it.hachaPiedra': 'Machado de pedra', 'it.picoPiedra': 'Picareta de pedra', 'it.pala': 'Pá', 'it.guadana': 'Foice',
    'it.cana': 'Vara de pesca', 'it.canaBuena': 'Vara dourada', 'it.farol': 'Lanterna', 'it.picoHierro': 'Picareta de ferro', 'it.hachaHierro': 'Machado de ferro',
    'it.picoAmatista': 'Picareta de ametista', 'it.mesa': 'Bancada', 'it.cofre': 'Baú', 'it.bloqueMadera': 'Bloco de madeira', 'it.tablon': 'Tábua',
    'it.bloquePiedra': 'Bloco de pedra', 'it.farolPie': 'Poste com lanterna',
    'd.pirita': 'O ouro dos tolos: brilha igual, vale pouco.', 'd.lapislazuli': 'Tinha que estar aqui: está no Minecraft.',
    'd.estrella': 'Tem luz própria. Caem à noite.',
    'd.cielo': 'Literalmente um pedaço do céu: sempre mostra o céu, onde quer que você esteja.',
    'd.uranio': 'Radioativo, claro.', 'd.gravinita': 'Deixa ver o espaço-tempo ao redor.',
    'd.antimateria': 'Olhar dentro é olhar o universo.', 'd.quarks': 'Partículas que aparecem e desaparecem.',
    'd.abisal': 'Não deveria estar tão perto da praia. É um jogo.',
  },
};
