// Los textos en tres idiomas y en una sola tabla, como en ritmo/ y paraguas/.
//
// El castellano es el original. Lo que falta en otro idioma cae al inglés, y
// si tampoco está, al castellano: se nota, que es la idea (un hueco callado no
// se arregla nunca). Los nombres de los ítems en castellano viven en items.js
// junto al resto de sus datos; acá están sus traducciones ('it.' y 'd.').
//
// Las marcas {así} se reemplazan con t(clave, { así: valor }). Las que no se
// pasan quedan como están: la notificación "+{n} Madera" completa su {n} más
// tarde, cuando suma lo que va juntando.
export const IDIOMAS = { es: 'Español', en: 'English', pt: 'Português' };
const LOCALES = { es: 'es-AR', en: 'en-US', pt: 'pt-BR' };
let actual = 'es';

export function idioma() { return actual; }
export function locale() { return LOCALES[actual]; }
export function ponerIdioma(c) {
  if (!IDIOMAS[c]) return false;
  actual = c;
  document.documentElement.lang = c;
  return true;
}
export function detectarIdioma() {
  for (const l of navigator.languages || [navigator.language || 'es']) {
    const c = String(l).slice(0, 2).toLowerCase();
    if (IDIOMAS[c]) return c;
  }
  return 'en';
}
export function t(clave, v = null, def = undefined) {
  let s = T[actual][clave] ?? (actual === 'es' ? undefined : T.en[clave]) ?? def ?? T.es[clave] ?? clave;
  if (v) s = s.replace(/\{(\w+)\}/g, (m, k) => (k in v ? v[k] : m));
  return s;
}

const T = {
  es: {
    'doc.titulo': 'La Isla',
    'menu.la': 'LA', 'menu.isla': 'ISLA',
    'menu.jugar': 'JUGAR', 'menu.ajustes': 'AJUSTES', 'menu.creditos': 'CRÉDITOS',
    'menu.continuar': 'CONTINUAR', 'menu.nueva': 'NUEVA PARTIDA', 'menu.volver': '← VOLVER',
    'menu.deNuevo1': '¿DE', 'menu.deNuevo2': 'NUEVO?', 'menu.siBorrar': 'SÍ, BORRAR LA ISLA', 'menu.no': '← NO',
    'menu.pausa': 'PAUSA', 'menu.salir': 'SALIR AL MENÚ',
    'menu.pie': 'La isla de @vfx843, rehecha en HTML · Menú al estilo de @brutu_scripts',
    'menu.pieBorrar': 'Se borra lo guardado: el terreno, lo construido y lo juntado.',
    'menu.pieCartel': 'Tocá los botones del cartel',
    'menu.pieGuarda': 'La isla se guarda sola',
    'menu.pieIdioma': 'Elegí tu idioma · Choose your language · Escolha seu idioma',
    'menu.guardada': 'Guardada el {fecha} a las {hora} · Día {dia}',
    'aj.titulo': 'AJUSTES', 'aj.musica': 'MÚSICA', 'aj.efectos': 'EFECTOS', 'aj.ambiente': 'AMBIENTE',
    'aj.mirar': 'MIRAR', 'aj.calidad': 'CALIDAD', 'aj.baja': 'BAJA', 'aj.media': 'MEDIA', 'aj.alta': 'ALTA',
    'aj.pixel': 'PÍXEL', 'aj.auto': 'AUTO', 'aj.idioma': 'IDIOMA',
    'cr.titulo': 'CRÉDITOS',
    'cr.1': 'La isla de Phoenix Baker (@vfx843)', 'cr.2': 'rehecha en HTML a partir de sus videos.',
    'cr.3': 'Menú: la idea de @brutu_scripts', 'cr.4': 'cámara que se mece y vuela a los carteles.',
    'cr.5': 'Todo hecho con código', 'cr.6': 'texturas, modelos, música y sonidos:', 'cr.7': 'ni una imagen ni un audio de archivo.',
    'hud.dia': 'Día {n} · {hora}', 'hud.objetivo': 'OBJETIVO',
    'v.mochila': 'Mochila', 'v.mesa': 'Mesa', 'v.cofre': 'Cofre', 'v.coleccion': 'Colección',
    'v.fabricarMano': 'Fabricar a mano', 'v.mesaTitulo': 'Mesa de trabajo', 'v.mesaLejos': 'Mesa de trabajo — acercate a una para fabricar',
    'v.barra': 'Barra', 'v.mesaCerca': 'Hay una mesa cerca: {n} recetas más en la pestaña Mesa.',
    'v.mesaFalta': 'Con una mesa de trabajo cerca se desbloquean {n} recetas más.', 'v.hacer': 'Hacer',
    'v.coleccionTitulo': 'Colección — {a} de {b}', 'v.patrimonio': 'Patrimonio: <b>{p}</b> · Día {d}',
    'v.stats': 'Palmeras taladas: {a} · Rocas picadas: {b} · Peces: {c} · Bloques puestos: {d} · Enemigos vencidos: {e}',
    'tip.desconocido': 'Todavía no lo encontraste.', 'tip.cu': '{p} c/u · {t}', 'tip.comida': 'Se come (F): +{n} de hambre',
    'pincel.titulo': '{nombre} (R cambia)',
    'pincel.subir': 'Subir', 'pincel.bajar': 'Bajar', 'pincel.aplanar': 'Aplanar', 'pincel.suavizar': 'Suavizar', 'pincel.arena': 'Arena', 'pincel.pasto': 'Pasto',
    'a.clic': 'Hacé clic para jugar', 'a.juntar': 'Juntar {n}', 'a.mina': 'Bajar a la mina', 'a.subir': 'Subir a la isla',
    'a.descansar': 'Descansar hasta el amanecer', 'a.mesa': 'Mesa de trabajo', 'a.cofre': 'Abrir cofre',
    'a.picoHierro': 'Necesitás un pico de hierro', 'a.aca': 'Acá no: está la choza o el muelle', 'a.piedra': 'Para subir el piso hace falta piedra',
    'n.llena': 'La mochila está llena', 'n.mina': 'La mina: más adentro, vetas más raras', 'n.farol': 'Sin farol no se ve casi nada…',
    'n.dia': 'Día {n}. ¡Buen día!', 'n.sinHambre': 'No tenés hambre', 'n.veta': 'Esta veta necesita un pico de hierro',
    'n.estrella': '¡Cayó una estrella cerca!', 'n.nuevo': '¡Nuevo! {nombre} {e}', 'n.junta': '+{n} {nombre}', 'n.hiciste': 'Hiciste: {nombre}',
    'n.hambre': 'Tenés hambre: comé algo (F)', 'n.desmayo': 'Te desmayaste y despertaste en la choza',
    'o.1': 'Juntá ramas y piedras del piso: caminá por encima o apretá E',
    'o.2': 'Abrí la mochila (Tab) y hacé un hacha de piedra',
    'o.3': 'Con el hacha en la mano, talá una palmera (clic)',
    'o.4': 'Con 4 de madera hacé una mesa de trabajo y ponela (clic derecho)',
    'o.botella': 'Buscá la botella junto al barco roto y leela (clic derecho)',
    'o.espada': 'Hacé un arma: una espada de piedra o una lanza (Tab)',
    'o.fogata': 'Hacé una fogata y ponela: cocina y espanta a los esqueletos',
    'o.noche': 'Sobreviví: vencé a 3 enemigos (cangrejos, esqueletos…)',
    'o.cocinar': 'Cociná carne o pescado en la fogata (clic derecho)',
    'o.faro': 'Buscá el faro en la punta de la isla (M abre el mapa)',
    'o.pico': 'En la mesa (E): hacé un pico de piedra',
    'o.farol': 'Con hierro, carbón y madera, hacé un farol: la mina es oscura',
    'o.mina': 'Bajá a la mina: la boca está en la ladera del cerro',
    'o.escalera': 'Arreglá la escalera del faro: 20 de madera y 4 de hierro (E en la puerta)',
    'o.lente': 'Armá la lente del faro: 3 de cuarzo y 1 de oro',
    'o.picoHierro': 'Hacé un pico de hierro (y un peto, si te alcanza)',
    'o.jefe': 'Vencé al guardián en la sala más honda de la mina',
    'o.cristal': 'Llevá el corazón de cristal al faro',
    'o.encender': 'De noche, encendé el faro con una estrella caída',
    'o.barco': 'Al amanecer llega un barco al muelle: subí (E)',
    'o.coleccion': 'Llená la colección: pescá, minerá y mirá el cielo de noche',
    'cap.titulo': 'Capítulo {n} · {nombre}',
    'cap.1': 'El naufragio', 'cap.2': 'La primera noche', 'cap.3': 'El faro', 'cap.4': 'El guardián', 'cap.5': 'La luz', 'cap.6': 'La isla es tuya',
    'cap.bajada.1': 'Juntá lo que trajo el mar y armá tus primeras herramientas.',
    'cap.bajada.2': 'Hacé un arma y una fogata: de noche salen los esqueletos.',
    'cap.bajada.3': 'En la punta de la isla hay un faro apagado. Si vuelve a alumbrar, alguien va a venir.',
    'cap.bajada.4': 'El corazón del faro lo tiene el guardián de la mina, en la sala más honda.',
    'cap.bajada.5': 'Poné el cristal y encendé el faro con una estrella caída.',
    'cap.bajada.6': 'Te vinieron a buscar. La isla sigue acá: completá la colección.',
    'c.1': 'Si alguien lee esto: el faro de la isla está apagado. El guardián de la mina, un gólem de piedra, se llevó su corazón de cristal y lo guarda en la sala más honda. Sin luz, ningún barco se anima a acercarse.\n\nArreglá el faro y encendelo: te van a venir a buscar.\n\n— el último farero',
    'c.2': 'De noche salen de la arena los esqueletos de la tripulación del Albatros. Le tienen miedo al fuego: una fogata los aleja, y el sol los quema.',
    'c.3': 'La escalera del faro se pudrió con la sal. Se rehace con madera y un poco de hierro. La lente, con cuarzo y oro.',
    'c.4': 'El mercader viene de día y amarra al lado del muelle. Paga bien las gemas. Dicen que vende el mapa de un tesoro enterrado en una playa lejana.',
    'c.5': 'La luz del faro se prende con fuego del cielo: una estrella de las que caen de noche.',
    'v.faro': 'Faro', 'v.tienda': 'Mercader',
    'f.titulo': 'El faro', 'f.bajada': 'Cuatro arreglos y vuelve a alumbrar. Con luz, algún barco se va a animar a venir.',
    'f.escalera': 'Escalera y baranda', 'f.lente': 'La lente', 'f.cristal': 'El corazón de cristal', 'f.luz': 'Encenderlo (de noche)',
    'f.deNoche': 'De noche', 'f.reparar': 'Arreglar',
    'f.hecho.escalera': 'Escalera arreglada', 'f.hecho.lente': 'La lente está en su lugar',
    'f.hecho.cristal': 'El corazón de cristal brilla arriba del faro', 'f.hecho.luz': '¡El faro está encendido!',
    'n.faroLuz': 'Al amanecer, algún barco va a ver la luz', 'n.barcoViene': '¡Un barco en el horizonte! Viene al muelle',
    'n.barcoLlego': 'El barco llegó al muelle: subí con E',
    'm.plata': 'Tu plata: {p}', 'm.vender': 'Vender · clic: uno · Shift o clic derecho: la pila', 'm.comprar': 'Comprar',
    'm.teDa': 'Te da', 'm.ayudaVenta': 'El mercader paga el 80 % de lo que vale',
    'tip.dano': 'Daño: {n}', 'tip.defensa': 'Defensa: {n} % · clic derecho para ponértelo', 'tip.cocina': 'Se cocina en la fogata', 'tip.cura': '+{n} de vida',
    'jefe.nombre': 'EL GUARDIÁN DE LA MINA',
    'a.faro': 'Arreglar el faro', 'a.mercader': 'Comerciar', 'a.barco': 'Subir al barco',
    'a.cocinar': 'Clic derecho: cocinar', 'a.plantar': 'Clic derecho: plantar el coco', 'a.leer': 'Clic derecho: leer el mensaje',
    'a.ponerse': 'Clic derecho: ponértelo', 'a.tesoro': 'Cavá acá con la pala (▼)',
    'n.cocinado': 'Cocinaste: {nombre}', 'n.plantado': 'Plantaste un coco: en un rato es una palmera', 'n.ponerse': 'Te pusiste: {nombre}',
    'n.compraste': 'Compraste: {nombre}', 'n.jefeVencido': '¡Venciste al guardián! Llevá el corazón de cristal al faro',
    'n.noVende': 'Eso no se vende: lo vas a necesitar', 'n.tesoro': '¡Encontraste el tesoro!', 'n.sinFlechas': 'No tenés flechas',
    'n.jefeEnojado': '¡El guardián se enojó!', 'n.noche': 'Se hace de noche: salen los esqueletos',
    'n.mercader': 'El mercader amarró su bote al lado del muelle',
    'mapa.ayuda': 'M o tocá para cerrar', 'carta.cerrar': 'Tocá para cerrar',
    'fin.titulo': '¡RESCATADO!', 'fin.texto1': 'Después de un día en la isla, el barco te lleva de vuelta a casa. El faro queda prendido para el próximo náufrago.', 'fin.texto': 'Después de {d} días en la isla, el barco te lleva de vuelta a casa. El faro queda prendido para el próximo náufrago.',
    'fin.stats': 'Enemigos vencidos: {a} · Palmeras: {b} · Rocas: {c} · Peces: {e} · Patrimonio: {p}',
    'fin.seguir': 'SEGUIR EN LA ISLA',
    'b.mapa': 'Mapa', 'b.vista': 'Cambiar la vista',
    'b.pausa': 'Pausa', 'b.cerrar': 'Cerrar', 'b.saltar': 'Saltar', 'b.usar': 'Usar', 'b.poner': 'Poner', 'b.e': 'Interactuar', 'b.inv': 'Inventario',
  },
  en: {
    'doc.titulo': 'The Island',
    'menu.la': 'THE', 'menu.isla': 'ISLAND',
    'menu.jugar': 'PLAY', 'menu.ajustes': 'SETTINGS', 'menu.creditos': 'CREDITS',
    'menu.continuar': 'CONTINUE', 'menu.nueva': 'NEW GAME', 'menu.volver': '← BACK',
    'menu.deNuevo1': 'START', 'menu.deNuevo2': 'OVER?', 'menu.siBorrar': 'YES, ERASE THE ISLAND', 'menu.no': '← NO',
    'menu.pausa': 'PAUSED', 'menu.salir': 'QUIT TO MENU',
    'menu.pie': "@vfx843's island, remade in HTML · Menu in the style of @brutu_scripts",
    'menu.pieBorrar': 'Everything saved is erased: the terrain, what you built and what you collected.',
    'menu.pieCartel': 'Press the buttons on the sign',
    'menu.pieGuarda': 'The island saves itself',
    'menu.guardada': 'Saved on {fecha} at {hora} · Day {dia}',
    'aj.titulo': 'SETTINGS', 'aj.musica': 'MUSIC', 'aj.efectos': 'SOUNDS', 'aj.ambiente': 'AMBIENCE',
    'aj.mirar': 'LOOK', 'aj.calidad': 'QUALITY', 'aj.baja': 'LOW', 'aj.media': 'MED', 'aj.alta': 'HIGH',
    'aj.pixel': 'PIXEL', 'aj.auto': 'AUTO', 'aj.idioma': 'LANGUAGE',
    'cr.titulo': 'CREDITS',
    'cr.1': 'The island by Phoenix Baker (@vfx843)', 'cr.2': 'remade in HTML from the videos.',
    'cr.3': 'Menu: the idea by @brutu_scripts', 'cr.4': 'a camera that sways and flies to the signs.',
    'cr.5': 'All made with code', 'cr.6': 'textures, models, music and sounds:', 'cr.7': 'not a single image or audio file.',
    'hud.dia': 'Day {n} · {hora}', 'hud.objetivo': 'GOAL',
    'v.mochila': 'Backpack', 'v.mesa': 'Workbench', 'v.cofre': 'Chest', 'v.coleccion': 'Collection',
    'v.fabricarMano': 'Craft by hand', 'v.mesaTitulo': 'Workbench', 'v.mesaLejos': 'Workbench — get close to one to craft',
    'v.barra': 'Hotbar', 'v.mesaCerca': 'There is a workbench nearby: {n} more recipes in the Workbench tab.',
    'v.mesaFalta': 'Near a workbench, {n} more recipes unlock.', 'v.hacer': 'Craft',
    'v.coleccionTitulo': 'Collection — {a} of {b}', 'v.patrimonio': 'Net worth: <b>{p}</b> · Day {d}',
    'v.stats': 'Palms felled: {a} · Rocks mined: {b} · Fish: {c} · Blocks placed: {d} · Enemies defeated: {e}',
    'tip.desconocido': "You haven't found it yet.", 'tip.cu': '{p} each · {t}', 'tip.comida': 'Edible (F): +{n} food',
    'pincel.titulo': '{nombre} (R to switch)',
    'pincel.subir': 'Raise', 'pincel.bajar': 'Lower', 'pincel.aplanar': 'Flatten', 'pincel.suavizar': 'Smooth', 'pincel.arena': 'Sand', 'pincel.pasto': 'Grass',
    'a.clic': 'Click to play', 'a.juntar': 'Pick up {n}', 'a.mina': 'Go down into the mine', 'a.subir': 'Climb up to the island',
    'a.descansar': 'Rest until dawn', 'a.mesa': 'Workbench', 'a.cofre': 'Open chest',
    'a.picoHierro': 'You need an iron pickaxe', 'a.aca': 'Not here: the hut or the dock is in the way', 'a.piedra': 'Raising the ground takes stone',
    'n.llena': 'Your backpack is full', 'n.mina': 'The mine: the deeper, the rarer the veins', 'n.farol': 'Without a lantern you can barely see…',
    'n.dia': 'Day {n}. Good morning!', 'n.sinHambre': "You're not hungry", 'n.veta': 'This vein needs an iron pickaxe',
    'n.estrella': 'A star fell nearby!', 'n.nuevo': 'New! {nombre} {e}', 'n.junta': '+{n} {nombre}', 'n.hiciste': 'You made: {nombre}',
    'n.hambre': "You're hungry: eat something (F)", 'n.desmayo': 'You passed out and woke up at the hut',
    'o.1': 'Pick up sticks and stones: walk over them or press E',
    'o.2': 'Open your backpack (Tab) and craft a stone axe',
    'o.3': 'With the axe in hand, chop down a palm tree (click)',
    'o.4': 'With 4 wood, craft a workbench and place it (right click)',
    'o.botella': 'Find the bottle by the wrecked ship and read it (right click)',
    'o.espada': 'Make a weapon: a stone sword or a spear (Tab)',
    'o.fogata': 'Make a campfire and place it: it cooks and keeps skeletons away',
    'o.noche': 'Survive: defeat 3 enemies (crabs, skeletons…)',
    'o.cocinar': 'Cook meat or fish at the campfire (right click)',
    'o.faro': 'Find the lighthouse at the tip of the island (M opens the map)',
    'o.pico': 'At the workbench (E): craft a stone pickaxe',
    'o.farol': 'With iron, coal and wood, craft a lantern: the mine is dark',
    'o.mina': 'Go down into the mine: the entrance is on the hillside',
    'o.escalera': 'Fix the lighthouse stairs: 20 wood and 4 iron (E at the door)',
    'o.lente': 'Build the lighthouse lens: 3 quartz and 1 gold',
    'o.picoHierro': 'Craft an iron pickaxe (and a chestplate, if you can)',
    'o.jefe': 'Defeat the guardian in the deepest room of the mine',
    'o.cristal': 'Take the crystal heart to the lighthouse',
    'o.encender': 'At night, light the lighthouse with a fallen star',
    'o.barco': 'At dawn a ship reaches the dock: board it (E)',
    'o.coleccion': 'Fill the collection: fish, mine and watch the night sky',
    'cap.titulo': 'Chapter {n} · {nombre}',
    'cap.1': 'The shipwreck', 'cap.2': 'The first night', 'cap.3': 'The lighthouse', 'cap.4': 'The guardian', 'cap.5': 'The light', 'cap.6': 'The island is yours',
    'cap.bajada.1': 'Gather what the sea brought and make your first tools.',
    'cap.bajada.2': 'Make a weapon and a campfire: skeletons come out at night.',
    'cap.bajada.3': 'At the tip of the island stands a dark lighthouse. If it shines again, someone will come.',
    'cap.bajada.4': "The lighthouse's heart is held by the mine guardian, in the deepest room.",
    'cap.bajada.5': 'Set the crystal and light the lighthouse with a fallen star.',
    'cap.bajada.6': 'They came for you. The island is still here: complete the collection.',
    'c.1': "If anyone reads this: the island's lighthouse is dark. The mine guardian, a stone golem, took its crystal heart and keeps it in the deepest room. Without a light, no ship dares to come near.\n\nFix the lighthouse and light it: they will come for you.\n\n— the last lighthouse keeper",
    'c.2': "At night, the skeletons of the Albatross crew rise from the sand. They fear fire: a campfire keeps them away, and the sun burns them.",
    'c.3': "The lighthouse stairs rotted in the salt air. Wood and a little iron will rebuild them. The lens takes quartz and gold.",
    'c.4': "The merchant comes by day and moors beside the dock. Pays well for gems. They say he sells a map to a treasure buried on a faraway beach.",
    'c.5': "The lighthouse is lit with fire from the sky: one of the stars that fall at night.",
    'v.faro': 'Lighthouse', 'v.tienda': 'Merchant',
    'f.titulo': 'The lighthouse', 'f.bajada': 'Four repairs and it shines again. With a light, some ship will dare to come.',
    'f.escalera': 'Stairs and railing', 'f.lente': 'The lens', 'f.cristal': 'The crystal heart', 'f.luz': 'Light it (at night)',
    'f.deNoche': 'At night', 'f.reparar': 'Repair',
    'f.hecho.escalera': 'Stairs fixed', 'f.hecho.lente': 'The lens is in place',
    'f.hecho.cristal': 'The crystal heart glows atop the lighthouse', 'f.hecho.luz': 'The lighthouse is lit!',
    'n.faroLuz': 'At dawn, some ship will see the light', 'n.barcoViene': 'A ship on the horizon! Heading for the dock',
    'n.barcoLlego': 'The ship reached the dock: board it with E',
    'm.plata': 'Your money: {p}', 'm.vender': 'Sell · click: one · Shift or right click: the stack', 'm.comprar': 'Buy',
    'm.teDa': 'Pays', 'm.ayudaVenta': 'The merchant pays 80% of the value',
    'tip.dano': 'Damage: {n}', 'tip.defensa': 'Defense: {n}% · right click to wear it', 'tip.cocina': 'Cook it at a campfire', 'tip.cura': '+{n} health',
    'jefe.nombre': 'THE MINE GUARDIAN',
    'a.faro': 'Repair the lighthouse', 'a.mercader': 'Trade', 'a.barco': 'Board the ship',
    'a.cocinar': 'Right click: cook', 'a.plantar': 'Right click: plant the coconut', 'a.leer': 'Right click: read the message',
    'a.ponerse': 'Right click: put it on', 'a.tesoro': 'Dig here with the shovel (▼)',
    'n.cocinado': 'You cooked: {nombre}', 'n.plantado': 'You planted a coconut: soon it will be a palm tree', 'n.ponerse': 'You put on: {nombre}',
    'n.compraste': 'You bought: {nombre}', 'n.jefeVencido': 'You defeated the guardian! Take the crystal heart to the lighthouse',
    'n.noVende': "That's not for sale: you'll need it", 'n.tesoro': 'You found the treasure!', 'n.sinFlechas': 'You have no arrows',
    'n.jefeEnojado': 'The guardian is enraged!', 'n.noche': 'Night falls: the skeletons come out',
    'n.mercader': 'The merchant moored his boat beside the dock',
    'mapa.ayuda': 'M or tap to close', 'carta.cerrar': 'Tap to close',
    'fin.titulo': 'RESCUED!', 'fin.texto1': 'After a single day on the island, the ship takes you home. The lighthouse stays lit for the next castaway.', 'fin.texto': 'After {d} days on the island, the ship takes you home. The lighthouse stays lit for the next castaway.',
    'fin.stats': 'Enemies defeated: {a} · Palms: {b} · Rocks: {c} · Fish: {e} · Net worth: {p}',
    'fin.seguir': 'STAY ON THE ISLAND',
    'b.mapa': 'Map', 'b.vista': 'Switch view',
    'it.espadaMadera': 'Wooden sword', 'it.espadaPiedra': 'Stone sword', 'it.espadaHierro': 'Iron sword', 'it.espadaAmatista': 'Amethyst sword',
    'it.lanza': 'Spear', 'it.arco': 'Bow', 'it.flecha': 'Arrow', 'it.petoCaparazon': 'Shell chestplate', 'it.petoHierro': 'Iron chestplate',
    'it.carneCangrejo': 'Crab meat', 'it.cangrejoAsado': 'Roast crab', 'it.pescadoAsado': 'Grilled fish', 'it.caparazon': 'Shell', 'it.hueso': 'Bone',
    'it.pocion': 'Health potion', 'it.mapaTesoro': 'Treasure map', 'it.corazonCristal': 'Crystal heart', 'it.fogata': 'Campfire',
    'd.espadaAmatista': 'Cuts leaving a violet trail.', 'd.lanza': 'Reaches farther than a sword.', 'd.arco': 'Hold to draw. Uses arrows.',
    'd.pocion': 'From the merchant. Heals almost everything.', 'd.mapaTesoro': 'An X on a faraway beach. Dig it up with the shovel.',
    'd.corazonCristal': "The lighthouse crystal. The mine guardian had it.", 'd.fogata': 'Cooks food and keeps skeletons away.',
    'b.pausa': 'Pause', 'b.cerrar': 'Close', 'b.saltar': 'Jump', 'b.usar': 'Use', 'b.poner': 'Place', 'b.e': 'Interact', 'b.inv': 'Inventory',
    'it.rama': 'Stick', 'it.piedra': 'Stone', 'it.madera': 'Wood', 'it.fibra': 'Fiber', 'it.coco': 'Coconut', 'it.carbon': 'Coal',
    'it.hierro': 'Iron', 'it.pirita': 'Pyrite', 'it.oro': 'Gold', 'it.cuarzo': 'Quartz', 'it.citrino': 'Citrine', 'it.amatista': 'Amethyst',
    'it.esmeralda': 'Emerald', 'it.rubi': 'Ruby', 'it.zafiro': 'Sapphire', 'it.lapislazuli': 'Lapis lazuli', 'it.malaquita': 'Malachite',
    'it.aguamarina': 'Phosphophyllite', 'it.tanzanita': 'Tanzanite', 'it.opalo': 'Opal', 'it.bismuto': 'Bismuth', 'it.estrella': 'Fallen star',
    'it.cielo': 'Sky shard', 'it.uranio': 'Uranium', 'it.gravinita': 'Gravinite', 'it.antimateria': 'Antimatter', 'it.quarks': 'Quark cluster',
    'it.atun': 'Tuna', 'it.payaso': 'Clownfish', 'it.calamar': 'Squid', 'it.abisal': 'Anglerfish', 'it.botella': 'Message in a bottle',
    'it.moneda': 'Ancient coin', 'it.hachaPiedra': 'Stone axe', 'it.picoPiedra': 'Stone pickaxe', 'it.pala': 'Shovel', 'it.guadana': 'Scythe',
    'it.cana': 'Fishing rod', 'it.canaBuena': 'Golden rod', 'it.farol': 'Lantern', 'it.picoHierro': 'Iron pickaxe', 'it.hachaHierro': 'Iron axe',
    'it.picoAmatista': 'Amethyst pickaxe', 'it.mesa': 'Workbench', 'it.cofre': 'Chest', 'it.bloqueMadera': 'Wood block', 'it.tablon': 'Plank',
    'it.bloquePiedra': 'Stone block', 'it.farolPie': 'Standing lantern',
    'd.pirita': "Fool's gold: shines the same, worth little.", 'd.lapislazuli': "It had to be here: it's in Minecraft.",
    'd.estrella': 'Gives off its own light. They fall at night.',
    'd.cielo': 'Literally a piece of the sky: it always shows the sky, wherever you are.',
    'd.uranio': 'Radioactive, of course.', 'd.gravinita': 'Lets you see the spacetime around it.',
    'd.antimateria': 'Looking inside is looking at the universe.', 'd.quarks': 'Particles that pop in and out of existence.',
    'd.abisal': "It shouldn't be this close to shore. It's a game.",
  },
  pt: {
    'doc.titulo': 'A Ilha',
    'menu.la': 'A', 'menu.isla': 'ILHA',
    'menu.jugar': 'JOGAR', 'menu.ajustes': 'AJUSTES', 'menu.creditos': 'CRÉDITOS',
    'menu.continuar': 'CONTINUAR', 'menu.nueva': 'NOVO JOGO', 'menu.volver': '← VOLTAR',
    'menu.deNuevo1': 'COMEÇAR', 'menu.deNuevo2': 'DE NOVO?', 'menu.siBorrar': 'SIM, APAGAR A ILHA', 'menu.no': '← NÃO',
    'menu.pausa': 'PAUSA', 'menu.salir': 'SAIR PARA O MENU',
    'menu.pie': 'A ilha de @vfx843, refeita em HTML · Menu no estilo de @brutu_scripts',
    'menu.pieBorrar': 'Tudo o que foi salvo é apagado: o terreno, o que você construiu e o que juntou.',
    'menu.pieCartel': 'Toque nos botões da placa',
    'menu.pieGuarda': 'A ilha se salva sozinha',
    'menu.guardada': 'Salva em {fecha} às {hora} · Dia {dia}',
    'aj.titulo': 'AJUSTES', 'aj.musica': 'MÚSICA', 'aj.efectos': 'EFEITOS', 'aj.ambiente': 'AMBIENTE',
    'aj.mirar': 'OLHAR', 'aj.calidad': 'QUALIDADE', 'aj.baja': 'BAIXA', 'aj.media': 'MÉDIA', 'aj.alta': 'ALTA',
    'aj.pixel': 'PIXEL', 'aj.auto': 'AUTO', 'aj.idioma': 'IDIOMA',
    'cr.titulo': 'CRÉDITOS',
    'cr.1': 'A ilha de Phoenix Baker (@vfx843)', 'cr.2': 'refeita em HTML a partir dos vídeos.',
    'cr.3': 'Menu: a ideia de @brutu_scripts', 'cr.4': 'câmera que balança e voa até as placas.',
    'cr.5': 'Tudo feito com código', 'cr.6': 'texturas, modelos, música e sons:', 'cr.7': 'nenhuma imagem nem áudio de arquivo.',
    'hud.dia': 'Dia {n} · {hora}', 'hud.objetivo': 'OBJETIVO',
    'v.mochila': 'Mochila', 'v.mesa': 'Bancada', 'v.cofre': 'Baú', 'v.coleccion': 'Coleção',
    'v.fabricarMano': 'Fabricar à mão', 'v.mesaTitulo': 'Bancada', 'v.mesaLejos': 'Bancada — chegue perto de uma para fabricar',
    'v.barra': 'Barra', 'v.mesaCerca': 'Tem uma bancada perto: mais {n} receitas na aba Bancada.',
    'v.mesaFalta': 'Perto de uma bancada, mais {n} receitas são liberadas.', 'v.hacer': 'Fazer',
    'v.coleccionTitulo': 'Coleção — {a} de {b}', 'v.patrimonio': 'Patrimônio: <b>{p}</b> · Dia {d}',
    'v.stats': 'Palmeiras derrubadas: {a} · Rochas quebradas: {b} · Peixes: {c} · Blocos colocados: {d} · Inimigos vencidos: {e}',
    'tip.desconocido': 'Você ainda não encontrou.', 'tip.cu': '{p} cada · {t}', 'tip.comida': 'Comestível (F): +{n} de fome',
    'pincel.titulo': '{nombre} (R troca)',
    'pincel.subir': 'Elevar', 'pincel.bajar': 'Baixar', 'pincel.aplanar': 'Aplanar', 'pincel.suavizar': 'Suavizar', 'pincel.arena': 'Areia', 'pincel.pasto': 'Grama',
    'a.clic': 'Clique para jogar', 'a.juntar': 'Pegar {n}', 'a.mina': 'Descer para a mina', 'a.subir': 'Subir para a ilha',
    'a.descansar': 'Descansar até o amanhecer', 'a.mesa': 'Bancada', 'a.cofre': 'Abrir baú',
    'a.picoHierro': 'Você precisa de uma picareta de ferro', 'a.aca': 'Aqui não: a cabana ou o píer está no caminho', 'a.piedra': 'Para elevar o chão é preciso pedra',
    'n.llena': 'A mochila está cheia', 'n.mina': 'A mina: quanto mais fundo, mais raros os veios', 'n.farol': 'Sem lanterna quase não se vê nada…',
    'n.dia': 'Dia {n}. Bom dia!', 'n.sinHambre': 'Você não está com fome', 'n.veta': 'Este veio precisa de uma picareta de ferro',
    'n.estrella': 'Uma estrela caiu por perto!', 'n.nuevo': 'Novo! {nombre} {e}', 'n.junta': '+{n} {nombre}', 'n.hiciste': 'Você fez: {nombre}',
    'n.hambre': 'Você está com fome: coma algo (F)', 'n.desmayo': 'Você desmaiou e acordou na cabana',
    'o.1': 'Pegue gravetos e pedras do chão: passe por cima ou aperte E',
    'o.2': 'Abra a mochila (Tab) e faça um machado de pedra',
    'o.3': 'Com o machado na mão, derrube uma palmeira (clique)',
    'o.4': 'Com 4 de madeira, faça uma bancada e coloque no chão (clique direito)',
    'o.botella': 'Procure a garrafa perto do barco destruído e leia (clique direito)',
    'o.espada': 'Faça uma arma: uma espada de pedra ou uma lança (Tab)',
    'o.fogata': 'Faça uma fogueira e coloque no chão: cozinha e afasta os esqueletos',
    'o.noche': 'Sobreviva: vença 3 inimigos (caranguejos, esqueletos…)',
    'o.cocinar': 'Cozinhe carne ou peixe na fogueira (clique direito)',
    'o.faro': 'Encontre o farol na ponta da ilha (M abre o mapa)',
    'o.pico': 'Na bancada (E): faça uma picareta de pedra',
    'o.farol': 'Com ferro, carvão e madeira, faça uma lanterna: a mina é escura',
    'o.mina': 'Desça para a mina: a entrada fica na encosta do morro',
    'o.escalera': 'Conserte a escada do farol: 20 de madeira e 4 de ferro (E na porta)',
    'o.lente': 'Monte a lente do farol: 3 de quartzo e 1 de ouro',
    'o.picoHierro': 'Faça uma picareta de ferro (e um peitoral, se der)',
    'o.jefe': 'Vença o guardião na sala mais funda da mina',
    'o.cristal': 'Leve o coração de cristal ao farol',
    'o.encender': 'À noite, acenda o farol com uma estrela caída',
    'o.barco': 'Ao amanhecer um navio chega ao píer: suba (E)',
    'o.coleccion': 'Complete a coleção: pesque, minere e olhe o céu à noite',
    'cap.titulo': 'Capítulo {n} · {nombre}',
    'cap.1': 'O naufrágio', 'cap.2': 'A primeira noite', 'cap.3': 'O farol', 'cap.4': 'O guardião', 'cap.5': 'A luz', 'cap.6': 'A ilha é sua',
    'cap.bajada.1': 'Junte o que o mar trouxe e faça suas primeiras ferramentas.',
    'cap.bajada.2': 'Faça uma arma e uma fogueira: à noite saem os esqueletos.',
    'cap.bajada.3': 'Na ponta da ilha há um farol apagado. Se voltar a brilhar, alguém vai vir.',
    'cap.bajada.4': 'O coração do farol está com o guardião da mina, na sala mais funda.',
    'cap.bajada.5': 'Coloque o cristal e acenda o farol com uma estrela caída.',
    'cap.bajada.6': 'Vieram te buscar. A ilha continua aqui: complete a coleção.',
    'c.1': 'Se alguém ler isto: o farol da ilha está apagado. O guardião da mina, um golem de pedra, levou o coração de cristal e o guarda na sala mais funda. Sem luz, nenhum navio se arrisca a chegar perto.\n\nConserte o farol e acenda: vão vir te buscar.\n\n— o último faroleiro',
    'c.2': 'À noite, os esqueletos da tripulação do Albatroz saem da areia. Têm medo do fogo: uma fogueira os afasta, e o sol os queima.',
    'c.3': 'A escada do farol apodreceu com o sal. Se refaz com madeira e um pouco de ferro. A lente, com quartzo e ouro.',
    'c.4': 'O mercador vem de dia e atraca ao lado do píer. Paga bem pelas gemas. Dizem que vende o mapa de um tesouro enterrado numa praia distante.',
    'c.5': 'A luz do farol se acende com fogo do céu: uma das estrelas que caem à noite.',
    'v.faro': 'Farol', 'v.tienda': 'Mercador',
    'f.titulo': 'O farol', 'f.bajada': 'Quatro consertos e ele volta a brilhar. Com luz, algum navio vai se arriscar a vir.',
    'f.escalera': 'Escada e grade', 'f.lente': 'A lente', 'f.cristal': 'O coração de cristal', 'f.luz': 'Acendê-lo (à noite)',
    'f.deNoche': 'À noite', 'f.reparar': 'Consertar',
    'f.hecho.escalera': 'Escada consertada', 'f.hecho.lente': 'A lente está no lugar',
    'f.hecho.cristal': 'O coração de cristal brilha no alto do farol', 'f.hecho.luz': 'O farol está aceso!',
    'n.faroLuz': 'Ao amanhecer, algum navio vai ver a luz', 'n.barcoViene': 'Um navio no horizonte! Vem para o píer',
    'n.barcoLlego': 'O navio chegou ao píer: suba com E',
    'm.plata': 'Seu dinheiro: {p}', 'm.vender': 'Vender · clique: um · Shift ou clique direito: a pilha', 'm.comprar': 'Comprar',
    'm.teDa': 'Paga', 'm.ayudaVenta': 'O mercador paga 80% do valor',
    'tip.dano': 'Dano: {n}', 'tip.defensa': 'Defesa: {n}% · clique direito para vestir', 'tip.cocina': 'Cozinha na fogueira', 'tip.cura': '+{n} de vida',
    'jefe.nombre': 'O GUARDIÃO DA MINA',
    'a.faro': 'Consertar o farol', 'a.mercader': 'Negociar', 'a.barco': 'Subir no navio',
    'a.cocinar': 'Clique direito: cozinhar', 'a.plantar': 'Clique direito: plantar o coco', 'a.leer': 'Clique direito: ler a mensagem',
    'a.ponerse': 'Clique direito: vestir', 'a.tesoro': 'Cave aqui com a pá (▼)',
    'n.cocinado': 'Você cozinhou: {nombre}', 'n.plantado': 'Você plantou um coco: logo vira uma palmeira', 'n.ponerse': 'Você vestiu: {nombre}',
    'n.compraste': 'Você comprou: {nombre}', 'n.jefeVencido': 'Você venceu o guardião! Leve o coração de cristal ao farol',
    'n.noVende': 'Isso não se vende: você vai precisar', 'n.tesoro': 'Você encontrou o tesouro!', 'n.sinFlechas': 'Você não tem flechas',
    'n.jefeEnojado': 'O guardião ficou furioso!', 'n.noche': 'Anoitece: os esqueletos saem',
    'n.mercader': 'O mercador atracou o barco ao lado do píer',
    'mapa.ayuda': 'M ou toque para fechar', 'carta.cerrar': 'Toque para fechar',
    'fin.titulo': 'RESGATADO!', 'fin.texto1': 'Depois de um dia na ilha, o navio te leva para casa. O farol fica aceso para o próximo náufrago.', 'fin.texto': 'Depois de {d} dias na ilha, o navio te leva para casa. O farol fica aceso para o próximo náufrago.',
    'fin.stats': 'Inimigos vencidos: {a} · Palmeiras: {b} · Rochas: {c} · Peixes: {e} · Patrimônio: {p}',
    'fin.seguir': 'FICAR NA ILHA',
    'b.mapa': 'Mapa', 'b.vista': 'Trocar a visão',
    'it.espadaMadera': 'Espada de madeira', 'it.espadaPiedra': 'Espada de pedra', 'it.espadaHierro': 'Espada de ferro', 'it.espadaAmatista': 'Espada de ametista',
    'it.lanza': 'Lança', 'it.arco': 'Arco', 'it.flecha': 'Flecha', 'it.petoCaparazon': 'Peitoral de carapaça', 'it.petoHierro': 'Peitoral de ferro',
    'it.carneCangrejo': 'Carne de caranguejo', 'it.cangrejoAsado': 'Caranguejo assado', 'it.pescadoAsado': 'Peixe assado', 'it.caparazon': 'Carapaça', 'it.hueso': 'Osso',
    'it.pocion': 'Poção de vida', 'it.mapaTesoro': 'Mapa do tesouro', 'it.corazonCristal': 'Coração de cristal', 'it.fogata': 'Fogueira',
    'd.espadaAmatista': 'Corta deixando um rastro violeta.', 'd.lanza': 'Alcança mais longe que uma espada.', 'd.arco': 'Segure para puxar. Usa flechas.',
    'd.pocion': 'Do mercador. Cura quase tudo.', 'd.mapaTesoro': 'Um X numa praia distante. É preciso cavar com a pá.',
    'd.corazonCristal': 'O cristal do farol. Estava com o guardião da mina.', 'd.fogata': 'Cozinha e afasta os esqueletos.',
    'b.pausa': 'Pausa', 'b.cerrar': 'Fechar', 'b.saltar': 'Pular', 'b.usar': 'Usar', 'b.poner': 'Colocar', 'b.e': 'Interagir', 'b.inv': 'Inventário',
    'it.rama': 'Graveto', 'it.piedra': 'Pedra', 'it.madera': 'Madeira', 'it.fibra': 'Fibra', 'it.coco': 'Coco', 'it.carbon': 'Carvão',
    'it.hierro': 'Ferro', 'it.pirita': 'Pirita', 'it.oro': 'Ouro', 'it.cuarzo': 'Quartzo', 'it.citrino': 'Citrino', 'it.amatista': 'Ametista',
    'it.esmeralda': 'Esmeralda', 'it.rubi': 'Rubi', 'it.zafiro': 'Safira', 'it.lapislazuli': 'Lápis-lazúli', 'it.malaquita': 'Malaquita',
    'it.aguamarina': 'Fosfofilita', 'it.tanzanita': 'Tanzanita', 'it.opalo': 'Opala', 'it.bismuto': 'Bismuto', 'it.estrella': 'Estrela caída',
    'it.cielo': 'Fragmento de céu', 'it.uranio': 'Urânio', 'it.gravinita': 'Gravinita', 'it.antimateria': 'Antimatéria', 'it.quarks': 'Aglomerado de quarks',
    'it.atun': 'Atum', 'it.payaso': 'Peixe-palhaço', 'it.calamar': 'Lula', 'it.abisal': 'Peixe-abissal', 'it.botella': 'Mensagem na garrafa',
    'it.moneda': 'Moeda antiga', 'it.hachaPiedra': 'Machado de pedra', 'it.picoPiedra': 'Picareta de pedra', 'it.pala': 'Pá', 'it.guadana': 'Foice',
    'it.cana': 'Vara de pesca', 'it.canaBuena': 'Vara dourada', 'it.farol': 'Lanterna', 'it.picoHierro': 'Picareta de ferro', 'it.hachaHierro': 'Machado de ferro',
    'it.picoAmatista': 'Picareta de ametista', 'it.mesa': 'Bancada', 'it.cofre': 'Baú', 'it.bloqueMadera': 'Bloco de madeira', 'it.tablon': 'Tábua',
    'it.bloquePiedra': 'Bloco de pedra', 'it.farolPie': 'Poste com lanterna',
    'd.pirita': 'O ouro dos tolos: brilha igual, vale pouco.', 'd.lapislazuli': 'Tinha que estar aqui: está no Minecraft.',
    'd.estrella': 'Tem luz própria. Caem à noite.',
    'd.cielo': 'Literalmente um pedaço do céu: sempre mostra o céu, onde quer que você esteja.',
    'd.uranio': 'Radioativo, claro.', 'd.gravinita': 'Deixa ver o espaço-tempo ao redor.',
    'd.antimateria': 'Olhar dentro é olhar o universo.', 'd.quarks': 'Partículas que aparecem e desaparecem.',
    'd.abisal': 'Não deveria estar tão perto da praia. É um jogo.',
  },
};
