// Recorrido del capítulo 1 con la app completa (index.html): aviso → menú → prólogo → narración → controles → dormitorio.
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
const { chromium } = createRequire('/opt/node22/lib/node_modules/playwright/')('playwright');
const AQUI = path.dirname(new URL(import.meta.url).pathname);
const PUERTO = 18000 + Math.floor(Math.random() * 2000);
fs.mkdirSync(path.join(AQUI, 'pruebas/salida'), { recursive: true });
const srv = spawn('python3', ['-m', 'http.server', String(PUERTO), '--bind', '127.0.0.1'], { cwd: path.join(AQUI, 'dist'), stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 700));
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required'] });
const p = await b.newPage({ viewport: { width: 400, height: 225 }, deviceScaleFactor: 1 });
const errores = [];
p.on('pageerror', (e) => errores.push('PAGEERROR ' + (e.stack || e.message).slice(0, 400)));
p.on('console', (m) => { const t = m.text(); if (m.type() === 'error' && !/favicon|404/.test(t)) errores.push(t.slice(0, 300)); });
await p.addInitScript(() => { localStorage.setItem('tjoc.ajustes', JSON.stringify({ idioma: 'es' })); });
await p.goto(`http://127.0.0.1:${PUERTO}/index.html`);
await p.click('#empezar');
const nivel = () => p.evaluate(() => window.__tjoc?.J?.M?.nombreNivel || null);
const esperarNivel = async (n, ms = 120000) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { if ((await nivel()) === n && await p.evaluate(() => document.querySelector('#carga').hidden)) return true; await p.waitForTimeout(300); } return false; };
const foto = (n) => p.screenshot({ path: path.join(AQUI, 'pruebas/salida', 'rec-' + n + '.jpg'), type: 'jpeg', quality: 55 });
const tecla = async (k, ms = 120) => { await p.evaluate((x) => __tjoc.J.M.tecla(x, true), k); await p.waitForTimeout(ms); await p.evaluate((x) => __tjoc.J.M.tecla(x, false), k); };
const log = (...a) => console.log(...a);
log('aviso', await esperarNivel('SM_Warning')); await p.waitForTimeout(2500); await foto('1-aviso');
log('menu', await esperarNivel('SMMenu', 90000)); await p.waitForTimeout(3000); await foto('2-menu');
// elegir la primera puerta y jugar
log('errores', errores.slice(0, 5));
log('estado', await p.evaluate(() => { const M = __tjoc.J.M; return [M.nombreNivel, M.porNombre.size, M.actores.length, [...M.porNombre.keys()].filter((k) => /Door/.test(k)).slice(0, 8)]; }));
log('puerta', await p.evaluate(() => { const M = __tjoc.J.M; const a = M.porNombre.get('DoorLivingRoom'); const v = new __tjoc.J.camara.position.constructor(); a.raiz.o3.getWorldPosition(v); v.project(M.camara); return M.clicEnPantalla(v.x, v.y)?.nombre; }));
await p.waitForTimeout(2000); await foto('3-puerta');
await p.evaluate(() => { const el = document.querySelector('[data-w=Play]'); el.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true })); el.dispatchEvent(new PointerEvent('pointerup', { bubbles: true })); });
log('prologo', await esperarNivel('SM_Cutscene01', 60000)); await p.waitForTimeout(6000); await foto('4-prologo');
await tecla('X'); await p.waitForTimeout(1500); await tecla('X');
log('narracion', await esperarNivel('SM_NarrationsBM02', 60000)); await p.waitForTimeout(4000); await foto('5-narracion');
const ok = await esperarNivel('SM_Bedroom_Controls', 240000); log('controles', ok); await p.waitForTimeout(2500); await foto('6-controles');
await tecla('X');
log('dormitorio', await esperarNivel('SM_Bedroom', 60000)); await p.waitForTimeout(8000); await foto('7-dormitorio');
const info = await p.evaluate(() => { const M = __tjoc.J.M; return { faltan: [...M.vm.faltan.keys()].slice(0, 20), botones: [...document.querySelectorAll('.boton')].map((b) => b.dataset.k + ':' + b.textContent) }; });
log(JSON.stringify(info));
log(errores.length ? 'ERRORES:\n' + [...new Set(errores)].slice(0, 8).join('\n') : 'sin errores');
await b.close(); srv.kill();
