// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.U2D
{
    public partial class SpriteShapeRenderer : global::UnityEngine.Renderer
    {
    }
}
