// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.U2D
{
    public partial class SpriteAtlas : global::UnityEngine.Object
    {
        public bool CanBindTo(global::UnityEngine.Sprite sprite) { global::Porteo.Falta.Llamada("UnityEngine.U2D.SpriteAtlas::CanBindTo"); return default; }
    }
}
