// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngineInternal
{
    public partial class ScriptingUtils
    {
        public static global::System.Delegate CreateDelegate(global::System.Type type, global::System.Reflection.MethodInfo methodInfo) { global::Porteo.Falta.Llamada("UnityEngineInternal.ScriptingUtils::CreateDelegate"); return default; }
    }
}
