// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.ParticleSystemModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.ParticleSystem))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.ParticleSystemCurveMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.ParticleSystemGradientMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.ParticleSystemRenderer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.ParticleSystemSimulationSpace))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.ParticleSystemStopBehavior))]
