// Los idiomas: castellano, inglés y portugués. Todo texto que se ve pasa por
// t("clave") o por un atributo data-t en el HTML. Las voces grabadas del Guacho
// quedan en castellano (son 61 frases con acento rioplatense y no hay otras):
// lo que se traduce es el subtítulo, por eso cada lista de frases tiene el
// mismo largo y el mismo orden en los tres idiomas (el índice elige la voz).
//
// Va antes que datos.js, igual que giro.js: así la pantalla de carga ya sale
// en el idioma que se eligió la vez anterior. Por eso no cuelga de E (que
// todavía no existe) sino de window.IDIOMA y window.t.
"use strict";
(() => {
  // Plurales y listas: en inglés y portugués el orden de las palabras cambia,
  // así que algunas entradas son funciones y no texto con {huecos}.
  const pl = (n, uno, varios) => (n === 1 ? uno : varios);

  const es = {
    "titulo": "Estancia: La Ley del Monte",
    "idioma.nombre": "Español",
    "idioma.nota": "Lo podés cambiar después en Opciones.",
    "idioma.opcion": "Idioma",

    // ── carga y escaneo ──
    "carga.cargando": "Cargando…",
    "carga.encendiendo": "Encendiendo…",
    "carga.animales": "Los animales y el Guacho…",
    "carga.tierra": "Tierra colorada…",
    "carga.monte": "El monte: quebrachos y algarrobos…",
    "carga.rancho": "Rancho, corral y manga…",
    "carga.hacienda": "La hacienda…",
    "carga.mapa": "Dibujando el mapa del campo…",
    "carga.luz": "Preparando la luz…",
    "carga.error": "No se pudo arrancar: {e}",
    "escaneo.midiendo": "Midiendo tu compu para elegir los gráficos…",
    "escaneo.probando": "Probando gráficos {nivel}…",
    "escaneo.graficos": "Gráficos: {nivel}",
    "escaneo.graficosSolo": "Gráficos: {nivel} (elegidos por el escaneo)",
    "escaneo.fps": "cuadros por segundo",
    "escaneo.ayuda": "¿Anda trabado? Tocá <b>Ultra baja</b>: sin sombras, plantas quietas y más luz.",
    "escaneo.saltar": "Saltar",
    "escaneo.seguir": "Seguir",
    "calidad.ultrabaja": "Ultra baja",
    "calidad.ultrabajaLarga": "Ultra baja (sin sombras)",
    "calidad.baja": "Baja",
    "calidad.media": "Media",
    "calidad.alta": "Alta",
    "calidad.ultra": "Ultra",

    // ── el menú ──
    "menu.marca": "Chaco · temporada de verano",
    "menu.subtitulo": "La Ley del Monte",
    "menu.jugar": "Jugar",
    "menu.libreta": "Libreta",
    "menu.como": "Cómo se juega",
    "menu.opciones": "Opciones",
    "menu.creditos": "Créditos",
    "menu.calificacion": "<strong>+18.</strong> Sangre y trabajo veterinario sin maquillaje, animales que lastiman y tabaco. No es una caricatura.",
    "menu.intro": "Chaco, verano. Quinientas hectáreas de tierra colorada, quebrachales y algarrobos. Sos El Guacho: sin poderes, sin magia. Rastrear, enlazar, pialar, curar la bichera, arrear al corral y trabajar en la manga. Veinte días. Si se te muere más de un tercio de la hacienda, fundís.",
    "menu.empezar": "Empezar la temporada",
    "menu.hitoDias": "{n} días",
    "menu.hitoDiasSub": "de temporada",
    "menu.hitoVacas": "{n} vacas",
    "menu.hitoVacasSub": "a tu cargo",
    "menu.hitoFundis": "1/3",
    "menu.hitoFundisSub": "muertas y fundís",
    "menu.perfil": (v) => `${v.rango} · ${v.n} ${pl(v.n, "temporada salvada", "temporadas salvadas")} · ${v.d} ${pl(v.d, "día", "días")} de campo`,
    "consejo.titulo": "Consejo del puestero",
    "consejos": [
      "Las agusanadas no se curan solas: a los tres días se mueren.",
      "Con la mira roja del ojo de águila, el tiro va derecho al cogote.",
      "Si la tensión se pone roja, aflojá: el tiento se corta.",
      "El hierro caliente dura una hora y media. Calentalo antes de la manga.",
      "Al zaino hay que bañarlo y darle forraje cada tarde.",
      "Tomá agua seguido: con 40 °C el golpe de calor llega rápido.",
      "Con el mapa (M) marcás un destino y aparece una columna de luz.",
      "Los perros juntan la tropa hacia vos: usalos para llenar el corral.",
    ],
    "libreta.titulo": "Libreta del Guacho",
    "libreta.nombre": "El Guacho",
    "libreta.rangos": ["Peón", "Puestero", "Capataz", "Mayordomo", "Patrón"],
    "libreta.proximo": (v) => `Próximo rango: ${v.rango} · ${pl(v.n, "falta 1 temporada salvada", `faltan ${v.n} temporadas salvadas`)}`,
    "libreta.maximo": "Rango máximo. El campo te conoce.",
    "libreta.jugadas": "Temporadas empezadas",
    "libreta.salvadas": "Salvadas",
    "libreta.fundidas": "Fundidas",
    "libreta.dias": "Días en el campo",
    "libreta.curadas": "Bicheras curadas",
    "libreta.enlazadas": "Vacas enlazadas",
    "libreta.trabajadas": "Trabajadas en la manga",
    "libreta.mejor": "Mejor hacienda salvada",
    "libreta.mejorValor": "{v} de {t}",
    "libreta.plata": "Más plata en la caja",
    "libreta.ultimaSalvada": "Última temporada: salvada, con {v} de {t} vivas.",
    "libreta.ultimaFundida": "Última temporada: fundida en el día {d}.",
    "libreta.ninguna": "Todavía no terminaste ninguna temporada.",
    "libreta.nota": "Se guarda en este navegador.",
    "libreta.borrar": "Borrar la libreta",
    "libreta.seguro": "¿Seguro? Tocá de nuevo",
    "como.rastrear": "Rastrear",
    "como.rastrearT": "Las agusanadas se esconden en el monte. Seguí las huellas frescas y la bosta con moscas.",
    "como.enlazar": "Enlazar",
    "como.enlazarT": "Mantené para revolear y soltá con el aro lleno. Con una vaca adelante se abre el ojo de águila.",
    "como.pialar": "Pialar y cobrar",
    "como.pialarT": "Enlazada, aguantá la tensión sin cortar el tiento. Cansada, pialala en la ventana verde.",
    "como.curar": "Curar la bichera",
    "como.curarT": "Pinza para sacar los gusanos y curabichera hasta tapar la herida. Sin apurar a la vaca: patea.",
    "como.manga": "La manga",
    "como.mangaT": "Aftosa e ivermectina en el cuello, caravana en la oreja, hierro al rojo en el anca.",
    "como.perros": "Los perros",
    "como.perrosT": "Tigre, Negra y Chispa: vengan, quietos, junten la tropa o busquen la vaca que mirás.",
    "como.puesto": "El puesto",
    "como.puestoT": "Mate, agua fría, guiso en el fogón y el catre. La sed y la noche no perdonan.",
    "como.zaino": "El zaino",
    "como.zainoT": "Bañalo, dale forraje y no lo revientes al galope: un caballo rengo es un día perdido.",
    "como.teclasBoton": "Todas las teclas y el celular",
    "cred.lema": "Un simulador crudo de trabajo de campo en el monte chaqueño.",
    "cred.motor": "Motor 3D",
    "cred.modelos": "Modelos 3D y esqueletos",
    "cred.texturas": "Texturas del suelo",
    "cred.voz": "Voz del Guacho",
    "cred.vozValor": "Higgsfield · qwen_audio_tts (voz Julian, acento rioplatense)",
    "cred.sonido": "Sonido",
    "cred.sonidoValor": "Grabaciones CC0 y CC-BY (abajo); mugidos, cascos al paso, teros y chicharras, sintetizados en el juego",
    "cred.grabaciones": "Sonidos grabados con licencia CC-BY",
    "cred.grabacionesNota": "Las demás grabaciones son CC0 (dominio público): viento, pájaros, fogón, agua, ladridos, pasos y tranquera.",
    "snd.cascos_galope": "Galope del caballo",
    "snd.lazo_zumbido": "Zumbido del lazo (una soga de saltar)",
    "cred.letras": "Tipografías",
    "cred.letrasValor": "Anton y Barlow Condensed (SIL OFL)",
    "cred.radio": "Radio",
    "cred.radioValor": "Emisoras FM del Chaco, Formosa y Corrientes · Radio Browser",
    "cred.idiomas": "Idiomas",
    "cred.idiomasValor": "Español, English, Português. Las voces quedan en castellano, con subtítulos.",

    // ── paneles ──
    "pausa.titulo": "Pausa",
    "pausa.texto": "El monte espera. Las moscas no.",
    "pausa.seguir": "Seguir",
    "boton.como": "Cómo se juega",
    "boton.opciones": "Opciones",
    "boton.volver": "Volver",
    "boton.listo": "Listo",
    "parte.sello": "Parte del puestero",
    "parte.seguir": "Salir al campo",
    "fin.otra": "Otra temporada",
    "fogon.titulo": "El fogón",
    "fogon.texto": "La leña de quebracho aguanta toda la noche. El costillar está desde la tarde.",
    "fogon.calentar": "Calentar el hierro",
    "fogon.guiso": "Preparar un guiso",
    "fogon.comer": "Comer asado (de noche)",
    "fogon.nada": "Nada",
    "cura.titulo": "Bichera",
    "cura.pinza": "Pinza",
    "cura.spray": "Curabichera",
    "cura.paciencia": "Paciencia de la vaca",
    "cura.dejar": "Dejar",
    "cura.estado": "Gusanos: {q} · Curabichera: {c} %",
    "manga.aftosa": "1 · Aftosa",
    "manga.ivermectina": "2 · Ivermectina",
    "manga.caravana": "3 · Caravana",
    "manga.hierro": "4 · Hierro",
    "manga.soltar": "Soltar (E)",
    "manga.ayuda": "Elegí la herramienta y tocá la vaca: la vacuna en la tabla del cuello, la caravana en la oreja, la marca en el anca.",
    "manga.hAftosa": "Aftosa",
    "manga.hIvermectina": "Ivermectina",
    "manga.hCaravana": "Caravana",
    "manga.hMarca": "Marca",
    "manga.hierroCaliente": "Hierro (caliente)",
    "manga.hierroFrio": "Hierro (frío)",
    "manga.noHay": "No hay ninguna vaca sin trabajar adentro del corral.",
    "manga.cuello": "La vacuna va en la tabla del cuello.",
    "manga.oreja": "La caravana va en la oreja.",
    "manga.anca": "La marca va en el anca.",
    "manga.hecho": "Eso ya está hecho.",
    "manga.frio": "El hierro está frío. Calentalo en el fogón.",
    "manga.lista": "Lista. Soltala con el botón o con E.",
    "radio.titulo": "Radio",
    "radio.apagada": "Apagada",
    "radio.prender": "Prender",
    "radio.apagar": "Apagar",
    "radio.anterior": "Emisora anterior",
    "radio.siguiente": "Emisora siguiente",
    "radio.volumen": "Volumen",
    "radio.nota": "FM del Chaco, Formosa y Corrientes por internet. Se escucha cerca del rancho y se apaga de a poco a medida que te alejás.",
    "radio.otras": "Otras",
    "radio.sinComprobar": " · sin comprobar",
    "radio.sinSenal": " · sin señal",
    "radio.soloArchivo": " · solo en el archivo descargado",
    "radio.en el aire": "en el aire",
    "radio.sintonizando…": "sintonizando…",
    "radio.sin señal: probá otra": "sin señal: probá otra",
    "radio.solo archivo": "esta emisora solo anda en el archivo descargado",
    "radio.apagada2": "apagada",
    "radio.chip": "La radio (tocá para cambiar la emisora)",
    "mapa.titulo": "El campo",
    "mapa.ayuda": "Tocá un lugar para ir. Aparece una columna de luz y arriba la brújula.",
    "mapa.sacar": "Sacar el destino",
    "mapa.volver": "Volver (M)",
    "mapa.acercar": "Acercar",
    "mapa.alejar": "Alejar",
    "mapa.yo": "Centrar en mí",
    "mapa.destino": "Destino marcado: {nombre}. Seguí la columna de luz.",
    "mapa.llegaste": "Llegaste: {nombre}.",
    "lugar.casco": "Casco de la estancia", "lugar.cascoC": "Casco",
    "lugar.corral": "Corral y manga", "lugar.corralC": "Corral",
    "lugar.comedero": "Comedero (encierre)", "lugar.comederoC": "Comedero",
    "lugar.aguada": "Aguada: tanque y molino", "lugar.aguadaC": "Aguada",
    "lugar.estero": "Estero (aguada natural)", "lugar.esteroC": "Estero",
    "lugar.fogon": "Fogón", "lugar.fogonC": "Fogón",
    "lugar.tranquera": "Tranquera de entrada", "lugar.tranqueraC": "Tranquera",
    "lugar.pueblo": "{nombre} (el pueblo)", "lugar.puebloC": "Pueblo",
    "lugar.caballo": "El zaino", "lugar.caballoC": "Zaino",
    "lugar.vaca": "La {num} (con bichera)", "lugar.vacaC": "La {num}",
    "lugar.punto": "el punto marcado", "lugar.puntoC": "Punto",
    "como.titulo": "Cómo se juega",
    "como.teclas": "Las teclas",
    "como.t1": "<kbd>W A S D</kbd>caminar · <kbd>Shift</kbd>correr / galopar",
    "como.t2": "<kbd>E</kbd>usar, montar, curar",
    "como.t3": "<kbd>1</kbd>el lazo · mantener <kbd>clic</kbd> revolear, soltar tirar",
    "como.t4": "<kbd>clic der.</kbd>cobrar lazo · <kbd>P</kbd>pialar",
    "como.t5": "<kbd>C</kbd>caballo al paso · <kbd>H</kbd>silbar al caballo",
    "como.t6": "<kbd>V</kbd>cámara · <kbd>F</kbd>armar un cigarro",
    "como.t7": "<kbd>G</kbd>perros: vengan · <kbd>X</kbd>quietos",
    "como.t8": "<kbd>J</kbd>perros: junten la tropa · <kbd>B</kbd>busquen la vaca que mirás",
    "como.t9": "<kbd>Enter</kbd> o <kbd>/</kbd> el chat de comandos",
    "como.t10": "<kbd>M</kbd> el mapa: corral, casco, pueblo, comedero, aguada",
    "como.ojo": "Ojo de águila",
    "como.ojoT": "Revoleá con una vaca adelante, entre 4 y 18 metros: el mundo se pone gris, el tiempo se frena y la mira se cierra sobre la cabeza. Cuando se pone roja, soltá: la armada va derecho al cogote y la cámara gira para verla caer.",
    "como.celular": "En el celular",
    "como.celularT": "Acostado o parado: si lo tenés parado, el juego se gira solo. Palanca a la izquierda, mirar deslizando a la derecha, los botones en pantalla.",
    "op.titulo": "Opciones",
    "op.brillo": "Brillo",
    "op.volumen": "Volumen general",
    "op.voz": "Voz del Guacho",
    "op.sensib": "Sensibilidad del ratón",
    "op.calidad": "Calidad gráfica",
    "op.escaneo": "Escaneo de cuadros",
    "op.noMedido": "Todavía no se midió.",
    "op.medido": "Midió {fps} cuadros por segundo y eligió {nivel}.",
    "op.medir": "Medir de nuevo",
    "op.ojo": "Ojo de águila",
    "op.ojoT": "Cámara lenta y mira al revolear. Sin esto, se emboca a pulso.",
    "op.subs": "Subtítulos",
    "op.subsT": "Lo que dice el Guacho, escrito abajo.",

    // ── el HUD ──
    "hud.dia": "Día {d} de {n}",
    "hud.costilla": "Costilla quebrada",
    "hud.lesion": "Caballo lesionado",
    "hud.sed": "Sed",
    "hud.cansancio": "Cansancio",
    "hud.salud": "Salud",
    "hud.caballo": "Caballo",
    "hud.tension": "Tensión",
    "hud.laVaca": "La vaca",
    "hud.minimapa": "Minimapa (tocá para abrir el mapa)",
    "hud.cansada": "Cansada: pialala (P)",
    "hud.aguanta": "Aguantá y cobrá (botón derecho)",
    "ojo.soltar": "Soltá para tirar",
    "ojo.fijando": "Fijando…",
    "tarea.bichera": (v) => `La ${v.num} con bichera · ${v.dias ? v.dias + pl(v.dias, " día", " días") : "de hoy"}`,
    "tarea.sinLazo": "Sin lazo: hay en la galería o en el almacén",
    "tarea.zaino": "El zaino: {cosas}",
    "tarea.banar": "bañar al zaino",
    "tarea.forraje": "darle forraje",
    "tarea.comedero": "Comedero del encierre vacío",
    "tarea.hierro": "Hierro caliente: {min} min",
    "tarea.manga": "Manga: {t} de {v} trabajadas",
    "tactil.controles": "Controles",
    "tactil.lazo": "Lazo", "tactil.cobrar": "Cobrar", "tactil.accion": "Acción", "tactil.pialar": "Pialar",
    "tactil.camara": "Cámara", "tactil.silbar": "Silbar", "tactil.perros": "Perros", "tactil.mapa": "Mapa",

    // ── lo que se puede hacer (el cartel de E) ──
    "accion.soltarVaca": "Soltar la vaca",
    "accion.soltarSinTerminar": "Soltarla sin terminar",
    "accion.bajate": "Bajate para trabajarla",
    "accion.curar": "Curar la bichera de la {num}",
    "accion.soltar": "Soltar la {num}",
    "accion.montar": "Montar el zaino",
    "accion.bajarse": "Bajate del caballo",
    "accion.comprarLazo": "Comprar un lazo en el almacén ($ {p})",
    "accion.almacen": "Almacén: una gaseosa fría, yerba y galletas ($ {p})",
    "accion.comederoLleno": "El comedero está lleno",
    "accion.zainoComio": "El zaino ya tiene forraje",
    "accion.banar": "Bañar al zaino con el balde",
    "accion.radio": "Radio FM: elegir la emisora",
    "accion.temprano": "Todavía es temprano para dormir",
    "accion.fogon": "Fogón: calentar el hierro, cocinar o comer",
    "accion.lazoGaleria": "Agarrar el lazo nuevo de la galería ($ {p})",
    "accion.desmontar": "Desmontar",
    "punto.mate": "Tomar mate cocido con galleta",
    "punto.mateCebar": "Cebar unos mates",
    "punto.catre": "Dormir en el catre",
    "punto.radio": "Prender la radio",
    "punto.fogon": "Fogón",
    "punto.manga": "Trabajar en la manga",
    "punto.corralCerrar": "Cerrar la tranquera del corral",
    "punto.corralAbrir": "Abrir la tranquera del corral",
    "punto.tanque": "Tomar agua en el bebedero",
    "punto.entradaAbrir": "Abrir la tranquera de entrada (camino al pueblo)",
    "punto.entradaCerrar": "Cerrar la tranquera de entrada",
    "punto.almacen": "Almacén",
    "punto.encierreAbrir": "Abrir la tranquera del encierre",
    "punto.encierreCerrar": "Cerrar la tranquera del encierre",
    "punto.comederoHacienda": "Cargar el comedero con silo",
    "punto.heladera": "Tomar agua fría de la heladera",
    "punto.forraje": "Darle forraje al zaino",

    // ── lo que pasa (los carteles de arriba) ──
    "msj.costilla": "Costilla quebrada: dos días sin correr y con menos fuerza en el lazo.",
    "msj.lazoComprado": "Don Benito te vendió un lazo de ocho tientos. Bien trenzado.",
    "msj.almacen": "Una gaseosa fría en la galería del almacén, y Don Benito con las noticias del pueblo.",
    "msj.aguaAmbos": "Tomaste agua, y el zaino también.",
    "msj.agua": "Agua del bebedero, tibia pero agua.",
    "msj.hierro": "El hierro está al rojo. Tenés una hora y media.",
    "msj.asado": "Asado al costillar, con cuero. Grasa y humo.",
    "msj.golpeCalor": "Te agarró un golpe de calor. Te encontró el puestero tirado y te trajo al rancho.",
    "msj.deCama": "Te dejó de cama. Te trajeron al rancho entre dos.",
    "msj.noche": "Te agarró la noche. Te dormiste donde estabas.",
    "msj.mate": "Unos mates amargos con galleta, mirando el monte. Uno vuelve a ser persona.",
    "msj.heladera": "Agua fría de la heladera: la gloria.",
    "msj.guiso": "Guiso de arroz con carne y zapallo. Panza llena, corazón contento.",
    "msj.banar": "Le echaste unos baldes y lo cepillaste. El zaino brilla.",
    "msj.forraje": "Un fardo de alfalfa en el comedero. El zaino ya viene.",
    "msj.puesto": "En el puesto: cebá unos mates en la mesa, prepará la comida en el fogón, y al zaino bañalo en el tanque y dale forraje en el comedero.",
    "msj.comederoLleno": "El comedero ya está lleno.",
    "msj.comederoCargado": "Cargaste el comedero con silo de maíz ($ {p}). La hacienda ya levanta la cabeza.",
    "perro.seguir": "¡Vengan!", "perro.seguirT": "los perros te siguen",
    "perro.quieto": "¡Quietos!", "perro.quietoT": "se echan donde están",
    "perro.juntar": "¡Junten!", "perro.juntarT": "arrean la tropa hacia vos",
    "perro.traer": "¡Busque!", "perro.traerT": "Tigre te trae la vaca que mirás",
    "perro.sinVaca": "No hay ninguna vaca adelante para ir a buscar. Mirá hacia una.",
    "perro.orden": "{texto} — {ayuda}.",
    "perro.vaABuscar": "Tigre va a buscar la {num}",
    "perro.trajo": "Tigre te trajo la {num}.",
    "perro.junta": "La hacienda está junta.",

    // ── el parte de cada mañana y el final ──
    "vaca.la": "la {num}",
    "y": " y ",
    "dias": (v) => `${v.n} ${pl(v.n, "día", "días")}`,
    "rumbo": (v) => `${v.lejos === 2 ? "lejos, " : v.lejos === 0 ? "cerquita, " : ""}para ${["el norte", "el noreste", "el este", "el sureste", "el sur", "el suroeste", "el oeste", "el noroeste"][v.i]}`,
    "parte.dia1Titulo": "Día 1 de {n}. Amanece en la estancia, 23 °C y se viene pesado.",
    "parte.dia1Texto": "El puestero vio la {num} con la bichera, rengueando {rumbo}, metida en el monte. Buscá las huellas frescas y la bosta con moscas. El zaino está ensillado al lado del rancho.",
    "parte.diaTitulo": "Día {d} de {n}.",
    "parte.muertas": "Amaneció muerta {lista}: la bichera la comió. Los chimangos ya están arriba. ",
    "parte.nueva": "El puestero vio la {num} agusanada, {rumbo}.",
    "parte.siguen": "Siguen con bichera: {lista}. A los tres días se mueren. ",
    "parte.sigueItem": "la {num} ({dias})",
    "parte.nadie": "Nadie agusanado hoy. Día para la manga: vacunar, caravanear y marcar. ",
    "parte.hacienda": "Hacienda: {vivas} de {total}, {trab} trabajadas.",
    "parte.zainoFlaco": "El zaino amaneció flaco: anoche no le diste forraje, y hoy se va a cansar enseguida. ",
    "parte.mataduras": "Lo dejaste con el sudor y el barro encima: amaneció con mataduras en el lomo y rengo. ",
    "parte.sucio": "El zaino sigue sucio desde ayer; si no lo bañás le van a salir mataduras. ",
    "parte.zainoBien": "El zaino amaneció limpio y comido, con ganas de trabajar. ",
    "parte.novillosBien": "Los novillos del encierre comieron bien: promedian {kg} kg. ",
    "parte.novillosAlgunos": "Solo {c} de {n} novillos alcanzaron el comedero; promedian {kg} kg. ",
    "parte.novillosNada": "Los novillos del encierre pasaron el día sin comer: bajaron a {kg} kg. Hay que cargarles el comedero. ",
    "fin.fundiste": "Fundiste la estancia.",
    "fin.salvaste": "Salvaste la temporada.",
    "fin.p1": "Hacienda viva: <b>{vivas} de {total}</b>. Vacunadas contra aftosa: <b>{vac}</b>. Trabajadas completas: <b>{trab}</b>.",
    "fin.p2": "Plata en la caja: <b>$ {plata}</b>. La hacienda vale <b>$ {hac}</b>.",
    "fin.malo": "Con lo que se murió y lo que no se vacunó, no alcanza para seguir. El banco se queda con el campo.",
    "fin.bueno": "La estancia sigue viva un año más. Nadie te va a dar las gracias, pero el campo sigue.",

    // ── el chat ──
    "chat.boton": "Chat de comandos",
    "chat.botonTitulo": "Chat (Enter o /)",
    "chat.placeholder": "Escribí / para ver los comandos",
    "chat.enviar": "Enviar",
    "chat.usar": "Usar comando",
    "chat.sistema": "[Sistema]:",
    "chat.vos": "Vos",
    "chat.bienvenida": "Escribí /{ayuda} para ver los comandos. Enter o / abren el chat.",
    "chat.noConozco": "No conozco \"/{cmd}\". Probá /{ayuda}.",
    "cmd.ayuda": "ayuda", "cmd.ayudaD": "La lista de comandos", "cmd.ayudaR": "Comandos: ",
    "cmd.saludar": "saludar", "cmd.saludarD": "El Guacho saluda", "cmd.saludarR": "¡Hola, {nombre}! Este comando funciona en celular.",
    "cmd.perros": "perros", "cmd.perrosA": "vengan | quietos | junten | busquen", "cmd.perrosD": "Órdenes a los perros",
    "cmd.perrosNo": "No hay perros en esta estancia.",
    "cmd.perrosQue": "¿Qué les decís? /{cmd} vengan, quietos, junten o busquen.",
    "cmd.perrosR": "{texto} Los perros: {ayuda}.",
    "cmd.perrosPalabras": { vengan: "seguir", quietos: "quieto", junten: "juntar", busquen: "traer" },
    "cmd.silbar": "silbar", "cmd.silbarD": "Silbarle al zaino para que venga",
    "cmd.mate": "mate", "cmd.mateD": "Cebar unos mates (en la galería)", "cmd.mateLejos": "La yerba y la pava están en la mesa de la galería, {rumbo}.",
    "cmd.comer": "comer", "cmd.comerD": "Preparar un guiso en el fogón", "cmd.comerLejos": "El fogón está {rumbo}.",
    "cmd.comerYa": "Ya comiste hoy.", "cmd.comerTemprano": "Es muy temprano para el guiso. Tomate unos mates.",
    "cmd.caballo": "caballo", "cmd.caballoD": "Cómo está el zaino",
    "cmd.caballoAliento": "aliento {n}%", "cmd.rengo": "rengo", "cmd.sano": "sano", "cmd.muySucio": "muy sucio", "cmd.algoSucio": "algo sucio",
    "cmd.limpio": "limpio", "cmd.comido": "comido", "cmd.sinForraje": "sin forraje hoy",
    "cmd.caballoR": "El zaino: {estado}.", "cmd.caballoDonde": " Está {rumbo}.",
    "cmd.hacienda": "hacienda", "cmd.haciendaD": "Cuántas quedan y dónde están las agusanadas",
    "cmd.haciendaR": "Rodeo del campo: {v} vacas, {t} toros y {te} terneros. De trabajo: {vivas} de {total} vacas, {trab} trabajadas.",
    "cmd.conBichera": " Con bichera: {lista}.", "cmd.ninguna": " Ninguna agusanada.", "cmd.vacaDonde": "la {num} ({rumbo})",
    "cmd.razas": "razas", "cmd.razasD": "Qué razas hay en la tropa", "cmd.razasR": "{lista}, y {n} terneros.", "cmd.toro": " (toro)",
    "raza.colorada": "Angus colorada", "raza.criolla": "Criolla overa",
    "cmd.comedero": "comedero", "cmd.comederoD": "Cómo está el comedero y los novillos",
    "cmd.comederoR": "Comedero al {n} %, {c} comiendo ahora. Novillos del encierre: {nov}, promedian {kg} kg. La tranquera del encierre está {estado}.",
    "cmd.abierta": "abierta", "cmd.cerrada": "cerrada",
    "cmd.mapa": "mapa", "cmd.mapaD": "Abrir el mapa del campo",
    "cmd.ir": "ir", "cmd.irA": "casco | corral | comedero | aguada | pueblo | estero | zaino", "cmd.irD": "Marcar a dónde ir",
    "cmd.irZaino": "zaino",
    "cmd.irAdonde": "¿Adónde? /{cmd} casco, corral, comedero, aguada, pueblo, estero o zaino.",
    "cmd.irNoSe": "No sé dónde queda \"{arg}\". Probá /{mapa}.",
    "cmd.irR": "{nombre}: {rumbo}, a {m} m. Seguí la columna de luz.",
    "cmd.hora": "hora", "cmd.horaD": "La hora y el día", "cmd.horaR": "Son las {hh}:{mm} del día {d} de {n}.",
    "cmd.puesto": "puesto", "cmd.puestoD": "Para qué lado queda el rancho", "cmd.puestoR": "El rancho queda {rumbo}, a {m} m.",
    "cmd.fumar": "fumar", "cmd.fumarD": "Armarse un cigarro",
    "cmd.camara": "camara", "cmd.camaraD": "Primera o tercera persona",
    "cmd.camaraPrimera": "Cámara en primera persona.", "cmd.camaraTercera": "Cámara en tercera persona.",
    "cmd.radio": "radio", "cmd.radioA": "apagar | siguiente | nombre", "cmd.radioD": "La radio FM (Chaco, Formosa, Corrientes)",
    "cmd.radioApagar": "apagar", "cmd.radioSiguiente": "siguiente",
    "cmd.radioApagada": "Radio apagada.", "cmd.sintonizando": "Sintonizando {nombre}.",
    "cmd.radioNo": "No encuentro \"{arg}\". Probá /{cmd} para ver el dial.", "cmd.sintonizandoLugar": "Sintonizando {nombre} ({lugar}).",
    "cmd.limpiar": "limpiar", "cmd.limpiarD": "Borrar el chat",

    // ── lo que dice el Guacho (el subtítulo de cada voz grabada) ──
    "frase.errar": ["¡Uh, la pucha!", "¡Pucha, digo!", "Se me fue por un pelo.", "¡Ay, mamita, qué tiro!"],
    "frase.enlazada": ["¡Ahí está, ya te tengo!", "¡Tomá, mañera!", "¡Quieta, quieta!", "Tranquila, negra."],
    "frase.cortado": ["¡Se cortó el lazo, pucha digo!", "Este tiento estaba podrido."],
    "frase.seFue": ["¡Se me fue con lazo y todo!", "¡Ahí va mi lazo, qué macana!"],
    "frase.pialada": ["¡Abajo!", "¡Echate, vamos!", "Ahí está. Quieta."],
    "frase.errarPial": ["¡Pará, pará…!", "Casi, casi. Otra vez."],
    "frase.todaviaNo": ["Está entera todavía. Hay que cansarla.", "Que se canse primero."],
    "frase.patada": ["¡Ay! ¡La costilla…!", "¡Uh, qué patada me pegó!"],
    "frase.cornada": ["¡Me ensartó, la mañera!", "¡Ay, ay, ay!"],
    "frase.embiste": ["¡Uy, viene!", "¡Cuidado que carga!"],
    "frase.sed": ["Me muero de sed.", "Tengo la garganta hecha polvo."],
    "frase.calor": ["Qué calor bárbaro.", "Cuarenta a la sombra, y sin sombra."],
    "frase.curada": ["Listo, negra. Ya está.", "Así, curadita."],
    "frase.lesion": ["Se me mancó el zaino. Lo reventé.", "Uh, el caballo viene rengo."],
    "frase.sinLazo": ["No tengo lazo. Hay uno colgado en la galería."],
    "frase.fumar": ["Un armado y seguimos."],
    "frase.manga": ["Vamos, adentro.", "A la manga, vamos."],
    "frase.silbar": ["¡Vení, zaino!"],
    "frase.apuntar": ["Ahí la tengo…", "Quieta… quieta…", "Ya sos mía."],
    "frase.perros": ["¡Vengan, perros!", "¡Vamos, Tigre! ¡Negra, vení!"],
    "frase.quietos": ["¡Quietos ahí!", "¡Echate, Chispa!"],
    "frase.junten": ["¡Junten, junten la hacienda!", "¡Vaya, vaya! ¡Juntela!"],
    "frase.busquen": ["¡Busque, busque!", "¡Traela, Tigre!"],
    "frase.mate": ["Un matecito y seguimos.", "Qué rico este mate amargo."],
    "frase.comida": ["A ver qué hay pa' comer.", "Un guiso de arroz, como Dios manda."],
    "frase.heladera": ["Agüita fresca, qué lindo."],
    "frase.banar": ["Vení, zaino, que te baño.", "Ahí está, limpito."],
    "frase.forraje": ["Tomá, comé tranquilo."],
    "frase.saludar": ["¡Buenas! ¿Cómo andan?", "¡Buen día, paisano!"],
    "frase.puesto": ["Por fin en el puesto."],
    "frase.caballoSucio": ["Este zaino está hecho un barro."],
  };

  const en = {
    "titulo": "Estancia: The Law of the Bush",
    "idioma.nombre": "English",
    "idioma.nota": "You can change it later in Options.",
    "idioma.opcion": "Language",

    "carga.cargando": "Loading…",
    "carga.encendiendo": "Starting up…",
    "carga.animales": "The animals and the Guacho…",
    "carga.tierra": "Red earth…",
    "carga.monte": "The bush: quebrachos and carob trees…",
    "carga.rancho": "Shack, corral and chute…",
    "carga.hacienda": "The cattle…",
    "carga.mapa": "Drawing the ranch map…",
    "carga.luz": "Setting up the light…",
    "carga.error": "Couldn't start: {e}",
    "escaneo.midiendo": "Measuring your device to pick the graphics…",
    "escaneo.probando": "Testing {nivel} graphics…",
    "escaneo.graficos": "Graphics: {nivel}",
    "escaneo.graficosSolo": "Graphics: {nivel} (picked by the scan)",
    "escaneo.fps": "frames per second",
    "escaneo.ayuda": "Stuttering? Tap <b>Ultra low</b>: no shadows, still plants and more light.",
    "escaneo.saltar": "Skip",
    "escaneo.seguir": "Continue",
    "calidad.ultrabaja": "Ultra low",
    "calidad.ultrabajaLarga": "Ultra low (no shadows)",
    "calidad.baja": "Low",
    "calidad.media": "Medium",
    "calidad.alta": "High",
    "calidad.ultra": "Ultra",

    "menu.marca": "Chaco · summer season",
    "menu.subtitulo": "The Law of the Bush",
    "menu.jugar": "Play",
    "menu.libreta": "Logbook",
    "menu.como": "How to play",
    "menu.opciones": "Options",
    "menu.creditos": "Credits",
    "menu.calificacion": "<strong>18+.</strong> Blood and unvarnished veterinary work, animals that hurt you, and tobacco. It's not a cartoon.",
    "menu.intro": "Chaco, summer. Five hundred hectares of red earth, quebracho forests and carob trees. You are El Guacho: no powers, no magic. Track, lasso, leg-rope, treat screwworm, drive cattle to the corral and work the chute. Twenty days. Lose more than a third of the herd and you go bust.",
    "menu.empezar": "Start the season",
    "menu.hitoDias": "{n} days",
    "menu.hitoDiasSub": "of season",
    "menu.hitoVacas": "{n} cows",
    "menu.hitoVacasSub": "in your care",
    "menu.hitoFundis": "1/3",
    "menu.hitoFundisSub": "dead and you're bust",
    "menu.perfil": (v) => `${v.rango} · ${v.n} ${pl(v.n, "season saved", "seasons saved")} · ${v.d} ${pl(v.d, "day", "days")} on the land`,
    "consejo.titulo": "Ranch hand's tip",
    "consejos": [
      "Wormy cows don't heal on their own: after three days they die.",
      "With the eagle eye's red sight, the throw goes straight to the neck.",
      "If the tension turns red, ease off: the rope snaps.",
      "The hot iron lasts an hour and a half. Heat it before the chute.",
      "The bay needs a wash and fodder every evening.",
      "Drink often: at 40 °C heatstroke comes fast.",
      "With the map (M) you set a destination and a pillar of light appears.",
      "The dogs drive the herd toward you: use them to fill the corral.",
    ],
    "libreta.titulo": "The Guacho's logbook",
    "libreta.nombre": "El Guacho",
    "libreta.rangos": ["Ranch hand", "Outrider", "Foreman", "Manager", "Boss"],
    "libreta.proximo": (v) => `Next rank: ${v.rango} · ${v.n} more ${pl(v.n, "season", "seasons")} to save`,
    "libreta.maximo": "Top rank. The land knows you.",
    "libreta.jugadas": "Seasons started",
    "libreta.salvadas": "Saved",
    "libreta.fundidas": "Gone bust",
    "libreta.dias": "Days on the land",
    "libreta.curadas": "Screwworms treated",
    "libreta.enlazadas": "Cows lassoed",
    "libreta.trabajadas": "Worked in the chute",
    "libreta.mejor": "Best herd saved",
    "libreta.mejorValor": "{v} of {t}",
    "libreta.plata": "Most cash in the box",
    "libreta.ultimaSalvada": "Last season: saved, with {v} of {t} alive.",
    "libreta.ultimaFundida": "Last season: went bust on day {d}.",
    "libreta.ninguna": "You haven't finished a season yet.",
    "libreta.nota": "Saved in this browser.",
    "libreta.borrar": "Erase the logbook",
    "libreta.seguro": "Sure? Tap again",
    "como.rastrear": "Track",
    "como.rastrearT": "Wormy cows hide in the bush. Follow fresh tracks and dung with flies.",
    "como.enlazar": "Lasso",
    "como.enlazarT": "Hold to swing and release with the ring full. With a cow ahead, eagle eye kicks in.",
    "como.pialar": "Leg-rope and reel in",
    "como.pialarT": "Once she's caught, hold the tension without snapping the rope. When she tires, rope her legs in the green window.",
    "como.curar": "Treat screwworm",
    "como.curarT": "Tweezers to pull the worms, spray until the wound is covered. Don't rush the cow: she kicks.",
    "como.manga": "The chute",
    "como.mangaT": "Foot-and-mouth vaccine and ivermectin in the neck, tag in the ear, red-hot brand on the rump.",
    "como.perros": "The dogs",
    "como.perrosT": "Tigre, Negra and Chispa: come, stay, gather the herd or fetch the cow you're looking at.",
    "como.puesto": "The shack",
    "como.puestoT": "Mate, cold water, stew at the campfire and the cot. Thirst and nightfall don't forgive.",
    "como.zaino": "The bay",
    "como.zainoT": "Wash him, feed him and don't run him into the ground: a lame horse is a lost day.",
    "como.teclasBoton": "All keys and mobile controls",
    "cred.lema": "A raw ranch-work simulator in the Chaco bush.",
    "cred.motor": "3D engine",
    "cred.modelos": "3D models and rigs",
    "cred.texturas": "Ground textures",
    "cred.voz": "Guacho's voice",
    "cred.vozValor": "Higgsfield · qwen_audio_tts (Julian voice, River Plate accent)",
    "cred.sonido": "Sound",
    "cred.sonidoValor": "CC0 and CC-BY recordings (below); moos, walking hooves, lapwings and cicadas synthesized in-game",
    "cred.grabaciones": "Recorded sounds under CC-BY",
    "cred.grabacionesNota": "The other recordings are CC0 (public domain): wind, birds, campfire, water, barks, footsteps and gate.",
    "snd.cascos_galope": "Horse gallop",
    "snd.lazo_zumbido": "Lasso whoosh (a jump rope)",
    "cred.letras": "Typefaces",
    "cred.letrasValor": "Anton and Barlow Condensed (SIL OFL)",
    "cred.radio": "Radio",
    "cred.radioValor": "FM stations from Chaco, Formosa and Corrientes · Radio Browser",
    "cred.idiomas": "Languages",
    "cred.idiomasValor": "Español, English, Português. Voices stay in Spanish, with subtitles.",

    "pausa.titulo": "Paused",
    "pausa.texto": "The bush waits. The flies don't.",
    "pausa.seguir": "Resume",
    "boton.como": "How to play",
    "boton.opciones": "Options",
    "boton.volver": "Back",
    "boton.listo": "Done",
    "parte.sello": "Ranch hand's report",
    "parte.seguir": "Head out",
    "fin.otra": "Another season",
    "fogon.titulo": "The campfire",
    "fogon.texto": "Quebracho firewood lasts all night. The ribs have been on since the afternoon.",
    "fogon.calentar": "Heat the branding iron",
    "fogon.guiso": "Cook a stew",
    "fogon.comer": "Eat asado (at night)",
    "fogon.nada": "Nothing",
    "cura.titulo": "Screwworm",
    "cura.pinza": "Tweezers",
    "cura.spray": "Wound spray",
    "cura.paciencia": "Cow's patience",
    "cura.dejar": "Leave it",
    "cura.estado": "Worms: {q} · Spray: {c} %",
    "manga.aftosa": "1 · Foot-and-mouth",
    "manga.ivermectina": "2 · Ivermectin",
    "manga.caravana": "3 · Ear tag",
    "manga.hierro": "4 · Brand",
    "manga.soltar": "Release (E)",
    "manga.ayuda": "Pick the tool and touch the cow: the vaccine in the side of the neck, the tag in the ear, the brand on the rump.",
    "manga.hAftosa": "Foot-and-mouth",
    "manga.hIvermectina": "Ivermectin",
    "manga.hCaravana": "Ear tag",
    "manga.hMarca": "Brand",
    "manga.hierroCaliente": "Brand (hot)",
    "manga.hierroFrio": "Brand (cold)",
    "manga.noHay": "There's no unworked cow inside the corral.",
    "manga.cuello": "The vaccine goes in the side of the neck.",
    "manga.oreja": "The tag goes in the ear.",
    "manga.anca": "The brand goes on the rump.",
    "manga.hecho": "That's already done.",
    "manga.frio": "The iron is cold. Heat it at the campfire.",
    "manga.lista": "Done. Release her with the button or E.",
    "radio.titulo": "Radio",
    "radio.apagada": "Off",
    "radio.prender": "Turn on",
    "radio.apagar": "Turn off",
    "radio.anterior": "Previous station",
    "radio.siguiente": "Next station",
    "radio.volumen": "Volume",
    "radio.nota": "FM stations from Chaco, Formosa and Corrientes over the internet. You hear it near the shack and it fades as you walk away.",
    "radio.otras": "Others",
    "radio.sinComprobar": " · untested",
    "radio.sinSenal": " · no signal",
    "radio.soloArchivo": " · only in the downloaded file",
    "radio.en el aire": "on air",
    "radio.sintonizando…": "tuning…",
    "radio.sin señal: probá otra": "no signal: try another",
    "radio.solo archivo": "this station only works in the downloaded file",
    "radio.apagada2": "off",
    "radio.chip": "The radio (tap to change station)",
    "mapa.titulo": "The ranch",
    "mapa.ayuda": "Tap a place to go. A pillar of light appears, and the compass up top.",
    "mapa.sacar": "Clear destination",
    "mapa.volver": "Back (M)",
    "mapa.acercar": "Zoom in",
    "mapa.alejar": "Zoom out",
    "mapa.yo": "Center on me",
    "mapa.destino": "Destination set: {nombre}. Follow the pillar of light.",
    "mapa.llegaste": "You made it: {nombre}.",
    "lugar.casco": "Ranch main house", "lugar.cascoC": "House",
    "lugar.corral": "Corral and chute", "lugar.corralC": "Corral",
    "lugar.comedero": "Feed trough (feedlot)", "lugar.comederoC": "Trough",
    "lugar.aguada": "Water hole: tank and windmill", "lugar.aguadaC": "Water",
    "lugar.estero": "Marsh (natural water)", "lugar.esteroC": "Marsh",
    "lugar.fogon": "Campfire", "lugar.fogonC": "Campfire",
    "lugar.tranquera": "Entrance gate", "lugar.tranqueraC": "Gate",
    "lugar.pueblo": "{nombre} (the town)", "lugar.puebloC": "Town",
    "lugar.caballo": "The bay", "lugar.caballoC": "Bay",
    "lugar.vaca": "Cow {num} (screwworm)", "lugar.vacaC": "Cow {num}",
    "lugar.punto": "the marked spot", "lugar.puntoC": "Spot",
    "como.titulo": "How to play",
    "como.teclas": "The keys",
    "como.t1": "<kbd>W A S D</kbd>walk · <kbd>Shift</kbd>run / gallop",
    "como.t2": "<kbd>E</kbd>use, mount, treat",
    "como.t3": "<kbd>1</kbd>the lasso · hold <kbd>click</kbd> to swing, release to throw",
    "como.t4": "<kbd>right click</kbd>reel in · <kbd>P</kbd>leg rope",
    "como.t5": "<kbd>C</kbd>horse at a walk · <kbd>H</kbd>whistle for the horse",
    "como.t6": "<kbd>V</kbd>camera · <kbd>F</kbd>roll a cigarette",
    "como.t7": "<kbd>G</kbd>dogs: come · <kbd>X</kbd>stay",
    "como.t8": "<kbd>J</kbd>dogs: gather the herd · <kbd>B</kbd>fetch the cow you're looking at",
    "como.t9": "<kbd>Enter</kbd> or <kbd>/</kbd> the command chat",
    "como.t10": "<kbd>M</kbd> the map: corral, house, town, trough, water",
    "como.ojo": "Eagle eye",
    "como.ojoT": "Swing with a cow ahead, between 4 and 18 meters: the world turns gray, time slows down and the sight closes on her head. When it turns red, let go: the loop flies straight to the neck and the camera turns to watch it land.",
    "como.celular": "On mobile",
    "como.celularT": "Landscape or portrait: if you hold it upright, the game rotates itself. Stick on the left, swipe on the right to look, on-screen buttons.",
    "op.titulo": "Options",
    "op.brillo": "Brightness",
    "op.volumen": "Master volume",
    "op.voz": "Guacho's voice",
    "op.sensib": "Mouse sensitivity",
    "op.calidad": "Graphics quality",
    "op.escaneo": "Frame-rate scan",
    "op.noMedido": "Not measured yet.",
    "op.medido": "Measured {fps} frames per second and picked {nivel}.",
    "op.medir": "Measure again",
    "op.ojo": "Eagle eye",
    "op.ojoT": "Slow motion and a sight while swinging. Without it, you aim by hand.",
    "op.subs": "Subtitles",
    "op.subsT": "What the Guacho says, written at the bottom.",

    "hud.dia": "Day {d} of {n}",
    "hud.costilla": "Broken rib",
    "hud.lesion": "Horse injured",
    "hud.sed": "Thirst",
    "hud.cansancio": "Fatigue",
    "hud.salud": "Health",
    "hud.caballo": "Horse",
    "hud.tension": "Tension",
    "hud.laVaca": "The cow",
    "hud.minimapa": "Minimap (tap to open the map)",
    "hud.cansada": "Tired: rope her legs (P)",
    "hud.aguanta": "Hold on and reel in (right button)",
    "ojo.soltar": "Release to throw",
    "ojo.fijando": "Locking on…",
    "tarea.bichera": (v) => `Cow ${v.num} with screwworm · ${v.dias ? v.dias + pl(v.dias, " day", " days") : "today"}`,
    "tarea.sinLazo": "No lasso: there's one on the porch or at the store",
    "tarea.zaino": "The bay: {cosas}",
    "tarea.banar": "wash him",
    "tarea.forraje": "give him fodder",
    "tarea.comedero": "Feedlot trough empty",
    "tarea.hierro": "Branding iron hot: {min} min",
    "tarea.manga": "Chute: {t} of {v} worked",
    "tactil.controles": "Controls",
    "tactil.lazo": "Lasso", "tactil.cobrar": "Reel in", "tactil.accion": "Action", "tactil.pialar": "Leg rope",
    "tactil.camara": "Camera", "tactil.silbar": "Whistle", "tactil.perros": "Dogs", "tactil.mapa": "Map",

    "accion.soltarVaca": "Release the cow",
    "accion.soltarSinTerminar": "Release her unfinished",
    "accion.bajate": "Get down to work her",
    "accion.curar": "Treat cow {num}'s screwworm",
    "accion.soltar": "Release cow {num}",
    "accion.montar": "Mount the bay",
    "accion.bajarse": "Get off the horse",
    "accion.comprarLazo": "Buy a lasso at the store ($ {p})",
    "accion.almacen": "Store: a cold soda, yerba and crackers ($ {p})",
    "accion.comederoLleno": "The trough is full",
    "accion.zainoComio": "The bay already has fodder",
    "accion.banar": "Wash the bay with the bucket",
    "accion.radio": "FM radio: pick a station",
    "accion.temprano": "Still too early to sleep",
    "accion.fogon": "Campfire: heat the iron, cook or eat",
    "accion.lazoGaleria": "Take the new lasso from the porch ($ {p})",
    "accion.desmontar": "Dismount",
    "punto.mate": "Have mate cocido with a cracker",
    "punto.mateCebar": "Brew some mate",
    "punto.catre": "Sleep on the cot",
    "punto.radio": "Turn on the radio",
    "punto.fogon": "Campfire",
    "punto.manga": "Work the chute",
    "punto.corralCerrar": "Close the corral gate",
    "punto.corralAbrir": "Open the corral gate",
    "punto.tanque": "Drink at the water trough",
    "punto.entradaAbrir": "Open the entrance gate (road to town)",
    "punto.entradaCerrar": "Close the entrance gate",
    "punto.almacen": "Store",
    "punto.encierreAbrir": "Open the feedlot gate",
    "punto.encierreCerrar": "Close the feedlot gate",
    "punto.comederoHacienda": "Fill the trough with silage",
    "punto.heladera": "Drink cold water from the fridge",
    "punto.forraje": "Give the bay some fodder",

    "msj.costilla": "Broken rib: two days without running and less strength on the lasso.",
    "msj.lazoComprado": "Don Benito sold you an eight-strand lasso. Well braided.",
    "msj.almacen": "A cold soda on the store's porch, and Don Benito with the town news.",
    "msj.aguaAmbos": "You drank water, and so did the bay.",
    "msj.agua": "Trough water, lukewarm but water.",
    "msj.hierro": "The iron is red-hot. You have an hour and a half.",
    "msj.asado": "Rib roast asado, skin on. Fat and smoke.",
    "msj.golpeCalor": "Heatstroke got you. The ranch hand found you lying there and brought you to the shack.",
    "msj.deCama": "You were laid up. Two men carried you to the shack.",
    "msj.noche": "Night caught you. You fell asleep where you were.",
    "msj.mate": "A few bitter mates with a cracker, looking at the bush. You feel human again.",
    "msj.heladera": "Cold water from the fridge: pure glory.",
    "msj.guiso": "Rice stew with beef and squash. Full belly, happy heart.",
    "msj.banar": "You threw a few buckets on him and brushed him down. The bay shines.",
    "msj.forraje": "A bale of alfalfa in the trough. The bay is on his way.",
    "msj.puesto": "At the shack: brew mate at the table, cook at the campfire, wash the bay at the tank and give him fodder at the trough.",
    "msj.comederoLleno": "The trough is already full.",
    "msj.comederoCargado": "You filled the trough with corn silage ($ {p}). The cattle are already raising their heads.",
    "perro.seguir": "Come!", "perro.seguirT": "the dogs follow you",
    "perro.quieto": "Stay!", "perro.quietoT": "they lie down where they are",
    "perro.juntar": "Gather!", "perro.juntarT": "they drive the herd toward you",
    "perro.traer": "Fetch!", "perro.traerT": "Tigre brings you the cow you're looking at",
    "perro.sinVaca": "There's no cow ahead to fetch. Look at one.",
    "perro.orden": "{texto} — {ayuda}.",
    "perro.vaABuscar": "Tigre goes to fetch cow {num}",
    "perro.trajo": "Tigre brought you cow {num}.",
    "perro.junta": "The herd is gathered.",

    "vaca.la": "cow {num}",
    "y": " and ",
    "dias": (v) => `${v.n} ${pl(v.n, "day", "days")}`,
    "rumbo": (v) => `${v.lejos === 2 ? "far off, " : v.lejos === 0 ? "close by, " : ""}to the ${["north", "northeast", "east", "southeast", "south", "southwest", "west", "northwest"][v.i]}`,
    "parte.dia1Titulo": "Day 1 of {n}. Dawn at the ranch, 23 °C and it's getting heavy.",
    "parte.dia1Texto": "The ranch hand saw cow {num} with screwworm, limping {rumbo}, deep in the bush. Look for fresh tracks and dung with flies. The bay is saddled next to the shack.",
    "parte.diaTitulo": "Day {d} of {n}.",
    "parte.muertas": "Found dead at dawn: {lista}. The screwworm ate her. The caracaras are already circling. ",
    "parte.nueva": "The ranch hand saw cow {num} with worms, {rumbo}.",
    "parte.siguen": "Still with screwworm: {lista}. After three days they die. ",
    "parte.sigueItem": "cow {num} ({dias})",
    "parte.nadie": "No wormy cattle today. A day for the chute: vaccinate, ear-tag and brand. ",
    "parte.hacienda": "Cattle: {vivas} of {total}, {trab} worked.",
    "parte.zainoFlaco": "The bay woke up weak: you didn't feed him last night, and today he'll tire quickly. ",
    "parte.mataduras": "You left him with sweat and mud on: he woke up with saddle sores on his back and lame. ",
    "parte.sucio": "The bay is still dirty from yesterday; if you don't wash him he'll get saddle sores. ",
    "parte.zainoBien": "The bay woke up clean and fed, ready to work. ",
    "parte.novillosBien": "The feedlot steers ate well: they average {kg} kg. ",
    "parte.novillosAlgunos": "Only {c} of {n} steers reached the trough; they average {kg} kg. ",
    "parte.novillosNada": "The feedlot steers went all day without food: down to {kg} kg. Fill their trough. ",
    "fin.fundiste": "You bankrupted the ranch.",
    "fin.salvaste": "You saved the season.",
    "fin.p1": "Live cattle: <b>{vivas} of {total}</b>. Vaccinated against foot-and-mouth: <b>{vac}</b>. Fully worked: <b>{trab}</b>.",
    "fin.p2": "Cash in the box: <b>$ {plata}</b>. The cattle are worth <b>$ {hac}</b>.",
    "fin.malo": "With what died and what wasn't vaccinated, there's not enough to go on. The bank takes the land.",
    "fin.bueno": "The ranch lives one more year. Nobody's going to thank you, but the land goes on.",

    "chat.boton": "Command chat",
    "chat.botonTitulo": "Chat (Enter or /)",
    "chat.placeholder": "Type / to see the commands",
    "chat.enviar": "Send",
    "chat.usar": "Use command",
    "chat.sistema": "[System]:",
    "chat.vos": "You",
    "chat.bienvenida": "Type /{ayuda} to see the commands. Enter or / opens the chat.",
    "chat.noConozco": "Unknown command \"/{cmd}\". Try /{ayuda}.",
    "cmd.ayuda": "help", "cmd.ayudaD": "The list of commands", "cmd.ayudaR": "Commands: ",
    "cmd.saludar": "greet", "cmd.saludarD": "The Guacho says hi", "cmd.saludarR": "Hi, {nombre}! This command works on mobile.",
    "cmd.perros": "dogs", "cmd.perrosA": "come | stay | gather | fetch", "cmd.perrosD": "Orders for the dogs",
    "cmd.perrosNo": "There are no dogs on this ranch.",
    "cmd.perrosQue": "What do you tell them? /{cmd} come, stay, gather or fetch.",
    "cmd.perrosR": "{texto} The dogs: {ayuda}.",
    "cmd.perrosPalabras": { come: "seguir", stay: "quieto", gather: "juntar", fetch: "traer" },
    "cmd.silbar": "whistle", "cmd.silbarD": "Whistle for the bay to come",
    "cmd.mate": "mate", "cmd.mateD": "Brew some mate (on the porch)", "cmd.mateLejos": "The yerba and the kettle are on the porch table, {rumbo}.",
    "cmd.comer": "eat", "cmd.comerD": "Cook a stew at the campfire", "cmd.comerLejos": "The campfire is {rumbo}.",
    "cmd.comerYa": "You already ate today.", "cmd.comerTemprano": "Too early for stew. Have some mate.",
    "cmd.caballo": "horse", "cmd.caballoD": "How the bay is doing",
    "cmd.caballoAliento": "breath {n}%", "cmd.rengo": "lame", "cmd.sano": "sound", "cmd.muySucio": "very dirty", "cmd.algoSucio": "a bit dirty",
    "cmd.limpio": "clean", "cmd.comido": "fed", "cmd.sinForraje": "no fodder today",
    "cmd.caballoR": "The bay: {estado}.", "cmd.caballoDonde": " He's {rumbo}.",
    "cmd.hacienda": "cattle", "cmd.haciendaD": "How many are left and where the wormy ones are",
    "cmd.haciendaR": "Ranch herd: {v} cows, {t} bulls and {te} calves. Working herd: {vivas} of {total} cows, {trab} worked.",
    "cmd.conBichera": " With screwworm: {lista}.", "cmd.ninguna": " None with worms.", "cmd.vacaDonde": "cow {num} ({rumbo})",
    "cmd.razas": "breeds", "cmd.razasD": "Which breeds are in the herd", "cmd.razasR": "{lista}, and {n} calves.", "cmd.toro": " (bull)",
    "raza.colorada": "Red Angus", "raza.criolla": "Pinto Criollo",
    "cmd.comedero": "trough", "cmd.comederoD": "How the trough and the steers are doing",
    "cmd.comederoR": "Trough at {n} %, {c} eating now. Feedlot steers: {nov}, averaging {kg} kg. The feedlot gate is {estado}.",
    "cmd.abierta": "open", "cmd.cerrada": "closed",
    "cmd.mapa": "map", "cmd.mapaD": "Open the ranch map",
    "cmd.ir": "go", "cmd.irA": "house | corral | trough | water | town | marsh | bay", "cmd.irD": "Mark where to go",
    "cmd.irZaino": "bay",
    "cmd.irAdonde": "Where to? /{cmd} house, corral, trough, water, town, marsh or bay.",
    "cmd.irNoSe": "I don't know where \"{arg}\" is. Try /{mapa}.",
    "cmd.irR": "{nombre}: {rumbo}, {m} m away. Follow the pillar of light.",
    "cmd.hora": "time", "cmd.horaD": "The time and the day", "cmd.horaR": "It's {hh}:{mm} on day {d} of {n}.",
    "cmd.puesto": "shack", "cmd.puestoD": "Which way the shack is", "cmd.puestoR": "The shack is {rumbo}, {m} m away.",
    "cmd.fumar": "smoke", "cmd.fumarD": "Roll a cigarette",
    "cmd.camara": "camera", "cmd.camaraD": "First or third person",
    "cmd.camaraPrimera": "Camera in first person.", "cmd.camaraTercera": "Camera in third person.",
    "cmd.radio": "radio", "cmd.radioA": "off | next | name", "cmd.radioD": "FM radio (Chaco, Formosa, Corrientes)",
    "cmd.radioApagar": "off", "cmd.radioSiguiente": "next",
    "cmd.radioApagada": "Radio off.", "cmd.sintonizando": "Tuning in {nombre}.",
    "cmd.radioNo": "Can't find \"{arg}\". Try /{cmd} to see the dial.", "cmd.sintonizandoLugar": "Tuning in {nombre} ({lugar}).",
    "cmd.limpiar": "clear", "cmd.limpiarD": "Clear the chat",

    "frase.errar": ["Oh, darn it!", "Shoot, I say!", "Missed by a hair.", "Oh boy, what a throw!"],
    "frase.enlazada": ["There you go, I got you!", "Take that, you stubborn thing!", "Easy, easy!", "Calm down, girl."],
    "frase.cortado": ["The lasso snapped, dang it!", "This rope was rotten."],
    "frase.seFue": ["She ran off, lasso and all!", "There goes my lasso, what a mess!"],
    "frase.pialada": ["Down!", "Lie down, come on!", "There. Stay still."],
    "frase.errarPial": ["Wait, wait…!", "Almost, almost. Again."],
    "frase.todaviaNo": ["She's still fresh. Gotta tire her out.", "Let her get tired first."],
    "frase.patada": ["Ow! My rib…!", "Ugh, what a kick she gave me!"],
    "frase.cornada": ["She gored me, the stubborn thing!", "Ow, ow, ow!"],
    "frase.embiste": ["Whoa, here she comes!", "Look out, she's charging!"],
    "frase.sed": ["I'm dying of thirst.", "My throat is dust."],
    "frase.calor": ["Brutal heat.", "Forty in the shade, and there's no shade."],
    "frase.curada": ["There, girl. All done.", "That's it, all patched up."],
    "frase.lesion": ["The bay went lame. I pushed him too hard.", "Oh no, the horse is limping."],
    "frase.sinLazo": ["I've got no lasso. There's one hanging on the porch."],
    "frase.fumar": ["A quick smoke and we carry on."],
    "frase.manga": ["Come on, inside.", "Into the chute, let's go."],
    "frase.silbar": ["Come here, boy!"],
    "frase.apuntar": ["Got her lined up…", "Easy… easy…", "You're mine now."],
    "frase.perros": ["Come on, dogs!", "Let's go, Tigre! Negra, come!"],
    "frase.quietos": ["Stay there!", "Down, Chispa!"],
    "frase.junten": ["Gather, gather the herd!", "Go on, go on! Round 'em up!"],
    "frase.busquen": ["Fetch, fetch!", "Bring her, Tigre!"],
    "frase.mate": ["A little mate and we carry on.", "This bitter mate is great."],
    "frase.comida": ["Let's see what there is to eat.", "A rice stew, done right."],
    "frase.heladera": ["Cool water, lovely."],
    "frase.banar": ["Come here, boy, bath time.", "There you go, all clean."],
    "frase.forraje": ["Here, eat in peace."],
    "frase.saludar": ["Howdy! How are you all?", "Good morning, friend!"],
    "frase.puesto": ["Finally back at the shack."],
    "frase.caballoSucio": ["This horse is caked in mud."],
  };

  const pt = {
    "titulo": "Estancia: A Lei do Mato",
    "idioma.nombre": "Português",
    "idioma.nota": "Você pode mudar depois em Opções.",
    "idioma.opcion": "Idioma",

    "carga.cargando": "Carregando…",
    "carga.encendiendo": "Ligando…",
    "carga.animales": "Os animais e o Guacho…",
    "carga.tierra": "Terra vermelha…",
    "carga.monte": "O mato: quebrachos e alfarrobeiras…",
    "carga.rancho": "Rancho, curral e brete…",
    "carga.hacienda": "O gado…",
    "carga.mapa": "Desenhando o mapa do campo…",
    "carga.luz": "Preparando a luz…",
    "carga.error": "Não foi possível iniciar: {e}",
    "escaneo.midiendo": "Medindo seu aparelho para escolher os gráficos…",
    "escaneo.probando": "Testando gráficos {nivel}…",
    "escaneo.graficos": "Gráficos: {nivel}",
    "escaneo.graficosSolo": "Gráficos: {nivel} (escolhidos pela varredura)",
    "escaneo.fps": "quadros por segundo",
    "escaneo.ayuda": "Travando? Toque em <b>Ultra baixa</b>: sem sombras, plantas paradas e mais luz.",
    "escaneo.saltar": "Pular",
    "escaneo.seguir": "Continuar",
    "calidad.ultrabaja": "Ultra baixa",
    "calidad.ultrabajaLarga": "Ultra baixa (sem sombras)",
    "calidad.baja": "Baixa",
    "calidad.media": "Média",
    "calidad.alta": "Alta",
    "calidad.ultra": "Ultra",

    "menu.marca": "Chaco · temporada de verão",
    "menu.subtitulo": "A Lei do Mato",
    "menu.jugar": "Jogar",
    "menu.libreta": "Caderneta",
    "menu.como": "Como jogar",
    "menu.opciones": "Opções",
    "menu.creditos": "Créditos",
    "menu.calificacion": "<strong>+18.</strong> Sangue e trabalho veterinário sem maquiagem, animais que machucam e tabaco. Não é um desenho animado.",
    "menu.intro": "Chaco, verão. Quinhentos hectares de terra vermelha, quebrachais e alfarrobeiras. Você é El Guacho: sem poderes, sem mágica. Rastrear, laçar, pealar, curar a bicheira, tocar o gado para o curral e trabalhar no brete. Vinte dias. Se morrer mais de um terço do gado, você quebra.",
    "menu.empezar": "Começar a temporada",
    "menu.hitoDias": "{n} dias",
    "menu.hitoDiasSub": "de temporada",
    "menu.hitoVacas": "{n} vacas",
    "menu.hitoVacasSub": "sob seus cuidados",
    "menu.hitoFundis": "1/3",
    "menu.hitoFundisSub": "mortas e você quebra",
    "menu.perfil": (v) => `${v.rango} · ${v.n} ${pl(v.n, "temporada salva", "temporadas salvas")} · ${v.d} ${pl(v.d, "dia", "dias")} de campo`,
    "consejo.titulo": "Dica do posteiro",
    "consejos": [
      "As bicheiradas não saram sozinhas: em três dias morrem.",
      "Com a mira vermelha do olho de águia, o tiro vai direto ao pescoço.",
      "Se a tensão ficar vermelha, afrouxe: o tento arrebenta.",
      "O ferro quente dura uma hora e meia. Esquente antes do brete.",
      "O zaino precisa de banho e forragem toda tarde.",
      "Beba água seguido: com 40 °C a insolação chega rápido.",
      "Com o mapa (M) você marca um destino e aparece uma coluna de luz.",
      "Os cães juntam a tropa até você: use-os para encher o curral.",
    ],
    "libreta.titulo": "Caderneta do Guacho",
    "libreta.nombre": "El Guacho",
    "libreta.rangos": ["Peão", "Posteiro", "Capataz", "Administrador", "Patrão"],
    "libreta.proximo": (v) => `Próximo posto: ${v.rango} · ${pl(v.n, "falta 1 temporada salva", `faltam ${v.n} temporadas salvas`)}`,
    "libreta.maximo": "Posto máximo. O campo te conhece.",
    "libreta.jugadas": "Temporadas começadas",
    "libreta.salvadas": "Salvas",
    "libreta.fundidas": "Quebradas",
    "libreta.dias": "Dias no campo",
    "libreta.curadas": "Bicheiras curadas",
    "libreta.enlazadas": "Vacas laçadas",
    "libreta.trabajadas": "Trabalhadas no brete",
    "libreta.mejor": "Melhor gado salvo",
    "libreta.mejorValor": "{v} de {t}",
    "libreta.plata": "Mais dinheiro no caixa",
    "libreta.ultimaSalvada": "Última temporada: salva, com {v} de {t} vivas.",
    "libreta.ultimaFundida": "Última temporada: quebrou no dia {d}.",
    "libreta.ninguna": "Você ainda não terminou nenhuma temporada.",
    "libreta.nota": "Fica salvo neste navegador.",
    "libreta.borrar": "Apagar a caderneta",
    "libreta.seguro": "Certeza? Toque de novo",
    "como.rastrear": "Rastrear",
    "como.rastrearT": "As bicheiradas se escondem no mato. Siga os rastros frescos e o esterco com moscas.",
    "como.enlazar": "Laçar",
    "como.enlazarT": "Segure para girar e solte com o anel cheio. Com uma vaca à frente, abre o olho de águia.",
    "como.pialar": "Pealar e recolher",
    "como.pialarT": "Laçada, aguente a tensão sem arrebentar o tento. Cansada, peale ela na janela verde.",
    "como.curar": "Curar a bicheira",
    "como.curarT": "Pinça para tirar os vermes e mata-bicheira até cobrir a ferida. Sem apressar a vaca: ela dá coice.",
    "como.manga": "O brete",
    "como.mangaT": "Aftosa e ivermectina no pescoço, brinco na orelha, ferro em brasa na anca.",
    "como.perros": "Os cães",
    "como.perrosT": "Tigre, Negra e Chispa: venham, quietos, juntem a tropa ou busquem a vaca que você olha.",
    "como.puesto": "O rancho",
    "como.puestoT": "Mate, água gelada, guisado no fogo de chão e o catre. A sede e a noite não perdoam.",
    "como.zaino": "O zaino",
    "como.zainoT": "Dê banho, dê forragem e não judie dele no galope: cavalo manco é dia perdido.",
    "como.teclasBoton": "Todas as teclas e o celular",
    "cred.lema": "Um simulador cru de trabalho de campo no mato chaquenho.",
    "cred.motor": "Motor 3D",
    "cred.modelos": "Modelos 3D e esqueletos",
    "cred.texturas": "Texturas do chão",
    "cred.voz": "Voz do Guacho",
    "cred.vozValor": "Higgsfield · qwen_audio_tts (voz Julian, sotaque rio-platense)",
    "cred.sonido": "Som",
    "cred.sonidoValor": "Gravações CC0 e CC-BY (abaixo); mugidos, cascos a passo, quero-queros e cigarras sintetizados no jogo",
    "cred.grabaciones": "Sons gravados sob licença CC-BY",
    "cred.grabacionesNota": "As demais gravações são CC0 (domínio público): vento, pássaros, fogo, água, latidos, passos e porteira.",
    "snd.cascos_galope": "Galope do cavalo",
    "snd.lazo_zumbido": "Zumbido do laço (uma corda de pular)",
    "cred.letras": "Tipografias",
    "cred.letrasValor": "Anton e Barlow Condensed (SIL OFL)",
    "cred.radio": "Rádio",
    "cred.radioValor": "Emissoras FM do Chaco, Formosa e Corrientes · Radio Browser",
    "cred.idiomas": "Idiomas",
    "cred.idiomasValor": "Español, English, Português. As vozes ficam em espanhol, com legendas.",

    "pausa.titulo": "Pausa",
    "pausa.texto": "O mato espera. As moscas não.",
    "pausa.seguir": "Continuar",
    "boton.como": "Como jogar",
    "boton.opciones": "Opções",
    "boton.volver": "Voltar",
    "boton.listo": "Pronto",
    "parte.sello": "Relatório do posteiro",
    "parte.seguir": "Sair para o campo",
    "fin.otra": "Outra temporada",
    "fogon.titulo": "O fogo de chão",
    "fogon.texto": "A lenha de quebracho aguenta a noite toda. A costela está no fogo desde a tarde.",
    "fogon.calentar": "Esquentar o ferro",
    "fogon.guiso": "Preparar um guisado",
    "fogon.comer": "Comer churrasco (à noite)",
    "fogon.nada": "Nada",
    "cura.titulo": "Bicheira",
    "cura.pinza": "Pinça",
    "cura.spray": "Mata-bicheira",
    "cura.paciencia": "Paciência da vaca",
    "cura.dejar": "Deixar",
    "cura.estado": "Vermes: {q} · Mata-bicheira: {c} %",
    "manga.aftosa": "1 · Aftosa",
    "manga.ivermectina": "2 · Ivermectina",
    "manga.caravana": "3 · Brinco",
    "manga.hierro": "4 · Ferro",
    "manga.soltar": "Soltar (E)",
    "manga.ayuda": "Escolha a ferramenta e toque na vaca: a vacina na tábua do pescoço, o brinco na orelha, a marca na anca.",
    "manga.hAftosa": "Aftosa",
    "manga.hIvermectina": "Ivermectina",
    "manga.hCaravana": "Brinco",
    "manga.hMarca": "Marca",
    "manga.hierroCaliente": "Ferro (quente)",
    "manga.hierroFrio": "Ferro (frio)",
    "manga.noHay": "Não há nenhuma vaca sem trabalhar dentro do curral.",
    "manga.cuello": "A vacina vai na tábua do pescoço.",
    "manga.oreja": "O brinco vai na orelha.",
    "manga.anca": "A marca vai na anca.",
    "manga.hecho": "Isso já está feito.",
    "manga.frio": "O ferro está frio. Esquente no fogo de chão.",
    "manga.lista": "Pronta. Solte com o botão ou com E.",
    "radio.titulo": "Rádio",
    "radio.apagada": "Desligado",
    "radio.prender": "Ligar",
    "radio.apagar": "Desligar",
    "radio.anterior": "Emissora anterior",
    "radio.siguiente": "Próxima emissora",
    "radio.volumen": "Volume",
    "radio.nota": "FMs do Chaco, Formosa e Corrientes pela internet. Dá para ouvir perto do rancho e vai sumindo conforme você se afasta.",
    "radio.otras": "Outras",
    "radio.sinComprobar": " · não verificada",
    "radio.sinSenal": " · sem sinal",
    "radio.soloArchivo": " · só no arquivo baixado",
    "radio.en el aire": "no ar",
    "radio.sintonizando…": "sintonizando…",
    "radio.sin señal: probá otra": "sem sinal: tente outra",
    "radio.solo archivo": "esta emissora só funciona no arquivo baixado",
    "radio.apagada2": "desligado",
    "radio.chip": "O rádio (toque para trocar a emissora)",
    "mapa.titulo": "O campo",
    "mapa.ayuda": "Toque um lugar para ir. Aparece uma coluna de luz e a bússola no alto.",
    "mapa.sacar": "Tirar o destino",
    "mapa.volver": "Voltar (M)",
    "mapa.acercar": "Aproximar",
    "mapa.alejar": "Afastar",
    "mapa.yo": "Centralizar em mim",
    "mapa.destino": "Destino marcado: {nombre}. Siga a coluna de luz.",
    "mapa.llegaste": "Você chegou: {nombre}.",
    "lugar.casco": "Sede da estância", "lugar.cascoC": "Sede",
    "lugar.corral": "Curral e brete", "lugar.corralC": "Curral",
    "lugar.comedero": "Cocho (confinamento)", "lugar.comederoC": "Cocho",
    "lugar.aguada": "Aguada: tanque e cata-vento", "lugar.aguadaC": "Aguada",
    "lugar.estero": "Banhado (aguada natural)", "lugar.esteroC": "Banhado",
    "lugar.fogon": "Fogo de chão", "lugar.fogonC": "Fogo",
    "lugar.tranquera": "Porteira de entrada", "lugar.tranqueraC": "Porteira",
    "lugar.pueblo": "{nombre} (o povoado)", "lugar.puebloC": "Povoado",
    "lugar.caballo": "O zaino", "lugar.caballoC": "Zaino",
    "lugar.vaca": "A {num} (com bicheira)", "lugar.vacaC": "A {num}",
    "lugar.punto": "o ponto marcado", "lugar.puntoC": "Ponto",
    "como.titulo": "Como jogar",
    "como.teclas": "As teclas",
    "como.t1": "<kbd>W A S D</kbd>andar · <kbd>Shift</kbd>correr / galopar",
    "como.t2": "<kbd>E</kbd>usar, montar, curar",
    "como.t3": "<kbd>1</kbd>o laço · segure o <kbd>clique</kbd> para girar, solte para jogar",
    "como.t4": "<kbd>clique dir.</kbd>recolher laço · <kbd>P</kbd>pealar",
    "como.t5": "<kbd>C</kbd>cavalo a passo · <kbd>H</kbd>assobiar para o cavalo",
    "como.t6": "<kbd>V</kbd>câmera · <kbd>F</kbd>enrolar um palheiro",
    "como.t7": "<kbd>G</kbd>cães: venham · <kbd>X</kbd>quietos",
    "como.t8": "<kbd>J</kbd>cães: juntem a tropa · <kbd>B</kbd>busquem a vaca que você olha",
    "como.t9": "<kbd>Enter</kbd> ou <kbd>/</kbd> o chat de comandos",
    "como.t10": "<kbd>M</kbd> o mapa: curral, sede, povoado, cocho, aguada",
    "como.ojo": "Olho de águia",
    "como.ojoT": "Gire o laço com uma vaca à frente, entre 4 e 18 metros: o mundo fica cinza, o tempo desacelera e a mira se fecha sobre a cabeça. Quando ficar vermelha, solte: a armada vai direto ao pescoço e a câmera gira para vê-la cair.",
    "como.celular": "No celular",
    "como.celularT": "Deitado ou em pé: se estiver em pé, o jogo gira sozinho. Alavanca à esquerda, deslize à direita para olhar, botões na tela.",
    "op.titulo": "Opções",
    "op.brillo": "Brilho",
    "op.volumen": "Volume geral",
    "op.voz": "Voz do Guacho",
    "op.sensib": "Sensibilidade do mouse",
    "op.calidad": "Qualidade gráfica",
    "op.escaneo": "Varredura de quadros",
    "op.noMedido": "Ainda não foi medido.",
    "op.medido": "Mediu {fps} quadros por segundo e escolheu {nivel}.",
    "op.medir": "Medir de novo",
    "op.ojo": "Olho de águia",
    "op.ojoT": "Câmera lenta e mira ao girar o laço. Sem isso, é na mão.",
    "op.subs": "Legendas",
    "op.subsT": "O que o Guacho diz, escrito embaixo.",

    "hud.dia": "Dia {d} de {n}",
    "hud.costilla": "Costela quebrada",
    "hud.lesion": "Cavalo machucado",
    "hud.sed": "Sede",
    "hud.cansancio": "Cansaço",
    "hud.salud": "Saúde",
    "hud.caballo": "Cavalo",
    "hud.tension": "Tensão",
    "hud.laVaca": "A vaca",
    "hud.minimapa": "Minimapa (toque para abrir o mapa)",
    "hud.cansada": "Cansada: peale ela (P)",
    "hud.aguanta": "Aguente e recolha (botão direito)",
    "ojo.soltar": "Solte para jogar",
    "ojo.fijando": "Mirando…",
    "tarea.bichera": (v) => `A ${v.num} com bicheira · ${v.dias ? v.dias + pl(v.dias, " dia", " dias") : "de hoje"}`,
    "tarea.sinLazo": "Sem laço: tem na varanda ou no armazém",
    "tarea.zaino": "O zaino: {cosas}",
    "tarea.banar": "dar banho",
    "tarea.forraje": "dar forragem",
    "tarea.comedero": "Cocho do confinamento vazio",
    "tarea.hierro": "Ferro quente: {min} min",
    "tarea.manga": "Brete: {t} de {v} trabalhadas",
    "tactil.controles": "Controles",
    "tactil.lazo": "Laço", "tactil.cobrar": "Recolher", "tactil.accion": "Ação", "tactil.pialar": "Pealar",
    "tactil.camara": "Câmera", "tactil.silbar": "Assobiar", "tactil.perros": "Cães", "tactil.mapa": "Mapa",

    "accion.soltarVaca": "Soltar a vaca",
    "accion.soltarSinTerminar": "Soltar sem terminar",
    "accion.bajate": "Desça para trabalhar nela",
    "accion.curar": "Curar a bicheira da {num}",
    "accion.soltar": "Soltar a {num}",
    "accion.montar": "Montar o zaino",
    "accion.bajarse": "Desça do cavalo",
    "accion.comprarLazo": "Comprar um laço no armazém ($ {p})",
    "accion.almacen": "Armazém: um refrigerante gelado, erva e bolachas ($ {p})",
    "accion.comederoLleno": "O cocho está cheio",
    "accion.zainoComio": "O zaino já tem forragem",
    "accion.banar": "Dar banho no zaino com o balde",
    "accion.radio": "Rádio FM: escolher a emissora",
    "accion.temprano": "Ainda é cedo para dormir",
    "accion.fogon": "Fogo de chão: esquentar o ferro, cozinhar ou comer",
    "accion.lazoGaleria": "Pegar o laço novo da varanda ($ {p})",
    "accion.desmontar": "Apear",
    "punto.mate": "Tomar mate cozido com bolacha",
    "punto.mateCebar": "Cevar uns mates",
    "punto.catre": "Dormir no catre",
    "punto.radio": "Ligar o rádio",
    "punto.fogon": "Fogo de chão",
    "punto.manga": "Trabalhar no brete",
    "punto.corralCerrar": "Fechar a porteira do curral",
    "punto.corralAbrir": "Abrir a porteira do curral",
    "punto.tanque": "Beber água no bebedouro",
    "punto.entradaAbrir": "Abrir a porteira de entrada (caminho do povoado)",
    "punto.entradaCerrar": "Fechar a porteira de entrada",
    "punto.almacen": "Armazém",
    "punto.encierreAbrir": "Abrir a porteira do confinamento",
    "punto.encierreCerrar": "Fechar a porteira do confinamento",
    "punto.comederoHacienda": "Encher o cocho com silagem",
    "punto.heladera": "Beber água gelada da geladeira",
    "punto.forraje": "Dar forragem ao zaino",

    "msj.costilla": "Costela quebrada: dois dias sem correr e com menos força no laço.",
    "msj.lazoComprado": "Don Benito te vendeu um laço de oito tentos. Bem trançado.",
    "msj.almacen": "Um refrigerante gelado na varanda do armazém, e Don Benito com as notícias do povoado.",
    "msj.aguaAmbos": "Você bebeu água, e o zaino também.",
    "msj.agua": "Água do bebedouro, morna mas é água.",
    "msj.hierro": "O ferro está em brasa. Você tem uma hora e meia.",
    "msj.asado": "Costela no fogo de chão, com couro. Gordura e fumaça.",
    "msj.golpeCalor": "Você teve uma insolação. O posteiro te achou caído e te trouxe ao rancho.",
    "msj.deCama": "Você ficou de cama. Te trouxeram ao rancho entre dois.",
    "msj.noche": "A noite te pegou. Você dormiu onde estava.",
    "msj.mate": "Uns mates amargos com bolacha, olhando o mato. A gente volta a ser gente.",
    "msj.heladera": "Água gelada da geladeira: uma glória.",
    "msj.guiso": "Guisado de arroz com carne e abóbora. Barriga cheia, coração contente.",
    "msj.banar": "Você jogou uns baldes e escovou ele. O zaino brilha.",
    "msj.forraje": "Um fardo de alfafa no cocho. O zaino já vem.",
    "msj.puesto": "No rancho: cevar uns mates na mesa, fazer a comida no fogo de chão, dar banho no zaino no tanque e forragem no cocho.",
    "msj.comederoLleno": "O cocho já está cheio.",
    "msj.comederoCargado": "Você encheu o cocho com silagem de milho ($ {p}). O gado já levanta a cabeça.",
    "perro.seguir": "Venham!", "perro.seguirT": "os cães te seguem",
    "perro.quieto": "Quietos!", "perro.quietoT": "deitam onde estão",
    "perro.juntar": "Juntem!", "perro.juntarT": "tocam a tropa até você",
    "perro.traer": "Busca!", "perro.traerT": "Tigre traz a vaca que você olha",
    "perro.sinVaca": "Não há vaca à frente para buscar. Olhe para uma.",
    "perro.orden": "{texto} — {ayuda}.",
    "perro.vaABuscar": "Tigre vai buscar a {num}",
    "perro.trajo": "Tigre te trouxe a {num}.",
    "perro.junta": "O gado está junto.",

    "vaca.la": "a {num}",
    "y": " e ",
    "dias": (v) => `${v.n} ${pl(v.n, "dia", "dias")}`,
    "rumbo": (v) => `${v.lejos === 2 ? "longe, " : v.lejos === 0 ? "pertinho, " : ""}para o ${["norte", "nordeste", "leste", "sudeste", "sul", "sudoeste", "oeste", "noroeste"][v.i]}`,
    "parte.dia1Titulo": "Dia 1 de {n}. Amanhece na estância, 23 °C e vem mormaço.",
    "parte.dia1Texto": "O posteiro viu a {num} com bicheira, mancando {rumbo}, metida no mato. Procure os rastros frescos e o esterco com moscas. O zaino está encilhado ao lado do rancho.",
    "parte.diaTitulo": "Dia {d} de {n}.",
    "parte.muertas": "Amanheceu morta {lista}: a bicheira a comeu. Os chimangos já estão rondando. ",
    "parte.nueva": "O posteiro viu a {num} bicheirada, {rumbo}.",
    "parte.siguen": "Seguem com bicheira: {lista}. Em três dias elas morrem. ",
    "parte.sigueItem": "a {num} ({dias})",
    "parte.nadie": "Nenhuma bicheirada hoje. Dia de brete: vacinar, brincar e marcar. ",
    "parte.hacienda": "Gado: {vivas} de {total}, {trab} trabalhadas.",
    "parte.zainoFlaco": "O zaino amanheceu fraco: ontem à noite você não deu forragem, e hoje ele vai cansar logo. ",
    "parte.mataduras": "Você deixou ele com suor e barro: amanheceu com feridas de sela no lombo e manco. ",
    "parte.sucio": "O zaino continua sujo desde ontem; se não der banho, vão sair feridas de sela. ",
    "parte.zainoBien": "O zaino amanheceu limpo e alimentado, com vontade de trabalhar. ",
    "parte.novillosBien": "Os novilhos do confinamento comeram bem: estão com {kg} kg em média. ",
    "parte.novillosAlgunos": "Só {c} de {n} novilhos alcançaram o cocho; estão com {kg} kg em média. ",
    "parte.novillosNada": "Os novilhos do confinamento passaram o dia sem comer: caíram para {kg} kg. É preciso encher o cocho. ",
    "fin.fundiste": "Você quebrou a estância.",
    "fin.salvaste": "Você salvou a temporada.",
    "fin.p1": "Gado vivo: <b>{vivas} de {total}</b>. Vacinadas contra aftosa: <b>{vac}</b>. Trabalhadas completas: <b>{trab}</b>.",
    "fin.p2": "Dinheiro no caixa: <b>$ {plata}</b>. O gado vale <b>$ {hac}</b>.",
    "fin.malo": "Com o que morreu e o que não foi vacinado, não dá para seguir. O banco fica com o campo.",
    "fin.bueno": "A estância segue viva mais um ano. Ninguém vai te agradecer, mas o campo segue.",

    "chat.boton": "Chat de comandos",
    "chat.botonTitulo": "Chat (Enter ou /)",
    "chat.placeholder": "Digite / para ver os comandos",
    "chat.enviar": "Enviar",
    "chat.usar": "Usar comando",
    "chat.sistema": "[Sistema]:",
    "chat.vos": "Você",
    "chat.bienvenida": "Digite /{ayuda} para ver os comandos. Enter ou / abrem o chat.",
    "chat.noConozco": "Não conheço \"/{cmd}\". Tente /{ayuda}.",
    "cmd.ayuda": "ajuda", "cmd.ayudaD": "A lista de comandos", "cmd.ayudaR": "Comandos: ",
    "cmd.saludar": "saudar", "cmd.saludarD": "O Guacho cumprimenta", "cmd.saludarR": "Olá, {nombre}! Este comando funciona no celular.",
    "cmd.perros": "caes", "cmd.perrosA": "venham | quietos | juntem | busquem", "cmd.perrosD": "Ordens para os cães",
    "cmd.perrosNo": "Não há cães nesta estância.",
    "cmd.perrosQue": "O que você diz? /{cmd} venham, quietos, juntem ou busquem.",
    "cmd.perrosR": "{texto} Os cães: {ayuda}.",
    "cmd.perrosPalabras": { venham: "seguir", quietos: "quieto", juntem: "juntar", busquem: "traer", busca: "traer" },
    "cmd.silbar": "assobiar", "cmd.silbarD": "Assobiar para o zaino vir",
    "cmd.mate": "mate", "cmd.mateD": "Cevar uns mates (na varanda)", "cmd.mateLejos": "A erva e a chaleira estão na mesa da varanda, {rumbo}.",
    "cmd.comer": "comer", "cmd.comerD": "Preparar um guisado no fogo de chão", "cmd.comerLejos": "O fogo de chão fica {rumbo}.",
    "cmd.comerYa": "Você já comeu hoje.", "cmd.comerTemprano": "Muito cedo para o guisado. Tome uns mates.",
    "cmd.caballo": "cavalo", "cmd.caballoD": "Como está o zaino",
    "cmd.caballoAliento": "fôlego {n}%", "cmd.rengo": "manco", "cmd.sano": "são", "cmd.muySucio": "muito sujo", "cmd.algoSucio": "meio sujo",
    "cmd.limpio": "limpo", "cmd.comido": "alimentado", "cmd.sinForraje": "sem forragem hoje",
    "cmd.caballoR": "O zaino: {estado}.", "cmd.caballoDonde": " Está {rumbo}.",
    "cmd.hacienda": "gado", "cmd.haciendaD": "Quantas restam e onde estão as bicheiradas",
    "cmd.haciendaR": "Rebanho do campo: {v} vacas, {t} touros e {te} bezerros. De trabalho: {vivas} de {total} vacas, {trab} trabalhadas.",
    "cmd.conBichera": " Com bicheira: {lista}.", "cmd.ninguna": " Nenhuma bicheirada.", "cmd.vacaDonde": "a {num} ({rumbo})",
    "cmd.razas": "racas", "cmd.razasD": "Quais raças há na tropa", "cmd.razasR": "{lista}, e {n} bezerros.", "cmd.toro": " (touro)",
    "raza.colorada": "Angus vermelha", "raza.criolla": "Crioula pintada",
    "cmd.comedero": "cocho", "cmd.comederoD": "Como estão o cocho e os novilhos",
    "cmd.comederoR": "Cocho a {n} %, {c} comendo agora. Novilhos do confinamento: {nov}, com {kg} kg em média. A porteira do confinamento está {estado}.",
    "cmd.abierta": "aberta", "cmd.cerrada": "fechada",
    "cmd.mapa": "mapa", "cmd.mapaD": "Abrir o mapa do campo",
    "cmd.ir": "ir", "cmd.irA": "sede | curral | cocho | aguada | povoado | banhado | zaino", "cmd.irD": "Marcar para onde ir",
    "cmd.irZaino": "zaino",
    "cmd.irAdonde": "Para onde? /{cmd} sede, curral, cocho, aguada, povoado, banhado ou zaino.",
    "cmd.irNoSe": "Não sei onde fica \"{arg}\". Tente /{mapa}.",
    "cmd.irR": "{nombre}: {rumbo}, a {m} m. Siga a coluna de luz.",
    "cmd.hora": "hora", "cmd.horaD": "A hora e o dia", "cmd.horaR": "São {hh}:{mm} do dia {d} de {n}.",
    "cmd.puesto": "rancho", "cmd.puestoD": "Para que lado fica o rancho", "cmd.puestoR": "O rancho fica {rumbo}, a {m} m.",
    "cmd.fumar": "fumar", "cmd.fumarD": "Enrolar um palheiro",
    "cmd.camara": "camera", "cmd.camaraD": "Primeira ou terceira pessoa",
    "cmd.camaraPrimera": "Câmera em primeira pessoa.", "cmd.camaraTercera": "Câmera em terceira pessoa.",
    "cmd.radio": "radio", "cmd.radioA": "desligar | proxima | nome", "cmd.radioD": "Rádio FM (Chaco, Formosa, Corrientes)",
    "cmd.radioApagar": "desligar", "cmd.radioSiguiente": "proxima",
    "cmd.radioApagada": "Rádio desligado.", "cmd.sintonizando": "Sintonizando {nombre}.",
    "cmd.radioNo": "Não encontro \"{arg}\". Tente /{cmd} para ver o dial.", "cmd.sintonizandoLugar": "Sintonizando {nombre} ({lugar}).",
    "cmd.limpiar": "limpar", "cmd.limpiarD": "Limpar o chat",

    "frase.errar": ["Ah, que droga!", "Bah, tchê!", "Passou raspando.", "Ai, mãezinha, que tiro!"],
    "frase.enlazada": ["Aí está, te peguei!", "Toma, manhosa!", "Quieta, quieta!", "Calma, nega."],
    "frase.cortado": ["O laço arrebentou, bah!", "Esse tento estava podre."],
    "frase.seFue": ["Ela fugiu com laço e tudo!", "Lá se vai meu laço, que azar!"],
    "frase.pialada": ["Pro chão!", "Deita, vamos!", "Aí está. Quieta."],
    "frase.errarPial": ["Para, para…!", "Quase, quase. De novo."],
    "frase.todaviaNo": ["Ainda está inteira. Tem que cansar ela.", "Que se canse primeiro."],
    "frase.patada": ["Ai! A costela…!", "Uh, que coice ela me deu!"],
    "frase.cornada": ["Me chifrou, a manhosa!", "Ai, ai, ai!"],
    "frase.embiste": ["Opa, lá vem!", "Cuidado que ela investe!"],
    "frase.sed": ["Estou morrendo de sede.", "Minha garganta virou pó."],
    "frase.calor": ["Que calor bárbaro.", "Quarenta à sombra, e sem sombra."],
    "frase.curada": ["Pronto, nega. Já está.", "Assim, curadinha."],
    "frase.lesion": ["O zaino mancou. Judiei dele.", "Uh, o cavalo está mancando."],
    "frase.sinLazo": ["Estou sem laço. Tem um pendurado na varanda."],
    "frase.fumar": ["Um palheiro e seguimos."],
    "frase.manga": ["Vamos, pra dentro.", "Pro brete, vamos."],
    "frase.silbar": ["Vem, zaino!"],
    "frase.apuntar": ["Tô com ela na mira…", "Quieta… quieta…", "Agora é minha."],
    "frase.perros": ["Venham, cachorros!", "Vamos, Tigre! Negra, vem!"],
    "frase.quietos": ["Quietos aí!", "Deita, Chispa!"],
    "frase.junten": ["Juntem, juntem o gado!", "Vai, vai! Junta!"],
    "frase.busquen": ["Busca, busca!", "Traz ela, Tigre!"],
    "frase.mate": ["Um chimarrãozinho e seguimos.", "Que bom esse mate amargo."],
    "frase.comida": ["Vamos ver o que tem pra comer.", "Um guisado de arroz, como manda o figurino."],
    "frase.heladera": ["Aguinha fresca, que beleza."],
    "frase.banar": ["Vem, zaino, que eu te dou banho.", "Aí está, limpinho."],
    "frase.forraje": ["Toma, come sossegado."],
    "frase.saludar": ["Buenas! Como vão?", "Bom dia, paisano!"],
    "frase.puesto": ["Enfim no rancho."],
    "frase.caballoSucio": ["Esse zaino está um barro só."],
  };

  const DICC = { es, en, pt };
  const LOCALES = { es: "es-AR", en: "en-US", pt: "pt-BR" };

  // La elección de la vez anterior; si no hay, la del navegador, y si no, castellano.
  let guardado = null;
  try { guardado = localStorage.getItem("estancia-idioma"); } catch (e) { /* sin almacenamiento */ }
  const delNavegador = (navigator.language || "es").slice(0, 2).toLowerCase();
  const I = (window.IDIOMA = {
    CODIGOS: ["es", "en", "pt"],
    DICC,
    guardado: DICC[guardado] ? guardado : null,
    actual: DICC[guardado] ? guardado : DICC[delNavegador] ? delNavegador : "es",
  });
  const avisar = [];

  // Lo que falta en un idioma sale en castellano (mejor que ver la clave), y lo
  // que falta en los tres sale como la clave, para que se note en las pruebas.
  I.t = (clave, vars) => {
    let v = DICC[I.actual][clave];
    if (v === undefined) v = es[clave];
    if (v === undefined) return clave;
    if (typeof v === "function") return v(vars || {});
    if (vars && typeof v === "string") v = v.replace(/\{(\w+)\}/g, (m, k) => (vars[k] !== undefined ? vars[k] : m));
    return v;
  };
  I.lista = (clave) => {
    const l = DICC[I.actual][clave];
    return Array.isArray(l) ? l : es[clave] || [];
  };
  I.numero = (n) => new Intl.NumberFormat(LOCALES[I.actual]).format(n);

  // El HTML trae el castellano escrito (se lee mejor y es el respaldo); acá se
  // pisa con el idioma elegido. data-t: texto; data-t-html: con <b> o <kbd>;
  // data-t-ph, data-t-aria, data-t-title: los atributos.
  I.aplicar = (raiz = document) => {
    raiz.querySelectorAll("[data-t]").forEach((el) => { el.textContent = I.t(el.dataset.t); });
    raiz.querySelectorAll("[data-t-html]").forEach((el) => { el.innerHTML = I.t(el.dataset.tHtml); });
    raiz.querySelectorAll("[data-t-ph]").forEach((el) => { el.placeholder = I.t(el.dataset.tPh); });
    raiz.querySelectorAll("[data-t-aria]").forEach((el) => { el.setAttribute("aria-label", I.t(el.dataset.tAria)); });
    raiz.querySelectorAll("[data-t-title]").forEach((el) => { el.title = I.t(el.dataset.tTitle); });
    document.documentElement.lang = I.actual;
    document.title = I.t("titulo");
  };
  I.cambiar = (cod) => {
    if (!DICC[cod]) return;
    I.actual = cod; I.guardado = cod;
    try { localStorage.setItem("estancia-idioma", cod); } catch (e) { /* no importa */ }
    I.aplicar();
    avisar.forEach((f) => f(cod));
  };
  // Lo que se arma con JS (el HUD, las listas, la libreta) se repinta solo.
  I.alCambiar = (f) => avisar.push(f);

  window.t = I.t;
  I.aplicar();
})();
