// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Analytics
{
    public static partial class Analytics
    {
        public static bool enabled { get { global::Porteo.Falta.Llamada("UnityEngine.Analytics.Analytics::enabled"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Analytics.Analytics::enabled="); } }
    }
}
