// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Events
{
    public abstract partial class BaseInvokableCall
    {
        public abstract void Invoke(object[] args);
        public abstract bool Find(object targetObj, global::System.Reflection.MethodInfo method);
    }
}
