// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Events
{
    public abstract partial class UnityEvent<T0, T1, T2>
    {
    }
}
