// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Events
{
    public delegate void UnityAction<T0>(T0 arg0);
}
