// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Scripting
{
    [System.AttributeUsage((System.AttributeTargets)6141, Inherited = false)]
    public partial class PreserveAttribute : global::System.Attribute
    {
        public PreserveAttribute() { global::Porteo.Falta.Llamada("UnityEngine.Scripting.PreserveAttribute::.ctor"); }
    }
}
