// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AddComponentMenu : global::System.Attribute
    {
        public AddComponentMenu(string menuName) { global::Porteo.Falta.Llamada("UnityEngine.AddComponentMenu::.ctor"); }
        public AddComponentMenu(string menuName, int order) { global::Porteo.Falta.Llamada("UnityEngine.AddComponentMenu::.ctor"); }
    }
}
