// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct AnimatorClipInfo
    {
        public int m_ClipInstanceID;
        public float m_Weight;
    }
}
