// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AnimatorOverrideController
    {
        public global::UnityEngine.AnimationClipPair[] clips { get { global::Porteo.Falta.Llamada("UnityEngine.AnimatorOverrideController::clips"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.AnimatorOverrideController::clips="); } }
    }
}
