// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum AnimationPlayMode : int
    {
        Stop = 0,
        Queue = 1,
        Mix = 2,
    }
}
