// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AnimatorControllerParameter
    {
        public override bool Equals(object o) { global::Porteo.Falta.Llamada("UnityEngine.AnimatorControllerParameter::Equals"); return default; }
        public override int GetHashCode() { global::Porteo.Falta.Llamada("UnityEngine.AnimatorControllerParameter::GetHashCode"); return default; }
    }
}
