// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Animation
    {
        public void AddClip(global::UnityEngine.AnimationClip clip, string newName, int firstFrame, int lastFrame) { global::Porteo.Falta.Llamada("UnityEngine.Animation::AddClip"); }
        public void AddClip(global::UnityEngine.AnimationClip clip, string newName, int firstFrame, int lastFrame, bool addLoopFrame) { global::Porteo.Falta.Llamada("UnityEngine.Animation::AddClip"); }
        public bool Play(global::UnityEngine.AnimationPlayMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Animation::Play"); return default; }
        public bool Play(string animation, global::UnityEngine.AnimationPlayMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Animation::Play"); return default; }
    }
}
