// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Application
    {
        public static bool isBatchMode { get { global::Porteo.Falta.Llamada("UnityEngine.Application::isBatchMode"); return default; } }
        public static void Quit(int exitCode) { global::Porteo.Falta.Llamada("UnityEngine.Application::Quit"); }
        public static bool IsPlaying(global::UnityEngine.Object obj) { global::Porteo.Falta.Llamada("UnityEngine.Application::IsPlaying"); return default; }
        public static void DontDestroyOnLoad(global::UnityEngine.Object o) { global::Porteo.Falta.Llamada("UnityEngine.Application::DontDestroyOnLoad"); }
        public delegate void LogCallback(string condition, string stackTrace, global::UnityEngine.LogType type);
    }
}
