// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4, Inherited = false)]
    public sealed partial class AssetFileNameExtensionAttribute : global::System.Attribute
    {
        public AssetFileNameExtensionAttribute(string preferredExtension, params string[] otherExtensions) { global::Porteo.Falta.Llamada("UnityEngine.AssetFileNameExtensionAttribute::.ctor"); }
    }
}
