// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AudioSettings
    {
        public static bool Reset(global::UnityEngine.AudioConfiguration config) { global::Porteo.Falta.Llamada("UnityEngine.AudioSettings::Reset"); return default; }
    }
}
