// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AudioClip
    {
        public static global::UnityEngine.AudioClip Create(string name, int lengthSamples, int channels, int frequency, bool _3D, bool stream) { global::Porteo.Falta.Llamada("UnityEngine.AudioClip::Create"); return default; }
        public static global::UnityEngine.AudioClip Create(string name, int lengthSamples, int channels, int frequency, bool _3D, bool stream, global::UnityEngine.AudioClip.PCMReaderCallback pcmreadercallback) { global::Porteo.Falta.Llamada("UnityEngine.AudioClip::Create"); return default; }
        public static global::UnityEngine.AudioClip Create(string name, int lengthSamples, int channels, int frequency, bool _3D, bool stream, global::UnityEngine.AudioClip.PCMReaderCallback pcmreadercallback, global::UnityEngine.AudioClip.PCMSetPositionCallback pcmsetpositioncallback) { global::Porteo.Falta.Llamada("UnityEngine.AudioClip::Create"); return default; }
        public static global::UnityEngine.AudioClip Create(string name, int lengthSamples, int channels, int frequency, bool stream) { global::Porteo.Falta.Llamada("UnityEngine.AudioClip::Create"); return default; }
        public static global::UnityEngine.AudioClip Create(string name, int lengthSamples, int channels, int frequency, bool stream, global::UnityEngine.AudioClip.PCMReaderCallback pcmreadercallback) { global::Porteo.Falta.Llamada("UnityEngine.AudioClip::Create"); return default; }
        public static global::UnityEngine.AudioClip Create(string name, int lengthSamples, int channels, int frequency, bool stream, global::UnityEngine.AudioClip.PCMReaderCallback pcmreadercallback, global::UnityEngine.AudioClip.PCMSetPositionCallback pcmsetpositioncallback) { global::Porteo.Falta.Llamada("UnityEngine.AudioClip::Create"); return default; }
        public delegate void PCMReaderCallback(float[] data);
        public delegate void PCMSetPositionCallback(int position);
    }
}
