// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Avatar
    {
        public global::UnityEngine.HumanDescription humanDescription { get { global::Porteo.Falta.Llamada("UnityEngine.Avatar::humanDescription"); return default; } }
    }
}
