// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AvatarMask : global::UnityEngine.Object
    {
        public int transformCount { get { global::Porteo.Falta.Llamada("UnityEngine.AvatarMask::transformCount"); return default; } }
        public bool GetHumanoidBodyPartActive(global::UnityEngine.AvatarMaskBodyPart index) { global::Porteo.Falta.Llamada("UnityEngine.AvatarMask::GetHumanoidBodyPartActive"); return default; }
        public string GetTransformPath(int index) { global::Porteo.Falta.Llamada("UnityEngine.AvatarMask::GetTransformPath"); return default; }
        public bool GetTransformActive(int index) { global::Porteo.Falta.Llamada("UnityEngine.AvatarMask::GetTransformActive"); return default; }
    }
}
