// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct BoundsInt : global::System.IEquatable<global::UnityEngine.BoundsInt>, global::System.IFormattable
    {
        public global::UnityEngine.Vector3Int m_Position;
        public global::UnityEngine.Vector3Int m_Size;
        public int x { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::x"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::x="); } }
        public int y { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::y"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::y="); } }
        public int z { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::z"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::z="); } }
        public global::UnityEngine.Vector3 center { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::center"); return default; } }
        public global::UnityEngine.Vector3Int min { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::min"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::min="); } }
        public global::UnityEngine.Vector3Int max { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::max"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::max="); } }
        public int xMin { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::xMin"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::xMin="); } }
        public int yMin { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::yMin"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::yMin="); } }
        public int xMax { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::xMax"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::xMax="); } }
        public int yMax { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::yMax"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::yMax="); } }
        public global::UnityEngine.Vector3Int position { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::position"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::position="); } }
        public global::UnityEngine.Vector3Int size { get { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::size"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::size="); } }
        public void SetMinMax(global::UnityEngine.Vector3Int minPosition, global::UnityEngine.Vector3Int maxPosition) { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::SetMinMax"); }
        public bool Contains(global::UnityEngine.Vector3Int position) { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::Contains"); return default; }
        public override string ToString() { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::ToString"); return default; }
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::ToString"); return default; }
        public string ToString(string format, global::System.IFormatProvider formatProvider) { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::ToString"); return default; }
        public override bool Equals(object other) { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::Equals"); return default; }
        public bool Equals(global::UnityEngine.BoundsInt other) { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::Equals"); return default; }
        public override int GetHashCode() { global::Porteo.Falta.Llamada("UnityEngine.BoundsInt::GetHashCode"); return default; }
    }
}
