// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Bounds
    {
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.Bounds::ToString"); return default; }
        public string ToString(string format, global::System.IFormatProvider formatProvider) { global::Porteo.Falta.Llamada("UnityEngine.Bounds::ToString"); return default; }
    }
}
