// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct BoundingSphere
    {
        public global::UnityEngine.Vector3 position;
        public float radius;
    }
}
