// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class BoxCollider
    {
        public global::UnityEngine.Vector3 extents { get { global::Porteo.Falta.Llamada("UnityEngine.BoxCollider::extents"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoxCollider::extents="); } }
    }
}
