// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Cache : global::System.IEquatable<global::UnityEngine.Cache>
    {
        public int m_Handle;
        public string path { get { global::Porteo.Falta.Llamada("UnityEngine.Cache::path"); return default; } }
        public int index { get { global::Porteo.Falta.Llamada("UnityEngine.Cache::index"); return default; } }
        public override int GetHashCode() { global::Porteo.Falta.Llamada("UnityEngine.Cache::GetHashCode"); return default; }
        public override bool Equals(object other) { global::Porteo.Falta.Llamada("UnityEngine.Cache::Equals"); return default; }
        public bool Equals(global::UnityEngine.Cache other) { global::Porteo.Falta.Llamada("UnityEngine.Cache::Equals"); return default; }
    }
}
