// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Camera
    {
        public bool allowDynamicResolution { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::allowDynamicResolution"); return default; } }
        public global::UnityEngine.CameraType cameraType { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::cameraType"); return default; } }
        public bool usePhysicalProperties { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::usePhysicalProperties"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::usePhysicalProperties="); } }
        public bool useJitteredProjectionMatrixForTransparentRendering { set { global::Porteo.Falta.Llamada("UnityEngine.Camera::useJitteredProjectionMatrixForTransparentRendering="); } }
        public global::UnityEngine.SceneManagement.Scene scene { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::scene"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::scene="); } }
        public global::UnityEngine.StereoTargetEyeMask stereoTargetEye { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::stereoTargetEye"); return default; } }
        public global::UnityEngine.Camera.MonoOrStereoscopicEye stereoActiveEye { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::stereoActiveEye"); return default; } }
        public void Reset() { global::Porteo.Falta.Llamada("UnityEngine.Camera::Reset"); }
        public global::UnityEngine.Vector3 WorldToScreenPoint(global::UnityEngine.Vector3 position, global::UnityEngine.Camera.MonoOrStereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::WorldToScreenPoint"); return default; }
        public global::UnityEngine.Vector3 WorldToViewportPoint(global::UnityEngine.Vector3 position, global::UnityEngine.Camera.MonoOrStereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::WorldToViewportPoint"); return default; }
        public global::UnityEngine.Vector3 ViewportToWorldPoint(global::UnityEngine.Vector3 position, global::UnityEngine.Camera.MonoOrStereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ViewportToWorldPoint"); return default; }
        public global::UnityEngine.Vector3 ScreenToWorldPoint(global::UnityEngine.Vector3 position, global::UnityEngine.Camera.MonoOrStereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ScreenToWorldPoint"); return default; }
        public global::UnityEngine.Ray ViewportPointToRay(global::UnityEngine.Vector3 pos, global::UnityEngine.Camera.MonoOrStereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ViewportPointToRay"); return default; }
        public global::UnityEngine.Ray ScreenPointToRay(global::UnityEngine.Vector3 pos, global::UnityEngine.Camera.MonoOrStereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ScreenPointToRay"); return default; }
        public global::UnityEngine.Matrix4x4 GetStereoNonJitteredProjectionMatrix(global::UnityEngine.Camera.StereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::GetStereoNonJitteredProjectionMatrix"); return default; }
        public void CopyStereoDeviceProjectionMatrixToNonJittered(global::UnityEngine.Camera.StereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::CopyStereoDeviceProjectionMatrixToNonJittered"); }
        public global::UnityEngine.Matrix4x4 GetStereoProjectionMatrix(global::UnityEngine.Camera.StereoscopicEye eye) { global::Porteo.Falta.Llamada("UnityEngine.Camera::GetStereoProjectionMatrix"); return default; }
        public void SetStereoProjectionMatrix(global::UnityEngine.Camera.StereoscopicEye eye, global::UnityEngine.Matrix4x4 matrix) { global::Porteo.Falta.Llamada("UnityEngine.Camera::SetStereoProjectionMatrix"); }
        public void ResetStereoProjectionMatrices() { global::Porteo.Falta.Llamada("UnityEngine.Camera::ResetStereoProjectionMatrices"); }
        public void AddCommandBuffer(global::UnityEngine.Rendering.CameraEvent evt, global::UnityEngine.Rendering.CommandBuffer buffer) { global::Porteo.Falta.Llamada("UnityEngine.Camera::AddCommandBuffer"); }
        public void RemoveCommandBuffer(global::UnityEngine.Rendering.CameraEvent evt, global::UnityEngine.Rendering.CommandBuffer buffer) { global::Porteo.Falta.Llamada("UnityEngine.Camera::RemoveCommandBuffer"); }
        public enum MonoOrStereoscopicEye : int
        {
            Left = 0,
            Right = 1,
            Mono = 2,
        }
        public enum StereoscopicEye : int
        {
            Left = 0,
            Right = 1,
        }
    }
}
