// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class CanvasRenderer
    {
        public global::UnityEngine.Vector2 clippingSoftness { set { global::Porteo.Falta.Llamada("UnityEngine.CanvasRenderer::clippingSoftness="); } }
        public static void AddUIVertexStream(global::System.Collections.Generic.List<global::UnityEngine.UIVertex> verts, global::System.Collections.Generic.List<global::UnityEngine.Vector3> positions, global::System.Collections.Generic.List<global::UnityEngine.Color32> colors, global::System.Collections.Generic.List<global::UnityEngine.Vector4> uv0S, global::System.Collections.Generic.List<global::UnityEngine.Vector4> uv1S, global::System.Collections.Generic.List<global::UnityEngine.Vector4> uv2S, global::System.Collections.Generic.List<global::UnityEngine.Vector4> uv3S, global::System.Collections.Generic.List<global::UnityEngine.Vector3> normals, global::System.Collections.Generic.List<global::UnityEngine.Vector4> tangents) { global::Porteo.Falta.Llamada("UnityEngine.CanvasRenderer::AddUIVertexStream"); }
        public void SetVertices(global::System.Collections.Generic.List<global::UnityEngine.UIVertex> vertices) { global::Porteo.Falta.Llamada("UnityEngine.CanvasRenderer::SetVertices"); }
        public void SetVertices(global::UnityEngine.UIVertex[] vertices, int size) { global::Porteo.Falta.Llamada("UnityEngine.CanvasRenderer::SetVertices"); }
    }
}
