// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct CharacterInfo
    {
        public global::UnityEngine.Rect uv;
        public global::UnityEngine.Rect vert;
        public float width;
    }
}
