// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Collision
    {
        public global::UnityEngine.Component other { get { global::Porteo.Falta.Llamada("UnityEngine.Collision::other"); return default; } }
        public virtual global::System.Collections.IEnumerator GetEnumerator() { global::Porteo.Falta.Llamada("UnityEngine.Collision::GetEnumerator"); return default; }
    }
}
