// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)256, Inherited = true, AllowMultiple = false)]
    public sealed partial class ColorUsageAttribute : global::UnityEngine.PropertyAttribute
    {
        public ColorUsageAttribute(bool showAlpha) { global::Porteo.Falta.Llamada("UnityEngine.ColorUsageAttribute::.ctor"); }
        public ColorUsageAttribute(bool showAlpha, bool hdr) { global::Porteo.Falta.Llamada("UnityEngine.ColorUsageAttribute::.ctor"); }
    }
}
