// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Color32
    {
        public byte this[int index] { get { global::Porteo.Falta.Llamada("UnityEngine.Color32::Item"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Color32::Item="); } }
        public static global::UnityEngine.Color32 LerpUnclamped(global::UnityEngine.Color32 a, global::UnityEngine.Color32 b, float t) { global::Porteo.Falta.Llamada("UnityEngine.Color32::LerpUnclamped"); return default; }
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.Color32::ToString"); return default; }
    }
}
