// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Component
    {
        public global::UnityEngine.Component[] GetComponentsInChildren(global::System.Type t) { global::Porteo.Falta.Llamada("UnityEngine.Component::GetComponentsInChildren"); return default; }
        public global::UnityEngine.Component GetComponentInParent(global::System.Type t, bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.Component::GetComponentInParent"); return default; }
        public T GetComponentInParent<T>(bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.Component::GetComponentInParent"); return default; }
        public global::UnityEngine.Component[] GetComponentsInParent(global::System.Type t, bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.Component::GetComponentsInParent"); return default; }
        public global::UnityEngine.Component[] GetComponentsInParent(global::System.Type t) { global::Porteo.Falta.Llamada("UnityEngine.Component::GetComponentsInParent"); return default; }
        public void SendMessageUpwards(string methodName, object value, global::UnityEngine.SendMessageOptions options) { global::Porteo.Falta.Llamada("UnityEngine.Component::SendMessageUpwards"); }
        public void SendMessageUpwards(string methodName, object value) { global::Porteo.Falta.Llamada("UnityEngine.Component::SendMessageUpwards"); }
        public void SendMessageUpwards(string methodName) { global::Porteo.Falta.Llamada("UnityEngine.Component::SendMessageUpwards"); }
        public void BroadcastMessage(string methodName, object parameter) { global::Porteo.Falta.Llamada("UnityEngine.Component::BroadcastMessage"); }
    }
}
