// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ComputeShader : global::UnityEngine.Object
    {
        public int FindKernel(string name) { global::Porteo.Falta.Llamada("UnityEngine.ComputeShader::FindKernel"); return default; }
        public void GetKernelThreadGroupSizes(int kernelIndex, out uint x, out uint y, out uint z) { x = default; y = default; z = default;  global::Porteo.Falta.Llamada("UnityEngine.ComputeShader::GetKernelThreadGroupSizes");  }
    }
}
