// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ComputeBuffer : global::System.IDisposable
    {
        public int count { get { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::count"); return default; } }
        public string name { set { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::name="); } }
        public void Dispose() { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::Dispose"); }
        public ComputeBuffer(int count, int stride) { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::.ctor"); }
        public void Release() { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::Release"); }
        public bool IsValid() { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::IsValid"); return default; }
    }
}
