// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)64, AllowMultiple = true)]
    public sealed partial class ContextMenu : global::System.Attribute
    {
        public ContextMenu(string itemName) { global::Porteo.Falta.Llamada("UnityEngine.ContextMenu::.ctor"); }
    }
}
