// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct ContactPoint
    {
        public global::UnityEngine.Vector3 m_Impulse;
        public global::UnityEngine.Vector3 impulse { get { global::Porteo.Falta.Llamada("UnityEngine.ContactPoint::impulse"); return default; } }
    }
}
