// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Cubemap
    {
        public override bool isReadable { get { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::isReadable"); return default; } }
        public global::UnityEngine.Color[] GetPixels(global::UnityEngine.CubemapFace face, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::GetPixels"); return default; }
        public global::UnityEngine.Color[] GetPixels(global::UnityEngine.CubemapFace face) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::GetPixels"); return default; }
        public void SetPixels(global::UnityEngine.Color[] colors, global::UnityEngine.CubemapFace face, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::SetPixels"); }
        public void SetPixels(global::UnityEngine.Color[] colors, global::UnityEngine.CubemapFace face) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::SetPixels"); }
        public void SetPixel(global::UnityEngine.CubemapFace face, int x, int y, global::UnityEngine.Color color) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::SetPixel"); }
        public void SetPixel(global::UnityEngine.CubemapFace face, int x, int y, global::UnityEngine.Color color, int mip) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::SetPixel"); }
        public global::UnityEngine.Color GetPixel(global::UnityEngine.CubemapFace face, int x, int y) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::GetPixel"); return default; }
        public global::UnityEngine.Color GetPixel(global::UnityEngine.CubemapFace face, int x, int y, int mip) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::GetPixel"); return default; }
        public void Apply(bool updateMipmaps, bool makeNoLongerReadable) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::Apply"); }
        public void Apply(bool updateMipmaps) { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::Apply"); }
        public void Apply() { global::Porteo.Falta.Llamada("UnityEngine.Cubemap::Apply"); }
    }
}
