// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class CullingGroup
    {
        public bool enabled { get { global::Porteo.Falta.Llamada("UnityEngine.CullingGroup::enabled"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.CullingGroup::enabled="); } }
        public static void EraseSwapBack<T>(int index, T[] myArray, ref int size) { global::Porteo.Falta.Llamada("UnityEngine.CullingGroup::EraseSwapBack"); }
    }
}
