// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Debug
    {
        public static void LogFormat(global::UnityEngine.LogType logType, global::UnityEngine.LogOption logOptions, global::UnityEngine.Object context, string format, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.Debug::LogFormat"); }
        public static void LogErrorFormat(global::UnityEngine.Object context, string format, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.Debug::LogErrorFormat"); }
        public static void LogWarningFormat(global::UnityEngine.Object context, string format, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.Debug::LogWarningFormat"); }
        public static void Assert(bool condition, string message, global::UnityEngine.Object context) { global::Porteo.Falta.Llamada("UnityEngine.Debug::Assert"); }
        public static void Assert(bool condition, string format, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.Debug::Assert"); }
    }
}
