// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4)]
    public partial class DefaultExecutionOrder : global::System.Attribute
    {
    }
}
