// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4, Inherited = false)]
    public sealed partial class DisallowMultipleComponent : global::System.Attribute
    {
        public DisallowMultipleComponent() { global::Porteo.Falta.Llamada("UnityEngine.DisallowMultipleComponent::.ctor"); }
    }
}
