// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Display
    {
        public global::UnityEngine.RenderBuffer colorBuffer { get { global::Porteo.Falta.Llamada("UnityEngine.Display::colorBuffer"); return default; } }
        public global::UnityEngine.RenderBuffer depthBuffer { get { global::Porteo.Falta.Llamada("UnityEngine.Display::depthBuffer"); return default; } }
        public void Activate(int width, int height, global::UnityEngine.RefreshRate refreshRate) { global::Porteo.Falta.Llamada("UnityEngine.Display::Activate"); }
        public void Activate(int width, int height, int refreshRate) { global::Porteo.Falta.Llamada("UnityEngine.Display::Activate"); }
    }
}
