// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct DrivenRectTransformTracker
    {
        public void Clear(bool revertValues) { global::Porteo.Falta.Llamada("UnityEngine.DrivenRectTransformTracker::Clear"); }
    }
}
