// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Event
    {
        public global::UnityEngine.Vector2 delta { get { global::Porteo.Falta.Llamada("UnityEngine.Event::delta"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Event::delta="); } }
        public int button { get { global::Porteo.Falta.Llamada("UnityEngine.Event::button"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Event::button="); } }
        public float pressure { get { global::Porteo.Falta.Llamada("UnityEngine.Event::pressure"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Event::pressure="); } }
        public static global::UnityEngine.Event current { get { global::Porteo.Falta.Llamada("UnityEngine.Event::current"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Event::current="); } }
        public override int GetHashCode() { global::Porteo.Falta.Llamada("UnityEngine.Event::GetHashCode"); return default; }
        public override bool Equals(object obj) { global::Porteo.Falta.Llamada("UnityEngine.Event::Equals"); return default; }
        public override string ToString() { global::Porteo.Falta.Llamada("UnityEngine.Event::ToString"); return default; }
    }
}
