// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4, Inherited = false)]
    public partial class ExcludeFromPresetAttribute : global::System.Attribute
    {
        public ExcludeFromPresetAttribute() { global::Porteo.Falta.Llamada("UnityEngine.ExcludeFromPresetAttribute::.ctor"); }
    }
}
