// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ExecuteAlways : global::System.Attribute
    {
        public ExecuteAlways() { global::Porteo.Falta.Llamada("UnityEngine.ExecuteAlways::.ctor"); }
    }
}
