// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct ExposedReference<T> where T : global::UnityEngine.Object
    {
        public global::UnityEngine.PropertyName exposedName;
        public global::UnityEngine.Object defaultValue;
        public T Resolve(global::UnityEngine.IExposedPropertyTable resolver) { global::Porteo.Falta.Llamada("UnityEngine.ExposedReference`1::Resolve"); return default; }
    }
}
