// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum FogMode : int
    {
        Linear = 1,
        Exponential = 2,
        ExponentialSquared = 3,
    }
}
