// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GameObject
    {
        public bool active { get { global::Porteo.Falta.Llamada("UnityEngine.GameObject::active"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.GameObject::active="); } }
        public global::UnityEngine.Component GetComponentInParent(global::System.Type type, bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::GetComponentInParent"); return default; }
        public T GetComponentInParent<T>(bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::GetComponentInParent"); return default; }
        public global::UnityEngine.Component[] GetComponentsInChildren(global::System.Type type) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::GetComponentsInChildren"); return default; }
        public global::UnityEngine.Component[] GetComponentsInParent(global::System.Type type) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::GetComponentsInParent"); return default; }
        public global::UnityEngine.Component[] GetComponentsInParent(global::System.Type type, bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::GetComponentsInParent"); return default; }
        public bool TryGetComponent<T>(out T component) { component = default;  global::Porteo.Falta.Llamada("UnityEngine.GameObject::TryGetComponent"); return default;  }
        public void SendMessageUpwards(string methodName, object value, global::UnityEngine.SendMessageOptions options) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::SendMessageUpwards"); }
        public void SendMessageUpwards(string methodName, object value) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::SendMessageUpwards"); }
        public void SendMessageUpwards(string methodName) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::SendMessageUpwards"); }
        public void BroadcastMessage(string methodName, object parameter) { global::Porteo.Falta.Llamada("UnityEngine.GameObject::BroadcastMessage"); }
    }
}
