// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Gizmos
    {
        public static global::UnityEngine.Matrix4x4 matrix { set { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::matrix="); } }
        public static void DrawWireSphere(global::UnityEngine.Vector3 center, float radius) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawWireSphere"); }
        public static void DrawSphere(global::UnityEngine.Vector3 center, float radius) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawSphere"); }
        public static void DrawWireCube(global::UnityEngine.Vector3 center, global::UnityEngine.Vector3 size) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawWireCube"); }
        public static void DrawCube(global::UnityEngine.Vector3 center, global::UnityEngine.Vector3 size) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawCube"); }
        public static void DrawMesh(global::UnityEngine.Mesh mesh) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawMesh"); }
        public static void DrawWireMesh(global::UnityEngine.Mesh mesh, global::UnityEngine.Vector3 position, global::UnityEngine.Quaternion rotation, global::UnityEngine.Vector3 scale) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawWireMesh"); }
    }
}
