// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GL
    {
        public static global::UnityEngine.Matrix4x4 GetGPUProjectionMatrix(global::UnityEngine.Matrix4x4 proj, bool renderIntoTexture) { global::Porteo.Falta.Llamada("UnityEngine.GL::GetGPUProjectionMatrix"); return default; }
    }
}
