// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct GraphicsBufferHandle : global::System.IEquatable<global::UnityEngine.GraphicsBufferHandle>
    {
        public uint value;
        public bool Equals(global::UnityEngine.GraphicsBufferHandle other) { global::Porteo.Falta.Llamada("UnityEngine.GraphicsBufferHandle::Equals"); return default; }
    }
}
