// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GraphicsBuffer : global::System.IDisposable
    {
        public void Dispose() { global::Porteo.Falta.Llamada("UnityEngine.GraphicsBuffer::Dispose"); }
        [System.Flags]
        public enum Target : int
        {
            Vertex = 1,
            Index = 2,
            CopySource = 4,
            CopyDestination = 8,
            Structured = 16,
            Raw = 32,
            Append = 64,
            Counter = 128,
            IndirectArguments = 256,
            Constant = 512,
        }
    }
}
