// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class GUI
    {
        public static void DrawTexture(global::UnityEngine.Rect position, global::UnityEngine.Texture image) { global::Porteo.Falta.Llamada("UnityEngine.GUI::DrawTexture"); }
    }
}
