// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4, AllowMultiple = false)]
    public partial class HelpURLAttribute : global::System.Attribute
    {
        public HelpURLAttribute(string url) { global::Porteo.Falta.Llamada("UnityEngine.HelpURLAttribute::.ctor"); }
    }
}
