// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class HingeJoint
    {
        public global::UnityEngine.JointSpring spring { get { global::Porteo.Falta.Llamada("UnityEngine.HingeJoint::spring"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.HingeJoint::spring="); } }
        public float velocity { get { global::Porteo.Falta.Llamada("UnityEngine.HingeJoint::velocity"); return default; } }
        public float angle { get { global::Porteo.Falta.Llamada("UnityEngine.HingeJoint::angle"); return default; } }
    }
}
