// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum HorizontalWrapMode : int
    {
        Wrap = 0,
        Overflow = 1,
    }
}
