// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct HumanBone
    {
        public string m_BoneName;
        public string m_HumanName;
        public global::UnityEngine.HumanLimit limit;
    }
}
