// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct HumanDescription
    {
        public global::UnityEngine.HumanBone[] human;
        public global::UnityEngine.SkeletonBone[] skeleton;
        public float m_ArmTwist;
        public float m_ForeArmTwist;
        public float m_UpperLegTwist;
        public float m_LegTwist;
        public float m_ArmStretch;
        public float m_LegStretch;
        public float m_FeetSpacing;
        public float m_GlobalScale;
        public string m_RootMotionBoneName;
        public bool m_HasTranslationDoF;
        public bool m_HasExtraRoot;
        public bool m_SkeletonHasParents;
    }
}
