// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial interface IExposedPropertyTable
    {
        void SetReferenceValue(global::UnityEngine.PropertyName id, global::UnityEngine.Object value);
        global::UnityEngine.Object GetReferenceValue(global::UnityEngine.PropertyName id, out bool idValid);
        void ClearReferenceValue(global::UnityEngine.PropertyName id);
    }
}
