// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)64)]
    public sealed partial class ImageEffectUsesCommandBuffer : global::System.Attribute
    {
        public ImageEffectUsesCommandBuffer() { global::Porteo.Falta.Llamada("UnityEngine.ImageEffectUsesCommandBuffer::.ctor"); }
    }
}
