// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct JointSpring
    {
        public float spring;
        public float damper;
        public float targetPosition;
    }
}
