// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class LensFlare
    {
        public global::UnityEngine.Color color { get { global::Porteo.Falta.Llamada("UnityEngine.LensFlare::color"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.LensFlare::color="); } }
        public global::UnityEngine.Flare flare { get { global::Porteo.Falta.Llamada("UnityEngine.LensFlare::flare"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.LensFlare::flare="); } }
    }
}
