// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Light
    {
        public static int pixelLightCount { get { global::Porteo.Falta.Llamada("UnityEngine.Light::pixelLightCount"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Light::pixelLightCount="); } }
        public void Reset() { global::Porteo.Falta.Llamada("UnityEngine.Light::Reset"); }
    }
}
