// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct LightBakingOutput
    {
        public int probeOcclusionLightIndex;
        public int occlusionMaskChannel;
        public global::UnityEngine.LightmapBakeType lightmapBakeType;
        public global::UnityEngine.MixedLightingMode mixedLightingMode;
        public bool isBaked;
    }
}
