// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class LightProbes
    {
        public global::UnityEngine.Vector3[] positions { get { global::Porteo.Falta.Llamada("UnityEngine.LightProbes::positions"); return default; } }
        public int count { get { global::Porteo.Falta.Llamada("UnityEngine.LightProbes::count"); return default; } }
    }
}
