// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Material
    {
        public static global::UnityEngine.Material Create(string scriptContents) { global::Porteo.Falta.Llamada("UnityEngine.Material::Create"); return default; }
        public void EnableKeyword(in global::UnityEngine.Rendering.LocalKeyword keyword) { global::Porteo.Falta.Llamada("UnityEngine.Material::EnableKeyword"); }
        public void DisableKeyword(in global::UnityEngine.Rendering.LocalKeyword keyword) { global::Porteo.Falta.Llamada("UnityEngine.Material::DisableKeyword"); }
        public bool IsKeywordEnabled(in global::UnityEngine.Rendering.LocalKeyword keyword) { global::Porteo.Falta.Llamada("UnityEngine.Material::IsKeywordEnabled"); return default; }
        public int ComputeCRC() { global::Porteo.Falta.Llamada("UnityEngine.Material::ComputeCRC"); return default; }
        public void SetInteger(string name, int value) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetInteger"); }
        public void SetInteger(int nameID, int value) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetInteger"); }
        public void SetTexture(string name, global::UnityEngine.RenderTexture value, global::UnityEngine.Rendering.RenderTextureSubElement element) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetTexture"); }
        public void SetTexture(int nameID, global::UnityEngine.RenderTexture value, global::UnityEngine.Rendering.RenderTextureSubElement element) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetTexture"); }
        public void SetBuffer(int nameID, global::UnityEngine.ComputeBuffer value) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetBuffer"); }
        public void SetBuffer(string name, global::UnityEngine.GraphicsBuffer value) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetBuffer"); }
        public void SetBuffer(int nameID, global::UnityEngine.GraphicsBuffer value) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetBuffer"); }
        public void SetFloatArray(string name, global::System.Collections.Generic.List<float> values) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetFloatArray"); }
        public void SetFloatArray(int nameID, global::System.Collections.Generic.List<float> values) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetFloatArray"); }
        public void SetVectorArray(string name, global::System.Collections.Generic.List<global::UnityEngine.Vector4> values) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetVectorArray"); }
        public void SetVectorArray(int nameID, global::System.Collections.Generic.List<global::UnityEngine.Vector4> values) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetVectorArray"); }
        public int GetInteger(string name) { global::Porteo.Falta.Llamada("UnityEngine.Material::GetInteger"); return default; }
        public int GetInteger(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Material::GetInteger"); return default; }
        public global::UnityEngine.Matrix4x4 GetMatrix(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Material::GetMatrix"); return default; }
        public void SetTextureOffset(int nameID, global::UnityEngine.Vector2 value) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetTextureOffset"); }
        public void SetTextureScale(int nameID, global::UnityEngine.Vector2 value) { global::Porteo.Falta.Llamada("UnityEngine.Material::SetTextureScale"); }
        public global::UnityEngine.Vector2 GetTextureOffset(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Material::GetTextureOffset"); return default; }
        public global::UnityEngine.Vector2 GetTextureScale(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Material::GetTextureScale"); return default; }
    }
}
