// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class MaterialPropertyBlock
    {
        public void SetInt(int nameID, int value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetInt"); }
        public void SetInteger(string name, int value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetInteger"); }
        public void SetInteger(int nameID, int value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetInteger"); }
        public void SetMatrix(int nameID, global::UnityEngine.Matrix4x4 value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetMatrix"); }
        public void SetBuffer(string name, global::UnityEngine.ComputeBuffer value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetBuffer"); }
        public void SetBuffer(int nameID, global::UnityEngine.ComputeBuffer value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetBuffer"); }
        public void SetBuffer(string name, global::UnityEngine.GraphicsBuffer value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetBuffer"); }
        public void SetBuffer(int nameID, global::UnityEngine.GraphicsBuffer value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetBuffer"); }
        public void SetTexture(string name, global::UnityEngine.RenderTexture value, global::UnityEngine.Rendering.RenderTextureSubElement element) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetTexture"); }
        public void SetTexture(int nameID, global::UnityEngine.RenderTexture value, global::UnityEngine.Rendering.RenderTextureSubElement element) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetTexture"); }
        public void SetFloatArray(string name, global::System.Collections.Generic.List<float> values) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetFloatArray"); }
        public void SetFloatArray(int nameID, global::System.Collections.Generic.List<float> values) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetFloatArray"); }
        public void SetFloatArray(int nameID, float[] values) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetFloatArray"); }
        public void SetVectorArray(string name, global::System.Collections.Generic.List<global::UnityEngine.Vector4> values) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetVectorArray"); }
        public void SetVectorArray(int nameID, global::System.Collections.Generic.List<global::UnityEngine.Vector4> values) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetVectorArray"); }
        public void SetVectorArray(int nameID, global::UnityEngine.Vector4[] values) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetVectorArray"); }
        public bool HasProperty(string name) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::HasProperty"); return default; }
        public bool HasProperty(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::HasProperty"); return default; }
        public int GetInt(string name) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetInt"); return default; }
        public int GetInt(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetInt"); return default; }
        public int GetInteger(string name) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetInteger"); return default; }
        public int GetInteger(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetInteger"); return default; }
        public global::UnityEngine.Vector4 GetVector(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetVector"); return default; }
        public global::UnityEngine.Color GetColor(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetColor"); return default; }
        public global::UnityEngine.Matrix4x4 GetMatrix(string name) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetMatrix"); return default; }
        public global::UnityEngine.Matrix4x4 GetMatrix(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetMatrix"); return default; }
        public global::UnityEngine.Texture GetTexture(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::GetTexture"); return default; }
    }
}
