// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Mathf
    {
        public static float SmoothDampAngle(float current, float target, ref float currentVelocity, float smoothTime, float maxSpeed) { global::Porteo.Falta.Llamada("UnityEngine.Mathf::SmoothDampAngle"); return default; }
    }
}
