// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Matrix4x4
    {
        public global::UnityEngine.FrustumPlanes decomposeProjection { get { global::Porteo.Falta.Llamada("UnityEngine.Matrix4x4::decomposeProjection"); return default; } }
        public static global::UnityEngine.Matrix4x4 Frustum(global::UnityEngine.FrustumPlanes fp) { global::Porteo.Falta.Llamada("UnityEngine.Matrix4x4::Frustum"); return default; }
    }
}
