// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Mesh
    {
        public void SetVertices(global::System.Collections.Generic.List<global::UnityEngine.Vector3> inVertices, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetVertices(global::System.Collections.Generic.List<global::UnityEngine.Vector3> inVertices, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetVertices(global::UnityEngine.Vector3[] inVertices) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetVertices(global::UnityEngine.Vector3[] inVertices, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetVertices(global::UnityEngine.Vector3[] inVertices, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetVertices<T>(global::Unity.Collections.NativeArray<T> inVertices) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetVertices<T>(global::Unity.Collections.NativeArray<T> inVertices, int start, int length) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetVertices<T>(global::Unity.Collections.NativeArray<T> inVertices, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetVertices"); }
        public void SetNormals(global::System.Collections.Generic.List<global::UnityEngine.Vector3> inNormals, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetNormals(global::System.Collections.Generic.List<global::UnityEngine.Vector3> inNormals, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetNormals(global::UnityEngine.Vector3[] inNormals) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetNormals(global::UnityEngine.Vector3[] inNormals, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetNormals(global::UnityEngine.Vector3[] inNormals, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetNormals<T>(global::Unity.Collections.NativeArray<T> inNormals) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetNormals<T>(global::Unity.Collections.NativeArray<T> inNormals, int start, int length) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetNormals<T>(global::Unity.Collections.NativeArray<T> inNormals, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetNormals"); }
        public void SetTangents(global::System.Collections.Generic.List<global::UnityEngine.Vector4> inTangents, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetTangents(global::System.Collections.Generic.List<global::UnityEngine.Vector4> inTangents, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetTangents(global::UnityEngine.Vector4[] inTangents) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetTangents(global::UnityEngine.Vector4[] inTangents, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetTangents(global::UnityEngine.Vector4[] inTangents, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetTangents<T>(global::Unity.Collections.NativeArray<T> inTangents) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetTangents<T>(global::Unity.Collections.NativeArray<T> inTangents, int start, int length) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetTangents<T>(global::Unity.Collections.NativeArray<T> inTangents, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTangents"); }
        public void SetColors(global::System.Collections.Generic.List<global::UnityEngine.Color> inColors, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::System.Collections.Generic.List<global::UnityEngine.Color> inColors, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::UnityEngine.Color[] inColors) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::UnityEngine.Color[] inColors, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::UnityEngine.Color[] inColors, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::System.Collections.Generic.List<global::UnityEngine.Color32> inColors, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::System.Collections.Generic.List<global::UnityEngine.Color32> inColors, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::UnityEngine.Color32[] inColors) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::UnityEngine.Color32[] inColors, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors(global::UnityEngine.Color32[] inColors, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors<T>(global::Unity.Collections.NativeArray<T> inColors) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors<T>(global::Unity.Collections.NativeArray<T> inColors, int start, int length) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetColors<T>(global::Unity.Collections.NativeArray<T> inColors, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetColors"); }
        public void SetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector3> uvs) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector2> uvs, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector2> uvs, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector3> uvs, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector3> uvs, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector4> uvs, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector4> uvs, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector2[] uvs) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector3[] uvs) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector4[] uvs) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector2[] uvs, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector2[] uvs, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector3[] uvs, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector3[] uvs, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector4[] uvs, int start, int length) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs(int channel, global::UnityEngine.Vector4[] uvs, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs<T>(int channel, global::Unity.Collections.NativeArray<T> uvs) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs<T>(int channel, global::Unity.Collections.NativeArray<T> uvs, int start, int length) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void SetUVs<T>(int channel, global::Unity.Collections.NativeArray<T> uvs, int start, int length, global::UnityEngine.Rendering.MeshUpdateFlags flags) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetUVs"); }
        public void GetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector3> uvs) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetUVs"); }
        public void GetUVs(int channel, global::System.Collections.Generic.List<global::UnityEngine.Vector4> uvs) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetUVs"); }
        public int[] GetTriangles(int submesh, bool applyBaseVertex) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetTriangles"); return default; }
        public void GetTriangles(global::System.Collections.Generic.List<int> triangles, int submesh) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetTriangles"); }
        public void GetTriangles(global::System.Collections.Generic.List<int> triangles, int submesh, bool applyBaseVertex) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetTriangles"); }
        public void GetTriangles(global::System.Collections.Generic.List<ushort> triangles, int submesh, bool applyBaseVertex = true) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetTriangles"); }
        public int[] GetIndices(int submesh, bool applyBaseVertex) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetIndices"); return default; }
        public void GetIndices(global::System.Collections.Generic.List<int> indices, int submesh) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetIndices"); }
        public void GetIndices(global::System.Collections.Generic.List<int> indices, int submesh, bool applyBaseVertex) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetIndices"); }
        public void GetIndices(global::System.Collections.Generic.List<ushort> indices, int submesh, bool applyBaseVertex = true) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::GetIndices"); }
        public void SetTriangles(int[] triangles, int submesh, bool calculateBounds) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(int[] triangles, int submesh, bool calculateBounds, int baseVertex) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(int[] triangles, int trianglesStart, int trianglesLength, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(ushort[] triangles, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(ushort[] triangles, int trianglesStart, int trianglesLength, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(global::System.Collections.Generic.List<int> triangles, int submesh, bool calculateBounds) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(global::System.Collections.Generic.List<int> triangles, int submesh, bool calculateBounds, int baseVertex) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(global::System.Collections.Generic.List<int> triangles, int trianglesStart, int trianglesLength, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(global::System.Collections.Generic.List<ushort> triangles, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetTriangles(global::System.Collections.Generic.List<ushort> triangles, int trianglesStart, int trianglesLength, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetTriangles"); }
        public void SetIndices(int[] indices, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds, int baseVertex) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices(int[] indices, int indicesStart, int indicesLength, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices(ushort[] indices, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices(ushort[] indices, int indicesStart, int indicesLength, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices<T>(global::Unity.Collections.NativeArray<T> indices, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices<T>(global::Unity.Collections.NativeArray<T> indices, int indicesStart, int indicesLength, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices(global::System.Collections.Generic.List<int> indices, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices(global::System.Collections.Generic.List<int> indices, int indicesStart, int indicesLength, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices(global::System.Collections.Generic.List<ushort> indices, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void SetIndices(global::System.Collections.Generic.List<ushort> indices, int indicesStart, int indicesLength, global::UnityEngine.MeshTopology topology, int submesh, bool calculateBounds = true, int baseVertex = 0) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::SetIndices"); }
        public void RecalculateBounds(global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::RecalculateBounds"); }
        public void RecalculateNormals(global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::RecalculateNormals"); }
        public void RecalculateTangents(global::UnityEngine.Rendering.MeshUpdateFlags flags) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::RecalculateTangents"); }
        public void CombineMeshes(global::UnityEngine.CombineInstance[] combine, bool mergeSubMeshes, bool useMatrices, bool hasLightmapData) { global::Porteo.Falta.Llamada("UnityEngine.Mesh::CombineMeshes"); }
    }
}
