// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class MeshCollider
    {
        public float skinWidth { get { global::Porteo.Falta.Llamada("UnityEngine.MeshCollider::skinWidth"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.MeshCollider::skinWidth="); } }
    }
}
