// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum MixedLightingMode : int
    {
        IndirectOnly = 0,
        Shadowmask = 2,
        Subtractive = 1,
    }
}
