// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct ModifiableContactPatch
    {
        public global::UnityEngine.ModifiableMassProperties massProperties;
        public global::UnityEngine.Vector3 normal;
        public float restitution;
        public float dynamicFriction;
        public float staticFriction;
        public byte startContactIndex;
        public byte contactCount;
        public byte materialFlags;
        public byte internalFlags;
        public ushort materialIndex;
        public ushort otherMaterialIndex;
        public enum Flags : int
        {
            HasFaceIndices = 1,
            HasModifiedMassRatios = 8,
            HasTargetVelocity = 16,
            HasMaxImpulse = 32,
            RegeneratePatches = 64,
        }
    }
}
