// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct ModifiableMassProperties
    {
        public float inverseMassScale;
        public float inverseInertiaScale;
        public float otherInverseMassScale;
        public float otherInverseInertiaScale;
    }
}
