// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Motion : global::UnityEngine.Object
    {
        public bool isLooping { get { global::Porteo.Falta.Llamada("UnityEngine.Motion::isLooping"); return default; } }
        public bool legacy { get { global::Porteo.Falta.Llamada("UnityEngine.Motion::legacy"); return default; } }
    }
}
