// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Object
    {
        public static global::UnityEngine.Object[] FindObjectsOfType(global::System.Type type, bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.Object::FindObjectsOfType"); return default; }
        public static T[] FindObjectsOfType<T>(bool includeInactive) where T : global::UnityEngine.Object { global::Porteo.Falta.Llamada("UnityEngine.Object::FindObjectsOfType"); return default; }
        public static T FindObjectOfType<T>(bool includeInactive) where T : global::UnityEngine.Object { global::Porteo.Falta.Llamada("UnityEngine.Object::FindObjectOfType"); return default; }
        public static global::UnityEngine.Object[] FindObjectsOfTypeAll(global::System.Type type) { global::Porteo.Falta.Llamada("UnityEngine.Object::FindObjectsOfTypeAll"); return default; }
        public static global::UnityEngine.Object FindObjectOfType(global::System.Type type, bool includeInactive) { global::Porteo.Falta.Llamada("UnityEngine.Object::FindObjectOfType"); return default; }
    }
}
