// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum OperatingSystemFamily : int
    {
        Other = 0,
        MacOSX = 1,
        Windows = 2,
        Linux = 3,
    }
}
