// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ParticleSystemRenderer
    {
        public float shadowBias { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystemRenderer::shadowBias"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystemRenderer::shadowBias="); } }
        public global::UnityEngine.Vector3 flip { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystemRenderer::flip"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystemRenderer::flip="); } }
        public void BakeMesh(global::UnityEngine.Mesh mesh, bool useTransform = false) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystemRenderer::BakeMesh"); }
        public void BakeMesh(global::UnityEngine.Mesh mesh, global::UnityEngine.Camera camera, bool useTransform = false) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystemRenderer::BakeMesh"); }
    }
}
