// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ParticleSystem
    {
        public float startDelay { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startDelay"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startDelay="); } }
        public bool loop { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::loop"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::loop="); } }
        public bool playOnAwake { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::playOnAwake"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::playOnAwake="); } }
        public float duration { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::duration"); return default; } }
        public float startSpeed { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startSpeed"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startSpeed="); } }
        public float startSize { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startSize"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startSize="); } }
        public global::UnityEngine.Color startColor { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startColor"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startColor="); } }
        public float startRotation { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startRotation"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startRotation="); } }
        public float startLifetime { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startLifetime"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::startLifetime="); } }
        public float gravityModifier { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::gravityModifier"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::gravityModifier="); } }
        public int maxParticles { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::maxParticles"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::maxParticles="); } }
        public global::UnityEngine.ParticleSystemSimulationSpace simulationSpace { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::simulationSpace"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::simulationSpace="); } }
        public global::UnityEngine.ParticleSystem.TriggerModule trigger { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::trigger"); return default; } }
        public global::UnityEngine.ParticleSystem.SubEmittersModule subEmitters { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::subEmitters"); return default; } }
        public void Emit(global::UnityEngine.Vector3 position, global::UnityEngine.Vector3 velocity, float size, float lifetime, global::UnityEngine.Color32 color) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Emit"); }
        public void Emit(global::UnityEngine.ParticleSystem.Particle particle) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Emit"); }
        public void SetParticles(global::UnityEngine.ParticleSystem.Particle[] particles, int size, int offset) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::SetParticles"); }
        public void SetParticles(global::Unity.Collections.NativeArray<global::UnityEngine.ParticleSystem.Particle> particles, int size, int offset) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::SetParticles"); }
        public void SetParticles(global::Unity.Collections.NativeArray<global::UnityEngine.ParticleSystem.Particle> particles, int size) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::SetParticles"); }
        public void SetParticles(global::Unity.Collections.NativeArray<global::UnityEngine.ParticleSystem.Particle> particles) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::SetParticles"); }
        public int GetParticles(global::UnityEngine.ParticleSystem.Particle[] particles, int size, int offset) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::GetParticles"); return default; }
        public int GetParticles(global::Unity.Collections.NativeArray<global::UnityEngine.ParticleSystem.Particle> particles, int size, int offset) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::GetParticles"); return default; }
        public int GetParticles(global::Unity.Collections.NativeArray<global::UnityEngine.ParticleSystem.Particle> particles, int size) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::GetParticles"); return default; }
        public int GetParticles(global::Unity.Collections.NativeArray<global::UnityEngine.ParticleSystem.Particle> particles) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::GetParticles"); return default; }
        public void Emit(global::UnityEngine.ParticleSystem.EmitParams emitParams, int count) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Emit"); }
        public partial struct EmissionModule
        {
            public global::UnityEngine.ParticleSystemEmissionType type { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/EmissionModule::type"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/EmissionModule::type="); } }
        }
        public partial struct EmitParams
        {
            public global::UnityEngine.ParticleSystem.Particle m_Particle;
            public bool m_PositionSet;
            public bool m_VelocitySet;
            public bool m_AxisOfRotationSet;
            public bool m_RotationSet;
            public bool m_AngularVelocitySet;
            public bool m_StartSizeSet;
            public bool m_StartColorSet;
            public bool m_RandomSeedSet;
            public bool m_StartLifetimeSet;
            public bool m_MeshIndexSet;
            public bool m_ApplyShapeToPosition;
        }
        public partial struct MainModule
        {
            public bool startSize3D { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::startSize3D"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::startSize3D="); } }
            public global::UnityEngine.ParticleSystemCullingMode cullingMode { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::cullingMode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::cullingMode="); } }
        }
        public partial struct MinMaxCurve
        {
        }
        public partial struct MinMaxGradient
        {
        }
        public partial struct Particle
        {
            public uint m_ParentRandomSeed;
            public int m_MeshIndex;
            public float size { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::size"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::size="); } }
            public global::UnityEngine.Color32 color { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::color"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::color="); } }
        }
        public partial struct SubEmittersModule
        {
            public global::UnityEngine.ParticleSystem m_ParticleSystem;
            public int subEmittersCount { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/SubEmittersModule::subEmittersCount"); return default; } }
            public global::UnityEngine.ParticleSystem GetSubEmitterSystem(int index) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/SubEmittersModule::GetSubEmitterSystem"); return default; }
        }
        public partial struct TextureSheetAnimationModule
        {
            public global::UnityEngine.ParticleSystemAnimationMode mode { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::mode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::mode="); } }
            public global::UnityEngine.ParticleSystemAnimationType animation { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::animation"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::animation="); } }
        }
        public partial struct TriggerModule
        {
            public global::UnityEngine.ParticleSystem m_ParticleSystem;
        }
    }
}
