// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Plane
    {
        public global::UnityEngine.Plane flipped { get { global::Porteo.Falta.Llamada("UnityEngine.Plane::flipped"); return default; } }
        public void Translate(global::UnityEngine.Vector3 translation) { global::Porteo.Falta.Llamada("UnityEngine.Plane::Translate"); }
        public static global::UnityEngine.Plane Translate(global::UnityEngine.Plane plane, global::UnityEngine.Vector3 translation) { global::Porteo.Falta.Llamada("UnityEngine.Plane::Translate"); return default; }
        public override string ToString() { global::Porteo.Falta.Llamada("UnityEngine.Plane::ToString"); return default; }
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.Plane::ToString"); return default; }
        public string ToString(string format, global::System.IFormatProvider formatProvider) { global::Porteo.Falta.Llamada("UnityEngine.Plane::ToString"); return default; }
    }
}
