// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class PlayerPrefs
    {
        public static void SetInt(string key, int value) { global::Porteo.Falta.Llamada("UnityEngine.PlayerPrefs::SetInt"); }
        public static int GetInt(string key, int defaultValue) { global::Porteo.Falta.Llamada("UnityEngine.PlayerPrefs::GetInt"); return default; }
        public static int GetInt(string key) { global::Porteo.Falta.Llamada("UnityEngine.PlayerPrefs::GetInt"); return default; }
        public static void SetFloat(string key, float value) { global::Porteo.Falta.Llamada("UnityEngine.PlayerPrefs::SetFloat"); }
        public static float GetFloat(string key, float defaultValue) { global::Porteo.Falta.Llamada("UnityEngine.PlayerPrefs::GetFloat"); return default; }
    }
}
