// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)256, Inherited = true, AllowMultiple = false)]
    public abstract partial class PropertyAttribute : global::System.Attribute
    {
        protected PropertyAttribute() { }
    }
}
