// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct PropertyName : global::System.IEquatable<global::UnityEngine.PropertyName>
    {
        public int id;
        public PropertyName(string name) { this = default; }
        public bool Equals(global::UnityEngine.PropertyName other) { global::Porteo.Falta.Llamada("UnityEngine.PropertyName::Equals"); return default; }
    }
}
