// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class QualitySettings
    {
        public static int count { get { global::Porteo.Falta.Llamada("UnityEngine.QualitySettings::count"); return default; } }
        public static void IncreaseLevel() { global::Porteo.Falta.Llamada("UnityEngine.QualitySettings::IncreaseLevel"); }
        public static void DecreaseLevel() { global::Porteo.Falta.Llamada("UnityEngine.QualitySettings::DecreaseLevel"); }
    }
}
