// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum QueryTriggerInteraction : int
    {
        UseGlobal = 0,
        Ignore = 1,
        Collide = 2,
    }
}
