// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct RectInt : global::System.IEquatable<global::UnityEngine.RectInt>, global::System.IFormattable
    {
        public int m_XMin;
        public int m_YMin;
        public int m_Width;
        public int m_Height;
        public int x { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::x"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::x="); } }
        public int y { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::y"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::y="); } }
        public global::UnityEngine.Vector2 center { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::center"); return default; } }
        public global::UnityEngine.Vector2Int min { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::min"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::min="); } }
        public global::UnityEngine.Vector2Int max { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::max"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::max="); } }
        public int width { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::width"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::width="); } }
        public int height { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::height"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::height="); } }
        public int xMin { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::xMin"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::xMin="); } }
        public int yMin { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::yMin"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::yMin="); } }
        public int xMax { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::xMax"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::xMax="); } }
        public int yMax { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::yMax"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::yMax="); } }
        public global::UnityEngine.Vector2Int position { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::position"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::position="); } }
        public global::UnityEngine.Vector2Int size { get { global::Porteo.Falta.Llamada("UnityEngine.RectInt::size"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RectInt::size="); } }
        public void SetMinMax(global::UnityEngine.Vector2Int minPosition, global::UnityEngine.Vector2Int maxPosition) { global::Porteo.Falta.Llamada("UnityEngine.RectInt::SetMinMax"); }
        public bool Contains(global::UnityEngine.Vector2Int position) { global::Porteo.Falta.Llamada("UnityEngine.RectInt::Contains"); return default; }
        public bool Overlaps(global::UnityEngine.RectInt other) { global::Porteo.Falta.Llamada("UnityEngine.RectInt::Overlaps"); return default; }
        public override string ToString() { global::Porteo.Falta.Llamada("UnityEngine.RectInt::ToString"); return default; }
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.RectInt::ToString"); return default; }
        public string ToString(string format, global::System.IFormatProvider formatProvider) { global::Porteo.Falta.Llamada("UnityEngine.RectInt::ToString"); return default; }
        public bool Equals(global::UnityEngine.RectInt other) { global::Porteo.Falta.Llamada("UnityEngine.RectInt::Equals"); return default; }
    }
}
