// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class RectTransformUtility
    {
        public static bool RectangleContainsScreenPoint(global::UnityEngine.RectTransform rect, global::UnityEngine.Vector2 screenPoint, global::UnityEngine.Camera cam, global::UnityEngine.Vector4 offset) { global::Porteo.Falta.Llamada("UnityEngine.RectTransformUtility::RectangleContainsScreenPoint"); return default; }
    }
}
