// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Rect
    {
        public float left { get { global::Porteo.Falta.Llamada("UnityEngine.Rect::left"); return default; } }
        public float right { get { global::Porteo.Falta.Llamada("UnityEngine.Rect::right"); return default; } }
        public float top { get { global::Porteo.Falta.Llamada("UnityEngine.Rect::top"); return default; } }
        public float bottom { get { global::Porteo.Falta.Llamada("UnityEngine.Rect::bottom"); return default; } }
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.Rect::ToString"); return default; }
        public string ToString(string format, global::System.IFormatProvider formatProvider) { global::Porteo.Falta.Llamada("UnityEngine.Rect::ToString"); return default; }
    }
}
