// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ReflectionProbe
    {
        public global::UnityEngine.Rendering.ReflectionProbeType type { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::type"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::type="); } }
        public global::UnityEngine.Vector3 size { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::size"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::size="); } }
        public global::UnityEngine.Vector3 center { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::center"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::center="); } }
        public float nearClipPlane { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::nearClipPlane"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::nearClipPlane="); } }
        public float farClipPlane { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::farClipPlane"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::farClipPlane="); } }
        public float intensity { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::intensity"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::intensity="); } }
        public global::UnityEngine.Bounds bounds { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::bounds"); return default; } }
        public bool hdr { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::hdr"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::hdr="); } }
        public float shadowDistance { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::shadowDistance"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::shadowDistance="); } }
        public int cullingMask { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::cullingMask"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::cullingMask="); } }
        public global::UnityEngine.Rendering.ReflectionProbeClearFlags clearFlags { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::clearFlags"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::clearFlags="); } }
        public global::UnityEngine.Color backgroundColor { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::backgroundColor"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::backgroundColor="); } }
        public global::UnityEngine.Rendering.ReflectionProbeMode mode { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::mode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::mode="); } }
        public global::UnityEngine.Texture texture { get { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::texture"); return default; } }
        public void Reset() { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::Reset"); }
    }
}
