// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct RefreshRate : global::System.IEquatable<global::UnityEngine.RefreshRate>, global::System.IComparable<global::UnityEngine.RefreshRate>
    {
        public uint numerator;
        public uint denominator;
        public bool Equals(global::UnityEngine.RefreshRate other) { global::Porteo.Falta.Llamada("UnityEngine.RefreshRate::Equals"); return default; }
        public int CompareTo(global::UnityEngine.RefreshRate other) { global::Porteo.Falta.Llamada("UnityEngine.RefreshRate::CompareTo"); return default; }
    }
}
