// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct RenderTextureDescriptor
    {
        public global::UnityEngine.Experimental.Rendering.GraphicsFormat _graphicsFormat;
        public global::UnityEngine.RenderTextureCreationFlags _flags;
        public int width { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::width"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::width="); } }
        public int height { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::height"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::height="); } }
        public int msaaSamples { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::msaaSamples"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::msaaSamples="); } }
        public int volumeDepth { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::volumeDepth"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::volumeDepth="); } }
        public int mipCount { set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::mipCount="); } }
        public global::UnityEngine.RenderTextureFormat colorFormat { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::colorFormat"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::colorFormat="); } }
        public bool sRGB { set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::sRGB="); } }
        public int depthBufferBits { set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::depthBufferBits="); } }
        public global::UnityEngine.Rendering.TextureDimension dimension { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::dimension"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::dimension="); } }
        public global::UnityEngine.Rendering.ShadowSamplingMode shadowSamplingMode { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::shadowSamplingMode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::shadowSamplingMode="); } }
        public global::UnityEngine.VRTextureUsage vrUsage { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::vrUsage"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::vrUsage="); } }
        public global::UnityEngine.RenderTextureMemoryless memoryless { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::memoryless"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::memoryless="); } }
        public bool useMipMap { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::useMipMap"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::useMipMap="); } }
        public bool autoGenerateMips { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::autoGenerateMips"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::autoGenerateMips="); } }
        public bool enableRandomWrite { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::enableRandomWrite"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::enableRandomWrite="); } }
        public bool useDynamicScale { set { global::Porteo.Falta.Llamada("UnityEngine.RenderTextureDescriptor::useDynamicScale="); } }
        public RenderTextureDescriptor(int width, int height) { this = default; }
        public RenderTextureDescriptor(int width, int height, global::UnityEngine.RenderTextureFormat colorFormat, int depthBufferBits) { this = default; }
    }
}
