// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class RenderTexture
    {
        public global::UnityEngine.VRTextureUsage vrUsage { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::vrUsage"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::vrUsage="); } }
        public global::UnityEngine.RenderTextureMemoryless memorylessMode { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::memorylessMode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::memorylessMode="); } }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode, global::UnityEngine.VRTextureUsage vrUsage, bool useDynamicScale) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode, global::UnityEngine.VRTextureUsage vrUsage) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
    }
}
