// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.Flags]
    public enum RenderTextureMemoryless : int
    {
        None = 0,
        Color = 1,
        Depth = 2,
        MSAA = 4,
    }
}
