// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Renderer
    {
        public bool castShadows { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::castShadows"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::castShadows="); } }
        public global::UnityEngine.Bounds localBounds { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::localBounds"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::localBounds="); } }
        public global::UnityEngine.Vector4 realtimeLightmapScaleOffset { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::realtimeLightmapScaleOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::realtimeLightmapScaleOffset="); } }
        public void SetPropertyBlock(global::UnityEngine.MaterialPropertyBlock properties, int materialIndex) { global::Porteo.Falta.Llamada("UnityEngine.Renderer::SetPropertyBlock"); }
        public void GetPropertyBlock(global::UnityEngine.MaterialPropertyBlock properties, int materialIndex) { global::Porteo.Falta.Llamada("UnityEngine.Renderer::GetPropertyBlock"); }
    }
}
