// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct RenderBuffer
    {
        public int m_RenderTextureInstanceID;
        public global::System.IntPtr m_BufferPtr;
    }
}
