// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class RenderTexture
    {
        public int volumeDepth { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::volumeDepth"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::volumeDepth="); } }
        public bool useDynamicScale { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::useDynamicScale"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::useDynamicScale="); } }
        public global::UnityEngine.RenderBuffer colorBuffer { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::colorBuffer"); return default; } }
        public global::UnityEngine.RenderBuffer depthBuffer { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::depthBuffer"); return default; } }
        public static bool enabled { get { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::enabled"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::enabled="); } }
        public RenderTexture(int width, int height, int depth, global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::.ctor"); }
        public static global::UnityEngine.RenderTexture GetTemporary(global::UnityEngine.RenderTextureDescriptor desc) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode, global::UnityEngine.VRTextureUsage vrUsage, bool useDynamicScale) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode, global::UnityEngine.VRTextureUsage vrUsage) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, int antiAliasing) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.Experimental.Rendering.GraphicsFormat format) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode, global::UnityEngine.VRTextureUsage vrUsage, bool useDynamicScale) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode, global::UnityEngine.VRTextureUsage vrUsage) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
        public static global::UnityEngine.RenderTexture GetTemporary(int width, int height, int depthBuffer, global::UnityEngine.RenderTextureFormat format, global::UnityEngine.RenderTextureReadWrite readWrite, int antiAliasing, global::UnityEngine.RenderTextureMemoryless memorylessMode) { global::Porteo.Falta.Llamada("UnityEngine.RenderTexture::GetTemporary"); return default; }
    }
}
