// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4, AllowMultiple = true)]
    public sealed partial class RequireComponent : global::System.Attribute
    {
        public RequireComponent(global::System.Type requiredComponent) { global::Porteo.Falta.Llamada("UnityEngine.RequireComponent::.ctor"); }
    }
}
