// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Rigidbody
    {
        public void Move(global::UnityEngine.Vector3 position, global::UnityEngine.Quaternion rotation) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::Move"); }
        public void AddRelativeForce(float x, float y, float z, global::UnityEngine.ForceMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddRelativeForce"); }
        public void AddRelativeForce(float x, float y, float z) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddRelativeForce"); }
        public void AddRelativeTorque(float x, float y, float z, global::UnityEngine.ForceMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddRelativeTorque"); }
        public void AddRelativeTorque(float x, float y, float z) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddRelativeTorque"); }
    }
}
