// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)64, AllowMultiple = false)]
    public partial class RuntimeInitializeOnLoadMethodAttribute : global::UnityEngine.Scripting.PreserveAttribute
    {
        public RuntimeInitializeOnLoadMethodAttribute(global::UnityEngine.RuntimeInitializeLoadType loadType) { global::Porteo.Falta.Llamada("UnityEngine.RuntimeInitializeOnLoadMethodAttribute::.ctor"); }
    }
}
