// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public static partial class ScalableBufferManager
    {
        public static float widthScaleFactor { get { global::Porteo.Falta.Llamada("UnityEngine.ScalableBufferManager::widthScaleFactor"); return default; } }
        public static float heightScaleFactor { get { global::Porteo.Falta.Llamada("UnityEngine.ScalableBufferManager::heightScaleFactor"); return default; } }
    }
}
