// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Screen
    {
        public static void SetResolution(int width, int height, global::UnityEngine.FullScreenMode fullscreenMode, global::UnityEngine.RefreshRate preferredRefreshRate) { global::Porteo.Falta.Llamada("UnityEngine.Screen::SetResolution"); }
        public static void SetResolution(int width, int height, global::UnityEngine.FullScreenMode fullscreenMode, int preferredRefreshRate) { global::Porteo.Falta.Llamada("UnityEngine.Screen::SetResolution"); }
    }
}
