// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.Serializable]
    public partial struct SecondarySpriteTexture
    {
        public string name;
        public global::UnityEngine.Texture2D texture;
    }
}
