// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum SendMessageOptions : int
    {
        RequireReceiver = 0,
        DontRequireReceiver = 1,
    }
}
