// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum ShadowProjection : int
    {
        CloseFit = 0,
        StableFit = 1,
    }
}
