// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Shader
    {
        public static void EnableKeyword(in global::UnityEngine.Rendering.GlobalKeyword keyword) { global::Porteo.Falta.Llamada("UnityEngine.Shader::EnableKeyword"); }
        public static void DisableKeyword(in global::UnityEngine.Rendering.GlobalKeyword keyword) { global::Porteo.Falta.Llamada("UnityEngine.Shader::DisableKeyword"); }
        public static bool IsKeywordEnabled(in global::UnityEngine.Rendering.GlobalKeyword keyword) { global::Porteo.Falta.Llamada("UnityEngine.Shader::IsKeywordEnabled"); return default; }
        public static void SetGlobalTexture(string name, global::UnityEngine.RenderTexture value, global::UnityEngine.Rendering.RenderTextureSubElement element) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalTexture"); }
        public static void SetGlobalTexture(int nameID, global::UnityEngine.RenderTexture value, global::UnityEngine.Rendering.RenderTextureSubElement element) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalTexture"); }
        public static void SetGlobalFloatArray(string name, global::System.Collections.Generic.List<float> values) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalFloatArray"); }
        public static void SetGlobalFloatArray(int nameID, global::System.Collections.Generic.List<float> values) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalFloatArray"); }
        public static void SetGlobalFloatArray(int nameID, float[] values) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalFloatArray"); }
        public static void SetGlobalVectorArray(string name, global::System.Collections.Generic.List<global::UnityEngine.Vector4> values) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalVectorArray"); }
        public static void SetGlobalVectorArray(int nameID, global::System.Collections.Generic.List<global::UnityEngine.Vector4> values) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalVectorArray"); }
        public static void SetGlobalVectorArray(int nameID, global::UnityEngine.Vector4[] values) { global::Porteo.Falta.Llamada("UnityEngine.Shader::SetGlobalVectorArray"); }
        public static global::UnityEngine.Vector4 GetGlobalVector(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Shader::GetGlobalVector"); return default; }
        public static global::UnityEngine.Color GetGlobalColor(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Shader::GetGlobalColor"); return default; }
        public static global::UnityEngine.Texture GetGlobalTexture(int nameID) { global::Porteo.Falta.Llamada("UnityEngine.Shader::GetGlobalTexture"); return default; }
    }
}
