// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct SkeletonBone
    {
        public string name;
        public string parentName;
        public global::UnityEngine.Vector3 position;
        public global::UnityEngine.Quaternion rotation;
        public global::UnityEngine.Vector3 scale;
    }
}
