// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class SkinnedMeshRenderer
    {
        public void BakeMesh(global::UnityEngine.Mesh mesh, bool useScale) { global::Porteo.Falta.Llamada("UnityEngine.SkinnedMeshRenderer::BakeMesh"); }
    }
}
