// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Skybox : global::UnityEngine.Behaviour
    {
        public global::UnityEngine.Material material { get { global::Porteo.Falta.Llamada("UnityEngine.Skybox::material"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Skybox::material="); } }
    }
}
