// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct SortingLayer
    {
        public int m_Id;
        public int id { get { global::Porteo.Falta.Llamada("UnityEngine.SortingLayer::id"); return default; } }
        public string name { get { global::Porteo.Falta.Llamada("UnityEngine.SortingLayer::name"); return default; } }
        public int value { get { global::Porteo.Falta.Llamada("UnityEngine.SortingLayer::value"); return default; } }
        public static bool IsValid(int id) { global::Porteo.Falta.Llamada("UnityEngine.SortingLayer::IsValid"); return default; }
    }
}
