// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)256, Inherited = true, AllowMultiple = true)]
    public partial class SpaceAttribute : global::UnityEngine.PropertyAttribute
    {
        public SpaceAttribute() { global::Porteo.Falta.Llamada("UnityEngine.SpaceAttribute::.ctor"); }
        public SpaceAttribute(float height) { global::Porteo.Falta.Llamada("UnityEngine.SpaceAttribute::.ctor"); }
    }
}
