// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Sprite
    {
        public static global::UnityEngine.Sprite Create(global::UnityEngine.Texture2D texture, global::UnityEngine.Rect rect, global::UnityEngine.Vector2 pivot, float pixelsPerUnit, uint extrude, global::UnityEngine.SpriteMeshType meshType, global::UnityEngine.Vector4 border, bool generateFallbackPhysicsShape) { global::Porteo.Falta.Llamada("UnityEngine.Sprite::Create"); return default; }
        public static global::UnityEngine.Sprite Create(global::UnityEngine.Texture2D texture, global::UnityEngine.Rect rect, global::UnityEngine.Vector2 pivot, float pixelsPerUnit, uint extrude, global::UnityEngine.SpriteMeshType meshType, global::UnityEngine.Vector4 border, bool generateFallbackPhysicsShape, global::UnityEngine.SecondarySpriteTexture[] secondaryTextures) { global::Porteo.Falta.Llamada("UnityEngine.Sprite::Create"); return default; }
    }
}
