// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum StackTraceLogType : int
    {
        None = 0,
        ScriptOnly = 1,
        Full = 2,
    }
}
