// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum StereoTargetEyeMask : int
    {
        None = 0,
        Left = 1,
        Right = 2,
        Both = 3,
    }
}
