// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class SystemInfo
    {
        public static bool graphicsUVStartsAtTop { get { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::graphicsUVStartsAtTop"); return default; } }
        public static bool supportsMotionVectors { get { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::supportsMotionVectors"); return default; } }
        public static bool supports3DRenderTextures { get { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::supports3DRenderTextures"); return default; } }
        public static global::UnityEngine.Rendering.CopyTextureSupport copyTextureSupport { get { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::copyTextureSupport"); return default; } }
        public static int supportedRenderTargetCount { get { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::supportedRenderTargetCount"); return default; } }
        public static bool usesReversedZBuffer { get { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::usesReversedZBuffer"); return default; } }
        public static bool usesLoadStoreActions { get { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::usesLoadStoreActions"); return default; } }
        public static bool IsFormatSupported(global::UnityEngine.Experimental.Rendering.GraphicsFormat format, global::UnityEngine.Experimental.Rendering.FormatUsage usage) { global::Porteo.Falta.Llamada("UnityEngine.SystemInfo::IsFormatSupported"); return default; }
    }
}
