// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class TerrainData
    {
        public global::UnityEngine.Bounds bounds { get { global::Porteo.Falta.Llamada("UnityEngine.TerrainData::bounds"); return default; } }
    }
}
