// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Terrain
    {
        public global::UnityEngine.Vector4 lightmapScaleOffset { get { global::Porteo.Falta.Llamada("UnityEngine.Terrain::lightmapScaleOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Terrain::lightmapScaleOffset="); } }
        public global::UnityEngine.Vector4 realtimeLightmapScaleOffset { get { global::Porteo.Falta.Llamada("UnityEngine.Terrain::realtimeLightmapScaleOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Terrain::realtimeLightmapScaleOffset="); } }
        public global::UnityEngine.Rendering.ShadowCastingMode shadowCastingMode { get { global::Porteo.Falta.Llamada("UnityEngine.Terrain::shadowCastingMode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Terrain::shadowCastingMode="); } }
        public global::UnityEngine.Rendering.ReflectionProbeUsage reflectionProbeUsage { get { global::Porteo.Falta.Llamada("UnityEngine.Terrain::reflectionProbeUsage"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Terrain::reflectionProbeUsage="); } }
        public global::UnityEngine.Vector3 GetPosition() { global::Porteo.Falta.Llamada("UnityEngine.Terrain::GetPosition"); return default; }
    }
}
