// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Texture3D
    {
        public int depth { get { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::depth"); return default; } }
        public global::UnityEngine.TextureFormat format { get { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::format"); return default; } }
        public override bool isReadable { get { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::isReadable"); return default; } }
        public global::UnityEngine.Color[] GetPixels(int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixels"); return default; }
        public global::UnityEngine.Color[] GetPixels() { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixels"); return default; }
        public global::UnityEngine.Color32[] GetPixels32(int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixels32"); return default; }
        public global::UnityEngine.Color32[] GetPixels32() { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixels32"); return default; }
        public void SetPixels(global::UnityEngine.Color[] colors, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::SetPixels"); }
        public void SetPixels(global::UnityEngine.Color[] colors) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::SetPixels"); }
        public void SetPixels32(global::UnityEngine.Color32[] colors, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::SetPixels32"); }
        public void SetPixels32(global::UnityEngine.Color32[] colors) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::SetPixels32"); }
        public Texture3D(int width, int height, int depth, global::UnityEngine.TextureFormat textureFormat, bool mipChain) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::.ctor"); }
        public void Apply(bool updateMipmaps, bool makeNoLongerReadable) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::Apply"); }
        public void Apply(bool updateMipmaps) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::Apply"); }
        public void Apply() { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::Apply"); }
        public void SetPixel(int x, int y, int z, global::UnityEngine.Color color) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::SetPixel"); }
        public void SetPixel(int x, int y, int z, global::UnityEngine.Color color, int mipLevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::SetPixel"); }
        public global::UnityEngine.Color GetPixel(int x, int y, int z) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixel"); return default; }
        public global::UnityEngine.Color GetPixel(int x, int y, int z, int mipLevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixel"); return default; }
        public global::UnityEngine.Color GetPixelBilinear(float u, float v, float w) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixelBilinear"); return default; }
        public global::UnityEngine.Color GetPixelBilinear(float u, float v, float w, int mipLevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::GetPixelBilinear"); return default; }
    }
}
