// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Texture2D
    {
        public global::UnityEngine.Color[] GetPixels(int x, int y, int blockWidth, int blockHeight, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetPixels"); return default; }
        public void SetPixel(int x, int y, global::UnityEngine.Color color, int mipLevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::SetPixel"); }
        public void SetPixels(int x, int y, int blockWidth, int blockHeight, global::UnityEngine.Color[] colors, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::SetPixels"); }
        public global::UnityEngine.Color GetPixel(int x, int y, int mipLevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetPixel"); return default; }
        public global::UnityEngine.Color GetPixelBilinear(float u, float v, int mipLevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetPixelBilinear"); return default; }
        public void LoadRawTextureData(global::System.IntPtr data, int size) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::LoadRawTextureData"); }
        public void LoadRawTextureData<T>(global::Unity.Collections.NativeArray<T> data) where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::LoadRawTextureData"); }
        public global::Unity.Collections.NativeArray<T> GetRawTextureData<T>() where T : struct { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetRawTextureData"); return default; }
        public bool Resize(int width, int height, global::UnityEngine.Experimental.Rendering.GraphicsFormat format, bool hasMipMap) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::Resize"); return default; }
        public void SetPixels32(global::UnityEngine.Color32[] colors, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::SetPixels32"); }
        public void SetPixels32(int x, int y, int blockWidth, int blockHeight, global::UnityEngine.Color32[] colors, int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::SetPixels32"); }
        public void SetPixels32(int x, int y, int blockWidth, int blockHeight, global::UnityEngine.Color32[] colors) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::SetPixels32"); }
        public global::UnityEngine.Color[] GetPixels(int miplevel) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetPixels"); return default; }
    }
}
