// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)32767, Inherited = true, AllowMultiple = false)]
    public partial class TooltipAttribute : global::UnityEngine.PropertyAttribute
    {
        public TooltipAttribute(string tooltip) { global::Porteo.Falta.Llamada("UnityEngine.TooltipAttribute::.ctor"); }
    }
}
