// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class TouchScreenKeyboard
    {
        public static bool isSupported { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::isSupported"); return default; } }
        public static bool isInPlaceEditingAllowed { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::isInPlaceEditingAllowed"); return default; } }
        public string text { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::text"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::text="); } }
        public static bool hideInput { set { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::hideInput="); } }
        public bool active { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::active"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::active="); } }
        public global::UnityEngine.TouchScreenKeyboard.Status status { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::status"); return default; } }
        public int characterLimit { set { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::characterLimit="); } }
        public bool canGetSelection { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::canGetSelection"); return default; } }
        public bool canSetSelection { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::canSetSelection"); return default; } }
        public global::UnityEngine.RangeInt selection { get { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::selection"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::selection="); } }
        public static global::UnityEngine.TouchScreenKeyboard Open(string text, global::UnityEngine.TouchScreenKeyboardType keyboardType, bool autocorrection, bool multiline, bool secure, bool alert, string textPlaceholder, int characterLimit) { global::Porteo.Falta.Llamada("UnityEngine.TouchScreenKeyboard::Open"); return default; }
        public partial class Android
        {
        }
        public enum Status : int
        {
            Visible = 0,
            Done = 1,
            Canceled = 2,
            LostFocus = 3,
        }
    }
}
