// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class TrailRenderer : global::UnityEngine.Renderer
    {
        public float time { get { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::time"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::time="); } }
        public global::UnityEngine.Color startColor { get { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::startColor"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::startColor="); } }
        public float shadowBias { get { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::shadowBias"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::shadowBias="); } }
        public void Clear() { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::Clear"); }
        public void BakeMesh(global::UnityEngine.Mesh mesh, bool useTransform = false) { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::BakeMesh"); }
        public void BakeMesh(global::UnityEngine.Mesh mesh, global::UnityEngine.Camera camera, bool useTransform = false) { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::BakeMesh"); }
    }
}
