// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Transform
    {
        public void Translate(float x, float y, float z, global::UnityEngine.Transform relativeTo) { global::Porteo.Falta.Llamada("UnityEngine.Transform::Translate"); }
        public global::UnityEngine.Vector3 TransformVector(float x, float y, float z) { global::Porteo.Falta.Llamada("UnityEngine.Transform::TransformVector"); return default; }
        public global::UnityEngine.Vector3 InverseTransformVector(float x, float y, float z) { global::Porteo.Falta.Llamada("UnityEngine.Transform::InverseTransformVector"); return default; }
        public void RotateAround(global::UnityEngine.Vector3 axis, float angle) { global::Porteo.Falta.Llamada("UnityEngine.Transform::RotateAround"); }
    }
}
