// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class UnityString
    {
        public static string Format(string fmt, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.UnityString::Format"); return default; }
    }
}
