// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Vector2
    {
        public static global::UnityEngine.Vector2 SmoothDamp(global::UnityEngine.Vector2 current, global::UnityEngine.Vector2 target, ref global::UnityEngine.Vector2 currentVelocity, float smoothTime, float maxSpeed) { global::Porteo.Falta.Llamada("UnityEngine.Vector2::SmoothDamp"); return default; }
        public static global::UnityEngine.Vector2 SmoothDamp(global::UnityEngine.Vector2 current, global::UnityEngine.Vector2 target, ref global::UnityEngine.Vector2 currentVelocity, float smoothTime) { global::Porteo.Falta.Llamada("UnityEngine.Vector2::SmoothDamp"); return default; }
    }
}
