// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Vector3Int : global::System.IEquatable<global::UnityEngine.Vector3Int>, global::System.IFormattable
    {
        public int m_X;
        public int m_Y;
        public int m_Z;
        public int x { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::x"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::x="); } }
        public int y { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::y"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::y="); } }
        public int z { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::z"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::z="); } }
        public int this[int index] { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Item"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Item="); } }
        public float magnitude { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::magnitude"); return default; } }
        public int sqrMagnitude { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::sqrMagnitude"); return default; } }
        public static global::UnityEngine.Vector3Int zero { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::zero"); return default; } }
        public static global::UnityEngine.Vector3Int one { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::one"); return default; } }
        public static global::UnityEngine.Vector3Int up { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::up"); return default; } }
        public static global::UnityEngine.Vector3Int down { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::down"); return default; } }
        public static global::UnityEngine.Vector3Int left { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::left"); return default; } }
        public static global::UnityEngine.Vector3Int right { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::right"); return default; } }
        public static global::UnityEngine.Vector3Int forward { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::forward"); return default; } }
        public static global::UnityEngine.Vector3Int back { get { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::back"); return default; } }
        public void Set(int x, int y, int z) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Set"); }
        public static float Distance(global::UnityEngine.Vector3Int a, global::UnityEngine.Vector3Int b) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Distance"); return default; }
        public static global::UnityEngine.Vector3Int Min(global::UnityEngine.Vector3Int lhs, global::UnityEngine.Vector3Int rhs) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Min"); return default; }
        public static global::UnityEngine.Vector3Int Max(global::UnityEngine.Vector3Int lhs, global::UnityEngine.Vector3Int rhs) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Max"); return default; }
        public static global::UnityEngine.Vector3Int Scale(global::UnityEngine.Vector3Int a, global::UnityEngine.Vector3Int b) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Scale"); return default; }
        public void Scale(global::UnityEngine.Vector3Int scale) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Scale"); }
        public void Clamp(global::UnityEngine.Vector3Int min, global::UnityEngine.Vector3Int max) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Clamp"); }
        public static global::UnityEngine.Vector3Int FloorToInt(global::UnityEngine.Vector3 v) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::FloorToInt"); return default; }
        public static global::UnityEngine.Vector3Int CeilToInt(global::UnityEngine.Vector3 v) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::CeilToInt"); return default; }
        public static global::UnityEngine.Vector3Int RoundToInt(global::UnityEngine.Vector3 v) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::RoundToInt"); return default; }
        public override bool Equals(object other) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Equals"); return default; }
        public bool Equals(global::UnityEngine.Vector3Int other) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::Equals"); return default; }
        public override int GetHashCode() { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::GetHashCode"); return default; }
        public override string ToString() { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::ToString"); return default; }
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::ToString"); return default; }
        public string ToString(string format, global::System.IFormatProvider formatProvider) { global::Porteo.Falta.Llamada("UnityEngine.Vector3Int::ToString"); return default; }
    }
}
