// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Vector2Int : global::System.IEquatable<global::UnityEngine.Vector2Int>, global::System.IFormattable
    {
        public int m_X;
        public int m_Y;
        public int x { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::x"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::x="); } }
        public int y { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::y"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::y="); } }
        public int this[int index] { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Item"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Item="); } }
        public float magnitude { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::magnitude"); return default; } }
        public int sqrMagnitude { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::sqrMagnitude"); return default; } }
        public static global::UnityEngine.Vector2Int zero { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::zero"); return default; } }
        public static global::UnityEngine.Vector2Int one { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::one"); return default; } }
        public static global::UnityEngine.Vector2Int up { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::up"); return default; } }
        public static global::UnityEngine.Vector2Int down { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::down"); return default; } }
        public static global::UnityEngine.Vector2Int left { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::left"); return default; } }
        public static global::UnityEngine.Vector2Int right { get { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::right"); return default; } }
        public void Set(int x, int y) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Set"); }
        public static float Distance(global::UnityEngine.Vector2Int a, global::UnityEngine.Vector2Int b) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Distance"); return default; }
        public static global::UnityEngine.Vector2Int Min(global::UnityEngine.Vector2Int lhs, global::UnityEngine.Vector2Int rhs) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Min"); return default; }
        public static global::UnityEngine.Vector2Int Max(global::UnityEngine.Vector2Int lhs, global::UnityEngine.Vector2Int rhs) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Max"); return default; }
        public static global::UnityEngine.Vector2Int Scale(global::UnityEngine.Vector2Int a, global::UnityEngine.Vector2Int b) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Scale"); return default; }
        public void Scale(global::UnityEngine.Vector2Int scale) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Scale"); }
        public void Clamp(global::UnityEngine.Vector2Int min, global::UnityEngine.Vector2Int max) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Clamp"); }
        public static implicit operator global::UnityEngine.Vector2(global::UnityEngine.Vector2Int v) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::op_Implicit"); return default; }
        public static global::UnityEngine.Vector2Int FloorToInt(global::UnityEngine.Vector2 v) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::FloorToInt"); return default; }
        public static global::UnityEngine.Vector2Int CeilToInt(global::UnityEngine.Vector2 v) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::CeilToInt"); return default; }
        public static global::UnityEngine.Vector2Int RoundToInt(global::UnityEngine.Vector2 v) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::RoundToInt"); return default; }
        public override bool Equals(object other) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Equals"); return default; }
        public bool Equals(global::UnityEngine.Vector2Int other) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::Equals"); return default; }
        public override int GetHashCode() { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::GetHashCode"); return default; }
        public override string ToString() { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::ToString"); return default; }
        public string ToString(string format) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::ToString"); return default; }
        public string ToString(string format, global::System.IFormatProvider formatProvider) { global::Porteo.Falta.Llamada("UnityEngine.Vector2Int::ToString"); return default; }
    }
}
