// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Vector4
    {
        public static global::UnityEngine.Vector4 positiveInfinity { get { global::Porteo.Falta.Llamada("UnityEngine.Vector4::positiveInfinity"); return default; } }
        public static global::UnityEngine.Vector4 negativeInfinity { get { global::Porteo.Falta.Llamada("UnityEngine.Vector4::negativeInfinity"); return default; } }
        public static global::UnityEngine.Vector4 MoveTowards(global::UnityEngine.Vector4 current, global::UnityEngine.Vector4 target, float maxDistanceDelta) { global::Porteo.Falta.Llamada("UnityEngine.Vector4::MoveTowards"); return default; }
        public void Scale(global::UnityEngine.Vector4 scale) { global::Porteo.Falta.Llamada("UnityEngine.Vector4::Scale"); }
        public static global::UnityEngine.Vector4 Project(global::UnityEngine.Vector4 a, global::UnityEngine.Vector4 b) { global::Porteo.Falta.Llamada("UnityEngine.Vector4::Project"); return default; }
        public static float Magnitude(global::UnityEngine.Vector4 a) { global::Porteo.Falta.Llamada("UnityEngine.Vector4::Magnitude"); return default; }
        public static float SqrMagnitude(global::UnityEngine.Vector4 a) { global::Porteo.Falta.Llamada("UnityEngine.Vector4::SqrMagnitude"); return default; }
        public float SqrMagnitude() { global::Porteo.Falta.Llamada("UnityEngine.Vector4::SqrMagnitude"); return default; }
    }
}
