// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class WaitForSecondsRealtime
    {
        public override void Reset() { global::Porteo.Falta.Llamada("UnityEngine.WaitForSecondsRealtime::Reset"); }
    }
}
