// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public enum DirectorWrapMode : int
    {
        Hold = 0,
        Loop = 1,
        None = 2,
    }
}
