// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct FrameData
    {
        public ulong m_FrameID;
        public double m_DeltaTime;
        public float m_Weight;
        public float m_EffectiveWeight;
        public double m_EffectiveParentDelay;
        public float m_EffectiveParentSpeed;
        public float m_EffectiveSpeed;
        public global::UnityEngine.Playables.FrameData.Flags m_Flags;
        public global::UnityEngine.Playables.PlayableOutput m_Output;
        public float deltaTime { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::deltaTime"); return default; } }
        public float effectiveSpeed { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::effectiveSpeed"); return default; } }
        public global::UnityEngine.Playables.FrameData.EvaluationType evaluationType { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::evaluationType"); return default; } }
        public bool seekOccurred { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::seekOccurred"); return default; } }
        public bool timeLooped { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::timeLooped"); return default; } }
        public bool timeHeld { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::timeHeld"); return default; } }
        public global::UnityEngine.Playables.PlayableOutput output { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::output"); return default; } }
        public global::UnityEngine.Playables.PlayState effectivePlayState { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameData::effectivePlayState"); return default; } }
        public enum EvaluationType : int
        {
            Evaluate = 0,
            Playback = 1,
        }
        [System.Flags]
        public enum Flags : int
        {
            Evaluate = 1,
            SeekOccured = 2,
            Loop = 4,
            Hold = 8,
            EffectivePlayStateDelayed = 16,
            EffectivePlayStatePlaying = 32,
        }
    }
}
