// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct FrameRate : global::System.IEquatable<global::UnityEngine.Playables.FrameRate>
    {
        public static readonly global::UnityEngine.Playables.FrameRate k_24Fps;
        public static readonly global::UnityEngine.Playables.FrameRate k_23_976Fps;
        public static readonly global::UnityEngine.Playables.FrameRate k_25Fps;
        public static readonly global::UnityEngine.Playables.FrameRate k_30Fps;
        public static readonly global::UnityEngine.Playables.FrameRate k_29_97Fps;
        public static readonly global::UnityEngine.Playables.FrameRate k_50Fps;
        public static readonly global::UnityEngine.Playables.FrameRate k_60Fps;
        public static readonly global::UnityEngine.Playables.FrameRate k_59_94Fps;
        public int m_Rate;
        public double rate { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameRate::rate"); return default; } }
        public bool IsValid() { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameRate::IsValid"); return default; }
        public bool Equals(global::UnityEngine.Playables.FrameRate other) { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameRate::Equals"); return default; }
        public static bool operator ==(global::UnityEngine.Playables.FrameRate a, global::UnityEngine.Playables.FrameRate b) { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameRate::op_Equality"); return default; }
        public static bool operator !=(global::UnityEngine.Playables.FrameRate a, global::UnityEngine.Playables.FrameRate b) { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameRate::op_Inequality"); return default; }
        public static global::UnityEngine.Playables.FrameRate DoubleToFrameRate(double framerate) { global::Porteo.Falta.Llamada("UnityEngine.Playables.FrameRate::DoubleToFrameRate"); return default; }
    }
}
