// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial interface INotificationReceiver
    {
        void OnNotify(global::UnityEngine.Playables.Playable origin, global::UnityEngine.Playables.INotification notification, object context);
    }
}
