// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial interface IPlayableBehaviour
    {
        void OnGraphStart(global::UnityEngine.Playables.Playable playable);
        void OnGraphStop(global::UnityEngine.Playables.Playable playable);
        void OnPlayableCreate(global::UnityEngine.Playables.Playable playable);
        void OnPlayableDestroy(global::UnityEngine.Playables.Playable playable);
        void OnBehaviourPlay(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info);
        void OnBehaviourPause(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info);
        void PrepareFrame(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info);
        void ProcessFrame(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info, object playerData);
    }
}
