// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial interface IPlayableAsset
    {
        double duration { get; }
        global::System.Collections.Generic.IEnumerable<global::UnityEngine.Playables.PlayableBinding> outputs { get; }
        global::UnityEngine.Playables.Playable CreatePlayable(global::UnityEngine.Playables.PlayableGraph graph, global::UnityEngine.GameObject owner);
    }
}
