// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public enum PlayState : int
    {
        Paused = 0,
        Playing = 1,
        Delayed = 2,
    }
}
