// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct PlayableGraph
    {
        public global::System.IntPtr m_Handle;
        public uint m_Version;
        public global::UnityEngine.Playables.Playable GetRootPlayable(int index) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::GetRootPlayable"); return default; }
        public bool Connect<U, V>(U source, int sourceOutputPort, V destination, int destinationInputPort) where U : struct, global::UnityEngine.Playables.IPlayable where V : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::Connect"); return default; }
        public void Evaluate() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::Evaluate"); }
        public bool IsValid() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::IsValid"); return default; }
        public bool IsPlaying() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::IsPlaying"); return default; }
        public global::UnityEngine.IExposedPropertyTable GetResolver() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::GetResolver"); return default; }
        public int GetPlayableCount() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::GetPlayableCount"); return default; }
        public int GetRootPlayableCount() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::GetRootPlayableCount"); return default; }
        public void SynchronizeEvaluation(global::UnityEngine.Playables.PlayableGraph playable) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::SynchronizeEvaluation"); }
        public bool IsMatchFrameRateEnabled() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::IsMatchFrameRateEnabled"); return default; }
        public global::UnityEngine.Playables.FrameRate GetFrameRate() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableGraph::GetFrameRate"); return default; }
    }
}
