// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public abstract partial class PlayableBehaviour : global::UnityEngine.Playables.IPlayableBehaviour, global::System.ICloneable
    {
        public PlayableBehaviour() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::.ctor"); }
        public virtual void OnGraphStart(global::UnityEngine.Playables.Playable playable) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::OnGraphStart"); }
        public virtual void OnGraphStop(global::UnityEngine.Playables.Playable playable) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::OnGraphStop"); }
        public virtual void OnPlayableCreate(global::UnityEngine.Playables.Playable playable) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::OnPlayableCreate"); }
        public virtual void OnPlayableDestroy(global::UnityEngine.Playables.Playable playable) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::OnPlayableDestroy"); }
        public virtual void OnBehaviourDelay(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::OnBehaviourDelay"); }
        public virtual void OnBehaviourPlay(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::OnBehaviourPlay"); }
        public virtual void OnBehaviourPause(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::OnBehaviourPause"); }
        public virtual void PrepareData(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::PrepareData"); }
        public virtual void PrepareFrame(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::PrepareFrame"); }
        public virtual void ProcessFrame(global::UnityEngine.Playables.Playable playable, global::UnityEngine.Playables.FrameData info, object playerData) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::ProcessFrame"); }
        public virtual object Clone() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBehaviour::Clone"); return default; }
    }
}
