// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct Playable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Playables.Playable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Playables.Playable Null { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.Playable::Null"); return default; } }
        public static global::UnityEngine.Playables.Playable Create(global::UnityEngine.Playables.PlayableGraph graph, int inputCount = 0) { global::Porteo.Falta.Llamada("UnityEngine.Playables.Playable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Playables.Playable::GetHandle"); return default; }
        public bool IsPlayableOfType<T>() where T : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.Playable::IsPlayableOfType"); return default; }
        public global::System.Type GetPlayableType() { global::Porteo.Falta.Llamada("UnityEngine.Playables.Playable::GetPlayableType"); return default; }
        public bool Equals(global::UnityEngine.Playables.Playable other) { global::Porteo.Falta.Llamada("UnityEngine.Playables.Playable::Equals"); return default; }
    }
}
