// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial class PlayableDirector : global::UnityEngine.Behaviour, global::UnityEngine.IExposedPropertyTable
    {
        public global::UnityEngine.Playables.PlayState state { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::state"); return default; } }
        public global::UnityEngine.Playables.DirectorWrapMode extrapolationMode { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::extrapolationMode"); return default; } }
        public global::UnityEngine.Playables.PlayableAsset playableAsset { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::playableAsset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::playableAsset="); } }
        public global::UnityEngine.Playables.PlayableGraph playableGraph { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::playableGraph"); return default; } }
        public double time { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::time"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::time="); } }
        public void Play(global::UnityEngine.Playables.FrameRate frameRate) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::Play"); }
        public void Evaluate() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::Evaluate"); }
        public void Play() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::Play"); }
        public void Stop() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::Stop"); }
        public void Pause() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::Pause"); }
        public void Resume() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::Resume"); }
        public void ClearReferenceValue(global::UnityEngine.PropertyName id) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::ClearReferenceValue"); }
        public void SetReferenceValue(global::UnityEngine.PropertyName id, global::UnityEngine.Object value) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::SetReferenceValue"); }
        public global::UnityEngine.Object GetReferenceValue(global::UnityEngine.PropertyName id, out bool idValid) { idValid = default;  global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::GetReferenceValue"); return default;  }
        public global::UnityEngine.Object GetGenericBinding(global::UnityEngine.Object key) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableDirector::GetGenericBinding"); return default; }
    }
}
