// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct PlayableBinding
    {
        public string m_StreamName;
        public global::UnityEngine.Object m_SourceObject;
        public global::System.Type m_SourceBindingType;
        public global::UnityEngine.Playables.PlayableBinding.CreateOutputMethod m_CreateOutputMethod;
        public static readonly global::UnityEngine.Playables.PlayableBinding[] None;
        public static readonly double DefaultDuration;
        public global::UnityEngine.Object sourceObject { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBinding::sourceObject"); return default; } }
        public global::UnityEngine.Playables.PlayableOutput CreateOutput(global::UnityEngine.Playables.PlayableGraph graph) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableBinding::CreateOutput"); return default; }
        public delegate global::UnityEngine.Playables.PlayableOutput CreateOutputMethod(global::UnityEngine.Playables.PlayableGraph graph, string name);
    }
}
