// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public static partial class PlayableOutputExtensions
    {
        public static void SetReferenceObject<U>(U output, global::UnityEngine.Object value) where U : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::SetReferenceObject"); }
        public static void SetUserData<U>(U output, global::UnityEngine.Object value) where U : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::SetUserData"); }
        public static global::UnityEngine.Playables.Playable GetSourcePlayable<U>(U output) where U : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::GetSourcePlayable"); return default; }
        public static void SetSourcePlayable<U, V>(U output, V value, int port) where U : struct, global::UnityEngine.Playables.IPlayableOutput where V : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::SetSourcePlayable"); }
        public static int GetSourceOutputPort<U>(U output) where U : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::GetSourceOutputPort"); return default; }
        public static void SetWeight<U>(U output, float value) where U : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::SetWeight"); }
        public static void PushNotification<U>(U output, global::UnityEngine.Playables.Playable origin, global::UnityEngine.Playables.INotification notification, object context = null) where U : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::PushNotification"); }
        public static void AddNotificationReceiver<U>(U output, global::UnityEngine.Playables.INotificationReceiver receiver) where U : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutputExtensions::AddNotificationReceiver"); }
    }
}
