// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public enum PlayableTraversalMode : int
    {
        Mix = 0,
        Passthrough = 1,
    }
}
