// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct PlayableOutput : global::UnityEngine.Playables.IPlayableOutput, global::System.IEquatable<global::UnityEngine.Playables.PlayableOutput>
    {
        public global::UnityEngine.Playables.PlayableOutputHandle m_Handle;
        public global::UnityEngine.Playables.PlayableOutputHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutput::GetHandle"); return default; }
        public bool IsPlayableOutputOfType<T>() where T : struct, global::UnityEngine.Playables.IPlayableOutput { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutput::IsPlayableOutputOfType"); return default; }
        public bool Equals(global::UnityEngine.Playables.PlayableOutput other) { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableOutput::Equals"); return default; }
    }
}
