// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public static partial class PlayableExtensions
    {
        public static bool IsValid<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::IsValid"); return default; }
        public static global::UnityEngine.Playables.PlayableGraph GetGraph<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetGraph"); return default; }
        public static global::UnityEngine.Playables.PlayState GetPlayState<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetPlayState"); return default; }
        public static void Play<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::Play"); }
        public static void Pause<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::Pause"); }
        public static void SetSpeed<U>(U playable, double value) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetSpeed"); }
        public static void SetDuration<U>(U playable, double value) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetDuration"); }
        public static double GetDuration<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetDuration"); return default; }
        public static void SetTime<U>(U playable, double value) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetTime"); }
        public static double GetTime<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetTime"); return default; }
        public static double GetPreviousTime<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetPreviousTime"); return default; }
        public static bool IsDone<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::IsDone"); return default; }
        public static void SetPropagateSetTime<U>(U playable, bool value) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetPropagateSetTime"); }
        public static void SetInputCount<U>(U playable, int value) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetInputCount"); }
        public static int GetInputCount<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetInputCount"); return default; }
        public static global::UnityEngine.Playables.Playable GetInput<U>(U playable, int inputPort) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetInput"); return default; }
        public static void SetInputWeight<U>(U playable, int inputIndex, float weight) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetInputWeight"); }
        public static void SetInputWeight<U, V>(U playable, V input, float weight) where U : struct, global::UnityEngine.Playables.IPlayable where V : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetInputWeight"); }
        public static float GetInputWeight<U>(U playable, int inputIndex) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetInputWeight"); return default; }
        public static void SetTraversalMode<U>(U playable, global::UnityEngine.Playables.PlayableTraversalMode mode) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetTraversalMode"); }
        public static global::UnityEngine.Playables.DirectorWrapMode GetTimeWrapMode<U>(U playable) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::GetTimeWrapMode"); return default; }
        public static void SetTimeWrapMode<U>(U playable, global::UnityEngine.Playables.DirectorWrapMode value) where U : struct, global::UnityEngine.Playables.IPlayable { global::Porteo.Falta.Llamada("UnityEngine.Playables.PlayableExtensions::SetTimeWrapMode"); }
    }
}
