// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public static partial class ScriptPlayableBinding
    {
        public static global::UnityEngine.Playables.PlayableBinding Create(string name, global::UnityEngine.Object key, global::System.Type type) { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayableBinding::Create"); return default; }
    }
}
