// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Playables
{
    public partial struct ScriptPlayable<T> : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Playables.ScriptPlayable<T>> where T : class, global::UnityEngine.Playables.IPlayableBehaviour, new()
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Playables.ScriptPlayable<T> Null { get { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayable`1::Null"); return default; } }
        public static global::UnityEngine.Playables.ScriptPlayable<T> Create(global::UnityEngine.Playables.PlayableGraph graph, int inputCount = 0) { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayable`1::Create"); return default; }
        public static global::UnityEngine.Playables.ScriptPlayable<T> Create(global::UnityEngine.Playables.PlayableGraph graph, T template, int inputCount = 0) { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayable`1::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayable`1::GetHandle"); return default; }
        public T GetBehaviour() { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayable`1::GetBehaviour"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Playables.ScriptPlayable<T> playable) { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayable`1::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Playables.ScriptPlayable<T> other) { global::Porteo.Falta.Llamada("UnityEngine.Playables.ScriptPlayable`1::Equals"); return default; }
    }
}
