// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AndroidJavaObject : global::System.IDisposable
    {
        public AndroidJavaObject(string className, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaObject::.ctor"); }
        public void Dispose() { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaObject::Dispose"); }
        public void Call(string methodName, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaObject::Call"); }
        public FieldType Get<FieldType>(string fieldName) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaObject::Get"); return default; }
        public FieldType GetStatic<FieldType>(string fieldName) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaObject::GetStatic"); return default; }
        public ReturnType Call<ReturnType>(string methodName, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaObject::Call"); return default; }
        public ReturnType CallStatic<ReturnType>(string methodName, params object[] args) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaObject::CallStatic"); return default; }
    }
}
