// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AndroidJavaProxy
    {
        public AndroidJavaProxy(string javaInterface) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaProxy::.ctor"); }
        public virtual global::UnityEngine.AndroidJavaObject Invoke(string methodName, object[] args) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaProxy::Invoke"); return default; }
        public virtual global::UnityEngine.AndroidJavaObject Invoke(string methodName, global::UnityEngine.AndroidJavaObject[] javaArgs) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaProxy::Invoke"); return default; }
        public virtual bool equals(global::UnityEngine.AndroidJavaObject obj) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaProxy::equals"); return default; }
        public virtual int hashCode() { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaProxy::hashCode"); return default; }
        public virtual string toString() { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaProxy::toString"); return default; }
    }
}
