// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AndroidJavaClass : global::UnityEngine.AndroidJavaObject
    {
        public AndroidJavaClass(string className) : base(default(string), default(object[])) { global::Porteo.Falta.Llamada("UnityEngine.AndroidJavaClass::.ctor"); }
    }
}
