// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AndroidJNI
    {
        public static int AttachCurrentThread() { global::Porteo.Falta.Llamada("UnityEngine.AndroidJNI::AttachCurrentThread"); return default; }
    }
}
