// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AnimationEvent
    {
        public string stringParameter { get { global::Porteo.Falta.Llamada("UnityEngine.AnimationEvent::stringParameter"); return default; } }
        public global::UnityEngine.Object objectReferenceParameter { get { global::Porteo.Falta.Llamada("UnityEngine.AnimationEvent::objectReferenceParameter"); return default; } }
    }
}
