// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct AnimatorStateInfo
    {
        public int m_Name;
        public int m_Path;
        public int m_FullPath;
        public float m_NormalizedTime;
        public float m_Length;
        public float m_Speed;
        public float m_SpeedMultiplier;
        public int m_Tag;
        public int m_Loop;
        public int fullPathHash { get { global::Porteo.Falta.Llamada("UnityEngine.AnimatorStateInfo::fullPathHash"); return default; } }
        public int shortNameHash { get { global::Porteo.Falta.Llamada("UnityEngine.AnimatorStateInfo::shortNameHash"); return default; } }
        public float normalizedTime { get { global::Porteo.Falta.Llamada("UnityEngine.AnimatorStateInfo::normalizedTime"); return default; } }
        public bool IsName(string name) { global::Porteo.Falta.Llamada("UnityEngine.AnimatorStateInfo::IsName"); return default; }
    }
}
