// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AnimationClip
    {
        public float length { get { global::Porteo.Falta.Llamada("UnityEngine.AnimationClip::length"); return default; } }
    }
}
