// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AnimatorControllerParameter
    {
        public int nameHash { get { global::Porteo.Falta.Llamada("UnityEngine.AnimatorControllerParameter::nameHash"); return default; } }
    }
}
