// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AnimationState : global::UnityEngine.TrackedReference
    {
        public float normalizedTime { set { global::Porteo.Falta.Llamada("UnityEngine.AnimationState::normalizedTime="); } }
        public float normalizedSpeed { set { global::Porteo.Falta.Llamada("UnityEngine.AnimationState::normalizedSpeed="); } }
    }
}
