// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Application
    {
        public delegate void LogCallback(string condition, string stackTrace, global::UnityEngine.LogType type);
    }
}
