// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class AssetBundle : global::UnityEngine.Object
    {
        public static global::UnityEngine.AssetBundle LoadFromFile(string path) { global::Porteo.Falta.Llamada("UnityEngine.AssetBundle::LoadFromFile"); return default; }
        public T LoadAsset<T>(string name) where T : global::UnityEngine.Object { global::Porteo.Falta.Llamada("UnityEngine.AssetBundle::LoadAsset"); return default; }
        public void Unload(bool unloadAllLoadedObjects) { global::Porteo.Falta.Llamada("UnityEngine.AssetBundle::Unload"); }
    }
}
