// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum AudioRolloffMode : int
    {
        Logarithmic = 0,
        Linear = 1,
        Custom = 2,
    }
}
