// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AudioLowPassFilter : global::UnityEngine.Behaviour
    {
        public float cutoffFrequency { set { global::Porteo.Falta.Llamada("UnityEngine.AudioLowPassFilter::cutoffFrequency="); } }
        public float lowpassResonanceQ { set { global::Porteo.Falta.Llamada("UnityEngine.AudioLowPassFilter::lowpassResonanceQ="); } }
    }
}
