// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum AudioVelocityUpdateMode : int
    {
        Auto = 0,
        Fixed = 1,
        Dynamic = 2,
    }
}
