// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AudioListener : global::UnityEngine.AudioBehaviour
    {
        public static bool pause { get { global::Porteo.Falta.Llamada("UnityEngine.AudioListener::pause"); return default; } }
    }
}
