// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class AudioReverbZone : global::UnityEngine.Behaviour
    {
        public float maxDistance { get { global::Porteo.Falta.Llamada("UnityEngine.AudioReverbZone::maxDistance"); return default; } }
    }
}
