// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum BlendWeights : int
    {
        OneBone = 1,
        TwoBones = 2,
        FourBones = 4,
    }
}
