// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class BoxCollider : global::UnityEngine.Collider
    {
        public global::UnityEngine.Vector3 center { get { global::Porteo.Falta.Llamada("UnityEngine.BoxCollider::center"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoxCollider::center="); } }
        public global::UnityEngine.Vector3 size { get { global::Porteo.Falta.Llamada("UnityEngine.BoxCollider::size"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.BoxCollider::size="); } }
    }
}
