// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Camera : global::UnityEngine.Behaviour
    {
        public static global::UnityEngine.Camera.CameraCallback onPreCull;
        public static global::UnityEngine.Camera.CameraCallback onPreRender;
        public float nearClipPlane { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::nearClipPlane"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::nearClipPlane="); } }
        public float farClipPlane { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::farClipPlane"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::farClipPlane="); } }
        public float fieldOfView { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::fieldOfView"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::fieldOfView="); } }
        public bool allowHDR { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::allowHDR"); return default; } }
        public float orthographicSize { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::orthographicSize"); return default; } }
        public bool orthographic { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::orthographic"); return default; } }
        public float depth { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::depth"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::depth="); } }
        public float aspect { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::aspect"); return default; } }
        public int cullingMask { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::cullingMask"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::cullingMask="); } }
        public global::UnityEngine.Color backgroundColor { set { global::Porteo.Falta.Llamada("UnityEngine.Camera::backgroundColor="); } }
        public global::UnityEngine.CameraClearFlags clearFlags { set { global::Porteo.Falta.Llamada("UnityEngine.Camera::clearFlags="); } }
        public global::UnityEngine.DepthTextureMode depthTextureMode { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::depthTextureMode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::depthTextureMode="); } }
        public global::UnityEngine.Rect rect { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::rect"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Camera::rect="); } }
        public global::UnityEngine.Rect pixelRect { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::pixelRect"); return default; } }
        public int pixelWidth { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::pixelWidth"); return default; } }
        public int pixelHeight { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::pixelHeight"); return default; } }
        public global::UnityEngine.RenderTexture targetTexture { set { global::Porteo.Falta.Llamada("UnityEngine.Camera::targetTexture="); } }
        public int targetDisplay { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::targetDisplay"); return default; } }
        public global::UnityEngine.Matrix4x4 cameraToWorldMatrix { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::cameraToWorldMatrix"); return default; } }
        public global::UnityEngine.Matrix4x4 worldToCameraMatrix { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::worldToCameraMatrix"); return default; } }
        public global::UnityEngine.Matrix4x4 projectionMatrix { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::projectionMatrix"); return default; } }
        public static global::UnityEngine.Camera main { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::main"); return default; } }
        public static global::UnityEngine.Camera current { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::current"); return default; } }
        public static global::UnityEngine.Camera[] allCameras { get { global::Porteo.Falta.Llamada("UnityEngine.Camera::allCameras"); return default; } }
        public global::UnityEngine.Vector3 WorldToScreenPoint(global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Camera::WorldToScreenPoint"); return default; }
        public global::UnityEngine.Vector3 WorldToViewportPoint(global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Camera::WorldToViewportPoint"); return default; }
        public global::UnityEngine.Vector3 ViewportToWorldPoint(global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ViewportToWorldPoint"); return default; }
        public global::UnityEngine.Vector3 ScreenToWorldPoint(global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ScreenToWorldPoint"); return default; }
        public global::UnityEngine.Vector3 ScreenToViewportPoint(global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ScreenToViewportPoint"); return default; }
        public global::UnityEngine.Ray ScreenPointToRay(global::UnityEngine.Vector3 pos) { global::Porteo.Falta.Llamada("UnityEngine.Camera::ScreenPointToRay"); return default; }
        public void RenderWithShader(global::UnityEngine.Shader shader, string replacementTag) { global::Porteo.Falta.Llamada("UnityEngine.Camera::RenderWithShader"); }
        public void CopyFrom(global::UnityEngine.Camera other) { global::Porteo.Falta.Llamada("UnityEngine.Camera::CopyFrom"); }
        public delegate void CameraCallback(global::UnityEngine.Camera cam);
    }
}
