// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Canvas : global::UnityEngine.Behaviour
    {
        public global::UnityEngine.RenderMode renderMode { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::renderMode"); return default; } }
        public bool isRootCanvas { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::isRootCanvas"); return default; } }
        public float scaleFactor { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::scaleFactor"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Canvas::scaleFactor="); } }
        public float referencePixelsPerUnit { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::referencePixelsPerUnit"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Canvas::referencePixelsPerUnit="); } }
        public bool pixelPerfect { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::pixelPerfect"); return default; } }
        public int renderOrder { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::renderOrder"); return default; } }
        public bool overrideSorting { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::overrideSorting"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Canvas::overrideSorting="); } }
        public int sortingOrder { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::sortingOrder"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Canvas::sortingOrder="); } }
        public int targetDisplay { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::targetDisplay"); return default; } }
        public int sortingLayerID { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::sortingLayerID"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Canvas::sortingLayerID="); } }
        public global::UnityEngine.AdditionalCanvasShaderChannels additionalShaderChannels { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::additionalShaderChannels"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Canvas::additionalShaderChannels="); } }
        public global::UnityEngine.Canvas rootCanvas { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::rootCanvas"); return default; } }
        public global::UnityEngine.Camera worldCamera { get { global::Porteo.Falta.Llamada("UnityEngine.Canvas::worldCamera"); return default; } }
        public static event global::UnityEngine.Canvas.WillRenderCanvases willRenderCanvases { add { global::Porteo.Falta.Llamada("UnityEngine.Canvas::willRenderCanvases+"); } remove { } }
        public static global::UnityEngine.Material GetDefaultCanvasMaterial() { global::Porteo.Falta.Llamada("UnityEngine.Canvas::GetDefaultCanvasMaterial"); return default; }
        public static global::UnityEngine.Material GetETC1SupportedCanvasMaterial() { global::Porteo.Falta.Llamada("UnityEngine.Canvas::GetETC1SupportedCanvasMaterial"); return default; }
        public static void ForceUpdateCanvases() { global::Porteo.Falta.Llamada("UnityEngine.Canvas::ForceUpdateCanvases"); }
        public delegate void WillRenderCanvases();
    }
}
