// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum CollisionDetectionMode : int
    {
        Discrete = 0,
        Continuous = 1,
        ContinuousDynamic = 2,
        ContinuousSpeculative = 3,
    }
}
