// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum ColorSpace : int
    {
        Uninitialized = -1,
        Gamma = 0,
        Linear = 1,
    }
}
