// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct CombineInstance
    {
        public int m_MeshInstanceID;
        public int m_SubMeshIndex;
        public global::UnityEngine.Matrix4x4 m_Transform;
        public global::UnityEngine.Vector4 m_LightmapScaleOffset;
        public global::UnityEngine.Vector4 m_RealtimeLightmapScaleOffset;
        public global::UnityEngine.Mesh mesh { set { global::Porteo.Falta.Llamada("UnityEngine.CombineInstance::mesh="); } }
        public global::UnityEngine.Matrix4x4 transform { set { global::Porteo.Falta.Llamada("UnityEngine.CombineInstance::transform="); } }
    }
}
