// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ComputeBuffer : global::System.IDisposable
    {
        public ComputeBuffer(int count, int stride, global::UnityEngine.ComputeBufferType type) { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::.ctor"); }
        public void Dispose() { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::Dispose"); }
        public void Release() { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::Release"); }
        public void SetData(global::System.Array data) { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::SetData"); }
        public static void CopyCount(global::UnityEngine.ComputeBuffer src, global::UnityEngine.ComputeBuffer dst, int dstOffsetBytes) { global::Porteo.Falta.Llamada("UnityEngine.ComputeBuffer::CopyCount"); }
    }
}
