// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.Flags]
    public enum ComputeBufferType : int
    {
        Default = 0,
        Raw = 1,
        Append = 2,
        Counter = 4,
        DrawIndirect = 256,
        IndirectArguments = 256,
        GPUMemory = 512,
    }
}
