// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class ControllerColliderHit
    {
        public global::UnityEngine.Collider collider { get { global::Porteo.Falta.Llamada("UnityEngine.ControllerColliderHit::collider"); return default; } }
        public global::UnityEngine.GameObject gameObject { get { global::Porteo.Falta.Llamada("UnityEngine.ControllerColliderHit::gameObject"); return default; } }
        public global::UnityEngine.Vector3 point { get { global::Porteo.Falta.Llamada("UnityEngine.ControllerColliderHit::point"); return default; } }
        public global::UnityEngine.Vector3 moveDirection { get { global::Porteo.Falta.Llamada("UnityEngine.ControllerColliderHit::moveDirection"); return default; } }
    }
}
