// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4, AllowMultiple = false, Inherited = false)]
    public sealed partial class CreateAssetMenuAttribute : global::System.Attribute
    {
        public string menuName { set { global::Porteo.Falta.Llamada("UnityEngine.CreateAssetMenuAttribute::menuName="); } }
        public string fileName { set { global::Porteo.Falta.Llamada("UnityEngine.CreateAssetMenuAttribute::fileName="); } }
        public CreateAssetMenuAttribute() { global::Porteo.Falta.Llamada("UnityEngine.CreateAssetMenuAttribute::.ctor"); }
    }
}
