// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Cursor
    {
        public static bool visible { get { global::Porteo.Falta.Llamada("UnityEngine.Cursor::visible"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Cursor::visible="); } }
        public static global::UnityEngine.CursorLockMode lockState { get { global::Porteo.Falta.Llamada("UnityEngine.Cursor::lockState"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Cursor::lockState="); } }
    }
}
