// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum CursorLockMode : int
    {
        None = 0,
        Locked = 1,
        Confined = 2,
    }
}
