// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Event
    {
        public global::UnityEngine.EventType rawType { get { global::Porteo.Falta.Llamada("UnityEngine.Event::rawType"); return default; } }
        public global::UnityEngine.EventModifiers modifiers { get { global::Porteo.Falta.Llamada("UnityEngine.Event::modifiers"); return default; } }
        public char character { get { global::Porteo.Falta.Llamada("UnityEngine.Event::character"); return default; } }
        public global::UnityEngine.KeyCode keyCode { get { global::Porteo.Falta.Llamada("UnityEngine.Event::keyCode"); return default; } }
        public global::UnityEngine.EventType type { get { global::Porteo.Falta.Llamada("UnityEngine.Event::type"); return default; } }
        public string commandName { get { global::Porteo.Falta.Llamada("UnityEngine.Event::commandName"); return default; } }
        public Event() { global::Porteo.Falta.Llamada("UnityEngine.Event::.ctor"); }
        public static bool PopEvent(global::UnityEngine.Event outEvent) { global::Porteo.Falta.Llamada("UnityEngine.Event::PopEvent"); return default; }
    }
}
