// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum FilterMode : int
    {
        Point = 0,
        Bilinear = 1,
        Trilinear = 2,
    }
}
