// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GeometryUtility
    {
        public static global::UnityEngine.Plane[] CalculateFrustumPlanes(global::UnityEngine.Camera camera) { global::Porteo.Falta.Llamada("UnityEngine.GeometryUtility::CalculateFrustumPlanes"); return default; }
    }
}
