// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Gizmos
    {
        public static global::UnityEngine.Color color { set { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::color="); } }
        public static global::UnityEngine.Matrix4x4 matrix { set { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::matrix="); } }
        public static void DrawLine(global::UnityEngine.Vector3 from, global::UnityEngine.Vector3 to) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawLine"); }
        public static void DrawWireSphere(global::UnityEngine.Vector3 center, float radius) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawWireSphere"); }
        public static void DrawSphere(global::UnityEngine.Vector3 center, float radius) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawSphere"); }
        public static void DrawWireCube(global::UnityEngine.Vector3 center, global::UnityEngine.Vector3 size) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawWireCube"); }
        public static void DrawCube(global::UnityEngine.Vector3 center, global::UnityEngine.Vector3 size) { global::Porteo.Falta.Llamada("UnityEngine.Gizmos::DrawCube"); }
    }
}
