// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GL
    {
        public static void Vertex3(float x, float y, float z) { global::Porteo.Falta.Llamada("UnityEngine.GL::Vertex3"); }
        public static void TexCoord2(float x, float y) { global::Porteo.Falta.Llamada("UnityEngine.GL::TexCoord2"); }
        public static void MultiTexCoord2(int unit, float x, float y) { global::Porteo.Falta.Llamada("UnityEngine.GL::MultiTexCoord2"); }
        public static void PushMatrix() { global::Porteo.Falta.Llamada("UnityEngine.GL::PushMatrix"); }
        public static void PopMatrix() { global::Porteo.Falta.Llamada("UnityEngine.GL::PopMatrix"); }
        public static void LoadIdentity() { global::Porteo.Falta.Llamada("UnityEngine.GL::LoadIdentity"); }
        public static void LoadOrtho() { global::Porteo.Falta.Llamada("UnityEngine.GL::LoadOrtho"); }
        public static void LoadProjectionMatrix(global::UnityEngine.Matrix4x4 mat) { global::Porteo.Falta.Llamada("UnityEngine.GL::LoadProjectionMatrix"); }
        public static global::UnityEngine.Matrix4x4 GetGPUProjectionMatrix(global::UnityEngine.Matrix4x4 proj, bool renderIntoTexture) { global::Porteo.Falta.Llamada("UnityEngine.GL::GetGPUProjectionMatrix"); return default; }
        public static void Begin(int mode) { global::Porteo.Falta.Llamada("UnityEngine.GL::Begin"); }
        public static void End() { global::Porteo.Falta.Llamada("UnityEngine.GL::End"); }
        public static void Clear(bool clearDepth, bool clearColor, global::UnityEngine.Color backgroundColor) { global::Porteo.Falta.Llamada("UnityEngine.GL::Clear"); }
        public static void ClearWithSkybox(bool clearDepth, global::UnityEngine.Camera camera) { global::Porteo.Falta.Llamada("UnityEngine.GL::ClearWithSkybox"); }
    }
}
