// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class GUIContent
    {
        public GUIContent(string text) { global::Porteo.Falta.Llamada("UnityEngine.GUIContent::.ctor"); }
    }
}
