// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class GUILayout
    {
        public static void Label(string text, params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::Label"); }
        public static void Label(string text, global::UnityEngine.GUIStyle style, params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::Label"); }
        public static bool Button(string text, params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::Button"); return default; }
        public static string TextField(string text, int maxLength, params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::TextField"); return default; }
        public static bool Toggle(bool value, string text, params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::Toggle"); return default; }
        public static float HorizontalSlider(float value, float leftValue, float rightValue, params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::HorizontalSlider"); return default; }
        public static void Space(float pixels) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::Space"); }
        public static void BeginHorizontal(params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::BeginHorizontal"); }
        public static void EndHorizontal() { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::EndHorizontal"); }
        public static void BeginVertical(global::UnityEngine.GUIStyle style, params global::UnityEngine.GUILayoutOption[] options) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::BeginVertical"); }
        public static void EndVertical() { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::EndVertical"); }
        public static void BeginArea(global::UnityEngine.Rect screenRect) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::BeginArea"); }
        public static void EndArea() { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::EndArea"); }
        public static global::UnityEngine.GUILayoutOption Width(float width) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::Width"); return default; }
        public static global::UnityEngine.GUILayoutOption MaxWidth(float maxWidth) { global::Porteo.Falta.Llamada("UnityEngine.GUILayout::MaxWidth"); return default; }
    }
}
