// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GUIStyle
    {
        public global::UnityEngine.Font font { set { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::font="); } }
        public global::UnityEngine.TextAnchor alignment { set { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::alignment="); } }
        public bool wordWrap { set { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::wordWrap="); } }
        public int fontSize { set { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::fontSize="); } }
        public bool richText { set { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::richText="); } }
        public global::UnityEngine.GUIStyleState normal { get { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::normal"); return default; } }
        public GUIStyle() { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::.ctor"); }
        public GUIStyle(global::UnityEngine.GUIStyle other) { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::.ctor"); }
        public static implicit operator global::UnityEngine.GUIStyle(string str) { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::op_Implicit"); return default; }
        public global::UnityEngine.Vector2 CalcSize(global::UnityEngine.GUIContent content) { global::Porteo.Falta.Llamada("UnityEngine.GUIStyle::CalcSize"); return default; }
    }
}
