// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GUIStyleState
    {
        public global::UnityEngine.Color textColor { set { global::Porteo.Falta.Llamada("UnityEngine.GUIStyleState::textColor="); } }
    }
}
