// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class GUISkin : global::UnityEngine.ScriptableObject
    {
        public global::UnityEngine.Font font { set { global::Porteo.Falta.Llamada("UnityEngine.GUISkin::font="); } }
        public global::UnityEngine.GUIStyle GetStyle(string styleName) { global::Porteo.Falta.Llamada("UnityEngine.GUISkin::GetStyle"); return default; }
    }
}
