// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class GUIUtility
    {
        public static string systemCopyBuffer { get { global::Porteo.Falta.Llamada("UnityEngine.GUIUtility::systemCopyBuffer"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.GUIUtility::systemCopyBuffer="); } }
    }
}
