// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Gyroscope
    {
        public global::UnityEngine.Quaternion attitude { get { global::Porteo.Falta.Llamada("UnityEngine.Gyroscope::attitude"); return default; } }
    }
}
