// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)256, Inherited = true, AllowMultiple = true)]
    public partial class HeaderAttribute : global::UnityEngine.PropertyAttribute
    {
        public HeaderAttribute(string header) { global::Porteo.Falta.Llamada("UnityEngine.HeaderAttribute::.ctor"); }
    }
}
