// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class HideInInspector : global::System.Attribute
    {
        public HideInInspector() { global::Porteo.Falta.Llamada("UnityEngine.HideInInspector::.ctor"); }
    }
}
