// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ImageEffectTransformsToLDR : global::System.Attribute
    {
        public ImageEffectTransformsToLDR() { global::Porteo.Falta.Llamada("UnityEngine.ImageEffectTransformsToLDR::.ctor"); }
    }
}
