// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum IMECompositionMode : int
    {
        Auto = 0,
        On = 1,
        Off = 2,
    }
}
