// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Input
    {
        public static global::UnityEngine.Vector3 mousePosition { get { global::Porteo.Falta.Llamada("UnityEngine.Input::mousePosition"); return default; } }
        public static global::UnityEngine.Vector2 mouseScrollDelta { get { global::Porteo.Falta.Llamada("UnityEngine.Input::mouseScrollDelta"); return default; } }
        public static global::UnityEngine.IMECompositionMode imeCompositionMode { get { global::Porteo.Falta.Llamada("UnityEngine.Input::imeCompositionMode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Input::imeCompositionMode="); } }
        public static string compositionString { get { global::Porteo.Falta.Llamada("UnityEngine.Input::compositionString"); return default; } }
        public static global::UnityEngine.Vector2 compositionCursorPos { get { global::Porteo.Falta.Llamada("UnityEngine.Input::compositionCursorPos"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Input::compositionCursorPos="); } }
        public static bool mousePresent { get { global::Porteo.Falta.Llamada("UnityEngine.Input::mousePresent"); return default; } }
        public static int touchCount { get { global::Porteo.Falta.Llamada("UnityEngine.Input::touchCount"); return default; } }
        public static bool touchSupported { get { global::Porteo.Falta.Llamada("UnityEngine.Input::touchSupported"); return default; } }
        public static global::UnityEngine.Gyroscope gyro { get { global::Porteo.Falta.Llamada("UnityEngine.Input::gyro"); return default; } }
        public static global::UnityEngine.Touch[] touches { get { global::Porteo.Falta.Llamada("UnityEngine.Input::touches"); return default; } }
        public static float GetAxis(string axisName) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetAxis"); return default; }
        public static float GetAxisRaw(string axisName) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetAxisRaw"); return default; }
        public static bool GetButtonDown(string buttonName) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetButtonDown"); return default; }
        public static bool GetMouseButton(int button) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetMouseButton"); return default; }
        public static bool GetMouseButtonDown(int button) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetMouseButtonDown"); return default; }
        public static bool GetMouseButtonUp(int button) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetMouseButtonUp"); return default; }
        public static string[] GetJoystickNames() { global::Porteo.Falta.Llamada("UnityEngine.Input::GetJoystickNames"); return default; }
        public static global::UnityEngine.Touch GetTouch(int index) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetTouch"); return default; }
        public static bool GetKey(global::UnityEngine.KeyCode key) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetKey"); return default; }
        public static bool GetKey(string name) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetKey"); return default; }
        public static bool GetKeyUp(global::UnityEngine.KeyCode key) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetKeyUp"); return default; }
        public static bool GetKeyDown(global::UnityEngine.KeyCode key) { global::Porteo.Falta.Llamada("UnityEngine.Input::GetKeyDown"); return default; }
    }
}
