// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class LightmapSettings : global::UnityEngine.Object
    {
        public static global::UnityEngine.LightmapData[] lightmaps { get { global::Porteo.Falta.Llamada("UnityEngine.LightmapSettings::lightmaps"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.LightmapSettings::lightmaps="); } }
        public static global::UnityEngine.LightmapsMode lightmapsMode { get { global::Porteo.Falta.Llamada("UnityEngine.LightmapSettings::lightmapsMode"); return default; } }
    }
}
