// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum LightShadows : int
    {
        None = 0,
        Hard = 1,
        Soft = 2,
    }
}
