// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class LightmapData
    {
        public global::UnityEngine.Texture2D lightmapColor { get { global::Porteo.Falta.Llamada("UnityEngine.LightmapData::lightmapColor"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.LightmapData::lightmapColor="); } }
        public global::UnityEngine.Texture2D lightmapDir { get { global::Porteo.Falta.Llamada("UnityEngine.LightmapData::lightmapDir"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.LightmapData::lightmapDir="); } }
        public LightmapData() { global::Porteo.Falta.Llamada("UnityEngine.LightmapData::.ctor"); }
    }
}
