// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.Flags]
    public enum LightmapBakeType : int
    {
        Realtime = 4,
        Baked = 2,
        Mixed = 1,
    }
}
