// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.Flags]
    public enum LightmapsMode : int
    {
        NonDirectional = 0,
        CombinedDirectional = 1,
        SeparateDirectional = 2,
        Single = 0,
        Dual = 1,
        Directional = 2,
    }
}
