// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class MaterialPropertyBlock
    {
        public MaterialPropertyBlock() { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::.ctor"); }
        public void SetColor(int nameID, global::UnityEngine.Color value) { global::Porteo.Falta.Llamada("UnityEngine.MaterialPropertyBlock::SetColor"); }
    }
}
