// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class MeshCollider : global::UnityEngine.Collider
    {
        public bool convex { get { global::Porteo.Falta.Llamada("UnityEngine.MeshCollider::convex"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.MeshCollider::convex="); } }
    }
}
