// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ParticleSystem : global::UnityEngine.Component
    {
        public bool isPlaying { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::isPlaying"); return default; } }
        public global::UnityEngine.ParticleSystem.MainModule main { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::main"); return default; } }
        public global::UnityEngine.ParticleSystem.EmissionModule emission { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::emission"); return default; } }
        public global::UnityEngine.ParticleSystem.TextureSheetAnimationModule textureSheetAnimation { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::textureSheetAnimation"); return default; } }
        public int GetParticles(global::UnityEngine.ParticleSystem.Particle[] particles) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::GetParticles"); return default; }
        public void Simulate(float t, bool withChildren, bool restart) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Simulate"); }
        public void Play(bool withChildren) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Play"); }
        public void Play() { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Play"); }
        public void Stop(bool withChildren, global::UnityEngine.ParticleSystemStopBehavior stopBehavior) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Stop"); }
        public void Stop(bool withChildren) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Stop"); }
        public void Stop() { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::Stop"); }
        public bool IsAlive(bool withChildren) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem::IsAlive"); return default; }
        public partial struct EmissionModule
        {
            public global::UnityEngine.ParticleSystem m_ParticleSystem;
            public bool enabled { set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/EmissionModule::enabled="); } }
        }
        public partial struct MainModule
        {
            public global::UnityEngine.ParticleSystem m_ParticleSystem;
            public float duration { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::duration"); return default; } }
            public bool loop { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::loop"); return default; } }
            public global::UnityEngine.ParticleSystem.MinMaxGradient startColor { set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::startColor="); } }
            public global::UnityEngine.ParticleSystemSimulationSpace simulationSpace { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::simulationSpace"); return default; } }
            public int maxParticles { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MainModule::maxParticles"); return default; } }
        }
        public partial struct MinMaxCurve
        {
            public global::UnityEngine.ParticleSystemCurveMode m_Mode;
            public float m_CurveMultiplier;
            public global::UnityEngine.AnimationCurve m_CurveMin;
            public global::UnityEngine.AnimationCurve m_CurveMax;
            public float m_ConstantMin;
            public float m_ConstantMax;
            public float Evaluate(float time) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MinMaxCurve::Evaluate"); return default; }
        }
        public partial struct MinMaxGradient
        {
            public global::UnityEngine.ParticleSystemGradientMode m_Mode;
            public global::UnityEngine.Gradient m_GradientMin;
            public global::UnityEngine.Gradient m_GradientMax;
            public global::UnityEngine.Color m_ColorMin;
            public global::UnityEngine.Color m_ColorMax;
            public global::UnityEngine.ParticleSystemGradientMode mode { set { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MinMaxGradient::mode="); } }
            public MinMaxGradient(global::UnityEngine.Color color) { this = default; }
            public MinMaxGradient(global::UnityEngine.Gradient gradient) { this = default; }
            public MinMaxGradient(global::UnityEngine.Color min, global::UnityEngine.Color max) { this = default; }
            public static implicit operator global::UnityEngine.ParticleSystem.MinMaxGradient(global::UnityEngine.Gradient gradient) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/MinMaxGradient::op_Implicit"); return default; }
        }
        public partial struct Particle
        {
            public global::UnityEngine.Vector3 m_Position;
            public global::UnityEngine.Vector3 m_Velocity;
            public global::UnityEngine.Vector3 m_AnimatedVelocity;
            public global::UnityEngine.Vector3 m_InitialVelocity;
            public global::UnityEngine.Vector3 m_AxisOfRotation;
            public global::UnityEngine.Vector3 m_Rotation;
            public global::UnityEngine.Vector3 m_AngularVelocity;
            public global::UnityEngine.Vector3 m_StartSize;
            public global::UnityEngine.Color32 m_StartColor;
            public uint m_RandomSeed;
            public float m_Lifetime;
            public float m_StartLifetime;
            public float m_EmitAccumulator0;
            public float m_EmitAccumulator1;
            public uint m_Flags;
            public global::UnityEngine.Vector3 position { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::position"); return default; } }
            public float remainingLifetime { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::remainingLifetime"); return default; } }
            public float startLifetime { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::startLifetime"); return default; } }
            public global::UnityEngine.Vector3 rotation3D { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::rotation3D"); return default; } }
            public global::UnityEngine.Vector3 GetCurrentSize3D(global::UnityEngine.ParticleSystem system) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::GetCurrentSize3D"); return default; }
            public global::UnityEngine.Color32 GetCurrentColor(global::UnityEngine.ParticleSystem system) { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/Particle::GetCurrentColor"); return default; }
        }
        public partial struct TextureSheetAnimationModule
        {
            public global::UnityEngine.ParticleSystem m_ParticleSystem;
            public bool enabled { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::enabled"); return default; } }
            public int numTilesX { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::numTilesX"); return default; } }
            public int numTilesY { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::numTilesY"); return default; } }
            public global::UnityEngine.ParticleSystem.MinMaxCurve frameOverTime { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::frameOverTime"); return default; } }
            public int cycleCount { get { global::Porteo.Falta.Llamada("UnityEngine.ParticleSystem/TextureSheetAnimationModule::cycleCount"); return default; } }
        }
    }
}
