// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum ParticleSystemStopBehavior : int
    {
        StopEmittingAndClear = 0,
        StopEmitting = 1,
    }
}
