// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ParticleSystem
    {
        public partial struct EmissionModule
        {
        }
        public partial struct MainModule
        {
        }
        public partial struct MinMaxCurve
        {
        }
        public partial struct MinMaxGradient
        {
        }
        public partial struct Particle
        {
        }
        public partial struct TextureSheetAnimationModule
        {
        }
    }
}
