// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Physics
    {
        public static global::UnityEngine.Vector3 gravity { get { global::Porteo.Falta.Llamada("UnityEngine.Physics::gravity"); return default; } }
        public static void IgnoreCollision(global::UnityEngine.Collider collider1, global::UnityEngine.Collider collider2, bool ignore) { global::Porteo.Falta.Llamada("UnityEngine.Physics::IgnoreCollision"); }
        public static void IgnoreLayerCollision(int layer1, int layer2) { global::Porteo.Falta.Llamada("UnityEngine.Physics::IgnoreLayerCollision"); }
        public static bool Raycast(global::UnityEngine.Vector3 origin, global::UnityEngine.Vector3 direction, float maxDistance, int layerMask, global::UnityEngine.QueryTriggerInteraction queryTriggerInteraction) { global::Porteo.Falta.Llamada("UnityEngine.Physics::Raycast"); return default; }
        public static bool Raycast(global::UnityEngine.Vector3 origin, global::UnityEngine.Vector3 direction, float maxDistance) { global::Porteo.Falta.Llamada("UnityEngine.Physics::Raycast"); return default; }
        public static bool Raycast(global::UnityEngine.Vector3 origin, global::UnityEngine.Vector3 direction, out global::UnityEngine.RaycastHit hitInfo, float maxDistance, int layerMask) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::Raycast"); return default;  }
        public static bool Raycast(global::UnityEngine.Vector3 origin, global::UnityEngine.Vector3 direction, out global::UnityEngine.RaycastHit hitInfo, float maxDistance) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::Raycast"); return default;  }
        public static bool Raycast(global::UnityEngine.Ray ray, out global::UnityEngine.RaycastHit hitInfo, float maxDistance, int layerMask, global::UnityEngine.QueryTriggerInteraction queryTriggerInteraction) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::Raycast"); return default;  }
        public static bool Raycast(global::UnityEngine.Ray ray, out global::UnityEngine.RaycastHit hitInfo, float maxDistance, int layerMask) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::Raycast"); return default;  }
        public static bool Raycast(global::UnityEngine.Ray ray, out global::UnityEngine.RaycastHit hitInfo, float maxDistance) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::Raycast"); return default;  }
        public static bool Linecast(global::UnityEngine.Vector3 start, global::UnityEngine.Vector3 end, out global::UnityEngine.RaycastHit hitInfo, int layerMask) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::Linecast"); return default;  }
        public static bool CapsuleCast(global::UnityEngine.Vector3 point1, global::UnityEngine.Vector3 point2, float radius, global::UnityEngine.Vector3 direction, out global::UnityEngine.RaycastHit hitInfo, float maxDistance, int layerMask) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::CapsuleCast"); return default;  }
        public static bool SphereCast(global::UnityEngine.Vector3 origin, float radius, global::UnityEngine.Vector3 direction, out global::UnityEngine.RaycastHit hitInfo, float maxDistance, int layerMask) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::SphereCast"); return default;  }
        public static bool SphereCast(global::UnityEngine.Ray ray, float radius, float maxDistance, int layerMask) { global::Porteo.Falta.Llamada("UnityEngine.Physics::SphereCast"); return default; }
        public static bool SphereCast(global::UnityEngine.Ray ray, float radius, out global::UnityEngine.RaycastHit hitInfo, float maxDistance, int layerMask, global::UnityEngine.QueryTriggerInteraction queryTriggerInteraction) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::SphereCast"); return default;  }
        public static bool SphereCast(global::UnityEngine.Ray ray, float radius, out global::UnityEngine.RaycastHit hitInfo, float maxDistance, int layerMask) { hitInfo = default;  global::Porteo.Falta.Llamada("UnityEngine.Physics::SphereCast"); return default;  }
        public static global::UnityEngine.RaycastHit[] RaycastAll(global::UnityEngine.Ray ray, float maxDistance, int layerMask, global::UnityEngine.QueryTriggerInteraction queryTriggerInteraction) { global::Porteo.Falta.Llamada("UnityEngine.Physics::RaycastAll"); return default; }
        public static global::UnityEngine.RaycastHit[] SphereCastAll(global::UnityEngine.Vector3 origin, float radius, global::UnityEngine.Vector3 direction, float maxDistance, int layerMask, global::UnityEngine.QueryTriggerInteraction queryTriggerInteraction) { global::Porteo.Falta.Llamada("UnityEngine.Physics::SphereCastAll"); return default; }
        public static global::UnityEngine.RaycastHit[] SphereCastAll(global::UnityEngine.Vector3 origin, float radius, global::UnityEngine.Vector3 direction, float maxDistance, int layerMask) { global::Porteo.Falta.Llamada("UnityEngine.Physics::SphereCastAll"); return default; }
        public static global::UnityEngine.Collider[] OverlapSphere(global::UnityEngine.Vector3 position, float radius, int layerMask, global::UnityEngine.QueryTriggerInteraction queryTriggerInteraction) { global::Porteo.Falta.Llamada("UnityEngine.Physics::OverlapSphere"); return default; }
        public static global::UnityEngine.Collider[] OverlapSphere(global::UnityEngine.Vector3 position, float radius, int layerMask) { global::Porteo.Falta.Llamada("UnityEngine.Physics::OverlapSphere"); return default; }
        public static global::UnityEngine.Collider[] OverlapSphere(global::UnityEngine.Vector3 position, float radius) { global::Porteo.Falta.Llamada("UnityEngine.Physics::OverlapSphere"); return default; }
        public static bool CheckSphere(global::UnityEngine.Vector3 position, float radius, int layerMask) { global::Porteo.Falta.Llamada("UnityEngine.Physics::CheckSphere"); return default; }
        public static bool CheckSphere(global::UnityEngine.Vector3 position, float radius) { global::Porteo.Falta.Llamada("UnityEngine.Physics::CheckSphere"); return default; }
    }
}
