// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct RangeInt
    {
        public int start;
        public int length;
        public int end { get { global::Porteo.Falta.Llamada("UnityEngine.RangeInt::end"); return default; } }
        public RangeInt(int start, int length) { this = default; }
    }
}
