// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct RaycastHit2D
    {
        public global::UnityEngine.Vector2 m_Centroid;
        public global::UnityEngine.Vector2 m_Point;
        public global::UnityEngine.Vector2 m_Normal;
        public float m_Distance;
        public float m_Fraction;
        public int m_Collider;
        public global::UnityEngine.Vector2 point { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit2D::point"); return default; } }
        public global::UnityEngine.Vector2 normal { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit2D::normal"); return default; } }
        public float distance { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit2D::distance"); return default; } }
        public global::UnityEngine.Collider2D collider { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit2D::collider"); return default; } }
    }
}
