// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct RaycastHit
    {
        public global::UnityEngine.Vector3 m_Point;
        public global::UnityEngine.Vector3 m_Normal;
        public uint m_FaceID;
        public float m_Distance;
        public global::UnityEngine.Vector2 m_UV;
        public int m_Collider;
        public global::UnityEngine.Collider collider { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit::collider"); return default; } }
        public global::UnityEngine.Vector3 point { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit::point"); return default; } }
        public global::UnityEngine.Vector3 normal { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit::normal"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit::normal="); } }
        public float distance { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit::distance"); return default; } }
        public global::UnityEngine.Transform transform { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit::transform"); return default; } }
        public global::UnityEngine.Rigidbody rigidbody { get { global::Porteo.Falta.Llamada("UnityEngine.RaycastHit::rigidbody"); return default; } }
    }
}
