// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class ReflectionProbe : global::UnityEngine.Behaviour
    {
        public int RenderProbe() { global::Porteo.Falta.Llamada("UnityEngine.ReflectionProbe::RenderProbe"); return default; }
    }
}
