// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Renderer : global::UnityEngine.Component
    {
        public global::UnityEngine.Bounds bounds { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::bounds"); return default; } }
        public bool enabled { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::enabled"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::enabled="); } }
        public bool isVisible { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::isVisible"); return default; } }
        public global::UnityEngine.Rendering.ShadowCastingMode shadowCastingMode { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::shadowCastingMode"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::shadowCastingMode="); } }
        public bool receiveShadows { set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::receiveShadows="); } }
        public int sortingLayerID { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sortingLayerID"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sortingLayerID="); } }
        public int sortingOrder { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sortingOrder"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sortingOrder="); } }
        public int lightmapIndex { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::lightmapIndex"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::lightmapIndex="); } }
        public global::UnityEngine.Vector4 lightmapScaleOffset { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::lightmapScaleOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::lightmapScaleOffset="); } }
        public global::UnityEngine.Material[] materials { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::materials"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::materials="); } }
        public global::UnityEngine.Material material { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::material"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::material="); } }
        public global::UnityEngine.Material sharedMaterial { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sharedMaterial"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sharedMaterial="); } }
        public global::UnityEngine.Material[] sharedMaterials { get { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sharedMaterials"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Renderer::sharedMaterials="); } }
        public void SetPropertyBlock(global::UnityEngine.MaterialPropertyBlock properties) { global::Porteo.Falta.Llamada("UnityEngine.Renderer::SetPropertyBlock"); }
        public void GetPropertyBlock(global::UnityEngine.MaterialPropertyBlock properties) { global::Porteo.Falta.Llamada("UnityEngine.Renderer::GetPropertyBlock"); }
    }
}
