// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Resolution
    {
        public int m_Width;
        public int m_Height;
        public int m_RefreshRate;
        public int width { get { global::Porteo.Falta.Llamada("UnityEngine.Resolution::width"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Resolution::width="); } }
        public int height { get { global::Porteo.Falta.Llamada("UnityEngine.Resolution::height"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Resolution::height="); } }
        public int refreshRate { get { global::Porteo.Falta.Llamada("UnityEngine.Resolution::refreshRate"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Resolution::refreshRate="); } }
    }
}
