// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Resolution
    {
        public int m_Width;
        public int m_Height;
        public int m_RefreshRate;
    }
}
