// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class Rigidbody : global::UnityEngine.Component
    {
        public global::UnityEngine.Vector3 velocity { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::velocity"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::velocity="); } }
        public global::UnityEngine.Vector3 angularVelocity { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::angularVelocity"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::angularVelocity="); } }
        public float drag { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::drag"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::drag="); } }
        public float angularDrag { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::angularDrag"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::angularDrag="); } }
        public float mass { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::mass"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::mass="); } }
        public bool useGravity { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::useGravity"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::useGravity="); } }
        public bool isKinematic { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::isKinematic"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::isKinematic="); } }
        public bool freezeRotation { set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::freezeRotation="); } }
        public global::UnityEngine.RigidbodyConstraints constraints { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::constraints"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::constraints="); } }
        public global::UnityEngine.CollisionDetectionMode collisionDetectionMode { set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::collisionDetectionMode="); } }
        public global::UnityEngine.Vector3 position { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::position"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::position="); } }
        public global::UnityEngine.Quaternion rotation { get { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::rotation"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::rotation="); } }
        public float maxAngularVelocity { set { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::maxAngularVelocity="); } }
        public void MovePosition(global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::MovePosition"); }
        public void MoveRotation(global::UnityEngine.Quaternion rot) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::MoveRotation"); }
        public void Sleep() { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::Sleep"); }
        public bool IsSleeping() { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::IsSleeping"); return default; }
        public void WakeUp() { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::WakeUp"); }
        public void AddForce(global::UnityEngine.Vector3 force, global::UnityEngine.ForceMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddForce"); }
        public void AddForce(global::UnityEngine.Vector3 force) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddForce"); }
        public void AddForce(float x, float y, float z, global::UnityEngine.ForceMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddForce"); }
        public void AddTorque(global::UnityEngine.Vector3 torque, global::UnityEngine.ForceMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddTorque"); }
        public void AddTorque(global::UnityEngine.Vector3 torque) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddTorque"); }
        public void AddTorque(float x, float y, float z, global::UnityEngine.ForceMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddTorque"); }
        public void AddTorque(float x, float y, float z) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddTorque"); }
        public void AddRelativeTorque(global::UnityEngine.Vector3 torque) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddRelativeTorque"); }
        public void AddForceAtPosition(global::UnityEngine.Vector3 force, global::UnityEngine.Vector3 position, global::UnityEngine.ForceMode mode) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddForceAtPosition"); }
        public void AddForceAtPosition(global::UnityEngine.Vector3 force, global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddForceAtPosition"); }
        public void AddExplosionForce(float explosionForce, global::UnityEngine.Vector3 explosionPosition, float explosionRadius, float upwardsModifier) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddExplosionForce"); }
        public void AddExplosionForce(float explosionForce, global::UnityEngine.Vector3 explosionPosition, float explosionRadius) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::AddExplosionForce"); }
        public global::UnityEngine.Vector3 ClosestPointOnBounds(global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Rigidbody::ClosestPointOnBounds"); return default; }
    }
}
