// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public static partial class ScreenCapture
    {
        public static void CaptureScreenshot(string filename) { global::Porteo.Falta.Llamada("UnityEngine.ScreenCapture::CaptureScreenshot"); }
    }
}
