// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)4, Inherited = true, AllowMultiple = false)]
    public partial class SelectionBaseAttribute : global::System.Attribute
    {
        public SelectionBaseAttribute() { global::Porteo.Falta.Llamada("UnityEngine.SelectionBaseAttribute::.ctor"); }
    }
}
