// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class SerializeField : global::System.Attribute
    {
        public SerializeField() { global::Porteo.Falta.Llamada("UnityEngine.SerializeField::.ctor"); }
    }
}
