// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct SoftJointLimitSpring
    {
        public float m_Spring;
        public float m_Damper;
        public float spring { set { global::Porteo.Falta.Llamada("UnityEngine.SoftJointLimitSpring::spring="); } }
        public float damper { set { global::Porteo.Falta.Llamada("UnityEngine.SoftJointLimitSpring::damper="); } }
    }
}
