// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class SplatPrototype
    {
        public global::UnityEngine.Texture2D texture { get { global::Porteo.Falta.Llamada("UnityEngine.SplatPrototype::texture"); return default; } }
    }
}
