// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class SpriteRenderer : global::UnityEngine.Renderer
    {
        public global::UnityEngine.Sprite sprite { get { global::Porteo.Falta.Llamada("UnityEngine.SpriteRenderer::sprite"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.SpriteRenderer::sprite="); } }
        public global::UnityEngine.Color color { get { global::Porteo.Falta.Llamada("UnityEngine.SpriteRenderer::color"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.SpriteRenderer::color="); } }
    }
}
