// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)256, Inherited = true, AllowMultiple = false)]
    public sealed partial class TextAreaAttribute : global::UnityEngine.PropertyAttribute
    {
        public TextAreaAttribute(int minLines, int maxLines) { global::Porteo.Falta.Llamada("UnityEngine.TextAreaAttribute::.ctor"); }
    }
}
