// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Texture2D
    {
        public static global::UnityEngine.Texture2D whiteTexture { get { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::whiteTexture"); return default; } }
        public Texture2D(int width, int height, global::UnityEngine.TextureFormat textureFormat, bool mipChain, bool linear) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::.ctor"); }
        public Texture2D(int width, int height, global::UnityEngine.TextureFormat textureFormat, bool mipChain) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::.ctor"); }
        public Texture2D(int width, int height) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::.ctor"); }
        public global::UnityEngine.Color32[] GetPixels32() { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetPixels32"); return default; }
        public void SetPixel(int x, int y, global::UnityEngine.Color color) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::SetPixel"); }
        public void SetPixels(global::UnityEngine.Color[] colors) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::SetPixels"); }
        public global::UnityEngine.Color GetPixelBilinear(float x, float y) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetPixelBilinear"); return default; }
        public void Apply() { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::Apply"); }
        public void ReadPixels(global::UnityEngine.Rect source, int destX, int destY) { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::ReadPixels"); }
        public global::UnityEngine.Color[] GetPixels() { global::Porteo.Falta.Llamada("UnityEngine.Texture2D::GetPixels"); return default; }
    }
}
