// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct TextGenerationSettings
    {
        public global::UnityEngine.Font font;
        public global::UnityEngine.Color color;
        public int fontSize;
        public float lineSpacing;
        public bool richText;
        public float scaleFactor;
        public global::UnityEngine.FontStyle fontStyle;
        public global::UnityEngine.TextAnchor textAnchor;
        public bool alignByGeometry;
        public bool resizeTextForBestFit;
        public int resizeTextMinSize;
        public int resizeTextMaxSize;
        public bool updateBounds;
        public global::UnityEngine.VerticalWrapMode verticalOverflow;
        public global::UnityEngine.HorizontalWrapMode horizontalOverflow;
        public global::UnityEngine.Vector2 generationExtents;
        public global::UnityEngine.Vector2 pivot;
        public bool generateOutOfBounds;
    }
}
