// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial class TextAsset
    {
        public string text { get { global::Porteo.Falta.Llamada("UnityEngine.TextAsset::text"); return default; } }
    }
}
