// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class Texture3D
    {
        public Texture3D(int width, int height, int depth, global::UnityEngine.TextureFormat textureFormat, bool mipChain) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::.ctor"); }
        public void SetPixels(global::UnityEngine.Color[] colors) { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::SetPixels"); }
        public void Apply() { global::Porteo.Falta.Llamada("UnityEngine.Texture3D::Apply"); }
    }
}
