// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public enum TouchType : int
    {
        Direct = 0,
        Indirect = 1,
        Stylus = 2,
    }
}
