// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct Touch
    {
        public int m_FingerId;
        public global::UnityEngine.Vector2 m_Position;
        public global::UnityEngine.Vector2 m_RawPosition;
        public global::UnityEngine.Vector2 m_PositionDelta;
        public float m_TimeDelta;
        public int m_TapCount;
        public global::UnityEngine.TouchPhase m_Phase;
        public global::UnityEngine.TouchType m_Type;
        public float m_Pressure;
        public float m_maximumPossiblePressure;
        public float m_Radius;
        public float m_RadiusVariance;
        public float m_AltitudeAngle;
        public float m_AzimuthAngle;
        public int fingerId { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::fingerId"); return default; } }
        public global::UnityEngine.Vector2 position { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::position"); return default; } }
        public int tapCount { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::tapCount"); return default; } }
        public global::UnityEngine.TouchPhase phase { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::phase"); return default; } }
        public float pressure { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::pressure"); return default; } }
        public float maximumPossiblePressure { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::maximumPossiblePressure"); return default; } }
        public global::UnityEngine.TouchType type { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::type"); return default; } }
        public float altitudeAngle { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::altitudeAngle"); return default; } }
        public float azimuthAngle { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::azimuthAngle"); return default; } }
        public float radius { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::radius"); return default; } }
        public float radiusVariance { get { global::Porteo.Falta.Llamada("UnityEngine.Touch::radiusVariance"); return default; } }
    }
}
