// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public sealed partial class TrailRenderer : global::UnityEngine.Renderer
    {
        public void Clear() { global::Porteo.Falta.Llamada("UnityEngine.TrailRenderer::Clear"); }
    }
}
