// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    public partial struct UICharInfo
    {
        public global::UnityEngine.Vector2 cursorPos;
        public float charWidth;
    }
}
