// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine
{
    [System.AttributeUsage((System.AttributeTargets)1, AllowMultiple = true)]
    public partial class UnityAPICompatibilityVersionAttribute : global::System.Attribute
    {
        public UnityAPICompatibilityVersionAttribute(string version) { global::Porteo.Falta.Llamada("UnityEngine.UnityAPICompatibilityVersionAttribute::.ctor"); }
    }
}
