// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore.LowLevel
{
    public sealed partial class FontEngine
    {
        public static global::UnityEngine.TextCore.LowLevel.FontEngineError InitializeFontEngine() { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::InitializeFontEngine"); return default; }
        public static global::UnityEngine.TextCore.LowLevel.FontEngineError LoadFontFace(global::UnityEngine.Font font, int pointSize) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::LoadFontFace"); return default; }
        public static global::UnityEngine.TextCore.FaceInfo GetFaceInfo() { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::GetFaceInfo"); return default; }
        public static uint GetGlyphIndex(uint unicode) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::GetGlyphIndex"); return default; }
        public static bool TryGetGlyphWithUnicodeValue(uint unicode, global::UnityEngine.TextCore.LowLevel.GlyphLoadFlags flags, out global::UnityEngine.TextCore.Glyph glyph) { glyph = default;  global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::TryGetGlyphWithUnicodeValue"); return default;  }
        public static bool TryGetGlyphWithIndexValue(uint glyphIndex, global::UnityEngine.TextCore.LowLevel.GlyphLoadFlags flags, out global::UnityEngine.TextCore.Glyph glyph) { glyph = default;  global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::TryGetGlyphWithIndexValue"); return default;  }
        public static bool TryAddGlyphToTexture(uint glyphIndex, int padding, global::UnityEngine.TextCore.LowLevel.GlyphPackingMode packingMode, global::System.Collections.Generic.List<global::UnityEngine.TextCore.GlyphRect> freeGlyphRects, global::System.Collections.Generic.List<global::UnityEngine.TextCore.GlyphRect> usedGlyphRects, global::UnityEngine.TextCore.LowLevel.GlyphRenderMode renderMode, global::UnityEngine.Texture2D texture, out global::UnityEngine.TextCore.Glyph glyph) { glyph = default;  global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::TryAddGlyphToTexture"); return default;  }
        public static bool TryAddGlyphsToTexture(global::System.Collections.Generic.List<uint> glyphIndexes, int padding, global::UnityEngine.TextCore.LowLevel.GlyphPackingMode packingMode, global::System.Collections.Generic.List<global::UnityEngine.TextCore.GlyphRect> freeGlyphRects, global::System.Collections.Generic.List<global::UnityEngine.TextCore.GlyphRect> usedGlyphRects, global::UnityEngine.TextCore.LowLevel.GlyphRenderMode renderMode, global::UnityEngine.Texture2D texture, out global::UnityEngine.TextCore.Glyph[] glyphs) { glyphs = default;  global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::TryAddGlyphsToTexture"); return default;  }
        public static global::UnityEngine.TextCore.LowLevel.GlyphPairAdjustmentRecord[] GetGlyphPairAdjustmentTable(uint[] glyphIndexes) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::GetGlyphPairAdjustmentTable"); return default; }
        public static global::UnityEngine.TextCore.LowLevel.GlyphPairAdjustmentRecord[] GetGlyphPairAdjustmentRecords(global::System.Collections.Generic.List<uint> glyphIndexes, out int recordCount) { recordCount = default;  global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::GetGlyphPairAdjustmentRecords"); return default;  }
        public static void ResetAtlasTexture(global::UnityEngine.Texture2D texture) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.FontEngine::ResetAtlasTexture"); }
    }
}
