// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore.LowLevel
{
    public partial struct GlyphValueRecord : global::System.IEquatable<global::UnityEngine.TextCore.LowLevel.GlyphValueRecord>
    {
        public float m_XPlacement;
        public float m_YPlacement;
        public float m_XAdvance;
        public float m_YAdvance;
        public float xPlacement { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphValueRecord::xPlacement"); return default; } }
        public float yPlacement { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphValueRecord::yPlacement"); return default; } }
        public float xAdvance { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphValueRecord::xAdvance"); return default; } }
        public float yAdvance { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphValueRecord::yAdvance"); return default; } }
        public bool Equals(global::UnityEngine.TextCore.LowLevel.GlyphValueRecord other) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphValueRecord::Equals"); return default; }
    }
}
