// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore.LowLevel
{
    public partial struct GlyphAdjustmentRecord : global::System.IEquatable<global::UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord>
    {
        public uint m_GlyphIndex;
        public global::UnityEngine.TextCore.LowLevel.GlyphValueRecord m_GlyphValueRecord;
        public uint glyphIndex { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord::glyphIndex"); return default; } }
        public global::UnityEngine.TextCore.LowLevel.GlyphValueRecord glyphValueRecord { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord::glyphValueRecord"); return default; } }
        public bool Equals(global::UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord other) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord::Equals"); return default; }
    }
}
