// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore.LowLevel
{
    public partial struct GlyphPairAdjustmentRecord : global::System.IEquatable<global::UnityEngine.TextCore.LowLevel.GlyphPairAdjustmentRecord>
    {
        public global::UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord m_FirstAdjustmentRecord;
        public global::UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord m_SecondAdjustmentRecord;
        public global::UnityEngine.TextCore.LowLevel.FontFeatureLookupFlags m_FeatureLookupFlags;
        public global::UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord firstAdjustmentRecord { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphPairAdjustmentRecord::firstAdjustmentRecord"); return default; } }
        public global::UnityEngine.TextCore.LowLevel.GlyphAdjustmentRecord secondAdjustmentRecord { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphPairAdjustmentRecord::secondAdjustmentRecord"); return default; } }
        public bool Equals(global::UnityEngine.TextCore.LowLevel.GlyphPairAdjustmentRecord other) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.LowLevel.GlyphPairAdjustmentRecord::Equals"); return default; }
    }
}
