// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace Unity.Profiling
{
    public partial struct ProfilerMarker
    {
        public global::System.IntPtr m_Ptr;
        public ProfilerMarker(string name) { this = default; }
    }
}
