/* ============================================================================
   NEBULOSA — los idiomas que se sumaron el 08/10 (la lista está en
   motor2d/idiomas.js). El de México es el mismo español con tuteo; Egipto,
   Irak y Arabia Saudita usan el árabe estándar. Lo que falte cae en inglés.
   Los números van con cifras occidentales, como en el resto del juego.
   ========================================================================== */

TXT['es-MX'] = Object.assign({}, TXT.es, {
  idioma: 'ELIGE TU IDIOMA', subtitulo: 'FUSIONA EL UNIVERSO', otra: 'OTRA VEZ', sacudon: 'SACUDIDA', seguir: 'CONTINUAR', seguirPartida: 'CONTINUAR LA PARTIDA',
  rayoAyuda: 'TOCA UN CUERPO PARA BORRARLO', ayuda: 'MUEVE EL DEDO PARA APUNTAR Y SUÉLTALO PARA TIRAR. DOS IGUALES SE FUSIONAN.', proba: 'PRUEBA AQUÍ',
});

Object.assign(TXT, {
  ar: {
    idioma: 'اختر لغتك', subtitulo: 'ادمج الكون',
    clasico: 'كلاسيكي', relampago: 'خاطف', relampagoD: 'دقيقتان بأقصى سرعة', diario: 'تحدي اليوم', catalogo: 'الكتالوج',
    controles: 'التحكم', idiomaBtn: 'اللغة', record: 'أفضل نتيجة', hoyRec: 'اليوم {0}', seguirPartida: 'متابعة اللعبة',
    siguiente: 'التالي', peligro: 'خطر!', fin: 'امتلأت الجرة', tiempo: 'انتهى الوقت!', otra: 'مرة أخرى', menu: 'القائمة',
    pausa: 'إيقاف مؤقت', seguir: 'متابعة', reiniciar: 'إعادة', musica: 'الموسيقى', sonido: 'الصوت', si: 'تشغيل', no: 'إيقاف',
    sacudon: 'هزّة', rayo: 'صاعقة', rayoAyuda: 'المس جرمًا لتمحوه', nuevoRecord: 'رقم قياسي جديد!', descubriste: 'اكتشفت {0}!',
    supernova: 'مستعر أعظم!', combo: 'سلسلة', ayuda: 'حرّك إصبعك للتصويب وارفعه للإسقاط. كل جرمين متماثلين يندمجان.',
    apuntar: 'التصويب', dedo: 'مع الإصبع', arrastre: 'السحب', sensib: 'الحساسية', soltar: 'الإسقاط', alLevantar: 'عند رفع الإصبع', conBoton: 'بالزر',
    guia: 'خط التوجيه', zurdo: 'أعسر', vibrar: 'الاهتزاز', tamBotones: 'حجم الأزرار', proba: 'جرّب هنا', restablecer: 'الإعدادات الأصلية', listo: 'تم', volver: 'رجوع',
    tirar: 'إسقاط', puntos: 'نقاط', descubiertos: '{0} من 11',
    nombres: ['غبار نجمي', 'مذنّب', 'القمر', 'المريخ', 'الأرض', 'زحل', 'المشتري', 'قزم أحمر', 'الشمس', 'عملاق أزرق', 'ثقب أسود'],
  },
  id: {
    idioma: 'PILIH BAHASAMU', subtitulo: 'GABUNGKAN ALAM SEMESTA',
    clasico: 'KLASIK', relampago: 'KILAT', relampagoD: '2 MENIT NONSTOP', diario: 'TANTANGAN HARIAN', catalogo: 'KATALOG',
    controles: 'KONTROL', idiomaBtn: 'BAHASA', record: 'REKOR', hoyRec: 'HARI INI {0}', seguirPartida: 'LANJUTKAN PERMAINAN',
    siguiente: 'BERIKUT', peligro: 'BAHAYA!', fin: 'TOPLESNYA PENUH', tiempo: 'WAKTU HABIS!', otra: 'LAGI', menu: 'MENU',
    pausa: 'JEDA', seguir: 'LANJUT', reiniciar: 'ULANGI', musica: 'MUSIK', sonido: 'SUARA', si: 'NYALA', no: 'MATI',
    sacudon: 'GUNCANG', rayo: 'PETIR', rayoAyuda: 'SENTUH BENDA LANGIT UNTUK MENGHAPUSNYA', nuevoRecord: 'REKOR BARU!', descubriste: 'KAMU MENEMUKAN {0}!',
    supernova: 'SUPERNOVA!', combo: 'BERANTAI', ayuda: 'GERAKKAN JARI UNTUK MEMBIDIK DAN ANGKAT UNTUK MENJATUHKAN. DUA YANG SAMA AKAN MENYATU.',
    apuntar: 'MEMBIDIK', dedo: 'IKUTI JARI', arrastre: 'GESER', sensib: 'SENSITIVITAS', soltar: 'MENJATUHKAN', alLevantar: 'SAAT JARI DIANGKAT', conBoton: 'DENGAN TOMBOL',
    guia: 'GARIS BANTU', zurdo: 'KIDAL', vibrar: 'GETAR', tamBotones: 'UKURAN TOMBOL', proba: 'COBA DI SINI', restablecer: 'ATUR ULANG', listo: 'SELESAI', volver: 'KEMBALI',
    tirar: 'JATUHKAN', puntos: 'POIN', descubiertos: '{0} DARI 11',
    nombres: ['DEBU BINTANG', 'KOMET', 'BULAN', 'MARS', 'BUMI', 'SATURNUS', 'YUPITER', 'KATAI MERAH', 'MATAHARI', 'RAKSASA BIRU', 'LUBANG HITAM'],
  },
  ms: {
    idioma: 'PILIH BAHASA ANDA', subtitulo: 'GABUNGKAN ALAM SEMESTA',
    clasico: 'KLASIK', relampago: 'KILAT', relampagoD: '2 MINIT TANPA HENTI', diario: 'CABARAN HARIAN', catalogo: 'KATALOG',
    controles: 'KAWALAN', idiomaBtn: 'BAHASA', record: 'REKOD', hoyRec: 'HARI INI {0}', seguirPartida: 'SAMBUNG PERMAINAN',
    siguiente: 'BERIKUT', peligro: 'BAHAYA!', fin: 'BALANG SUDAH PENUH', tiempo: 'MASA TAMAT!', otra: 'LAGI', menu: 'MENU',
    pausa: 'JEDA', seguir: 'SAMBUNG', reiniciar: 'MULA SEMULA', musica: 'MUZIK', sonido: 'BUNYI', si: 'HIDUP', no: 'MATI',
    sacudon: 'GONCANG', rayo: 'PETIR', rayoAyuda: 'SENTUH JASAD UNTUK MEMADAMNYA', nuevoRecord: 'REKOD BARU!', descubriste: 'ANDA MENEMUI {0}!',
    supernova: 'SUPERNOVA!', combo: 'RANTAIAN', ayuda: 'GERAKKAN JARI UNTUK MENGACU DAN ANGKAT UNTUK MENJATUHKAN. DUA YANG SAMA AKAN BERCANTUM.',
    apuntar: 'MENGACU', dedo: 'IKUT JARI', arrastre: 'SERET', sensib: 'KEPEKAAN', soltar: 'MENJATUHKAN', alLevantar: 'SEMASA DIANGKAT', conBoton: 'DENGAN BUTANG',
    guia: 'GARIS PANDUAN', zurdo: 'KIDAL', vibrar: 'GETARAN', tamBotones: 'SAIZ BUTANG', proba: 'CUBA DI SINI', restablecer: 'TETAP SEMULA', listo: 'SIAP', volver: 'KEMBALI',
    tirar: 'JATUHKAN', puntos: 'MATA', descubiertos: '{0} DARIPADA 11',
    nombres: ['DEBU BINTANG', 'KOMET', 'BULAN', 'MARIKH', 'BUMI', 'ZUHAL', 'MUSYTARI', 'KERDIL MERAH', 'MATAHARI', 'GERGASI BIRU', 'LUBANG HITAM'],
  },
  fil: {
    idioma: 'PUMILI NG WIKA', subtitulo: 'PAGSAMAHIN ANG SANSINUKOB',
    clasico: 'KLASIKO', relampago: 'MABILISAN', relampagoD: '2 MINUTONG BIRADA', diario: 'HAMON NGAYONG ARAW', catalogo: 'KATALOGO',
    controles: 'KONTROL', idiomaBtn: 'WIKA', record: 'PINAKAMATAAS', hoyRec: 'NGAYON {0}', seguirPartida: 'ITULOY ANG LARO',
    siguiente: 'SUSUNOD', peligro: 'PANGANIB!', fin: 'PUNO NA ANG GARAPON', tiempo: 'UBOS NA ANG ORAS!', otra: 'ULIT', menu: 'MENU',
    pausa: 'HINTO', seguir: 'ITULOY', reiniciar: 'ULITIN', musica: 'MUSIKA', sonido: 'TUNOG', si: 'BUKAS', no: 'SARADO',
    sacudon: 'YUGYOG', rayo: 'KIDLAT', rayoAyuda: 'PINDUTIN ANG ISANG BAGAY PARA BURAHIN', nuevoRecord: 'BAGONG RECORD!', descubriste: 'NATUKLASAN MO ANG {0}!',
    supernova: 'SUPERNOVA!', combo: 'KADENA', ayuda: 'IGALAW ANG DALIRI PARA PUMUNTERYA AT IANGAT PARA IHULOG. NAGSASANIB ANG DALAWANG MAGKAPAREHO.',
    apuntar: 'PAGPUNTERYA', dedo: 'SUNDAN ANG DALIRI', arrastre: 'HILA', sensib: 'SENSITIBIDAD', soltar: 'PAGHULOG', alLevantar: 'PAG-ANGAT', conBoton: 'MAY BUTONES',
    guia: 'GABAY NA LINYA', zurdo: 'KALIWETE', vibrar: 'VIBRATE', tamBotones: 'LAKI NG BUTONES', proba: 'SUBUKAN DITO', restablecer: 'I-RESET', listo: 'TAPOS', volver: 'BUMALIK',
    tirar: 'IHULOG', puntos: 'PUNTOS', descubiertos: '{0} SA 11',
    nombres: ['ALIKABOK NG BITUIN', 'KOMETA', 'BUWAN', 'MARTE', 'DAIGDIG', 'SATURNO', 'HUPITER', 'PULANG UNANO', 'ARAW', 'ASUL NA HIGANTE', 'ITIM NA BUTAS'],
  },
  tr: {
    idioma: 'DİLİNİ SEÇ', subtitulo: 'EVRENİ BİRLEŞTİR',
    clasico: 'KLASİK', relampago: 'YILDIRIM', relampagoD: '2 DAKİKA TAM GAZ', diario: 'GÜNÜN GÖREVİ', catalogo: 'KATALOG',
    controles: 'KONTROLLER', idiomaBtn: 'DİL', record: 'REKOR', hoyRec: 'BUGÜN {0}', seguirPartida: 'OYUNA DEVAM ET',
    siguiente: 'SIRADAKİ', peligro: 'TEHLİKE!', fin: 'KAVANOZ DOLDU', tiempo: 'SÜRE BİTTİ!', otra: 'TEKRAR', menu: 'MENÜ',
    pausa: 'DURAKLAT', seguir: 'DEVAM', reiniciar: 'YENİDEN BAŞLAT', musica: 'MÜZİK', sonido: 'SES', si: 'AÇIK', no: 'KAPALI',
    sacudon: 'SARSINTI', rayo: 'ŞİMŞEK', rayoAyuda: 'SİLMEK İÇİN BİR CİSME DOKUN', nuevoRecord: 'YENİ REKOR!', descubriste: 'YENİ KEŞİF: {0}!',
    supernova: 'SÜPERNOVA!', combo: 'ZİNCİR', ayuda: 'NİŞAN ALMAK İÇİN PARMAĞINI KAYDIR, BIRAKMAK İÇİN KALDIR. İKİ AYNI CİSİM BİRLEŞİR.',
    apuntar: 'NİŞAN', dedo: 'PARMAKLA', arrastre: 'SÜRÜKLE', sensib: 'HASSASİYET', soltar: 'BIRAKMA', alLevantar: 'KALDIRINCA', conBoton: 'DÜĞMEYLE',
    guia: 'KILAVUZ ÇİZGİ', zurdo: 'SOLAK', vibrar: 'TİTREŞİM', tamBotones: 'DÜĞME BOYUTU', proba: 'BURADA DENE', restablecer: 'SIFIRLA', listo: 'TAMAM', volver: 'GERİ',
    tirar: 'BIRAK', puntos: 'PUAN', descubiertos: '{0} / 11',
    nombres: ['YILDIZ TOZU', 'KUYRUKLU YILDIZ', 'AY', 'MARS', 'DÜNYA', 'SATÜRN', 'JÜPİTER', 'KIRMIZI CÜCE', 'GÜNEŞ', 'MAVİ DEV', 'KARA DELİK'],
  },
  ur: {
    idioma: 'اپنی زبان چنیں', subtitulo: 'کائنات کو ملائیں',
    clasico: 'کلاسک', relampago: 'تیز رفتار', relampagoD: '2 منٹ پوری رفتار سے', diario: 'آج کا چیلنج', catalogo: 'فہرست',
    controles: 'کنٹرولز', idiomaBtn: 'زبان', record: 'بہترین', hoyRec: 'آج {0}', seguirPartida: 'کھیل جاری رکھیں',
    siguiente: 'اگلا', peligro: 'خطرہ!', fin: 'مرتبان بھر گیا', tiempo: 'وقت ختم!', otra: 'دوبارہ', menu: 'مینو',
    pausa: 'وقفہ', seguir: 'جاری رکھیں', reiniciar: 'دوبارہ شروع', musica: 'موسیقی', sonido: 'آواز', si: 'آن', no: 'آف',
    sacudon: 'جھٹکا', rayo: 'بجلی', rayoAyuda: 'مٹانے کے لیے کسی جسم کو چھوئیں', nuevoRecord: 'نیا ریکارڈ!', descubriste: 'آپ نے {0} دریافت کیا!',
    supernova: 'سپرنووا!', combo: 'سلسلہ', ayuda: 'نشانہ لینے کے لیے انگلی ہلائیں اور گرانے کے لیے اٹھائیں۔ دو ایک جیسے آپس میں مل جاتے ہیں۔',
    apuntar: 'نشانہ', dedo: 'انگلی کے ساتھ', arrastre: 'گھسیٹنا', sensib: 'حساسیت', soltar: 'گرانا', alLevantar: 'انگلی اٹھانے پر', conBoton: 'بٹن سے',
    guia: 'رہنما لکیر', zurdo: 'بائیں ہاتھ والا', vibrar: 'تھرتھراہٹ', tamBotones: 'بٹنوں کا سائز', proba: 'یہاں آزمائیں', restablecer: 'ری سیٹ', listo: 'ہو گیا', volver: 'واپس',
    tirar: 'گرائیں', puntos: 'پوائنٹس', descubiertos: '11 میں سے {0}',
    nombres: ['ستاروں کی دھول', 'دمدار ستارہ', 'چاند', 'مریخ', 'زمین', 'زحل', 'مشتری', 'سرخ بونا', 'سورج', 'نیلا دیو', 'بلیک ہول'],
  },
  th: {
    idioma: 'เลือกภาษาของคุณ', subtitulo: 'รวมจักรวาล',
    clasico: 'คลาสสิก', relampago: 'สายฟ้าแลบ', relampagoD: '2 นาทีเต็มสปีด', diario: 'ภารกิจประจำวัน', catalogo: 'แคตตาล็อก',
    controles: 'การควบคุม', idiomaBtn: 'ภาษา', record: 'สถิติ', hoyRec: 'วันนี้ {0}', seguirPartida: 'เล่นต่อจากเดิม',
    siguiente: 'ถัดไป', peligro: 'อันตราย!', fin: 'โหลเต็มแล้ว', tiempo: 'หมดเวลา!', otra: 'อีกครั้ง', menu: 'เมนู',
    pausa: 'หยุดชั่วคราว', seguir: 'เล่นต่อ', reiniciar: 'เริ่มใหม่', musica: 'ดนตรี', sonido: 'เสียง', si: 'เปิด', no: 'ปิด',
    sacudon: 'เขย่า', rayo: 'สายฟ้า', rayoAyuda: 'แตะวัตถุเพื่อลบทิ้ง', nuevoRecord: 'สถิติใหม่!', descubriste: 'คุณค้นพบ {0}!',
    supernova: 'ซูเปอร์โนวา!', combo: 'ต่อเนื่อง', ayuda: 'เลื่อนนิ้วเพื่อเล็ง แล้วยกนิ้วเพื่อปล่อย ของสองชิ้นที่เหมือนกันจะรวมกัน',
    apuntar: 'การเล็ง', dedo: 'ตามนิ้ว', arrastre: 'ลาก', sensib: 'ความไว', soltar: 'การปล่อย', alLevantar: 'เมื่อยกนิ้ว', conBoton: 'ใช้ปุ่ม',
    guia: 'เส้นนำ', zurdo: 'ถนัดซ้าย', vibrar: 'สั่น', tamBotones: 'ขนาดปุ่ม', proba: 'ลองตรงนี้', restablecer: 'คืนค่าเดิม', listo: 'เสร็จ', volver: 'กลับ',
    tirar: 'ปล่อย', puntos: 'คะแนน', descubiertos: '{0} จาก 11',
    nombres: ['ฝุ่นดาว', 'ดาวหาง', 'ดวงจันทร์', 'ดาวอังคาร', 'โลก', 'ดาวเสาร์', 'ดาวพฤหัส', 'ดาวแคระแดง', 'ดวงอาทิตย์', 'ดาวยักษ์สีน้ำเงิน', 'หลุมดำ'],
  },
  my: {
    idioma: 'ဘာသာစကား ရွေးပါ', subtitulo: 'စကြဝဠာကို ပေါင်းစပ်ပါ',
    clasico: 'ဂန္ထဝင်', relampago: 'လျှပ်စီး', relampagoD: '2 မိနစ် အပြင်းဆုံး', diario: 'ယနေ့ စိန်ခေါ်မှု', catalogo: 'စာရင်း',
    controles: 'ထိန်းချုပ်မှု', idiomaBtn: 'ဘာသာစကား', record: 'အမြင့်ဆုံး', hoyRec: 'ယနေ့ {0}', seguirPartida: 'ဆက်ကစားမည်',
    siguiente: 'နောက်', peligro: 'အန္တရာယ်!', fin: 'ဖန်ဘူး ပြည့်သွားပြီ', tiempo: 'အချိန်ကုန်ပြီ!', otra: 'ထပ်ကစား', menu: 'မီနူး',
    pausa: 'ခဏရပ်', seguir: 'ဆက်ရန်', reiniciar: 'အစမှ ပြန်စ', musica: 'ဂီတ', sonido: 'အသံ', si: 'ဖွင့်', no: 'ပိတ်',
    sacudon: 'လှုပ်ခါ', rayo: 'မိုးကြိုး', rayoAyuda: 'ဖျက်ရန် ကိုယ်ထည်တစ်ခုကို ထိပါ', nuevoRecord: 'စံချိန်သစ်!', descubriste: '{0} ကို တွေ့ရှိပြီ!',
    supernova: 'ဆူပါနိုဗာ!', combo: 'ဆက်တိုက်', ayuda: 'ချိန်ရွယ်ရန် လက်ချောင်းကို ရွှေ့ပြီး ချရန် လက်ကို မြှောက်ပါ။ တူညီသော နှစ်ခု ပေါင်းသွားမည်။',
    apuntar: 'ချိန်ရွယ်ခြင်း', dedo: 'လက်ချောင်းနောက်လိုက်', arrastre: 'ဆွဲရွှေ့', sensib: 'အာရုံခံနိုင်မှု', soltar: 'ချခြင်း', alLevantar: 'လက်မြှောက်လျှင်', conBoton: 'ခလုတ်ဖြင့်',
    guia: 'လမ်းညွှန်မျဉ်း', zurdo: 'ဘယ်သန်', vibrar: 'တုန်ခါမှု', tamBotones: 'ခလုတ်အရွယ်', proba: 'ဒီမှာ စမ်းကြည့်ပါ', restablecer: 'မူလအတိုင်း', listo: 'ပြီးပြီ', volver: 'နောက်သို့',
    tirar: 'ချရန်', puntos: 'ရမှတ်', descubiertos: '11 ခုထဲမှ {0}',
    nombres: ['ကြယ်မှုန်', 'ကြယ်တံခွန်', 'လ', 'အင်္ဂါဂြိုဟ်', 'ကမ္ဘာ', 'စနေဂြိုဟ်', 'ကြာသပတေးဂြိုဟ်', 'အနီရောင် ကြယ်ပု', 'နေ', 'အပြာရောင် ကြယ်ကြီး', 'တွင်းနက်'],
  },
  ja: {
    idioma: '言語を選択', subtitulo: '宇宙を合体させよう',
    clasico: 'クラシック', relampago: 'ブリッツ', relampagoD: '2分間の全力勝負', diario: '今日のチャレンジ', catalogo: '図鑑',
    controles: '操作設定', idiomaBtn: '言語', record: 'ベスト', hoyRec: '今日 {0}', seguirPartida: '続きから遊ぶ',
    siguiente: 'つぎ', peligro: '危険！', fin: 'ビンがいっぱい', tiempo: 'タイムアップ！', otra: 'もう一回', menu: 'メニュー',
    pausa: 'ポーズ', seguir: '再開', reiniciar: 'やり直す', musica: '音楽', sonido: '効果音', si: 'オン', no: 'オフ',
    sacudon: 'シェイク', rayo: 'いなずま', rayoAyuda: '天体をタップして消す', nuevoRecord: '新記録！', descubriste: '{0}を発見！',
    supernova: '超新星！', combo: 'れんさ', ayuda: '指を動かしてねらいを決め、離して落とそう。同じもの2つが合体するよ。',
    apuntar: 'ねらい', dedo: '指に追従', arrastre: 'ドラッグ', sensib: '感度', soltar: '落とし方', alLevantar: '指を離したとき', conBoton: 'ボタンで',
    guia: 'ガイド線', zurdo: '左きき', vibrar: '振動', tamBotones: 'ボタンの大きさ', proba: 'ここで試そう', restablecer: '初期設定に戻す', listo: '完了', volver: '戻る',
    tirar: '落とす', puntos: 'ポイント', descubiertos: '{0} / 11',
    nombres: ['星くず', 'すい星', '月', '火星', '地球', '土星', '木星', '赤色矮星', '太陽', '青色巨星', 'ブラックホール'],
  },
});
