// ─────────────────────────────────────────────────────────────────────────────
// LOS DATOS. Sacados del código del original (main.lua/objects.lua/arena.lua de SNKRX, MIT):
// clases y sus bonos por cantidad, multiplicadores de stats por clase, tiers, lo que cuesta cada cosa,
// el oro por nivel, las oleadas, los élites y los jefes. Los nombres de los héroes con nombre propio
// son nuestros (los genéricos, arquero o mago, quedan). {d} en una descripción = el daño de ese nivel.
// ─────────────────────────────────────────────────────────────────────────────

// ── las 16 clases: color, cuántos hacen falta para cada nivel del bono y qué da ──
const CLASES = {
  ranger: { n: { en: "ranger", es: "tirador" }, col: "green", sets: [3, 6], d: { en: "{a}/{b} - [yellow]8%/16%[fg] chance to release a barrage on attack to allied rangers", es: "{a}/{b} - [yellow]8%/16%[fg] de lanzar una ráfaga al atacar, para los tiradores" } },
  warrior: { n: { en: "warrior", es: "guerrero" }, col: "yellow", sets: [3, 6], d: { en: "{a}/{b} - [yellow]+25/+50[fg] defense to allied warriors", es: "{a}/{b} - [yellow]+25/+50[fg] de defensa a los guerreros" } },
  mage: { n: { en: "mage", es: "mago" }, col: "blue", sets: [3, 6], d: { en: "{a}/{b} - [yellow]-15/-30[fg] enemy defense", es: "{a}/{b} - [yellow]-15/-30[fg] de defensa a los enemigos" } },
  rogue: { n: { en: "rogue", es: "pícaro" }, col: "red", sets: [3, 6], d: { en: "{a}/{b} - [yellow]15%/30%[fg] chance to crit to allied rogues, dealing [yellow]4x[fg] damage", es: "{a}/{b} - [yellow]15%/30%[fg] de crítico a los pícaros, que pega [yellow]4x[fg]" } },
  healer: { n: { en: "healer", es: "sanador" }, col: "green", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+15%/+30%[fg] chance to create [yellow]+1[fg] healing orb on healing orb creation", es: "{a}/{b} - [yellow]+15%/+30%[fg] de crear [yellow]+1[fg] orbe de cura al crear uno" } },
  enchanter: { n: { en: "enchanter", es: "encantador" }, col: "blue", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+15%/+25%[fg] damage to all allies", es: "{a}/{b} - [yellow]+15%/+25%[fg] de daño a todos" } },
  nuker: { n: { en: "nuker", es: "destructor" }, col: "red", sets: [3, 6], d: { en: "{a}/{b} - [yellow]+15%/+25%[fg] area damage and size to allied nukers", es: "{a}/{b} - [yellow]+15%/+25%[fg] de daño y tamaño de área a los destructores" } },
  conjurer: { n: { en: "conjurer", es: "invocador" }, col: "orange", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+25%/+50%[fg] construct damage and duration", es: "{a}/{b} - [yellow]+25%/+50%[fg] de daño y duración de construcciones" } },
  psyker: { n: { en: "psyker", es: "psíquico" }, col: "fg", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+2/+4[fg] total psyker orbs and [yellow]+1[fg] orb for each psyker", es: "{a}/{b} - [yellow]+2/+4[fg] orbes psíquicos y [yellow]+1[fg] por cada psíquico" } },
  curser: { n: { en: "curser", es: "maldecidor" }, col: "purple", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+1/+3[fg] max curse targets to allied cursers", es: "{a}/{b} - [yellow]+1/+3[fg] blancos de maldición a los maldecidores" } },
  forcer: { n: { en: "forcer", es: "empujador" }, col: "yellow", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+25%/+50%[fg] knockback force to all allies", es: "{a}/{b} - [yellow]+25%/+50%[fg] de empuje a todos" } },
  swarmer: { n: { en: "swarmer", es: "enjambre" }, col: "orange", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+1/+3[fg] hits to critters", es: "{a}/{b} - [yellow]+1/+3[fg] golpes a los bichitos" } },
  voider: { n: { en: "voider", es: "del vacío" }, col: "purple", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+20%/+40%[fg] damage over time to allied voiders", es: "{a}/{b} - [yellow]+20%/+40%[fg] de daño en el tiempo a los del vacío" } },
  sorcerer: { n: { en: "sorcerer", es: "hechicero" }, col: "blue2", sets: [2, 4, 6], d: { en: "{a}/{b}/{c} - sorcerers repeat their attacks once every [yellow]4/3/2[fg] attacks", es: "{a}/{b}/{c} - los hechiceros repiten su ataque cada [yellow]4/3/2[fg] ataques" } },
  mercenary: { n: { en: "mercenary", es: "mercenario" }, col: "yellow2", sets: [2, 4], d: { en: "{a}/{b} - [yellow]+8%/+16%[fg] chance for enemies to drop gold on death", es: "{a}/{b} - [yellow]+8%/+16%[fg] de que los enemigos suelten oro" } },
  explorer: { n: { en: "explorer", es: "explorador" }, col: "fg", sets: [1], d: { en: "[yellow]+15%[fg] attack speed and damage per active class to allied explorers", es: "[yellow]+15%[fg] de velocidad y daño por cada clase activa a los exploradores" } },
};
// class_stat_multipliers del original
const MULT = {
  ranger: { hp: 1, dmg: 1.2, aspd: 1.5, adm: 1, asz: 1, def: 0.9, mv: 1.2 }, warrior: { hp: 1.4, dmg: 1.1, aspd: 0.9, adm: 1, asz: 1, def: 1.25, mv: 0.9 },
  mage: { hp: 0.6, dmg: 1.4, aspd: 1, adm: 1.25, asz: 1.2, def: 0.75, mv: 1 }, rogue: { hp: 0.8, dmg: 1.3, aspd: 1.1, adm: 0.6, asz: 0.6, def: 0.8, mv: 1.4 },
  healer: { hp: 1.2, dmg: 1, aspd: 0.5, adm: 1, asz: 1, def: 1.2, mv: 1 }, enchanter: { hp: 1.2, dmg: 1, aspd: 1, adm: 1, asz: 1, def: 1.2, mv: 1.2 },
  nuker: { hp: 0.9, dmg: 1, aspd: 0.75, adm: 1.5, asz: 1.5, def: 1, mv: 1 }, conjurer: { hp: 1, dmg: 1, aspd: 1, adm: 1, asz: 1, def: 1, mv: 1 },
  psyker: { hp: 1.5, dmg: 1, aspd: 1, adm: 1, asz: 1, def: 0.5, mv: 1 }, curser: { hp: 1, dmg: 1, aspd: 1, adm: 1, asz: 1, def: 0.75, mv: 1 },
  forcer: { hp: 1.25, dmg: 1.1, aspd: 0.9, adm: 0.75, asz: 0.75, def: 1.2, mv: 1 }, swarmer: { hp: 1.2, dmg: 1, aspd: 1.25, adm: 1, asz: 1, def: 0.75, mv: 0.75 },
  voider: { hp: 0.75, dmg: 1.3, aspd: 1, adm: 0.8, asz: 0.75, def: 0.6, mv: 0.8 }, sorcerer: { hp: 0.8, dmg: 1.3, aspd: 1, adm: 1.2, asz: 1, def: 0.8, mv: 1 },
  mercenary: { hp: 1, dmg: 1, aspd: 1, adm: 1, asz: 1, def: 1, mv: 1 }, explorer: { hp: 1, dmg: 1, aspd: 1, adm: 1, asz: 1, def: 1, mv: 1.25 },
};

// ── los 51 héroes. tier = lo que cuesta. ataca: false = no pega (cura, da bonos, junta oro) ──
const HR = (n, clases, tier, d, ef, ataca = true) => ({ n, clases, tier, d, ef, ataca });
const HEROES = {
  // tier 1
  drifter: HR("Drifter", ["explorer", "psyker"], 1, { en: "shoots a projectile that deals [yellow]{d}[fg] damage", es: "dispara un proyectil de [yellow]{d}[fg] de daño" }, { n: "Experience", en: "[yellow]+15%[fg] attack speed and damage per active class", es: "[yellow]+15%[fg] de velocidad y daño por cada clase activa" }),
  swordsman: HR("Swordsman", ["warrior"], 1, { en: "deals [yellow]{d}[fg] damage in an area, deals extra [yellow]{d015}[fg] damage per unit hit", es: "pega [yellow]{d}[fg] en un área y [yellow]{d015}[fg] más por cada enemigo alcanzado" }, { n: "Cleave", en: "the swordsman's damage is [yellow]doubled", es: "el daño del espadachín se [yellow]duplica" }),
  magician: HR("Magician", ["mage"], 1, { en: "creates a small area that deals [yellow]{d} AoE[fg] damage", es: "crea un área chica de [yellow]{d}[fg] de daño en área" }, { n: "Quick Cast", en: "[yellow]+50%[fg] attack speed every [yellow]12[fg] seconds for [yellow]6[fg] seconds", es: "[yellow]+50%[fg] de velocidad cada [yellow]12[fg] segundos durante [yellow]6" }),
  archer: HR("Archer", ["ranger"], 1, { en: "shoots an arrow that deals [yellow]{d}[fg] damage and pierces", es: "tira una flecha de [yellow]{d}[fg] de daño que atraviesa" }, { n: "Bounce Shot", en: "the arrow ricochets off walls [yellow]3[fg] times", es: "la flecha rebota [yellow]3[fg] veces en las paredes" }),
  scout: HR("Scout", ["rogue"], 1, { en: "throws a knife that deals [yellow]{d}[fg] damage and chains [yellow]3[fg] times", es: "tira un cuchillo de [yellow]{d}[fg] que salta [yellow]3[fg] veces" }, { n: "Dagger Resonance", en: "[yellow]+25%[fg] damage per chain and [yellow]+3[fg] chains", es: "[yellow]+25%[fg] de daño por salto y [yellow]+3[fg] saltos" }),
  cleric: HR("Cleric", ["healer"], 1, { en: "creates [yellow]1[fg] healing orb every [yellow]8[fg] seconds", es: "crea [yellow]1[fg] orbe de cura cada [yellow]8[fg] segundos" }, { n: "Mass Heal", en: "creates [yellow]4[fg] healing orbs every [yellow]8[fg] seconds", es: "crea [yellow]4[fg] orbes de cura cada [yellow]8[fg] segundos" }, false),
  orbweaver: HR("Orbweaver", ["sorcerer"], 1, { en: "launches a slow moving orb that launches projectiles, each dealing [yellow]{d}[fg] damage", es: "lanza un orbe lento que dispara proyectiles de [yellow]{d}[fg] cada uno" }, { n: "Arcane Orb", en: "[yellow]+50%[fg] attack speed for the orb and [yellow]2[fg] projectiles are released per cast", es: "[yellow]+50%[fg] de velocidad del orbe y suelta [yellow]2[fg] proyectiles por vez" }),
  merchant: HR("Merchant", ["mercenary"], 1, { en: "gain [yellow]+1[fg] interest for every [yellow]10[fg] gold, up to a max of [yellow]+10[fg] from the merchant", es: "[yellow]+1[fg] de interés cada [yellow]10[fg] de oro, hasta [yellow]+10[fg] por el mercader" }, { n: "Item Shop", en: "your first item reroll is always free", es: "la primera vuelta de objetos siempre es gratis" }, false),
  // tier 2
  wizard: HR("Wizard", ["mage", "nuker"], 2, { en: "shoots a projectile that deals [yellow]{d} AoE[fg] damage", es: "dispara un proyectil de [yellow]{d}[fg] de daño en área" }, { n: "Magic Missile", en: "the projectile chains [yellow]2[fg] times", es: "el proyectil salta [yellow]2[fg] veces" }),
  bomber: HR("Bomber", ["nuker", "conjurer"], 2, { en: "plants a bomb, when it explodes it deals [yellow]{d2} AoE[fg] damage", es: "planta una bomba que al explotar pega [yellow]{d2}[fg] en área" }, { n: "Demoman", en: "[yellow]+100%[fg] bomb area and damage", es: "[yellow]+100%[fg] de área y daño de la bomba" }),
  sage: HR("Sage", ["nuker", "forcer"], 2, { en: "shoots a slow projectile that draws enemies in", es: "dispara un proyectil lento que atrae a los enemigos" }, { n: "Dimension Compression", en: "when the projectile expires deal [yellow]{d3}[fg] damage to all enemies under its influence", es: "al terminarse pega [yellow]{d3}[fg] a todos los que atrajo" }),
  squire: HR("Squire", ["warrior", "enchanter"], 2, { en: "[yellow]+20%[fg] damage and defense to all allies", es: "[yellow]+20%[fg] de daño y defensa a todos" }, { n: "Shiny Gear", en: "[yellow]+30%[fg] damage, attack speed, movement speed and defense to all allies", es: "[yellow]+30%[fg] de daño, velocidad de ataque, de movimiento y defensa a todos" }, false),
  gunslinger: HR("Gunslinger", ["ranger", "rogue"], 2, { en: "shoots two parallel projectiles, each dealing [yellow]{d}[fg] damage", es: "dispara dos proyectiles paralelos de [yellow]{d}[fg] cada uno" }, { n: "Gun Kata", en: "every 5th attack shoot in rapid succession for [yellow]2[fg] seconds", es: "cada 5 ataques dispara a lo loco durante [yellow]2[fg] segundos" }),
  sentry: HR("Sentry", ["ranger", "conjurer"], 2, { en: "spawns a rotating turret that shoots [yellow]4[fg] projectiles, each dealing [yellow]{d}[fg] damage", es: "pone una torreta giratoria que tira [yellow]4[fg] proyectiles de [yellow]{d}" }, { n: "Sentry Barrage", en: "[yellow]+50%[fg] turret attack speed and the projectiles ricochet [yellow]twice", es: "[yellow]+50%[fg] de velocidad de la torreta y los tiros rebotan [yellow]2[fg] veces" }),
  timekeeper: HR("Timekeeper", ["mage", "enchanter"], 2, { en: "[yellow]+20%[fg] attack speed to all allies", es: "[yellow]+20%[fg] de velocidad de ataque a todos" }, { n: "Quicken", en: "enemies take damage over time [yellow]50%[fg] faster", es: "el daño en el tiempo pega [yellow]50%[fg] más rápido" }, false),
  barbarian: HR("Barbarian", ["curser", "warrior"], 2, { en: "deals [yellow]{d}[fg] AoE damage and stuns enemies hit for [yellow]4[fg] seconds", es: "pega [yellow]{d}[fg] en área y aturde [yellow]4[fg] segundos" }, { n: "Seism", en: "stunned enemies also take [yellow]100%[fg] increased damage", es: "los aturdidos reciben [yellow]100%[fg] más de daño" }),
  frostcaller: HR("Frostcaller", ["mage", "voider"], 2, { en: "nearby enemies take [yellow]{d}[fg] damage per second", es: "los enemigos cerca reciben [yellow]{d}[fg] por segundo" }, { n: "Frostbite", en: "enemies are also slowed by [yellow]60%[fg] while in the area", es: "además quedan [yellow]60%[fg] más lentos en el área" }),
  beastmaster: HR("Beastmaster", ["rogue", "swarmer"], 2, { en: "throws a knife that deals [yellow]{d}[fg] damage, spawn [yellow]2[fg] critters if it crits", es: "tira un cuchillo de [yellow]{d}[fg]; si es crítico salen [yellow]2[fg] bichitos" }, { n: "Call of the Wild", en: "spawn [yellow]4[fg] small critters if the beastmaster gets hit", es: "salen [yellow]4[fg] bichitos cuando le pegan" }),
  jester: HR("Jester", ["curser", "rogue"], 2, { en: "curses [yellow]6[fg] nearby enemies for [yellow]6[fg] seconds, they will explode into [yellow]4[fg] knives on death", es: "maldice a [yellow]6[fg] enemigos por [yellow]6[fg] s: al morir revientan en [yellow]4[fg] cuchillos" }, { n: "Pandemonium", en: "all knives seek enemies and pierce [yellow]2[fg] times", es: "los cuchillos buscan enemigos y atraviesan [yellow]2[fg] veces" }),
  woodcarver: HR("Woodcarver", ["conjurer", "healer"], 2, { en: "carves a statue that creates [yellow]1[fg] healing orb every [yellow]6[fg] seconds", es: "talla una estatua que crea [yellow]1[fg] orbe de cura cada [yellow]6[fg] segundos" }, { n: "World Tree", en: "carves a tree that creates healing orbs [yellow]twice[fg] as fast", es: "talla un árbol que crea orbes [yellow]el doble[fg] de rápido" }, false),
  psychic: HR("Psychic", ["sorcerer", "psyker"], 2, { en: "creates a small area that deals [yellow]{d} AoE[fg] damage", es: "crea un área chica de [yellow]{d}[fg] de daño en área" }, { n: "Mental Strike", en: "the attack can happen from any distance and repeats once", es: "ataca a cualquier distancia y se repite una vez" }),
  witch: HR("Witch", ["sorcerer", "voider"], 2, { en: "creates an area that ricochets and deals [yellow]{d}[fg] damage per second", es: "crea un área que rebota y pega [yellow]{d}[fg] por segundo" }, { n: "Death Pool", en: "the area releases projectiles, each dealing [yellow]{d}[fg] damage and chaining once", es: "el área suelta proyectiles de [yellow]{d}[fg] que saltan una vez" }),
  hushcaller: HR("Hushcaller", ["sorcerer", "curser"], 2, { en: "curses [yellow]5[fg] nearby enemies for [yellow]6[fg] seconds, preventing them from using special attacks", es: "maldice a [yellow]5[fg] enemigos por [yellow]6[fg] s: no pueden usar ataques especiales" }, { n: "Arcane Curse", en: "the curse also deals [yellow]{d}[fg] damage per second", es: "la maldición además pega [yellow]{d}[fg] por segundo" }),
  outlaw: HR("Outlaw", ["warrior", "rogue"], 2, { en: "throws a fan of [yellow]5[fg] knives, each dealing [yellow]{d}[fg] damage", es: "tira un abanico de [yellow]5[fg] cuchillos de [yellow]{d}[fg] cada uno" }, { n: "Flying Daggers", en: "[yellow]+50%[fg] outlaw attack speed and his knives seek enemies", es: "[yellow]+50%[fg] de velocidad y los cuchillos buscan enemigos" }),
  miner: HR("Miner", ["mercenary"], 2, { en: "picking up gold releases [yellow]4[fg] homing projectiles that each deal [yellow]{d}[fg] damage", es: "al juntar oro salen [yellow]4[fg] proyectiles que buscan, de [yellow]{d}[fg] cada uno" }, { n: "Golden Bolts", en: "release [yellow]8[fg] homing projectiles instead and they pierce twice", es: "salen [yellow]8[fg] en vez de 4 y atraviesan dos veces" }, false),
  // tier 3
  tempest: HR("Tempest", ["mage", "nuker"], 3, { en: "deals [yellow]{d} AoE[fg] damage in a large area centered on a random target", es: "pega [yellow]{d}[fg] en un área grande sobre un enemigo al azar" }, { n: "Windfield", en: "slows enemies by [yellow]60%[fg] for [yellow]6[fg] seconds on hit", es: "frena [yellow]60%[fg] a los que alcanza durante [yellow]6[fg] segundos" }),
  sparkweaver: HR("Sparkweaver", ["enchanter"], 3, { en: "infuses projectiles with chain lightning that deals [yellow]20%[fg] damage to [yellow]2[fg] enemies", es: "carga los proyectiles con un rayo que salta a [yellow]2[fg] enemigos con [yellow]20%[fg] del daño" }, { n: "Wide Lightning", en: "chain lightning's trigger area of effect and number of units hit is [yellow]doubled", es: "el alcance del rayo y la cantidad de enemigos se [yellow]duplican" }, false),
  runeblade: HR("Runeblade", ["mage", "rogue"], 3, { en: "throws knives that deal [yellow]{d}[fg] damage, pierce and spiral outwards", es: "tira cuchillos de [yellow]{d}[fg] que atraviesan y salen en espiral" }, { n: "Spiralism", en: "faster projectile speed and tighter turns", es: "cuchillos más rápidos y con giros más cerrados" }),
  mindkeeper: HR("Mindkeeper", ["healer", "psyker"], 3, { en: "creates [yellow]3[fg] healing orbs every time the mindkeeper takes [yellow]25%[fg] of its max HP in damage", es: "crea [yellow]3[fg] orbes de cura cada vez que pierde [yellow]25%[fg] de su vida" }, { n: "Crucio", en: "deal [yellow]double[fg] the damage taken by the mindkeeper to all enemies", es: "pega a todos los enemigos [yellow]el doble[fg] del daño que recibe" }, false),
  engineer: HR("Engineer", ["conjurer"], 3, { en: "drops turrets that shoot bursts of projectiles, each dealing [yellow]{d}[fg] damage", es: "deja torretas que disparan ráfagas de [yellow]{d}[fg] por tiro" }, { n: "Upgrade!!!", en: "drops [yellow]2[fg] additional turrets and grants all turrets [yellow]+50%[fg] damage and attack speed", es: "deja [yellow]2[fg] torretas más y todas tienen [yellow]+50%[fg] de daño y velocidad" }),
  juggernaut: HR("Juggernaut", ["forcer", "warrior"], 3, { en: "deals [yellow]{d}[fg] AoE damage and pushes enemies away with a strong force", es: "pega [yellow]{d}[fg] en área y empuja fuerte a los enemigos" }, { n: "Brutal Impact", en: "enemies pushed by the juggernaut take [yellow]{d4}[fg] damage if they hit a wall", es: "los que empuja reciben [yellow]{d4}[fg] si chocan contra una pared" }),
  pyromancer: HR("Pyromancer", ["mage", "nuker", "voider"], 3, { en: "nearby enemies take [yellow]{d}[fg] damage per second", es: "los enemigos cerca reciben [yellow]{d}[fg] por segundo" }, { n: "Ignite", en: "enemies killed by the pyromancer explode, dealing [yellow]{d} AoE[fg] damage", es: "los que mata explotan y pegan [yellow]{d}[fg] en área" }),
  broodmother: HR("Broodmother", ["swarmer"], 3, { en: "periodically spawn [yellow]1[fg] small critter", es: "cada tanto suelta [yellow]1[fg] bichito" }, { n: "Invasion", en: "[yellow]+100%[fg] critter spawn rate and spawn [yellow]2[fg] critters instead", es: "[yellow]+100%[fg] de ritmo y salen [yellow]2[fg] bichitos por vez" }),
  assassin: HR("Assassin", ["rogue", "voider"], 3, { en: "throws a piercing knife that deals [yellow]{d}[fg] damage + [yellow]{dh}[fg] damage per second", es: "tira un cuchillo que atraviesa: [yellow]{d}[fg] + [yellow]{dh}[fg] de veneno por segundo" }, { n: "Toxic Delivery", en: "poison inflicted from crits deals [yellow]8x[fg] damage", es: "el veneno de los críticos pega [yellow]8x" }),
  dreadbringer: HR("Dreadbringer", ["curser", "voider"], 3, { en: "curses [yellow]6[fg] nearby enemies for [yellow]6[fg] seconds, they will create small void rifts on death", es: "maldice a [yellow]6[fg] enemigos por [yellow]6[fg] s: al morir abren grietas del vacío" }, { n: "Nightmare", en: "[yellow]100%[fg] increased area for the void rifts", es: "[yellow]100%[fg] más grandes las grietas" }, false),
  volleyer: HR("Volleyer", ["ranger", "forcer"], 3, { en: "shoots a barrage of [yellow]3[fg] arrows, each dealing [yellow]{d}[fg] damage and pushing enemies", es: "tira una ráfaga de [yellow]3[fg] flechas de [yellow]{d}[fg] que empujan" }, { n: "Barrage", en: "every 3rd attack the barrage shoots [yellow]15[fg] projectiles and they push harder", es: "cada 3 ataques la ráfaga es de [yellow]15[fg] flechas y empujan más" }),
  hivecaller: HR("Hivecaller", ["curser", "swarmer"], 3, { en: "curses [yellow]8[fg] nearby enemies for [yellow]6[fg] seconds, they will release [yellow]2[fg] critters on death", es: "maldice a [yellow]8[fg] enemigos por [yellow]6[fg] s: al morir sueltan [yellow]2[fg] bichitos" }, { n: "Infestation", en: "[yellow]triples[fg] the number of critters released", es: "[yellow]triplica[fg] los bichitos" }),
  penitent: HR("Penitent", ["psyker", "enchanter"], 3, { en: "deals [yellow]{d2}[fg] damage to self and grants [yellow]+4%[fg] damage to all allies per cast", es: "se pega [yellow]{d2}[fg] a sí mismo y da [yellow]+4%[fg] de daño a todos cada vez" }, { n: "Zealotry", en: "[yellow]2X[fg] penitent max HP and grants [yellow]+12%[fg] damage to all allies per cast instead", es: "[yellow]2X[fg] de vida y da [yellow]+12%[fg] de daño por vez" }, false),
  tinkerer: HR("Tinkerer", ["sorcerer", "conjurer"], 3, { en: "spawns an automaton that shoots a projectile that deals [yellow]{d}[fg] damage", es: "arma un autómata que dispara proyectiles de [yellow]{d}" }, { n: "Formula Efficiency", en: "automatons shoot and move [yellow]50%[fg] faster and release [yellow]12[fg] projectiles on death", es: "los autómatas van y disparan [yellow]50%[fg] más rápido y al romperse sueltan [yellow]12[fg] tiros" }),
  moneylender: HR("Moneylender", ["curser", "mercenary", "voider"], 3, { en: "curses [yellow]3[fg] nearby enemies indefinitely with debt, dealing [yellow]{d}[fg] damage per second", es: "maldice con deuda a [yellow]3[fg] enemigos para siempre: [yellow]{d}[fg] por segundo" }, { n: "Bankruptcy", en: "if the same enemy is cursed [yellow]3[fg] times it takes [yellow]{d10}[fg] damage", es: "si maldice 3 veces al mismo, le pega [yellow]{d10}" }),
  gambler: HR("Gambler", ["mercenary", "sorcerer"], 3, { en: "deal [yellow]2X[fg] damage to a single random enemy where X is how much gold you have", es: "pega [yellow]2X[fg] a un enemigo al azar, donde X es el oro que tenés" }, { n: "Multicast", en: "[yellow]60/40/20%[fg] chance to cast the attack [yellow]2/3/4[fg] times", es: "[yellow]60/40/20%[fg] de lanzarlo [yellow]2/3/4[fg] veces" }),
  // tier 4
  priest: HR("Priest", ["healer"], 4, { en: "creates [yellow]3[fg] healing orbs every [yellow]12[fg] seconds", es: "crea [yellow]3[fg] orbes de cura cada [yellow]12[fg] segundos" }, { n: "Divine Intervention", en: "picks [yellow]3[fg] units at random and grants them a buff that prevents death once", es: "elige [yellow]3[fg] héroes al azar: se salvan de morir una vez" }, false),
  whirlblade: HR("Whirlblade", ["warrior"], 4, { en: "deals [yellow]{d5}[fg] AoE damage", es: "pega [yellow]{d5}[fg] en área" }, { n: "Moulinet", en: "quickly repeats the attack [yellow]3[fg] times", es: "repite el ataque [yellow]3[fg] veces seguidas" }),
  gravitist: HR("Gravitist", ["mage", "psyker", "forcer"], 4, { en: "pulls enemies together for [yellow]2[fg] seconds", es: "junta a los enemigos durante [yellow]2[fg] segundos" }, { n: "Magnetic Force", en: "enemies take [yellow]{d4}[fg] damage and are pushed away when the area expires", es: "al terminar reciben [yellow]{d4}[fg] y salen despedidos" }),
  pixie: HR("Pixie", ["enchanter", "healer"], 4, { en: "creates [yellow]1[fg] healing orb and grants [yellow]1[fg] unit [yellow]+100%[fg] attack speed for [yellow]6[fg] seconds", es: "crea [yellow]1[fg] orbe de cura y da a [yellow]1[fg] héroe [yellow]+100%[fg] de velocidad por [yellow]6[fg] s" }, { n: "Whimsy", en: "creates [yellow]2[fg] healing orbs and grants [yellow]2[fg] units [yellow]+100%[fg] attack speed", es: "crea [yellow]2[fg] orbes y le da la velocidad a [yellow]2[fg] héroes" }, false),
  bladelord: HR("Bladelord", ["warrior", "nuker"], 4, { en: "throws multiple blades that deal [yellow]{d} AoE[fg] damage", es: "tira varias hojas que pegan [yellow]{d}[fg] en área" }, { n: "Blade Resonance", en: "deal additional [yellow]{d033}[fg] damage per enemy hit", es: "pega [yellow]{d033}[fg] más por cada enemigo alcanzado" }),
  plaguedoctor: HR("Plague Doctor", ["nuker", "voider"], 4, { en: "creates an area that deals [yellow]{d}[fg] damage per second", es: "crea un área que pega [yellow]{d}[fg] por segundo" }, { n: "Black Death Steam", en: "nearby enemies take an additional [yellow]{d}[fg] damage per second", es: "los que están cerca reciben [yellow]{d}[fg] más por segundo" }),
  cannoneer: HR("Cannoneer", ["ranger", "nuker"], 4, { en: "shoots a projectile that deals [yellow]{d2} AoE[fg] damage", es: "dispara un cañonazo de [yellow]{d2}[fg] en área" }, { n: "Cannon Barrage", en: "showers the hit area in [yellow]7[fg] additional cannon shots that deal [yellow]{dh} AoE[fg] damage", es: "llueven [yellow]7[fg] cañonazos más de [yellow]{dh}[fg] en área" }),
  magmaturge: HR("Magmaturge", ["sorcerer", "nuker"], 4, { en: "creates a volcano that explodes the nearby area [yellow]4[fg] times, dealing [yellow]{d} AoE[fg] damage", es: "crea un volcán que explota [yellow]4[fg] veces con [yellow]{d}[fg] en área" }, { n: "Lava Burst", en: "the number and speed of explosions is [yellow]doubled", es: "el doble de explosiones y el doble de rápido" }),
  warden: HR("Warden", ["sorcerer", "forcer"], 4, { en: "creates a force field around a random unit that prevents enemies from entering", es: "crea un campo de fuerza alrededor de un héroe que no deja pasar enemigos" }, { n: "Magnetic Field", en: "creates the force field around [yellow]2[fg] units", es: "el campo rodea a [yellow]2[fg] héroes" }),
  blightbow: HR("Blightbow", ["ranger", "swarmer"], 4, { en: "shoots an arrow that deals [yellow]{d}[fg] damage, spawn [yellow]3[fg] critters if it kills", es: "tira una flecha de [yellow]{d}[fg]; si mata salen [yellow]3[fg] bichitos" }, { n: "Corruption", en: "spawn [yellow]2[fg] small critters if the blightbow hits an enemy", es: "salen [yellow]2[fg] bichitos cada vez que pega" }),
  thief: HR("Thief", ["rogue", "mercenary"], 4, { en: "throws a knife that deals [yellow]{d2}[fg] damage and chains [yellow]5[fg] times", es: "tira un cuchillo de [yellow]{d2}[fg] que salta [yellow]5[fg] veces" }, { n: "Ultrakill", en: "if the knife crits it deals [yellow]{d10}[fg] damage, chains [yellow]10[fg] times and grants [yellow]1[fg] gold", es: "si es crítico pega [yellow]{d10}[fg], salta [yellow]10[fg] veces y da [yellow]1[fg] de oro" }),
};
// el color de cada héroe (character_colors del original; no siempre es el de su primera clase)
const COLOR_HEROE = { drifter: "fg", swordsman: "yellow", wizard: "blue", magician: "blue", archer: "green", scout: "red", cleric: "green", outlaw: "red", bladelord: "yellow", tempest: "blue",
  bomber: "orange", sparkweaver: "blue", sage: "purple", squire: "yellow", cannoneer: "orange", gunslinger: "green", sentry: "green", timekeeper: "blue", runeblade: "blue", mindkeeper: "fg",
  engineer: "orange", plaguedoctor: "purple", barbarian: "yellow", juggernaut: "yellow", frostcaller: "blue", pyromancer: "red", blightbow: "orange", beastmaster: "red", jester: "red",
  assassin: "purple", broodmother: "orange", woodcarver: "green", dreadbringer: "purple", gravitist: "fg", volleyer: "green", whirlblade: "yellow", pixie: "green", priest: "green",
  hivecaller: "orange", penitent: "fg", orbweaver: "blue2", tinkerer: "blue2", witch: "purple", hushcaller: "blue2", magmaturge: "red", warden: "yellow", psychic: "fg", miner: "yellow2",
  merchant: "yellow2", moneylender: "purple", gambler: "yellow2", thief: "red" };
for (const [k, h] of Object.entries(HEROES)) { h.id = k; h.col = COLOR_HEROE[k] || CLASES[h.clases[0]].col; }
const POR_TIER = [1, 2, 3, 4].map((t) => Object.keys(HEROES).filter((k) => HEROES[k].tier === t));

// ── los objetos (pasivos). niv: false = no se sube de nivel. Los números van "nivel 1/2/3" ──
const O = (n, d, niv = true) => ({ n, d, niv });
const OBJETOS = {
  centipede: O({ en: "Centipede", es: "Ciempiés" }, { en: "[yellow]+10/20/30%[fg] movement speed", es: "[yellow]+10/20/30%[fg] de velocidad de movimiento" }),
  coil_r: O({ en: "Coil Technique R", es: "Técnica del Rulo D" }, { en: "rotating around yourself to the right releases [yellow]2/3/4[fg] projectiles per second", es: "girar sobre vos mismo a la derecha suelta [yellow]2/3/4[fg] proyectiles por segundo" }),
  coil_l: O({ en: "Coil Technique L", es: "Técnica del Rulo I" }, { en: "rotating around yourself to the left grants [yellow]+15/25/35%[fg] defense to all units", es: "girar sobre vos mismo a la izquierda da [yellow]+15/25/35%[fg] de defensa a todos" }),
  amplify: O({ en: "Amplify", es: "Amplificar" }, { en: "[yellow]+20/35/50%[fg] AoE damage", es: "[yellow]+20/35/50%[fg] de daño en área" }),
  resonance: O({ en: "Resonance", es: "Resonancia" }, { en: "all AoE attacks deal [yellow]+3/5/7%[fg] damage per unit hit", es: "los ataques en área pegan [yellow]+3/5/7%[fg] por cada enemigo alcanzado" }),
  ballista: O({ en: "Ballista", es: "Balista" }, { en: "[yellow]+20/35/50%[fg] projectile damage", es: "[yellow]+20/35/50%[fg] de daño de proyectiles" }),
  void_call: O({ en: "Call of the Void", es: "Llamado del Vacío" }, { en: "[yellow]+30/60/90%[fg] DoT damage", es: "[yellow]+30/60/90%[fg] de daño en el tiempo" }),
  crucio: O({ en: "Shared Pain", es: "Dolor Compartido" }, { en: "taking damage also shares that across all enemies at [yellow]20/30/40%[fg] its value", es: "el daño que recibís se reparte entre todos los enemigos al [yellow]20/30/40%" }),
  speed_3: O({ en: "Speed 3", es: "Velocidad 3" }, { en: "position [yellow]3[fg] has [yellow]+50%[fg] attack speed", es: "el puesto [yellow]3[fg] tiene [yellow]+50%[fg] de velocidad de ataque" }, false),
  damage_4: O({ en: "Damage 4", es: "Daño 4" }, { en: "position [yellow]4[fg] has [yellow]+30%[fg] damage", es: "el puesto [yellow]4[fg] tiene [yellow]+30%[fg] de daño" }, false),
  shoot_5: O({ en: "Shoot 5", es: "Tiro 5" }, { en: "position [yellow]5[fg] shoots [yellow]3[fg] projectiles per second", es: "el puesto [yellow]5[fg] tira [yellow]3[fg] proyectiles por segundo" }, false),
  death_6: O({ en: "Death 6", es: "Muerte 6" }, { en: "position [yellow]6[fg] takes [yellow]10%[fg] of its health as damage every [yellow]3[fg] seconds", es: "el puesto [yellow]6[fg] pierde [yellow]10%[fg] de su vida cada [yellow]3[fg] segundos" }, false),
  lasting_7: O({ en: "Lasting 7", es: "Aguante 7" }, { en: "position [yellow]7[fg] will stay alive for [yellow]10[fg] seconds after dying", es: "el puesto [yellow]7[fg] sigue vivo [yellow]10[fg] segundos después de morir" }, false),
  defensive_stance: O({ en: "Defensive Stance", es: "Guardia Defensiva" }, { en: "first and last positions have [yellow]+10/20/30%[fg] defense", es: "el primero y el último tienen [yellow]+10/20/30%[fg] de defensa" }),
  offensive_stance: O({ en: "Offensive Stance", es: "Guardia Ofensiva" }, { en: "first and last positions have [yellow]+10/20/30%[fg] damage", es: "el primero y el último tienen [yellow]+10/20/30%[fg] de daño" }),
  kinetic_bomb: O({ en: "Kinetic Bomb", es: "Bomba Cinética" }, { en: "when an ally dies it explodes, launching enemies away", es: "cuando muere un héroe explota y despide a los enemigos" }, false),
  porcupine: O({ en: "Porcupine Technique", es: "Técnica del Puercoespín" }, { en: "when an ally dies it explodes, releasing piercing and ricocheting projectiles", es: "cuando muere un héroe suelta proyectiles que atraviesan y rebotan" }, false),
  last_stand: O({ en: "Last Stand", es: "Último en Pie" }, { en: "the last unit alive is fully healed and receives a [yellow]+20%[fg] bonus to all stats", es: "el último que queda se cura entero y gana [yellow]+20%[fg] en todo" }, false),
  seeping: O({ en: "Seeping", es: "Filtración" }, { en: "enemies taking DoT damage have [yellow]-15/25/35%[fg] defense", es: "los enemigos con daño en el tiempo tienen [yellow]-15/25/35%[fg] de defensa" }),
  deceleration: O({ en: "Deceleration", es: "Desaceleración" }, { en: "enemies taking DoT damage have [yellow]-15/25/35%[fg] movement speed", es: "los enemigos con daño en el tiempo van [yellow]15/25/35%[fg] más lentos" }),
  annihilation: O({ en: "Annihilation", es: "Aniquilación" }, { en: "when a voider dies deal its DoT damage to all enemies for [yellow]3[fg] seconds", es: "cuando muere uno del vacío, su daño en el tiempo le pega a todos por [yellow]3[fg] s" }, false),
  malediction: O({ en: "Malediction", es: "Maledicción" }, { en: "[yellow]+1/3/5[fg] max curse targets to all allied cursers", es: "[yellow]+1/3/5[fg] blancos de maldición a los maldecidores" }),
  hextouch: O({ en: "Hextouch", es: "Toque Maldito" }, { en: "enemies take [yellow]10/15/20[fg] damage per second for [yellow]3[fg] seconds when cursed", es: "los maldecidos reciben [yellow]10/15/20[fg] por segundo durante [yellow]3[fg] s" }),
  doom: O({ en: "Whispers of Doom", es: "Susurros de Perdición" }, { en: "curses apply doom, deal [yellow]100/150/200[fg] damage every [yellow]4/3/2[fg] doom instances", es: "las maldiciones suman perdición: [yellow]100/150/200[fg] de daño cada [yellow]4/3/2[fg] marcas" }),
  tremor: O({ en: "Tremor", es: "Temblor" }, { en: "when enemies hit walls they create an area based on the knockback force", es: "los enemigos que chocan con la pared crean un área según el empuje" }, false),
  heavy_impact: O({ en: "Heavy Impact", es: "Impacto Pesado" }, { en: "when enemies hit walls they take damage based on the knockback force", es: "los enemigos que chocan con la pared reciben daño según el empuje" }, false),
  fracture: O({ en: "Fracture", es: "Fractura" }, { en: "when enemies hit walls they explode into projectiles", es: "los enemigos que chocan con la pared revientan en proyectiles" }, false),
  meat_shield: O({ en: "Meat Shield", es: "Escudo de Carne" }, { en: "critters [yellow]block[fg] enemy projectiles", es: "los bichitos [yellow]frenan[fg] los proyectiles enemigos" }, false),
  hive: O({ en: "Hive", es: "Colmena" }, { en: "critters have [yellow]+1/2/3[fg] HP", es: "los bichitos tienen [yellow]+1/2/3[fg] de vida" }),
  baneling: O({ en: "Baneling Burst", es: "Estallido" }, { en: "critters die immediately on contact but also deal [yellow]50/100/150[fg] AoE damage", es: "los bichitos revientan al tocar y pegan [yellow]50/100/150[fg] en área" }),
  blunt_arrow: O({ en: "Blunt Arrow", es: "Flecha Roma" }, { en: "ranger arrows have [yellow]+10/20/30%[fg] chance to knockback", es: "las flechas de tiradores tienen [yellow]10/20/30%[fg] de empujar" }),
  explosive_arrow: O({ en: "Explosive Arrow", es: "Flecha Explosiva" }, { en: "ranger arrows have [yellow]+10/20/30%[fg] chance to deal [yellow]10/20/30%[fg] AoE damage", es: "las flechas de tiradores tienen [yellow]10/20/30%[fg] de explotar con [yellow]10/20/30%[fg] del daño" }),
  machine_arrow: O({ en: "Divine Machine Arrow", es: "Flecha Divina" }, { en: "ranger arrows have a [yellow]10/20/30%[fg] chance to seek and pierce [yellow]1/2/3[fg] times", es: "las flechas de tiradores tienen [yellow]10/20/30%[fg] de buscar y atravesar [yellow]1/2/3[fg] veces" }),
  chronomancy: O({ en: "Chronomancy", es: "Cronomancia" }, { en: "mages cast their spells [yellow]15/25/35%[fg] faster", es: "los magos lanzan [yellow]15/25/35%[fg] más rápido" }),
  awakening: O({ en: "Awakening", es: "Despertar" }, { en: "[yellow]+50/75/100%[fg] attack speed and damage to [yellow]1[fg] mage every round for that round", es: "[yellow]+50/75/100%[fg] de velocidad y daño a [yellow]1[fg] mago cada nivel" }),
  divine_punishment: O({ en: "Divine Punishment", es: "Castigo Divino" }, { en: "deal damage to all enemies based on how many mages you have", es: "pega a todos los enemigos según cuántos magos tengas" }, false),
  assassination: O({ en: "Assassination", es: "Asesinato" }, { en: "crits from rogues deal [yellow]8/10/12x[fg] damage but normal attacks deal [yellow]half[fg] damage", es: "los críticos de pícaros pegan [yellow]8/10/12x[fg] pero lo normal pega [yellow]la mitad" }),
  flying_daggers: O({ en: "Flying Daggers", es: "Dagas Voladoras" }, { en: "all projectiles thrown by rogues chain [yellow]+2/3/4[fg] times", es: "los proyectiles de pícaros saltan [yellow]+2/3/4[fg] veces" }),
  ultimatum: O({ en: "Ultimatum", es: "Ultimátum" }, { en: "projectiles that chain gain [yellow]+10/20/30%[fg] damage with each chain", es: "los proyectiles que saltan ganan [yellow]+10/20/30%[fg] de daño por salto" }),
  magnify: O({ en: "Magnify", es: "Magnificar" }, { en: "[yellow]+20/35/50%[fg] area size", es: "[yellow]+20/35/50%[fg] de tamaño de área" }),
  echo_barrage: O({ en: "Echo Barrage", es: "Eco" }, { en: "[yellow]10/20/30%[fg] chance to create [yellow]1/2/3[fg] secondary AoEs on AoE hit", es: "[yellow]10/20/30%[fg] de crear [yellow]1/2/3[fg] áreas más al pegar en área" }),
  unleash: O({ en: "Unleash", es: "Desatar" }, { en: "all nukers gain [yellow]+1%[fg] area size and damage every second", es: "los destructores ganan [yellow]+1%[fg] de área y daño por segundo" }, false),
  reinforce: O({ en: "Reinforce", es: "Refuerzo" }, { en: "[yellow]+10/20/30%[fg] global damage, defense and aspd if you have one or more enchanters", es: "[yellow]+10/20/30%[fg] de daño, defensa y velocidad si tenés un encantador" }),
  payback: O({ en: "Payback", es: "Revancha" }, { en: "[yellow]+2/5/8%[fg] damage to all allies whenever an enchanter is hit", es: "[yellow]+2/5/8%[fg] de daño a todos cada vez que le pegan a un encantador" }),
  enchanted: O({ en: "Enchanted", es: "Encantado" }, { en: "[yellow]+33/66/99%[fg] attack speed to a random unit if you have two or more enchanters", es: "[yellow]+33/66/99%[fg] de velocidad a un héroe al azar si tenés dos encantadores" }),
  freezing_field: O({ en: "Freezing Field", es: "Campo Helado" }, { en: "creates an area that slows enemies by [yellow]50%[fg] for [yellow]2[fg] seconds on sorcerer spell repeat", es: "cuando un hechicero repite, crea un área que frena [yellow]50%[fg] por [yellow]2[fg] s" }, false),
  burning_field: O({ en: "Burning Field", es: "Campo Ardiente" }, { en: "creates an area that deals [yellow]30[fg] dps for [yellow]2[fg] seconds on sorcerer spell repeat", es: "cuando un hechicero repite, crea un área de [yellow]30[fg] por segundo por [yellow]2[fg] s" }, false),
  gravity_field: O({ en: "Gravity Field", es: "Campo de Gravedad" }, { en: "creates an area that pulls enemies in for [yellow]1[fg] seconds on sorcerer spell repeat", es: "cuando un hechicero repite, crea un área que atrae por [yellow]1[fg] s" }, false),
  magnetism: O({ en: "Magnetism", es: "Magnetismo" }, { en: "gold coins and healing orbs are attracted to the snake from a longer range", es: "el oro y los orbes de cura vienen solos desde más lejos" }, false),
  insurance: O({ en: "Insurance", es: "Seguro" }, { en: "heroes have [yellow]4[fg] times the chance of mercenary's bonus to drop [yellow]2[fg] gold on death", es: "los héroes tienen [yellow]4[fg] veces el bono de mercenario de soltar [yellow]2[fg] de oro al morir" }, false),
  dividends: O({ en: "Dividends", es: "Dividendos" }, { en: "mercenaries deal [yellow]+X%[fg] damage, where X is how much gold you have", es: "los mercenarios pegan [yellow]+X%[fg], donde X es el oro que tenés" }, false),
  berserking: O({ en: "Berserking", es: "Furia" }, { en: "all warriors have up to [yellow]+50/75/100%[fg] attack speed based on missing HP", es: "los guerreros tienen hasta [yellow]+50/75/100%[fg] de velocidad según la vida que les falta" }),
  unwavering: O({ en: "Unwavering Stance", es: "Guardia Firme" }, { en: "all warriors gain [yellow]+4/8/12%[fg] defense every [yellow]5[fg] seconds", es: "los guerreros ganan [yellow]+4/8/12%[fg] de defensa cada [yellow]5[fg] s" }),
  unrelenting: O({ en: "Unrelenting Stance", es: "Guardia Implacable" }, { en: "[yellow]+2/5/8%[fg] defense to all allies whenever a warrior is hit", es: "[yellow]+2/5/8%[fg] de defensa a todos cuando le pegan a un guerrero" }),
  blessing: O({ en: "Blessing", es: "Bendición" }, { en: "[yellow]+10/20/30%[fg] healing effectiveness", es: "[yellow]+10/20/30%[fg] de curación" }),
  haste: O({ en: "Haste", es: "Prisa" }, { en: "[yellow]+50%[fg] movement speed that decays over [yellow]4[fg] seconds on healing orb pick up", es: "[yellow]+50%[fg] de velocidad que se va en [yellow]4[fg] s al juntar un orbe de cura" }, false),
  divine_barrage: O({ en: "Divine Barrage", es: "Ráfaga Divina" }, { en: "[yellow]20/40/60%[fg] chance to release a ricocheting barrage on healing orb pick up", es: "[yellow]20/40/60%[fg] de soltar una ráfaga que rebota al juntar un orbe de cura" }),
  orbitism: O({ en: "Orbitism", es: "Órbita" }, { en: "[yellow]+25/50/75%[fg] psyker orb movement speed", es: "[yellow]+25/50/75%[fg] de velocidad de los orbes psíquicos" }),
  psyker_orbs: O({ en: "Psyker Orbs", es: "Orbes Psíquicos" }, { en: "[yellow]+1/2/4[fg] total psyker orbs", es: "[yellow]+1/2/4[fg] orbes psíquicos" }),
  psychosink: O({ en: "Psychosink", es: "Psicohundimiento" }, { en: "psyker orbs deal [yellow]+40/80/120%[fg] damage", es: "los orbes psíquicos pegan [yellow]+40/80/120%" }),
  rearm: O({ en: "Rearm", es: "Recarga" }, { en: "constructs repeat their attacks once", es: "las construcciones repiten su ataque una vez" }, false),
  taunt: O({ en: "Taunt", es: "Provocar" }, { en: "[yellow]10/20/30%[fg] chance for constructs to taunt nearby enemies on attack", es: "[yellow]10/20/30%[fg] de que las construcciones provoquen a los enemigos cerca" }),
  construct_instability: O({ en: "Construct Instability", es: "Inestabilidad" }, { en: "constructs explode when disappearing, dealing [yellow]100/150/200%[fg] damage", es: "las construcciones explotan al irse con [yellow]100/150/200%[fg] del daño" }),
  intimidation: O({ en: "Intimidation", es: "Intimidación" }, { en: "enemies spawn with [yellow]-10/20/30%[fg] max HP", es: "los enemigos salen con [yellow]10/20/30%[fg] menos de vida" }),
  vulnerability: O({ en: "Vulnerability", es: "Vulnerabilidad" }, { en: "enemies take [yellow]+10/20/30%[fg] damage", es: "los enemigos reciben [yellow]+10/20/30%[fg] de daño" }),
  temporal_chains: O({ en: "Temporal Chains", es: "Cadenas del Tiempo" }, { en: "enemies are [yellow]10/20/30%[fg] slower", es: "los enemigos van [yellow]10/20/30%[fg] más lentos" }),
  ceremonial_dagger: O({ en: "Ceremonial Dagger", es: "Daga Ceremonial" }, { en: "killing an enemy fires a homing dagger", es: "matar a un enemigo dispara una daga que busca" }, false),
  homing_barrage: O({ en: "Homing Barrage", es: "Ráfaga Buscadora" }, { en: "[yellow]8/16/24%[fg] chance to release a homing barrage on enemy kill", es: "[yellow]8/16/24%[fg] de soltar una ráfaga que busca al matar" }),
  critical_strike: O({ en: "Critical Strike", es: "Golpe Crítico" }, { en: "[yellow]5/10/15%[fg] chance for attacks to critically strike, dealing [yellow]2x[fg] damage", es: "[yellow]5/10/15%[fg] de crítico, que pega [yellow]2x" }),
  noxious_strike: O({ en: "Noxious Strike", es: "Golpe Nocivo" }, { en: "[yellow]8/16/24%[fg] chance for attacks to poison, dealing [yellow]20%[fg] dps for [yellow]3[fg] seconds", es: "[yellow]8/16/24%[fg] de envenenar: [yellow]20%[fg] por segundo durante [yellow]3[fg] s" }),
  infesting_strike: O({ en: "Infesting Strike", es: "Golpe Infestante" }, { en: "[yellow]10/20/30%[fg] chance for attacks to spawn [yellow]2[fg] critters on kill", es: "[yellow]10/20/30%[fg] de soltar [yellow]2[fg] bichitos al matar" }),
  kinetic_strike: O({ en: "Kinetic Strike", es: "Golpe Cinético" }, { en: "[yellow]10/20/30%[fg] chance for attacks to push enemies away with high force", es: "[yellow]10/20/30%[fg] de empujar fuerte" }),
  burning_strike: O({ en: "Burning Strike", es: "Golpe Ardiente" }, { en: "[yellow]15%[fg] chance for attacks to burn, dealing [yellow]20%[fg] dps for [yellow]3[fg] seconds", es: "[yellow]15%[fg] de quemar: [yellow]20%[fg] por segundo durante [yellow]3[fg] s" }, false),
  lucky_strike: O({ en: "Lucky Strike", es: "Golpe de Suerte" }, { en: "[yellow]8%[fg] chance for attacks to cause enemies to drop gold on death", es: "[yellow]8%[fg] de que el enemigo suelte oro al morir" }, false),
  healing_strike: O({ en: "Healing Strike", es: "Golpe Sanador" }, { en: "[yellow]8%[fg] chance for attacks to spawn a healing orb on kill", es: "[yellow]8%[fg] de soltar un orbe de cura al matar" }, false),
  stunning_strike: O({ en: "Stunning Strike", es: "Golpe Aturdidor" }, { en: "[yellow]8/16/24%[fg] chance for attacks to stun for [yellow]2[fg] seconds", es: "[yellow]8/16/24%[fg] de aturdir [yellow]2[fg] s" }),
  silencing_strike: O({ en: "Silencing Strike", es: "Golpe Silenciador" }, { en: "[yellow]8/16/24%[fg] chance for attacks to silence for [yellow]2[fg] seconds on hit", es: "[yellow]8/16/24%[fg] de silenciar [yellow]2[fg] s" }),
  culling_strike: O({ en: "Culling Strike", es: "Golpe de Gracia" }, { en: "instantly kill elites below [yellow]10/20/30%[fg] max HP", es: "mata al toque a los élites con menos de [yellow]10/20/30%[fg] de vida" }),
  lightning_strike: O({ en: "Lightning Strike", es: "Golpe de Rayo" }, { en: "[yellow]5/10/15%[fg] chance for projectiles to create chain lightning, dealing [yellow]60/80/100%[fg] damage", es: "[yellow]5/10/15%[fg] de que un proyectil largue un rayo de [yellow]60/80/100%[fg] del daño" }),
  psycholeak: O({ en: "Psycholeak", es: "Psicofuga" }, { en: "position [yellow]1[fg] generates [yellow]1[fg] psyker orb every [yellow]10[fg] seconds", es: "el puesto [yellow]1[fg] genera [yellow]1[fg] orbe psíquico cada [yellow]10[fg] s" }, false),
  divine_blessing: O({ en: "Divine Blessing", es: "Bendición Divina" }, { en: "generate [yellow]1[fg] healing orb every [yellow]8[fg] seconds", es: "genera [yellow]1[fg] orbe de cura cada [yellow]8[fg] s" }, false),
  hardening: O({ en: "Hardening", es: "Endurecer" }, { en: "[yellow]+150%[fg] defense to all allies for [yellow]3[fg] seconds after an ally dies", es: "[yellow]+150%[fg] de defensa a todos por [yellow]3[fg] s cuando muere un héroe" }, false),
};
/** El valor de nivel `n` (1–3) de un texto "a/b/c": para el efecto real. */
const niv3 = (n, a, b, c) => (n >= 3 ? c : n === 2 ? b : a);

// ── los niveles (tablas del original, NG+0) ──
const TIER_PESOS = [null, [90, 10, 0, 0], [80, 15, 5, 0], [75, 20, 5, 0], [70, 20, 10, 0], [70, 20, 10, 0], [65, 25, 10, 0], [60, 25, 15, 0], [55, 25, 15, 5], [50, 30, 15, 5], [50, 30, 15, 5],
  [45, 30, 20, 5], [40, 30, 20, 10], [35, 30, 25, 10], [30, 30, 25, 15], [25, 30, 30, 15], [25, 25, 30, 20], [20, 25, 35, 20], [15, 25, 35, 25], [10, 25, 40, 25], [5, 25, 40, 30], [0, 25, 40, 35], [0, 20, 40, 40], [0, 20, 35, 45], [0, 10, 30, 60], [0, 0, 0, 100]];
const ORO_NIVEL = [null, [3, 3], [3, 3], [5, 6], [4, 5], [5, 8], [8, 10], [8, 10], [12, 14], [14, 18], [10, 13], [12, 15], [18, 20], [10, 14], [12, 16], [14, 18], [12, 12], [12, 12], [20, 24], [8, 12], [10, 14], [20, 28], [32, 32], [36, 36], [48, 48], [100, 100]];
const ELITE_PESOS = [null, [0], [4, 2], [10], [4, 4], [4, 3, 2], [12], [5, 3, 2], [6, 3, 3, 3], [14], [8, 4], [8, 6, 2], [16], [8, 8], [12, 6], [18], [10, 6, 4], [6, 5, 4, 3], [18], [10, 6], [8, 6, 2], [22], [10, 8, 4], [20, 5, 5], [30], [5, 5, 5, 5, 5, 5]];
const ELITE_TIPOS = [null, ["booster"], ["booster", "shooter"], ["booster"], ["booster", "exploder"], ["booster", "exploder", "shooter"], ["booster"], ["booster", "exploder", "headbutter"], ["booster", "exploder", "headbutter", "shooter"],
  ["shooter"], ["exploder", "headbutter"], ["exploder", "headbutter", "tank"], ["exploder"], ["booster", "shooter"], ["booster", "spawner"], ["shooter"], ["booster", "exploder", "spawner"], ["booster", "exploder", "spawner", "shooter"],
  ["spawner"], ["headbutter", "tank"], ["booster", "tank", "spawner"], ["headbutter"], ["booster", "headbutter", "tank"], ["headbutter", "tank", "shooter"], ["tank"], ["booster", "exploder", "headbutter", "tank", "shooter", "spawner"]];
const JEFES = { 6: "booster", 12: "exploder", 18: "swarmer", 24: "forcer", 25: "randomizer" };
const OLEADAS = [null, 2, 3, 4, 3, 4, 4, 5, 5, 5, 5, 5, 7, 6, 6, 7, 7, 8, 10, 8, 8, 10, 12, 14, 16, 25];
const REPARTIDOS = [null, 0, 5, 10, 10, 15, 15, 20, 20, 20, 20, 20, 25, 25, 25, 25, 25, 25, 30, 20, 25, 30, 35, 40, 45, 50];
const TIENDA_ODDS = [null, [70, 20, 10, 0], [50, 30, 15, 5], [25, 45, 20, 10], [10, 25, 45, 20], [5, 15, 30, 50]];
const TIENDA_XP = [0, 3, 4, 5, 6, 0];
// la curva de los enemigos: y[nivel] para los comunes y para los jefes
const Y_ENE = [0, 0, 1, 3, 3, 4, 6, 5, 6, 9, 7, 8, 12, 10, 11, 15, 12, 13, 18, 16, 17, 21, 17, 20, 24, 25];
const Y_JEFE = [0, 0, 0, 3, 0, 0, 6, 0, 0, 9, 0, 0, 12, 0, 0, 18, 0, 0, 40, 0, 0, 32, 0, 0, 64, 90];
const COLOR_ELITE = { booster: "green", exploder: "blue", shooter: "fg", headbutter: "orange", tank: "yellow", spawner: "purple" };
const COLOR_JEFE = { booster: "green", exploder: "blue", swarmer: "purple", forcer: "yellow", randomizer: "fg" };
