// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Sprites
{
    public sealed partial class DataUtility
    {
    }
}
