// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace AOT
{
    [System.AttributeUsage((System.AttributeTargets)64, AllowMultiple = true)]
    public partial class MonoPInvokeCallbackAttribute : global::System.Attribute
    {
        public MonoPInvokeCallbackAttribute(global::System.Type type) { global::Porteo.Falta.Llamada("AOT.MonoPInvokeCallbackAttribute::.ctor"); }
    }
}
