// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.TerrainModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.SplatPrototype))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Terrain))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.TerrainData))]
