// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.Physics2DModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Collider2D))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Physics2D))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.RaycastHit2D))]
