// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace Unity.Collections
{
    public unsafe partial struct NativeArray<T> : global::System.IDisposable, global::System.Collections.Generic.IEnumerable<T>, global::System.Collections.IEnumerable, global::System.IEquatable<global::Unity.Collections.NativeArray<T>> where T : struct
    {
        public void* m_Buffer;
        public int m_Length;
        public global::Unity.Collections.Allocator m_AllocatorLabel;
        public void Dispose() { global::Porteo.Falta.Llamada("Unity.Collections.NativeArray`1::Dispose"); }
        global::System.Collections.Generic.IEnumerator<T> global::System.Collections.Generic.IEnumerable<T>.GetEnumerator() { global::Porteo.Falta.Llamada("Unity.Collections.NativeArray`1::GetEnumerator"); return default; }
        global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() { global::Porteo.Falta.Llamada("Unity.Collections.NativeArray`1::GetEnumerator"); return default; }
        public bool Equals(global::Unity.Collections.NativeArray<T> other) { global::Porteo.Falta.Llamada("Unity.Collections.NativeArray`1::Equals"); return default; }
    }
}
