/* ============================================================================
   DORADO — los idiomas que se sumaron el 08/10 (la lista está en
   motor2d/idiomas.js). El de México es el mismo español con tuteo; Egipto,
   Irak y Arabia Saudita usan el árabe estándar. Las letras de los carriles
   (J·A·Z·Z) quedan como están en la mesa. Lo que falte cae en inglés.
   ========================================================================== */

TXT['es-MX'] = Object.assign({}, TXT.es, {
  idioma: 'ELIGE TU IDIOMA', clasicoD: 'TRES BOLAS · SUBE DE BOTONES A DUEÑO', seguir: 'CONTINUAR', otra: 'OTRA VEZ',
  tirar: 'JALA EL RESORTE', tocarLanzar: 'TOCA PARA LANZAR', ascenso: 'AHORA ERES {0}',
  m_hongos: 'GOLPEA {0} HONGOS', m_blancos: 'DERRIBA {0} BLANCOS', m_carriles: 'COMPLETA J·A·Z·Z', m_copa: 'ATINA A LA COPA {0} VECES',
  m_orbitas: 'HAZ {0} ÓRBITAS', m_molinete: 'GIRA EL MOLINETE {0} VECES',
  arrastra: 'ARRASTRA CADA BOTÓN A DONDE TE QUEDE CÓMODO', proba: 'PRUEBA AQUÍ',
  ayuda1: 'TOCA LA MITAD IZQUIERDA O LA DERECHA DE LA PANTALLA PARA MOVER CADA FLIPPER.', ayuda1b: 'TOCA LOS BOTONES DE ABAJO PARA MOVER CADA FLIPPER.',
  ayuda2: 'PARA LANZAR, JALA EL RESORTE HACIA ABAJO Y SUÉLTALO.', ayuda2b: 'PARA LANZAR, TOCA EL RESORTE.', ayuda3: 'CUMPLE LAS MISIONES PARA SUBIR DE RANGO EN EL HOTEL.', tocar: 'TOCA PARA CONTINUAR',
});

Object.assign(TXT, {
  ar: {
    idioma: 'اختر لغتك', subtitulo: 'بينبول الفندق الكبير',
    clasico: 'كلاسيكي', clasicoD: 'ثلاث كرات · من حامل الحقائب إلى المالك', reloj: 'ضد الساعة', relojD: 'دقيقتان ونصف · كرات بلا نهاية',
    diario: 'تحدي اليوم', diarioD: 'مهام اليوم، نفسها للجميع', controles: 'التحكم', idiomaBtn: 'اللغة',
    record: 'أفضل نتيجة', hoyRec: 'اليوم {0}', bola: 'الكرة {0}/{1}', pausa: 'إيقاف مؤقت', seguir: 'متابعة', reiniciar: 'إعادة', menu: 'القائمة',
    musica: 'الموسيقى', sonido: 'الصوت', si: 'نعم', no: 'لا', otra: 'مرة أخرى', fin: 'انتهت اللعبة', tiempo: 'انتهى الوقت!', nuevoRecord: 'رقم قياسي جديد!',
    volver: 'رجوع', listo: 'تم', restablecer: 'الإعدادات الأصلية',
    tirar: 'اسحب النابض', tocarLanzar: 'المس للإطلاق', teSalvo: 'أنقذتُ الكرة!', jackpot: 'جاكبوت!', multibola: 'كرات متعددة!',
    multiLista: 'الكرات المتعددة جاهزة', bolaExtra: 'كرة إضافية!', tiroMaestro: 'ضربة محترف!', mult: 'المضاعِف ×{0}', orbita: 'مدار!',
    cumplida: 'أنجزت المهمة!', ascenso: 'أصبحت الآن {0}', bonus: 'مكافأة', total: 'المجموع', perdida: 'ضاعت الكرة',
    m_hongos: 'اضرب المصدّات {0} مرة', m_blancos: 'أسقط {0} أهداف', m_carriles: 'أكمل J·A·Z·Z', m_copa: 'أدخل الكرة في الكأس {0} مرات',
    m_orbitas: 'نفّذ {0} مدارات', m_molinete: 'أدر الدوّارة {0} مرة',
    rangos: ['حامل الحقائب', 'نادل', 'ساقي', 'موظف الاستقبال', 'مدير', 'المالك'],
    hongos: 'المصدّات', carriles: 'الممرات', blancos: 'الأهداف', orbitas: 'المدارات', copas: 'الكؤوس', misiones: 'المهام', rango: 'الرتبة', mejorJackpot: 'أفضل جاكبوت',
    modo: 'المضارب', mitades: 'نصفا الشاشة', botones: 'أزرار', tamano: 'الحجم', chico: 'صغير', medio: 'متوسط', grande: 'كبير',
    transp: 'الشفافية', baja: 'منخفضة', media: 'متوسطة', alta: 'عالية', resorte: 'النابض', tirarOp: 'سحب', tocarOp: 'لمس', vibrar: 'الاهتزاز',
    acomodar: 'ترتيب الأزرار', arrastra: 'اسحب كل زر إلى المكان المريح لك', proba: 'جرّب هنا',
    ayuda1: 'المس النصف الأيسر أو الأيمن من الشاشة لتحريك كل مضرب.', ayuda1b: 'المس الأزرار في الأسفل لتحريك كل مضرب.',
    ayuda2: 'للإطلاق، اسحب النابض إلى الأسفل ثم اتركه.', ayuda2b: 'للإطلاق، المس النابض.', ayuda3: 'أنجز المهام لترتقي في رتب الفندق.', tocar: 'المس للمتابعة',
  },
  id: {
    idioma: 'PILIH BAHASAMU', subtitulo: 'PINBALL HOTEL MEGAH',
    clasico: 'KLASIK', clasicoD: 'TIGA BOLA · DARI PORTER JADI PEMILIK', reloj: 'LAWAN WAKTU', relojD: 'DUA SETENGAH MENIT · BOLA TANPA AKHIR',
    diario: 'TANTANGAN HARIAN', diarioD: 'MISI HARI INI, SAMA UNTUK SEMUA', controles: 'KONTROL', idiomaBtn: 'BAHASA',
    record: 'REKOR', hoyRec: 'HARI INI {0}', bola: 'BOLA {0}/{1}', pausa: 'JEDA', seguir: 'LANJUT', reiniciar: 'ULANGI', menu: 'MENU',
    musica: 'MUSIK', sonido: 'SUARA', si: 'YA', no: 'TIDAK', otra: 'LAGI', fin: 'PERMAINAN SELESAI', tiempo: 'WAKTU HABIS!', nuevoRecord: 'REKOR BARU!',
    volver: 'KEMBALI', listo: 'SELESAI', restablecer: 'ATUR ULANG',
    tirar: 'TARIK PEGASNYA', tocarLanzar: 'KETUK UNTUK MELUNCUR', teSalvo: 'BOLA SELAMAT!', jackpot: 'JACKPOT!', multibola: 'MULTIBOLA!',
    multiLista: 'MULTIBOLA SIAP', bolaExtra: 'BOLA EKSTRA!', tiroMaestro: 'TEMBAKAN JITU!', mult: 'PENGGANDA ×{0}', orbita: 'ORBIT!',
    cumplida: 'MISI SELESAI!', ascenso: 'SEKARANG KAMU {0}', bonus: 'BONUS', total: 'TOTAL', perdida: 'BOLA HILANG',
    m_hongos: 'PUKUL {0} BUMPER', m_blancos: 'JATUHKAN {0} TARGET', m_carriles: 'LENGKAPI J·A·Z·Z', m_copa: 'MASUKKAN KE GELAS {0} KALI',
    m_orbitas: 'BUAT {0} ORBIT', m_molinete: 'PUTAR SPINNER {0} KALI',
    rangos: ['PORTER', 'PELAYAN', 'BARTENDER', 'RESEPSIONIS', 'MANAJER', 'PEMILIK'],
    hongos: 'BUMPER', carriles: 'JALUR', blancos: 'TARGET', orbitas: 'ORBIT', copas: 'GELAS', misiones: 'MISI', rango: 'PANGKAT', mejorJackpot: 'JACKPOT TERBAIK',
    modo: 'FLIPPER', mitades: 'SEPARUH LAYAR', botones: 'TOMBOL', tamano: 'UKURAN', chico: 'KECIL', medio: 'SEDANG', grande: 'BESAR',
    transp: 'TRANSPARANSI', baja: 'RENDAH', media: 'SEDANG', alta: 'TINGGI', resorte: 'PEGAS', tirarOp: 'TARIK', tocarOp: 'KETUK', vibrar: 'GETAR',
    acomodar: 'ATUR TOMBOL', arrastra: 'SERET SETIAP TOMBOL KE TEMPAT YANG NYAMAN', proba: 'COBA DI SINI',
    ayuda1: 'KETUK SISI KIRI ATAU KANAN LAYAR UNTUK MENGGERAKKAN TIAP FLIPPER.', ayuda1b: 'KETUK TOMBOL DI BAWAH UNTUK MENGGERAKKAN TIAP FLIPPER.',
    ayuda2: 'UNTUK MELUNCURKAN, TARIK PEGAS KE BAWAH LALU LEPASKAN.', ayuda2b: 'UNTUK MELUNCURKAN, KETUK PEGASNYA.', ayuda3: 'SELESAIKAN MISI UNTUK NAIK PANGKAT DI HOTEL.', tocar: 'KETUK UNTUK LANJUT',
  },
  ms: {
    idioma: 'PILIH BAHASA ANDA', subtitulo: 'PINBALL HOTEL AGUNG',
    clasico: 'KLASIK', clasicoD: 'TIGA BOLA · DARI BELLBOY KE PEMILIK', reloj: 'LAWAN MASA', relojD: 'DUA MINIT SETENGAH · BOLA TANPA HAD',
    diario: 'CABARAN HARIAN', diarioD: 'MISI HARI INI, SAMA UNTUK SEMUA', controles: 'KAWALAN', idiomaBtn: 'BAHASA',
    record: 'REKOD', hoyRec: 'HARI INI {0}', bola: 'BOLA {0}/{1}', pausa: 'JEDA', seguir: 'SAMBUNG', reiniciar: 'MULA SEMULA', menu: 'MENU',
    musica: 'MUZIK', sonido: 'BUNYI', si: 'YA', no: 'TIDAK', otra: 'LAGI', fin: 'PERMAINAN TAMAT', tiempo: 'MASA TAMAT!', nuevoRecord: 'REKOD BAHARU!',
    volver: 'KEMBALI', listo: 'SIAP', restablecer: 'TETAP SEMULA',
    tirar: 'TARIK SPRING', tocarLanzar: 'KETIK UNTUK LANCAR', teSalvo: 'BOLA DISELAMATKAN!', jackpot: 'JACKPOT!', multibola: 'MULTIBOLA!',
    multiLista: 'MULTIBOLA SEDIA', bolaExtra: 'BOLA TAMBAHAN!', tiroMaestro: 'TEMBAKAN HEBAT!', mult: 'PENGGANDA ×{0}', orbita: 'ORBIT!',
    cumplida: 'MISI SELESAI!', ascenso: 'KINI ANDA {0}', bonus: 'BONUS', total: 'JUMLAH', perdida: 'BOLA HILANG',
    m_hongos: 'PUKUL {0} BUMPER', m_blancos: 'JATUHKAN {0} SASARAN', m_carriles: 'LENGKAPKAN J·A·Z·Z', m_copa: 'MASUKKAN KE PIALA {0} KALI',
    m_orbitas: 'BUAT {0} ORBIT', m_molinete: 'PUSING SPINNER {0} KALI',
    rangos: ['BELLBOY', 'PELAYAN', 'BARTENDER', 'PENYAMBUT TETAMU', 'PENGURUS', 'PEMILIK'],
    hongos: 'BUMPER', carriles: 'LORONG', blancos: 'SASARAN', orbitas: 'ORBIT', copas: 'PIALA', misiones: 'MISI', rango: 'PANGKAT', mejorJackpot: 'JACKPOT TERBAIK',
    modo: 'FLIPPER', mitades: 'SEPARUH SKRIN', botones: 'BUTANG', tamano: 'SAIZ', chico: 'KECIL', medio: 'SEDERHANA', grande: 'BESAR',
    transp: 'KELUTSINARAN', baja: 'RENDAH', media: 'SEDERHANA', alta: 'TINGGI', resorte: 'SPRING', tirarOp: 'TARIK', tocarOp: 'KETIK', vibrar: 'GETAR',
    acomodar: 'SUSUN BUTANG', arrastra: 'SERET SETIAP BUTANG KE TEMPAT YANG SELESA', proba: 'CUBA DI SINI',
    ayuda1: 'KETIK SEPARUH KIRI ATAU KANAN SKRIN UNTUK MENGGERAKKAN SETIAP FLIPPER.', ayuda1b: 'KETIK BUTANG DI BAWAH UNTUK MENGGERAKKAN SETIAP FLIPPER.',
    ayuda2: 'UNTUK MELANCAR, TARIK SPRING KE BAWAH DAN LEPASKAN.', ayuda2b: 'UNTUK MELANCAR, KETIK SPRING.', ayuda3: 'SELESAIKAN MISI UNTUK NAIK PANGKAT DI HOTEL.', tocar: 'KETIK UNTUK SAMBUNG',
  },
  fil: {
    idioma: 'PUMILI NG WIKA', subtitulo: 'PINBALL NG GRAND HOTEL',
    clasico: 'KLASIKO', clasicoD: 'TATLONG BOLA · MULA BELLBOY HANGGANG MAY-ARI', reloj: 'LABAN SA ORAS', relojD: "DALAWA'T KALAHATING MINUTO · WALANG-HANGGANG BOLA",
    diario: 'HAMON NGAYONG ARAW', diarioD: 'MGA MISYON NGAYON, PAREHO SA LAHAT', controles: 'KONTROL', idiomaBtn: 'WIKA',
    record: 'REKORD', hoyRec: 'NGAYON {0}', bola: 'BOLA {0}/{1}', pausa: 'HINTO', seguir: 'ITULOY', reiniciar: 'SIMULAN ULIT', menu: 'MENU',
    musica: 'MUSIKA', sonido: 'TUNOG', si: 'OO', no: 'HINDI', otra: 'ULIT', fin: 'TAPOS ANG LARO', tiempo: 'UBOS NA ANG ORAS!', nuevoRecord: 'BAGONG REKORD!',
    volver: 'BUMALIK', listo: 'TAPOS', restablecer: 'I-RESET',
    tirar: 'HILAHIN ANG SPRING', tocarLanzar: 'I-TAP PARA ITIRA', teSalvo: 'NASALBA ANG BOLA!', jackpot: 'JACKPOT!', multibola: 'MULTIBALL!',
    multiLista: 'HANDA NA ANG MULTIBALL', bolaExtra: 'DAGDAG NA BOLA!', tiroMaestro: 'MAHUSAY NA TIRA!', mult: 'MULTIPLIER ×{0}', orbita: 'ORBIT!',
    cumplida: 'TAPOS ANG MISYON!', ascenso: 'IKAW NA ANG {0}', bonus: 'BONUS', total: 'KABUUAN', perdida: 'NAWALA ANG BOLA',
    m_hongos: 'TAMAAN ANG {0} BUMPER', m_blancos: 'PABAGSAKIN ANG {0} TARGET', m_carriles: 'KUMPLETUHIN ANG J·A·Z·Z', m_copa: 'IPASOK SA KOPA NANG {0} BESES',
    m_orbitas: 'GUMAWA NG {0} ORBIT', m_molinete: 'PAIKUTIN ANG SPINNER NANG {0} BESES',
    rangos: ['BELLBOY', 'WAITER', 'BARTENDER', 'CONCIERGE', 'MANAGER', 'MAY-ARI'],
    hongos: 'BUMPER', carriles: 'DAANAN', blancos: 'TARGET', orbitas: 'ORBIT', copas: 'KOPA', misiones: 'MISYON', rango: 'RANGGO', mejorJackpot: 'PINAKAMALAKING JACKPOT',
    modo: 'FLIPPER', mitades: 'KALAHATI', botones: 'PINDUTAN', tamano: 'LAKI', chico: 'MALIIT', medio: 'KATAMTAMAN', grande: 'MALAKI',
    transp: 'LINAW', baja: 'MABABA', media: 'KATAMTAMAN', alta: 'MATAAS', resorte: 'SPRING', tirarOp: 'HILAHIN', tocarOp: 'I-TAP', vibrar: 'VIBRATE',
    acomodar: 'AYUSIN ANG PINDUTAN', arrastra: 'I-DRAG ANG BAWAT PINDUTAN SA KOMPORTABLENG LUGAR', proba: 'SUBUKAN DITO',
    ayuda1: 'I-TAP ANG KALIWA O KANANG BAHAGI NG SCREEN PARA IGALAW ANG BAWAT FLIPPER.', ayuda1b: 'I-TAP ANG MGA PINDUTAN SA IBABA PARA IGALAW ANG BAWAT FLIPPER.',
    ayuda2: 'PARA ITIRA, HILAHIN PABABA ANG SPRING AT BITAWAN.', ayuda2b: 'PARA ITIRA, I-TAP ANG SPRING.', ayuda3: 'TAPUSIN ANG MGA MISYON PARA UMANGAT ANG RANGGO SA HOTEL.', tocar: 'I-TAP PARA ITULOY',
  },
  tr: {
    idioma: 'DİLİNİ SEÇ', subtitulo: 'BÜYÜK OTELİN LANGIRTI',
    clasico: 'KLASİK', clasicoD: 'ÜÇ TOP · KOMİDEN PATRONA', reloj: 'ZAMANA KARŞI', relojD: 'İKİ BUÇUK DAKİKA · SONSUZ TOP',
    diario: 'GÜNÜN GÖREVİ', diarioD: 'BUGÜNÜN GÖREVLERİ, HERKES İÇİN AYNI', controles: 'KONTROLLER', idiomaBtn: 'DİL',
    record: 'REKOR', hoyRec: 'BUGÜN {0}', bola: 'TOP {0}/{1}', pausa: 'DURAKLAT', seguir: 'DEVAM', reiniciar: 'YENİDEN BAŞLAT', menu: 'MENÜ',
    musica: 'MÜZİK', sonido: 'SES', si: 'AÇIK', no: 'KAPALI', otra: 'TEKRAR', fin: 'OYUN BİTTİ', tiempo: 'SÜRE DOLDU!', nuevoRecord: 'YENİ REKOR!',
    volver: 'GERİ', listo: 'TAMAM', restablecer: 'SIFIRLA',
    tirar: 'YAYI ÇEK', tocarLanzar: 'FIRLATMAK İÇİN DOKUN', teSalvo: 'TOP KURTARILDI!', jackpot: 'JACKPOT!', multibola: 'ÇOKLU TOP!',
    multiLista: 'ÇOKLU TOP HAZIR', bolaExtra: 'EKSTRA TOP!', tiroMaestro: 'USTA ATIŞ!', mult: 'ÇARPAN ×{0}', orbita: 'YÖRÜNGE!',
    cumplida: 'GÖREV TAMAM!', ascenso: 'ARTIK {0}', bonus: 'BONUS', total: 'TOPLAM', perdida: 'TOP KAYBOLDU',
    m_hongos: '{0} KEZ TAMPONA VUR', m_blancos: '{0} HEDEF DÜŞÜR', m_carriles: 'J·A·Z·Z TAMAMLA', m_copa: 'KUPAYA {0} KEZ SOK',
    m_orbitas: '{0} YÖRÜNGE YAP', m_molinete: 'ÇARKI {0} KEZ DÖNDÜR',
    rangos: ['KOMİ', 'GARSON', 'BARMEN', 'RESEPSİYONİST', 'MÜDÜR', 'PATRON'],
    hongos: 'TAMPONLAR', carriles: 'ŞERİTLER', blancos: 'HEDEFLER', orbitas: 'YÖRÜNGELER', copas: 'KUPALAR', misiones: 'GÖREVLER', rango: 'RÜTBE', mejorJackpot: 'EN İYİ JACKPOT',
    modo: 'PALETLER', mitades: 'YARIMLAR', botones: 'DÜĞMELER', tamano: 'BOYUT', chico: 'KÜÇÜK', medio: 'ORTA', grande: 'BÜYÜK',
    transp: 'SAYDAMLIK', baja: 'DÜŞÜK', media: 'ORTA', alta: 'YÜKSEK', resorte: 'YAY', tirarOp: 'ÇEK', tocarOp: 'DOKUN', vibrar: 'TİTREŞİM',
    acomodar: 'DÜĞMELERİ YERLEŞTİR', arrastra: 'HER DÜĞMEYİ RAHAT EDECEĞİN YERE SÜRÜKLE', proba: 'BURADA DENE',
    ayuda1: 'HER PALETİ OYNATMAK İÇİN EKRANIN SOL YA DA SAĞ YARISINA DOKUN.', ayuda1b: 'HER PALETİ OYNATMAK İÇİN ALTTAKİ DÜĞMELERE DOKUN.',
    ayuda2: 'FIRLATMAK İÇİN YAYI AŞAĞI ÇEK VE BIRAK.', ayuda2b: 'FIRLATMAK İÇİN YAYA DOKUN.', ayuda3: 'OTELDE RÜTBE ATLAMAK İÇİN GÖREVLERİ TAMAMLA.', tocar: 'DEVAM İÇİN DOKUN',
  },
  ur: {
    idioma: 'اپنی زبان منتخب کریں', subtitulo: 'گرینڈ ہوٹل کا پن بال',
    clasico: 'کلاسک', clasicoD: 'تین گیندیں · بیل بوائے سے مالک تک', reloj: 'وقت کے خلاف', relojD: 'ڈھائی منٹ · لامحدود گیندیں',
    diario: 'آج کا چیلنج', diarioD: 'آج کے مشن، سب کے لیے ایک جیسے', controles: 'کنٹرولز', idiomaBtn: 'زبان',
    record: 'ریکارڈ', hoyRec: 'آج {0}', bola: 'گیند {0}/{1}', pausa: 'وقفہ', seguir: 'جاری رکھیں', reiniciar: 'دوبارہ شروع', menu: 'مینیو',
    musica: 'موسیقی', sonido: 'آواز', si: 'ہاں', no: 'نہیں', otra: 'دوبارہ', fin: 'کھیل ختم', tiempo: 'وقت ختم!', nuevoRecord: 'نیا ریکارڈ!',
    volver: 'واپس', listo: 'ٹھیک ہے', restablecer: 'اصل ترتیب',
    tirar: 'اسپرنگ کھینچیں', tocarLanzar: 'چلانے کے لیے ٹیپ کریں', teSalvo: 'گیند بچ گئی!', jackpot: 'جیک پاٹ!', multibola: 'ملٹی بال!',
    multiLista: 'ملٹی بال تیار', bolaExtra: 'اضافی گیند!', tiroMaestro: 'ماہرانہ شاٹ!', mult: 'ضرب ×{0}', orbita: 'مدار!',
    cumplida: 'مشن مکمل!', ascenso: 'اب آپ {0} ہیں', bonus: 'بونس', total: 'کل', perdida: 'گیند ضائع',
    m_hongos: 'بمپرز کو {0} بار ماریں', m_blancos: '{0} ہدف گرائیں', m_carriles: 'J·A·Z·Z مکمل کریں', m_copa: 'کپ میں {0} بار گیند ڈالیں',
    m_orbitas: '{0} مدار بنائیں', m_molinete: 'اسپنر کو {0} بار گھمائیں',
    rangos: ['بیل بوائے', 'ویٹر', 'بارٹینڈر', 'کنسیئرج', 'مینیجر', 'مالک'],
    hongos: 'بمپرز', carriles: 'راستے', blancos: 'اہداف', orbitas: 'مدار', copas: 'کپ', misiones: 'مشن', rango: 'عہدہ', mejorJackpot: 'بہترین جیک پاٹ',
    modo: 'فلپرز', mitades: 'آدھی اسکرین', botones: 'بٹن', tamano: 'سائز', chico: 'چھوٹا', medio: 'درمیانہ', grande: 'بڑا',
    transp: 'شفافیت', baja: 'کم', media: 'درمیانی', alta: 'زیادہ', resorte: 'اسپرنگ', tirarOp: 'کھینچیں', tocarOp: 'ٹیپ', vibrar: 'تھرتھراہٹ',
    acomodar: 'بٹن ترتیب دیں', arrastra: 'ہر بٹن کو آرام دہ جگہ پر گھسیٹیں', proba: 'یہاں آزمائیں',
    ayuda1: 'ہر فلپر چلانے کے لیے اسکرین کا بایاں یا دایاں حصہ ٹیپ کریں۔', ayuda1b: 'ہر فلپر چلانے کے لیے نیچے والے بٹن ٹیپ کریں۔',
    ayuda2: 'گیند چلانے کے لیے اسپرنگ نیچے کھینچ کر چھوڑ دیں۔', ayuda2b: 'گیند چلانے کے لیے اسپرنگ کو ٹیپ کریں۔', ayuda3: 'ہوٹل میں عہدہ بڑھانے کے لیے مشن مکمل کریں۔', tocar: 'جاری رکھنے کے لیے ٹیپ کریں',
  },
  th: {
    idioma: 'เลือกภาษา', subtitulo: 'พินบอลแห่งแกรนด์โฮเทล',
    clasico: 'คลาสสิก', clasicoD: 'ลูก 3 ลูก · จากพนักงานยกกระเป๋าสู่เจ้าของ', reloj: 'แข่งกับเวลา', relojD: 'สองนาทีครึ่ง · ลูกไม่จำกัด',
    diario: 'ภารกิจประจำวัน', diarioD: 'ภารกิจวันนี้ เหมือนกันทุกคน', controles: 'การควบคุม', idiomaBtn: 'ภาษา',
    record: 'สถิติ', hoyRec: 'วันนี้ {0}', bola: 'ลูก {0}/{1}', pausa: 'หยุดชั่วคราว', seguir: 'เล่นต่อ', reiniciar: 'เริ่มใหม่', menu: 'เมนู',
    musica: 'เพลง', sonido: 'เสียง', si: 'เปิด', no: 'ปิด', otra: 'อีกครั้ง', fin: 'จบเกม', tiempo: 'หมดเวลา!', nuevoRecord: 'สถิติใหม่!',
    volver: 'กลับ', listo: 'เสร็จ', restablecer: 'คืนค่าเดิม',
    tirar: 'ดึงสปริง', tocarLanzar: 'แตะเพื่อปล่อยลูก', teSalvo: 'รอดแล้ว!', jackpot: 'แจ็กพอต!', multibola: 'มัลติบอล!',
    multiLista: 'มัลติบอลพร้อม', bolaExtra: 'ลูกพิเศษ!', tiroMaestro: 'ช็อตเทพ!', mult: 'ตัวคูณ ×{0}', orbita: 'วงโคจร!',
    cumplida: 'ภารกิจสำเร็จ!', ascenso: 'ตอนนี้คุณคือ {0}', bonus: 'โบนัส', total: 'รวม', perdida: 'เสียลูก',
    m_hongos: 'ชนบัมเปอร์ {0} ครั้ง', m_blancos: 'ล้มเป้า {0} อัน', m_carriles: 'เติม J·A·Z·Z ให้ครบ', m_copa: 'ยิงลงถ้วย {0} ครั้ง',
    m_orbitas: 'วิ่งวงโคจร {0} รอบ', m_molinete: 'หมุนกังหัน {0} รอบ',
    rangos: ['พนักงานยกกระเป๋า', 'บริกร', 'บาร์เทนเดอร์', 'พนักงานต้อนรับ', 'ผู้จัดการ', 'เจ้าของ'],
    hongos: 'บัมเปอร์', carriles: 'เลน', blancos: 'เป้า', orbitas: 'วงโคจร', copas: 'ถ้วย', misiones: 'ภารกิจ', rango: 'ตำแหน่ง', mejorJackpot: 'แจ็กพอตสูงสุด',
    modo: 'ฟลิปเปอร์', mitades: 'ครึ่งจอ', botones: 'ปุ่ม', tamano: 'ขนาด', chico: 'เล็ก', medio: 'กลาง', grande: 'ใหญ่',
    transp: 'ความโปร่งใส', baja: 'ต่ำ', media: 'กลาง', alta: 'สูง', resorte: 'สปริง', tirarOp: 'ดึง', tocarOp: 'แตะ', vibrar: 'สั่น',
    acomodar: 'จัดตำแหน่งปุ่ม', arrastra: 'ลากปุ่มแต่ละปุ่มไปยังตำแหน่งที่ถนัด', proba: 'ลองที่นี่',
    ayuda1: 'แตะครึ่งซ้ายหรือครึ่งขวาของจอเพื่อขยับฟลิปเปอร์แต่ละข้าง', ayuda1b: 'แตะปุ่มด้านล่างเพื่อขยับฟลิปเปอร์แต่ละข้าง',
    ayuda2: 'ดึงสปริงลงแล้วปล่อยเพื่อยิงลูก', ayuda2b: 'แตะสปริงเพื่อยิงลูก', ayuda3: 'ทำภารกิจให้สำเร็จเพื่อเลื่อนตำแหน่งในโรงแรม', tocar: 'แตะเพื่อเล่นต่อ',
  },
  my: {
    idioma: 'ဘာသာစကား ရွေးပါ', subtitulo: 'ဟိုတယ်ကြီး၏ ပင်ဘော',
    clasico: 'ဂန္ထဝင်', clasicoD: 'ဘောလုံး 3 လုံး · အိတ်သယ်မှ ပိုင်ရှင်အထိ', reloj: 'အချိန်နှင့်ယှဉ်', relojD: 'နှစ်မိနစ်ခွဲ · ဘောလုံး အကန့်အသတ်မဲ့',
    diario: 'ယနေ့ စိန်ခေါ်မှု', diarioD: 'ယနေ့ မစ်ရှင်များ၊ လူတိုင်းအတွက် တူညီ', controles: 'ထိန်းချုပ်မှု', idiomaBtn: 'ဘာသာစကား',
    record: 'စံချိန်', hoyRec: 'ယနေ့ {0}', bola: 'ဘောလုံး {0}/{1}', pausa: 'ခဏရပ်', seguir: 'ဆက်ကစား', reiniciar: 'ပြန်စ', menu: 'မီနူး',
    musica: 'ဂီတ', sonido: 'အသံ', si: 'ဖွင့်', no: 'ပိတ်', otra: 'ထပ်ကစား', fin: 'ဂိမ်းပြီးပြီ', tiempo: 'အချိန်ကုန်ပြီ!', nuevoRecord: 'စံချိန်သစ်!',
    volver: 'နောက်သို့', listo: 'ပြီးပြီ', restablecer: 'မူလအတိုင်း',
    tirar: 'စပရင်ကို ဆွဲပါ', tocarLanzar: 'ပစ်ရန် နှိပ်ပါ', teSalvo: 'ဘောလုံး ကယ်ပြီ!', jackpot: 'ဂျက်ပေါ့!', multibola: 'ဘောလုံးအများ!',
    multiLista: 'ဘောလုံးအများ အသင့်', bolaExtra: 'ဘောလုံး အပို!', tiroMaestro: 'ကျွမ်းကျင်သည့် ပစ်ချက်!', mult: 'မြှောက်ကိန်း ×{0}', orbita: 'ပတ်လမ်း!',
    cumplida: 'မစ်ရှင် ပြီးပြီ!', ascenso: 'ယခု သင်သည် {0}', bonus: 'ဘောနပ်စ်', total: 'စုစုပေါင်း', perdida: 'ဘောလုံး ဆုံးပြီ',
    m_hongos: 'ဘမ်ပါကို {0} ကြိမ် တိုက်ပါ', m_blancos: 'ပစ်မှတ် {0} ခု လှဲပါ', m_carriles: 'J·A·Z·Z ပြည့်အောင် လုပ်ပါ', m_copa: 'ခွက်ထဲ {0} ကြိမ် ထည့်ပါ',
    m_orbitas: 'ပတ်လမ်း {0} ကြိမ် ပတ်ပါ', m_molinete: 'လည်ခုံကို {0} ကြိမ် လှည့်ပါ',
    rangos: ['အိတ်သယ်', 'စားပွဲထိုး', 'ဘားတင်ဒါ', 'ဧည့်ကြို', 'မန်နေဂျာ', 'ပိုင်ရှင်'],
    hongos: 'ဘမ်ပါများ', carriles: 'လမ်းကြောင်းများ', blancos: 'ပစ်မှတ်များ', orbitas: 'ပတ်လမ်းများ', copas: 'ခွက်များ', misiones: 'မစ်ရှင်များ', rango: 'ရာထူး', mejorJackpot: 'အကောင်းဆုံး ဂျက်ပေါ့',
    modo: 'ဖလစ်ပါ', mitades: 'မျက်နှာပြင်တစ်ဝက်', botones: 'ခလုတ်များ', tamano: 'အရွယ်အစား', chico: 'သေး', medio: 'အလယ်', grande: 'ကြီး',
    transp: 'ပွင့်လင်းမှု', baja: 'နိမ့်', media: 'အလယ်', alta: 'မြင့်', resorte: 'စပရင်', tirarOp: 'ဆွဲ', tocarOp: 'နှိပ်', vibrar: 'တုန်ခါမှု',
    acomodar: 'ခလုတ် နေရာချ', arrastra: 'ခလုတ်တစ်ခုစီကို အဆင်ပြေသည့်နေရာသို့ ဆွဲပါ', proba: 'ဒီမှာ စမ်းပါ',
    ayuda1: 'ဖလစ်ပါတစ်ခုစီ လှုပ်ရန် မျက်နှာပြင်၏ ဘယ် သို့မဟုတ် ညာတစ်ဝက်ကို နှိပ်ပါ။', ayuda1b: 'ဖလစ်ပါတစ်ခုစီ လှုပ်ရန် အောက်ရှိ ခလုတ်များကို နှိပ်ပါ။',
    ayuda2: 'ပစ်ရန် စပရင်ကို အောက်သို့ ဆွဲပြီး လွှတ်ပါ။', ayuda2b: 'ပစ်ရန် စပရင်ကို နှိပ်ပါ။', ayuda3: 'ဟိုတယ်တွင် ရာထူးတက်ရန် မစ်ရှင်များကို ပြီးမြောက်အောင် လုပ်ပါ။', tocar: 'ဆက်ရန် နှိပ်ပါ',
  },
  ja: {
    idioma: '言語を選択', subtitulo: 'グランドホテルのピンボール',
    clasico: 'クラシック', clasicoD: 'ボール3個・ベルボーイからオーナーへ', reloj: 'タイムアタック', relojD: '2分30秒・ボール無制限',
    diario: 'デイリーチャレンジ', diarioD: '今日のミッション、全員共通', controles: '操作設定', idiomaBtn: '言語',
    record: 'ベスト', hoyRec: '今日 {0}', bola: 'ボール {0}/{1}', pausa: 'ポーズ', seguir: '再開', reiniciar: 'やり直す', menu: 'メニュー',
    musica: '音楽', sonido: '効果音', si: 'オン', no: 'オフ', otra: 'もう一度', fin: 'ゲームオーバー', tiempo: 'タイムアップ！', nuevoRecord: '新記録！',
    volver: '戻る', listo: '完了', restablecer: '初期設定に戻す',
    tirar: 'バネを引こう', tocarLanzar: 'タップで発射', teSalvo: 'ボールセーブ！', jackpot: 'ジャックポット！', multibola: 'マルチボール！',
    multiLista: 'マルチボール準備OK', bolaExtra: 'エクストラボール！', tiroMaestro: 'スキルショット！', mult: '倍率 ×{0}', orbita: 'オービット！',
    cumplida: 'ミッション達成！', ascenso: '{0}に昇格！', bonus: 'ボーナス', total: '合計', perdida: 'ボールロスト',
    m_hongos: 'バンパーに{0}回当てる', m_blancos: 'ターゲットを{0}個倒す', m_carriles: 'J·A·Z·Zを完成させる', m_copa: 'カップに{0}回入れる',
    m_orbitas: 'オービットを{0}回決める', m_molinete: 'スピナーを{0}回転させる',
    rangos: ['ベルボーイ', 'ウェイター', 'バーテンダー', 'コンシェルジュ', '支配人', 'オーナー'],
    hongos: 'バンパー', carriles: 'レーン', blancos: 'ターゲット', orbitas: 'オービット', copas: 'カップ', misiones: 'ミッション', rango: 'ランク', mejorJackpot: '最高ジャックポット',
    modo: 'フリッパー', mitades: '画面の左右', botones: 'ボタン', tamano: 'サイズ', chico: '小', medio: '中', grande: '大',
    transp: '透明度', baja: '低', media: '中', alta: '高', resorte: 'バネ', tirarOp: '引く', tocarOp: 'タップ', vibrar: '振動',
    acomodar: 'ボタン配置', arrastra: '各ボタンを押しやすい位置にドラッグしてね', proba: 'ここで試す',
    ayuda1: '画面の左半分か右半分をタップして、それぞれのフリッパーを動かそう。', ayuda1b: '下のボタンをタップして、それぞれのフリッパーを動かそう。',
    ayuda2: '発射するには、バネを下に引いて離そう。', ayuda2b: '発射するには、バネをタップしよう。', ayuda3: 'ミッションを達成して、ホテルでランクを上げよう。', tocar: 'タップして続ける',
  },
});
