// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Audio
{
    public partial struct AudioMixerPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Audio.AudioMixerPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Audio.AudioMixerPlayable Create(global::UnityEngine.Playables.PlayableGraph graph, int inputCount = 0, bool normalizeInputVolumes = false) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioMixerPlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioMixerPlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Audio.AudioMixerPlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioMixerPlayable::op_Implicit"); return default; }
        public bool Equals(global::UnityEngine.Audio.AudioMixerPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioMixerPlayable::Equals"); return default; }
    }
}
