// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Audio
{
    public static partial class AudioPlayableBinding
    {
        public static global::UnityEngine.Playables.PlayableBinding Create(string name, global::UnityEngine.Object key) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioPlayableBinding::Create"); return default; }
    }
}
