// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Audio
{
    public partial struct AudioClipPlayable : global::UnityEngine.Playables.IPlayable, global::System.IEquatable<global::UnityEngine.Audio.AudioClipPlayable>
    {
        public global::UnityEngine.Playables.PlayableHandle m_Handle;
        public static global::UnityEngine.Audio.AudioClipPlayable Create(global::UnityEngine.Playables.PlayableGraph graph, global::UnityEngine.AudioClip clip, bool looping) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::Create"); return default; }
        public global::UnityEngine.Playables.PlayableHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::GetHandle"); return default; }
        public static implicit operator global::UnityEngine.Playables.Playable(global::UnityEngine.Audio.AudioClipPlayable playable) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::op_Implicit"); return default; }
        public static explicit operator global::UnityEngine.Audio.AudioClipPlayable(global::UnityEngine.Playables.Playable playable) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::op_Explicit"); return default; }
        public bool Equals(global::UnityEngine.Audio.AudioClipPlayable other) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::Equals"); return default; }
        public void SetVolume(float value) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::SetVolume"); }
        public void SetStereoPan(float value) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::SetStereoPan"); }
        public void SetSpatialBlend(float value) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::SetSpatialBlend"); }
        public void Seek(double startTime, double startDelay, double duration) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioClipPlayable::Seek"); }
    }
}
