// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Audio
{
    public partial struct AudioPlayableOutput : global::UnityEngine.Playables.IPlayableOutput
    {
        public global::UnityEngine.Playables.PlayableOutputHandle m_Handle;
        public global::UnityEngine.Playables.PlayableOutputHandle GetHandle() { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioPlayableOutput::GetHandle"); return default; }
        public static explicit operator global::UnityEngine.Audio.AudioPlayableOutput(global::UnityEngine.Playables.PlayableOutput output) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioPlayableOutput::op_Explicit"); return default; }
        public void SetEvaluateOnSeek(bool value) { global::Porteo.Falta.Llamada("UnityEngine.Audio.AudioPlayableOutput::SetEvaluateOnSeek"); }
    }
}
