// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.InputLegacyModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.DeviceOrientation))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Gyroscope))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.IMECompositionMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Input))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.PenStatus))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Touch))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.TouchPhase))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.TouchType))]
