// La historia de la casa entera sin manos: cada disparador en orden, el tiempo adelantado,
// las banderas de MainScript. Fotos chicas en salida/.     node recorrido.mjs
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import path from 'node:path';
const { chromium } = createRequire('/opt/node22/lib/node_modules/playwright/')('playwright');
const AQUI = path.dirname(new URL(import.meta.url).pathname);
(await import('node:fs')).mkdirSync(path.join(AQUI, 'salida'), { recursive: true });
const PUERTO = 18000 + Math.floor(Math.random() * 2000);
const srv = spawn('python3', ['-m', 'http.server', String(PUERTO), '--bind', '127.0.0.1'], { cwd: path.join(AQUI, '../dist'), stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 700));
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required'] });
const p = await b.newPage({ viewport: { width: 844, height: 390 }, deviceScaleFactor: 1 });
const errores = [];
p.on('pageerror', (e) => errores.push(e.message));
p.on('console', (m) => { if (m.type() === 'error') errores.push(m.text().slice(0, 300)); if (m.text().startsWith('dbg')) console.log(m.text()); });
let mal = 0;
const ok = (c, m) => { console.log((c ? '  ok  ' : '  MAL ') + m); if (!c) mal++; };
await p.addInitScript(() => { if (!localStorage.getItem('pizza.v1')) localStorage.setItem('pizza.v1', JSON.stringify({ idioma: 'es' })); });
await p.goto(`http://127.0.0.1:${PUERTO}/index.html`);
await p.waitForFunction(() => window.__pizza?.listo, null, { timeout: 120000 });
await p.click('[data-b="jugar"]');
await p.waitForFunction(() => __pizza.modo === 'jugando' && !__pizza.J.cargando, null, { timeout: 180000 });
const foto = async (n) => { await p.evaluate(() => __pizza.dibujar()); return p.screenshot({ path: path.join(AQUI, 'salida', n + '.jpg'), type: 'jpeg', quality: 50 }); };
await p.evaluate(() => {
  const J = __pizza.J; __pizza.congelar = 'todo';
  const V = { x: 0, y: 0, mx: 0, my: 0, toque: false, pausa: false };
  window.paso = async (seg, inp = {}) => { const n = Math.round(seg * 20); for (let k = 0; k < n; k++) { J.update(0.05, { ...V, ...inp }, { sens: 1 }); await null; await null; if (k % 40 === 39) await new Promise((r) => setTimeout(r, 0)); } };
  window.entrar = async (nombre, cual = 0) => { // al centro del disparador del nodo
    const S = J.S;
    const lista = S.disparadores.filter((d) => S.N[d.i].n === nombre);
    const d = lista[cual]; if (!d) return 'sin ' + nombre;
    const o = S.O[d.i], c = d.c;
    let cen;
    if (c.tipo === 'mesh') { const k = J.R.C.mallas[c.malla].caja; cen = new o.position.constructor((k[0] + k[3]) / 2, (k[1] + k[4]) / 2, (k[2] + k[5]) / 2); } else cen = new o.position.constructor(...c.c_);
    o.localToWorld(cen);
    J.jug.o.position.copy(cen); J.jug.est.vy = 0;
    J.dentro.clear();
    for (let k = 0; k < 3; k++) { J.jug.o.position.copy(cen); J.update(0.05, V, { sens: 1 }); await null; await null; }
    return 'ok';
  };
  window.mirarHacia = (nombre) => { const i = J.S.buscar(nombre); const t = J.S.O[i].getWorldPosition(new J.camara.position.constructor()); const c = J.jug.o.position; J.jug.yaw = Math.atan2(-(t.x - c.x), -(t.z - c.z)); J.jug.pitch = 0; };
});
await p.evaluate(async () => { await paso(0.1, { toque: true }); await paso(1); });
const G = () => p.evaluate(() => ({ ...__pizza.G, sub: __pizza.J.subtitulo }));
const r = async (fn) => p.evaluate(fn);
await r(async () => entrar('MainDoor')); await r(async () => paso(16));
await r(() => { const J = __pizza.J; J.jug.o.position.set(0, 0, 0); const i = J.S.buscar('MainDoor'); window.puerta = J.S.O[i].rotation.toArray(); });
ok(true, 'el timbre y la puerta (16 s)');
await r(async () => entrar('LobbyCollider')); await r(async () => paso(3));
let g = await G(); ok(g.doorShut, `entra: la puerta se cierra (doorShut ${g.doorShut})`);
await r(async () => entrar('PlacePizzaOnTable')); await r(async () => paso(1));
g = await G(); ok(g.pizzaKept, `deja la pizza en la mesa (pizzaKept ${g.pizzaKept})`);
await r(async () => paso(12)); g = await G(); ok(g.currentGone, 'a los 10 s se corta la luz');
await foto('h-sinluz');
await r(async () => paso(66)); g = await G(); ok(g.shotsHeared, `los diálogos y el grito (shotsHeared ${g.shotsHeared})`);
await r(async () => entrar('PlacePizzaOnTable')); await r(async () => paso(1));
g = await G(); ok(g.candleTaken, `agarra la vela (candleTaken ${g.candleTaken})`);
await r(async () => entrar('RoomCollider')); await r(async () => paso(13));
g = await G(); ok(g.corpseSeen, `el cuarto de arriba (corpseSeen ${g.corpseSeen})`);
await foto('h-cuarto');
await r(async () => entrar('LobbyCollider')); await r(async () => paso(12));
g = await G(); ok(g.pizzaOpenedSeen, `abajo: vibra el celular (pizzaOpenedSeen ${g.pizzaOpenedSeen})`);
await r(async () => entrar('cellPhoneCollider')); await r(async () => paso(3));
g = await G(); ok(g.mobileTaken, `atiende el celular (mobileTaken ${g.mobileTaken})`);
await r(async () => entrar('LobbyCollider')); await r(async () => paso(1));
await r(async () => entrar('kitchenGhostTrigger')); await r(async () => paso(2));
await foto('h-cocina');
g = await G(); ok(g.enteredKitchen, `el fantasma de la cocina (enteredKitchen ${g.enteredKitchen})`);
await r(async () => paso(110)); g = await G(); ok(g.wokeUp && !g.isDead, `quieto: se despierta (wokeUp ${g.wokeUp}, isDead ${g.isDead})`);
await r(async () => entrar('matchBoxTrigger')); await r(async () => paso(2));
g = await G(); ok(g.matchGot, `los fósforos (matchGot ${g.matchGot})`);
await r(async () => entrar('GirlTalkTrigger')); await r(async () => paso(30));
g = await G(); ok(g.girlSpoken, `la nena fantasma habla (girlSpoken ${g.girlSpoken})`);
await foto('h-nena');
await r(async () => entrar('keyFindTrigger')); await r(async () => paso(12));
g = await G(); ok(g.keySearched, `la llave y el monstruo (keySearched ${g.keySearched})`);
await foto('h-monstruo');
await r(async () => entrar('ClosetTrigger')); await r(async () => paso(3));
await r(async () => entrar('ClosetInsideTrigger')); await r(async () => paso(11));
g = await G(); ok(g.closetEntered, `en el placard (closetEntered ${g.closetEntered})`);
await r(async () => entrar('finalDemon')); await r(async () => paso(0.2));
await p.waitForFunction(() => __pizza.J.nivel === 'Scene2' && !__pizza.J.cargando, null, { timeout: 120000 }).catch(() => {});
ok(await r(() => __pizza.J.nivel) === 'Scene2', 'el demonio del placard lleva al bosque (Scene2)');
await r(() => { __pizza.congelar = false; }); await p.waitForTimeout(3000); await foto('h-bosque');
ok(errores.length === 0, 'sin errores' + (errores.length ? ': ' + [...new Set(errores)].slice(0, 3).join(' | ') : ''));
console.log(mal ? `${mal} cosas para arreglar` : 'Todo bien');
await b.close(); srv.kill();
