// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.IMGUIModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Event))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.EventModifiers))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.EventType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.GUI))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.GUIUtility))]
