// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Serialization
{
    [System.AttributeUsage((System.AttributeTargets)256, AllowMultiple = true, Inherited = false)]
    public partial class FormerlySerializedAsAttribute : global::System.Attribute
    {
        public FormerlySerializedAsAttribute(string oldName) { global::Porteo.Falta.Llamada("UnityEngine.Serialization.FormerlySerializedAsAttribute::.ctor"); }
    }
}
