// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Pool
{
    public partial class CollectionPool<TCollection, TItem> where TCollection : class, global::System.Collections.Generic.ICollection<TItem>, new()
    {
        public static TCollection Get() { global::Porteo.Falta.Llamada("UnityEngine.Pool.CollectionPool`2::Get"); return default; }
        public static void Release(TCollection toRelease) { global::Porteo.Falta.Llamada("UnityEngine.Pool.CollectionPool`2::Release"); }
    }
}
