// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Pool
{
    public partial interface IObjectPool<T> where T : class
    {
        int CountInactive { get; }
        T Get();
        global::UnityEngine.Pool.PooledObject<T> Get(out T v);
        void Release(T element);
        void Clear();
    }
}
