// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Pool
{
    public partial class ObjectPool<T> : global::System.IDisposable, global::UnityEngine.Pool.IObjectPool<T> where T : class
    {
        public int CountInactive { get { global::Porteo.Falta.Llamada("UnityEngine.Pool.ObjectPool`1::CountInactive"); return default; } }
        public ObjectPool(global::System.Func<T> createFunc, global::System.Action<T> actionOnGet = null, global::System.Action<T> actionOnRelease = null, global::System.Action<T> actionOnDestroy = null, bool collectionCheck = true, int defaultCapacity = 10, int maxSize = 10000) { global::Porteo.Falta.Llamada("UnityEngine.Pool.ObjectPool`1::.ctor"); }
        public T Get() { global::Porteo.Falta.Llamada("UnityEngine.Pool.ObjectPool`1::Get"); return default; }
        public global::UnityEngine.Pool.PooledObject<T> Get(out T v) { v = default;  global::Porteo.Falta.Llamada("UnityEngine.Pool.ObjectPool`1::Get"); return default;  }
        public void Release(T element) { global::Porteo.Falta.Llamada("UnityEngine.Pool.ObjectPool`1::Release"); }
        public void Clear() { global::Porteo.Falta.Llamada("UnityEngine.Pool.ObjectPool`1::Clear"); }
        public void Dispose() { global::Porteo.Falta.Llamada("UnityEngine.Pool.ObjectPool`1::Dispose"); }
    }
}
