// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Pool
{
    public partial struct PooledObject<T> : global::System.IDisposable where T : class
    {
        public T m_ToReturn;
        public global::UnityEngine.Pool.IObjectPool<T> m_Pool;
        void global::System.IDisposable.Dispose() { global::Porteo.Falta.Llamada("UnityEngine.Pool.PooledObject`1::Dispose"); }
    }
}
