// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Assertions
{
    public static partial class Assert
    {
        public static bool raiseExceptions;
    }
}
