/* ============================================================================
   kuntur/js/textos.js — todo lo que se lee en KUNTUR, en español, inglés y
   portugués. Las charlas son listas de [quién, texto]. Las coplas son
   inventadas al estilo de las de la Quebrada.
   ========================================================================== */
export const TEXTOS = {
  es: {
    ui: {
      elegi: 'Elegí tu idioma', lema: 'Una nena, un pichón de cóndor y la montaña que lo espera.',
      empezar: 'Empezar el viaje', seguir: 'Seguir el viaje', nuevo: 'Viaje nuevo', nuevoSeguro: '¿Empezar de cero? Tocá otra vez',
      capitulos: 'Capítulos', coplas: 'Coplas', opciones: 'Opciones', creditos: 'Créditos', volver: 'Volver',
      pausa: 'Pausa', continuar: 'Seguir', salir: 'Volver al teatro', reintentar: 'Volver a la apacheta',
      idioma: 'Idioma', musica: 'Música', efectos: 'Efectos', calidad: 'Calidad', temblor: 'Temblor de cámara', si: 'Sí', no: 'No',
      alta: 'Alta', media: 'Media', baja: 'Baja',
      capitulo: 'Capítulo {0}', prologo: 'Prólogo', epilogo: 'Epílogo', cerrado: 'Todavía no llegaste', coplasDe: '{0} de {1} coplas',
      copla: '¡Encontraste una copla!', apacheta: 'Dejaste una piedra en la apacheta', tocar: 'Tocá para seguir', saltear: 'Saltear',
      fin: 'Fin', gracias: 'Gracias por jugar',
      hablar: 'hablar', agarrar: 'agarrar', abrir: 'abrir', llamarApu: 'Apu, ¡andá!',
      falta: 'Esta copla todavía anda perdida', armando: 'Armando el teatrito…', saludo: '¡Hola!', pantalla: 'Pantalla completa',
      controles: 'Flechas: caminar · Espacio: saltar · X: hablar y agarrar · Esc: pausa', terminado: 'Viaje terminado', reiniciar: 'Empezar el capítulo de nuevo',
      tactiles: 'Controles de dedo', acomodar: 'Acomodar', acomodaTit: 'Acomodá los controles',
      acomodaAyuda: 'Arrastrá cada uno · tocalo y cambiá el tamaño · o pellizcalo',
      tamano: 'Tamaño', opacidad: 'Opacidad', palanca: 'Palanca', flotante: 'Flotante', fija: 'Fija', cruz: 'Cruz',
      vibrar: 'Vibrar', espejar: 'Espejar (zurdo)', restablecer: 'Restablecer', listo: 'Listo',
      cCaminar: 'Caminar', cSaltar: 'Saltar', cMano: 'Mano', cPausa: 'Pausa',
    },
    ayudas: {
      mover: ['Flechas o A y D para caminar', 'Mové con la palanca'],
      saltar: ['Espacio o Z para saltar', 'Tocá la pluma para saltar'],
      borde: ['Saltá contra un borde para agarrarte y trepar', 'Saltá contra un borde para agarrarte y trepar'],
      agachar: ['Abajo para agacharte y pasar por lo bajo', 'Palanca para abajo para agacharte'],
      empujar: ['X o E para agarrar la piedra: empujá o tirá', 'Mantené la mano para agarrar la piedra: empujá o tirá'],
      escalera: ['Arriba para subir la escalera', 'Palanca para arriba para subir'],
      hablar: ['X o E para hablar', 'Tocá la mano para hablar'],
      aleteo: ['Apu aletea: saltá otra vez en el aire', 'Apu aletea: tocá la pluma otra vez en el aire'],
      viento: ['Cuando sopla fuerte, agachate o escondete atrás de un bloque', 'Cuando sopla fuerte, agachate o escondete atrás de un bloque'],
      agua: ['¡Cuidado con la salmuera!', '¡Cuidado con la salmuera!'],
      planeo: ['Mantené el salto en el aire para planear', 'Mantené la pluma en el aire para planear'],
      llamar: ['X o E cerca de una traba: Apu vuela a abrirla', 'Tocá la mano cerca de una traba: Apu vuela a abrirla'],
      termica: ['Planeá sobre el aire caliente para subir', 'Planeá sobre el aire caliente para subir'],
      tunel: ['¡Agachate cuando pase una viga!', '¡Agachate cuando pase una viga!'],
    },
    capitulos: { prologo: 'La granizada', colores: 'Los Siete Colores', salinas: 'Las Salinas Grandes', tren: 'El Tren a las Nubes', puna: 'La Puna', nevado: 'El Nevado', epilogo: 'La vuelta' },
    narra: {
      prologo: ['Mi abuela dice que los cóndores llevan los mensajes de la tierra al cielo.', 'Que cuando alguien se va, un cóndor lo acompaña hasta arriba de todo.', 'Esa noche cayó la granizada más grande que vio Purmamarca.'],
      colores: ['A la mañana salimos. Apu no pesaba nada, pero no paraba de piar.', 'El cerro de los Siete Colores parecía pintado a mano.'],
      salinas: ['Arriba de la cuesta, el mundo se volvió blanco.', 'Las Salinas Grandes: un mar que se secó hace mucho y dejó la sal.'],
      tren: ['El Tren a las Nubes sube tan alto que las nubes le pasan por abajo.', 'Apu ya no entraba en el atado.'],
      puna: ['De noche, la Puna es un cielo que llega hasta el piso.', 'Apu ya era grande. Y pesaba.'],
      nevado: ['El Viento Blanco no avisa. Te encuentra.', 'Arriba de todo estaba el nido.'],
      epilogo: ['Volví a Purmamarca una tarde de viento.'],
    },
    nombres: { killa: 'Killa', abuela: 'La abuela', rosa: 'Doña Rosa', ceferino: 'Don Ceferino', tomas: 'Tomás', coquena: 'Coquena', apu: 'Apu' },
    charlas: {
      inicio: [['abuela', 'Killa... ¿escuchás? Algo llora afuera, en el corral.'], ['killa', 'Voy a ver, abuela.']],
      afuera: [['killa', '¡Qué granizo! Parecen piedras.']],
      corral: [['killa', 'El llanto viene de más allá del corral.']],
      pichon: [['killa', '¡Un pichón! Estás helado...'], ['killa', 'Vení, te llevo adentro.']],
      casa: [['abuela', 'Es un pichón de cóndor. La tormenta lo tiró del nido.'], ['killa', '¿De qué nido?'], ['abuela', 'De allá arriba, del Nevado de Chañi. Los cóndores anidan donde nadie llega.'],
        ['abuela', 'Un cóndor que no vuelve a su montaña no aprende a volar, m\'hija.'], ['killa', 'Entonces lo llevo yo.'], ['abuela', 'Es muy lejos, Killa...'],
        ['abuela', '...Pero tu mamá hubiera hecho lo mismo.'], ['killa', 'Se va a llamar Apu.']],
      rosa: [['rosa', '¿A dónde vas tan temprano, Killa?'], ['killa', 'A llevar a Apu a su casa, en el Nevado.'], ['rosa', '¡Uy, qué lejos! Seguí las apachetas, changuita. En cada una dejá una piedra: la Pachamama te cuida el camino.'],
        ['rosa', 'Y si ves una copla colgada por ahí, guardala. Tu abuela las sabe todas.']],
      rosa2: [['rosa', '¡Andá, andá! Y saludame a los cóndores.']],
      piedra: [['killa', 'Esa pared es muy alta... Si empujo la piedra, capaz llego.']],
      mirador: [['killa', 'Mirá, Apu. Siete colores. La abuela dice que el sol los pinta de a uno, despacito.'], ['apu', '¡Pío!']],
      cuesta: [['killa', 'Allá arriba el mundo se pone blanco. Vamos, Apu.']],
      ceferino: [['ceferino', '¡Epa! ¿Sola por las Salinas?'], ['killa', 'Con Apu.'], ['ceferino', 'Ah, bien acompañada entonces.'],
        ['ceferino', 'Escuchá: cuando sopla fuerte, agachate o ponete atrás de un bloque de sal. Si no, el viento te tira a la salmuera.'], ['ceferino', 'Y hacia el oeste pasa el tren. Ese sube hasta las nubes.']],
      ceferino2: [['ceferino', 'Agachate con el viento, gurisa. Como los juncos.']],
      aleteo: [['killa', 'Es muy ancho para saltar...'], ['apu', '¡Pío, pío!'], ['killa', '¡Apu! ¡Aleteaste! ¡Me levantaste!']],
      estacion: [['killa', '¡El tren! ¡Corré, Apu!']],
      arranca: [['killa', '¡Arrancó! Tengo que llegar adelante, a la locomotora.']],
      viaducto: [['killa', 'Estamos arriba de las nubes, Apu... No mires para abajo.']],
      tunel: [['killa', '¡Un túnel! Agachate o metete en el vagón.']],
      tomas: [['tomas', '¡Nena! ¿Qué hacés arriba del tren?'], ['killa', 'Voy al Nevado de Chañi. Tengo que llevar a Apu.'], ['tomas', '¿Y ese? ¿Es un cóndor?'], ['killa', 'Todavía no. Pero va a ser.'],
        ['tomas', 'Mirá vos... Yo también quería ir lejos cuando tenía tu edad.'], ['tomas', 'Tomá este farol. De noche, en la Puna, hace falta.'], ['tomas', 'El tren para en la última estación. De ahí, seguí la montaña.']],
      tomas2: [['tomas', '¡Buen viaje, nena! Y agarrate fuerte.']],
      planeo: [['killa', 'No hay por dónde bajar...'], ['apu', '¡Kiiá!'], ['killa', '¡Apu, me llevás! ¡Estás enorme!']],
      llamar: [['killa', 'Una tranquera cerrada... La traba está allá arriba.'], ['killa', 'Apu, ¡andá!']],
      puma: [['killa', '¡Un puma! ¡Corré, Apu!']],
      coquena: [['coquena', 'Nadie caza en mi Puna.'], ['killa', '¿Quién sos?'], ['coquena', 'Soy Coquena. Cuido a las vicuñas... y a los que caminan de noche.'],
        ['coquena', 'Tu pichón ya casi vuela, Killa. Mañana, en la cumbre, vas a tener que soltarlo.'], ['killa', '¿Y si no quiere irse?'], ['coquena', 'Los que queremos no se van. Suben.']],
      coquena2: [['coquena', 'Seguí para arriba. El Viento Blanco no espera a nadie.']],
      tormenta: [['killa', '¡Viene el Viento Blanco! ¡Corré!']],
      escapa: [['killa', 'Pasó... ¿Apu? ¿Estás?'], ['apu', '¡Kiiiá!']],
      cumbre: [['killa', 'Llegamos, Apu. Esta es tu casa.'], ['killa', 'Tomá. Era de mamá.'], ['killa', 'Dicen que ustedes llevan los mensajes de la tierra al cielo.'],
        ['killa', 'Decile que estamos bien. Que la abuela todavía canta sus coplas.'], ['killa', '¡Volá, Apu!']],
      epilogo: [['abuela', '¿Y? ¿Llegó?'], ['killa', 'Llegó, abuela.'], ['abuela', 'Mirá para arriba, m\'hija.'], ['killa', '...Gracias, Apu.']],
      final: ['Dicen que el cóndor lleva los mensajes de la tierra al cielo.', 'Yo sé que es verdad.'],
    },
    coplas: [
      ['Siete colores tiene el cerro,', 'siete penas tengo yo;', 'cada vez que el sol lo pinta', 'se me pinta el corazón.'],
      ['Pachamama, madre tierra,', 'te dejo mi piedrecita;', 'cuidame bien el camino,', 'que llevo un alma chiquita.'],
      ['El cardón de la quebrada', 'tiene espinas y da flor;', 'así es la gente del cerro:', 'dura afuera y puro amor.'],
      ['Blanca la sal de la puna,', 'blanca la luna también;', 'si me pierdo en tanto blanco,', 'que me encuentre tu querer.'],
      ['El viento de las salinas', 'me quiso llevar volando;', 'yo me agaché como el junco', 'y lo dejé pasar cantando.'],
      ['Salinero, salinero,', '¿qué cortás con tu pala?', '—Corto pedazos de un mar', 'que se durmió en la llanada.'],
      ['Tren que subís a las nubes', 'con tu humo de algodón,', 'llevame hasta la montaña', 'y traeme de vuelta al sol.'],
      ['Por el viaducto del cielo', 'pasa el tren y pasa el tiempo;', 'el que mira para abajo', 'se marea con el viento.'],
      ['Foguista de la locomotora,', '¿qué sueño echás al carbón?', '—Echo el de llegar más lejos,', 'y lo quema el corazón.'],
      ['De noche la Puna es cielo,', 'las estrellas llegan al pie;', 'si una se me cae al suelo,', 'la guardo para después.'],
      ['Coquena cuida las vicuñas', 'con su poncho de vellón;', 'al que caza sin permiso', 'le esconde el camino y el sol.'],
      ['Farolito de la noche,', 'no te apagues, por favor,', 'que el puma anda por la loma', 'y yo le tengo temor.'],
      ['El Viento Blanco no avisa,', 'baja del cerro a buscar;', 'abrazá fuerte a los tuyos,', 'que ya va a escampar.'],
      ['En la cumbre del Nevado', 'el sol se asoma primero;', 'por eso nacen los cóndores', 'donde se toca el cielo.'],
      ['Cóndor, cóndor que te vas', 'volando para el Nevado,', 'llevale este mensajito', 'a quien está del otro lado.'],
    ],
    creditos: ['KUNTUR', 'Un juego de papel, hecho a mano', 'Historia, dibujos, música y código: Claude, para el Nuevo General de Juegos', 'Inspirado en Purmamarca, las Salinas Grandes, el Tren a las Nubes, la Puna y el Nevado de Chañi (Jujuy y Salta, Argentina)', 'Las coplas son inventadas, a la manera de las de la Quebrada', 'Gracias por jugar'],
  },
  en: {
    ui: {
      elegi: 'Choose your language', lema: 'A girl, a condor chick and the mountain waiting for it.',
      empezar: 'Start the journey', seguir: 'Continue the journey', nuevo: 'New journey', nuevoSeguro: 'Start over? Tap again',
      capitulos: 'Chapters', coplas: 'Coplas', opciones: 'Options', creditos: 'Credits', volver: 'Back',
      pausa: 'Paused', continuar: 'Continue', salir: 'Back to the theater', reintentar: 'Back to the apacheta',
      idioma: 'Language', musica: 'Music', efectos: 'Sound effects', calidad: 'Quality', temblor: 'Camera shake', si: 'On', no: 'Off',
      alta: 'High', media: 'Medium', baja: 'Low',
      capitulo: 'Chapter {0}', prologo: 'Prologue', epilogo: 'Epilogue', cerrado: 'You have not got here yet', coplasDe: '{0} of {1} coplas',
      copla: 'You found a copla!', apacheta: 'You left a stone on the apacheta', tocar: 'Tap to continue', saltear: 'Skip',
      fin: 'The end', gracias: 'Thank you for playing',
      hablar: 'talk', agarrar: 'grab', abrir: 'open', llamarApu: 'Go, Apu!',
      falta: 'This copla is still lost somewhere', armando: 'Setting up the paper theater…', saludo: 'Hello!', pantalla: 'Fullscreen',
      controles: 'Arrows: walk · Space: jump · X: talk and grab · Esc: pause', terminado: 'Journey complete', reiniciar: 'Restart the chapter',
      tactiles: 'Touch controls', acomodar: 'Arrange', acomodaTit: 'Arrange your controls',
      acomodaAyuda: 'Drag each one · tap it to change its size · or pinch it',
      tamano: 'Size', opacidad: 'Opacity', palanca: 'Stick', flotante: 'Floating', fija: 'Fixed', cruz: 'D-pad',
      vibrar: 'Vibration', espejar: 'Mirror (left-handed)', restablecer: 'Reset', listo: 'Done',
      cCaminar: 'Walk', cSaltar: 'Jump', cMano: 'Hand', cPausa: 'Pause',
    },
    ayudas: {
      mover: ['Arrow keys or A and D to walk', 'Move with the stick'],
      saltar: ['Space or Z to jump', 'Tap the feather to jump'],
      borde: ['Jump against a ledge to grab it and climb', 'Jump against a ledge to grab it and climb'],
      agachar: ['Down to crouch and crawl under things', 'Stick down to crouch'],
      empujar: ['X or E to grab the stone: push or pull', 'Hold the hand to grab the stone: push or pull'],
      escalera: ['Up to climb the ladder', 'Stick up to climb'],
      hablar: ['X or E to talk', 'Tap the hand to talk'],
      aleteo: ['Apu flaps: jump again in the air', 'Apu flaps: tap the feather again in the air'],
      viento: ['When it blows hard, crouch or hide behind a block', 'When it blows hard, crouch or hide behind a block'],
      agua: ['Watch out for the brine!', 'Watch out for the brine!'],
      planeo: ['Hold jump in the air to glide', 'Hold the feather in the air to glide'],
      llamar: ['X or E near a latch: Apu flies to open it', 'Tap the hand near a latch: Apu flies to open it'],
      termica: ['Glide over the warm air to rise', 'Glide over the warm air to rise'],
      tunel: ['Crouch when a beam goes by!', 'Crouch when a beam goes by!'],
    },
    capitulos: { prologo: 'The hailstorm', colores: 'The Seven Colours', salinas: 'The Great Salt Flats', tren: 'The Train to the Clouds', puna: 'The Puna', nevado: 'The Snowy Peak', epilogo: 'Coming home' },
    narra: {
      prologo: ['My grandmother says condors carry messages from the earth to the sky.', 'That when someone leaves us, a condor goes with them all the way up.', 'That night came the biggest hailstorm Purmamarca had ever seen.'],
      colores: ['We left in the morning. Apu weighed nothing, but he would not stop chirping.', 'The Hill of Seven Colours looked painted by hand.'],
      salinas: ['At the top of the pass, the world turned white.', 'The Great Salt Flats: a sea that dried up long ago and left its salt behind.'],
      tren: ['The Train to the Clouds climbs so high that the clouds pass underneath.', 'Apu no longer fit in the bundle.'],
      puna: ['At night, the Puna is a sky that reaches down to the ground.', 'Apu was big now. And heavy.'],
      nevado: ['The White Wind gives no warning. It finds you.', 'At the very top was the nest.'],
      epilogo: ['I came back to Purmamarca on a windy afternoon.'],
    },
    nombres: { killa: 'Killa', abuela: 'Grandma', rosa: 'Doña Rosa', ceferino: 'Don Ceferino', tomas: 'Tomás', coquena: 'Coquena', apu: 'Apu' },
    charlas: {
      inicio: [['abuela', 'Killa... do you hear that? Something is crying outside, in the corral.'], ['killa', 'I\'ll go and see, Grandma.']],
      afuera: [['killa', 'Look at this hail! It\'s like stones.']],
      corral: [['killa', 'The crying comes from past the corral.']],
      pichon: [['killa', 'A chick! You\'re freezing...'], ['killa', 'Come on, I\'ll take you inside.']],
      casa: [['abuela', 'It\'s a condor chick. The storm threw it out of the nest.'], ['killa', 'What nest?'], ['abuela', 'Way up there, on the Nevado de Chañi. Condors nest where nobody can reach.'],
        ['abuela', 'A condor that never returns to its mountain never learns to fly, my girl.'], ['killa', 'Then I\'ll take him.'], ['abuela', 'It\'s very far, Killa...'],
        ['abuela', '...But your mother would have done the same.'], ['killa', 'His name will be Apu.']],
      rosa: [['rosa', 'Where are you off to so early, Killa?'], ['killa', 'I\'m taking Apu home, to the Nevado.'], ['rosa', 'Oh, that\'s far! Follow the apachetas, little one. Leave a stone on each one: Pachamama will keep your path safe.'],
        ['rosa', 'And if you see a copla hanging somewhere, keep it. Your grandma knows them all.']],
      rosa2: [['rosa', 'Go on, go on! And say hello to the condors for me.']],
      piedra: [['killa', 'That wall is too high... If I push the stone, maybe I can reach.']],
      mirador: [['killa', 'Look, Apu. Seven colours. Grandma says the sun paints them one by one, very slowly.'], ['apu', 'Peep!']],
      cuesta: [['killa', 'Up there the world turns white. Let\'s go, Apu.']],
      ceferino: [['ceferino', 'Hey there! Alone on the salt flats?'], ['killa', 'With Apu.'], ['ceferino', 'Ah, in good company then.'],
        ['ceferino', 'Listen: when the wind blows hard, crouch or get behind a block of salt. Otherwise it\'ll push you into the brine.'], ['ceferino', 'And out west the train goes by. That one climbs all the way to the clouds.']],
      ceferino2: [['ceferino', 'Crouch with the wind, girl. Like the reeds do.']],
      aleteo: [['killa', 'It\'s too wide to jump...'], ['apu', 'Peep, peep!'], ['killa', 'Apu! You flapped! You lifted me!']],
      estacion: [['killa', 'The train! Run, Apu!']],
      arranca: [['killa', 'It\'s moving! I have to get to the front, to the engine.']],
      viaducto: [['killa', 'We\'re above the clouds, Apu... Don\'t look down.']],
      tunel: [['killa', 'A tunnel! Crouch, or get inside the carriage.']],
      tomas: [['tomas', 'Girl! What are you doing on top of the train?'], ['killa', 'I\'m going to the Nevado de Chañi. I have to take Apu.'], ['tomas', 'And him? Is that a condor?'], ['killa', 'Not yet. But he will be.'],
        ['tomas', 'Well, look at that... I wanted to go far away too, when I was your age.'], ['tomas', 'Take this lantern. At night, on the Puna, you\'ll need it.'], ['tomas', 'The train stops at the last station. From there, follow the mountain.']],
      tomas2: [['tomas', 'Safe travels, girl! And hold on tight.']],
      planeo: [['killa', 'There\'s no way down...'], ['apu', 'Kee-ah!'], ['killa', 'Apu, you\'re carrying me! You\'re huge!']],
      llamar: [['killa', 'A closed gate... The latch is way up there.'], ['killa', 'Go, Apu!']],
      puma: [['killa', 'A puma! Run, Apu!']],
      coquena: [['coquena', 'Nobody hunts in my Puna.'], ['killa', 'Who are you?'], ['coquena', 'I am Coquena. I look after the vicuñas... and those who walk at night.'],
        ['coquena', 'Your chick can almost fly, Killa. Tomorrow, at the summit, you will have to let him go.'], ['killa', 'What if he doesn\'t want to leave?'], ['coquena', 'The ones we love don\'t leave. They rise.']],
      coquena2: [['coquena', 'Keep climbing. The White Wind waits for no one.']],
      tormenta: [['killa', 'The White Wind is coming! Run!']],
      escapa: [['killa', 'It passed... Apu? Are you there?'], ['apu', 'Kee-ah!']],
      cumbre: [['killa', 'We made it, Apu. This is your home.'], ['killa', 'Here. It was Mum\'s.'], ['killa', 'They say you carry messages from the earth to the sky.'],
        ['killa', 'Tell her we\'re fine. That Grandma still sings her coplas.'], ['killa', 'Fly, Apu!']],
      epilogo: [['abuela', 'Well? Did he make it?'], ['killa', 'He made it, Grandma.'], ['abuela', 'Look up, my girl.'], ['killa', '...Thank you, Apu.']],
      final: ['They say the condor carries messages from the earth to the sky.', 'I know it\'s true.'],
    },
    coplas: [
      ['The hill has seven colours,', 'and seven sorrows have I;', 'each time the sun paints the hill', 'it paints my heart as well.'],
      ['Pachamama, mother earth,', 'I leave my little stone for you;', 'keep my path safe, I beg you,', 'I carry a small soul too.'],
      ['The cardón in the ravine', 'has thorns and yet it flowers;', 'so are the people of the hills:', 'tough outside, love inside.'],
      ['White is the salt of the Puna,', 'and white the moon above;', 'if I get lost in so much white,', 'may I be found by your love.'],
      ['The wind of the salt flats', 'tried to carry me away;', 'I bent down like the reeds do', 'and let it pass, singing.'],
      ['Salt cutter, salt cutter,', 'what do you cut with your spade?', '—I cut pieces of a sea', 'that fell asleep on the plain.'],
      ['Train that climbs up to the clouds', 'with your smoke as soft as cotton,', 'take me all the way to the mountain', 'and bring me back to the sun.'],
      ['Across the viaduct of the sky', 'the train goes by, and time goes by;', 'whoever looks down below', 'gets dizzy in the wind.'],
      ['Stoker of the engine,', 'what dream do you feed the coal?', '—The dream of going further,', 'and my heart burns it whole.'],
      ['At night the Puna is sky,', 'the stars come down to your feet;', 'if one of them falls to the ground,', 'I\'ll keep it for later.'],
      ['Coquena guards the vicuñas', 'in his poncho of fleece;', 'whoever hunts without leave', 'loses the road and the sun.'],
      ['Little lantern of the night,', 'please don\'t go out on me,', 'for the puma prowls the hillside', 'and I am afraid.'],
      ['The White Wind gives no warning,', 'it comes down the hill to find you;', 'hold your loved ones tight,', 'the storm will clear soon.'],
      ['On the summit of the Nevado', 'the sun rises first of all;', 'that is why the condors are born', 'where you can touch the sky.'],
      ['Condor, condor, flying off', 'toward the Nevado so high,', 'carry this little message', 'to the one on the other side.'],
    ],
    creditos: ['KUNTUR', 'A handmade paper game', 'Story, art, music and code: Claude, for Nuevo General de Juegos', 'Inspired by Purmamarca, the Great Salt Flats, the Train to the Clouds, the Puna and the Nevado de Chañi (Jujuy and Salta, Argentina)', 'The coplas are made up, in the style of those from the Quebrada', 'Thank you for playing'],
  },
  pt: {
    ui: {
      elegi: 'Escolha seu idioma', lema: 'Uma menina, um filhote de condor e a montanha que o espera.',
      empezar: 'Começar a viagem', seguir: 'Continuar a viagem', nuevo: 'Nova viagem', nuevoSeguro: 'Começar do zero? Toque de novo',
      capitulos: 'Capítulos', coplas: 'Coplas', opciones: 'Opções', creditos: 'Créditos', volver: 'Voltar',
      pausa: 'Pausa', continuar: 'Continuar', salir: 'Voltar ao teatro', reintentar: 'Voltar à apacheta',
      idioma: 'Idioma', musica: 'Música', efectos: 'Efeitos', calidad: 'Qualidade', temblor: 'Tremor da câmera', si: 'Sim', no: 'Não',
      alta: 'Alta', media: 'Média', baja: 'Baixa',
      capitulo: 'Capítulo {0}', prologo: 'Prólogo', epilogo: 'Epílogo', cerrado: 'Você ainda não chegou aqui', coplasDe: '{0} de {1} coplas',
      copla: 'Você achou uma copla!', apacheta: 'Você deixou uma pedra na apacheta', tocar: 'Toque para continuar', saltear: 'Pular',
      fin: 'Fim', gracias: 'Obrigado por jogar',
      hablar: 'falar', agarrar: 'segurar', abrir: 'abrir', llamarApu: 'Vai, Apu!',
      falta: 'Esta copla ainda anda perdida', armando: 'Montando o teatrinho…', saludo: 'Olá!', pantalla: 'Tela cheia',
      controles: 'Setas: andar · Espaço: pular · X: falar e segurar · Esc: pausa', terminado: 'Viagem concluída', reiniciar: 'Recomeçar o capítulo',
      tactiles: 'Controles de toque', acomodar: 'Ajustar', acomodaTit: 'Ajuste seus controles',
      acomodaAyuda: 'Arraste cada um · toque para mudar o tamanho · ou faça pinça',
      tamano: 'Tamanho', opacidad: 'Opacidade', palanca: 'Direcional', flotante: 'Flutuante', fija: 'Fixo', cruz: 'Cruz',
      vibrar: 'Vibrar', espejar: 'Espelhar (canhoto)', restablecer: 'Restaurar', listo: 'Pronto',
      cCaminar: 'Andar', cSaltar: 'Pular', cMano: 'Mão', cPausa: 'Pausa',
    },
    ayudas: {
      mover: ['Setas ou A e D para andar', 'Mova com o direcional'],
      saltar: ['Espaço ou Z para pular', 'Toque na pena para pular'],
      borde: ['Pule contra uma borda para se agarrar e subir', 'Pule contra uma borda para se agarrar e subir'],
      agachar: ['Para baixo para se agachar e passar por baixo', 'Alavanca para baixo para se agachar'],
      empujar: ['X ou E para segurar a pedra: empurre ou puxe', 'Segure a mão para pegar a pedra: empurre ou puxe'],
      escalera: ['Para cima para subir a escada', 'Alavanca para cima para subir'],
      hablar: ['X ou E para falar', 'Toque na mão para falar'],
      aleteo: ['Apu bate as asas: pule de novo no ar', 'Apu bate as asas: toque na pena de novo no ar'],
      viento: ['Quando venta forte, agache-se ou esconda-se atrás de um bloco', 'Quando venta forte, agache-se ou esconda-se atrás de um bloco'],
      agua: ['Cuidado com a salmoura!', 'Cuidado com a salmoura!'],
      planeo: ['Segure o pulo no ar para planar', 'Segure a pena no ar para planar'],
      llamar: ['X ou E perto de uma trava: Apu voa para abri-la', 'Toque na mão perto de uma trava: Apu voa para abri-la'],
      termica: ['Plane sobre o ar quente para subir', 'Plane sobre o ar quente para subir'],
      tunel: ['Agache-se quando passar uma viga!', 'Agache-se quando passar uma viga!'],
    },
    capitulos: { prologo: 'A chuva de granizo', colores: 'As Sete Cores', salinas: 'As Grandes Salinas', tren: 'O Trem das Nuvens', puna: 'A Puna', nevado: 'O Nevado', epilogo: 'A volta' },
    narra: {
      prologo: ['Minha avó diz que os condores levam as mensagens da terra para o céu.', 'Que quando alguém parte, um condor o acompanha até lá em cima.', 'Naquela noite caiu a maior chuva de granizo que Purmamarca já viu.'],
      colores: ['De manhã nós saímos. Apu não pesava nada, mas não parava de piar.', 'O Morro das Sete Cores parecia pintado à mão.'],
      salinas: ['No alto da serra, o mundo ficou branco.', 'As Grandes Salinas: um mar que secou há muito tempo e deixou o sal.'],
      tren: ['O Trem das Nuvens sobe tão alto que as nuvens passam por baixo.', 'Apu já não cabia na trouxa.'],
      puna: ['À noite, a Puna é um céu que chega até o chão.', 'Apu já era grande. E pesado.'],
      nevado: ['O Vento Branco não avisa. Ele te encontra.', 'Lá no alto estava o ninho.'],
      epilogo: ['Voltei a Purmamarca numa tarde de vento.'],
    },
    nombres: { killa: 'Killa', abuela: 'A avó', rosa: 'Dona Rosa', ceferino: 'Seu Ceferino', tomas: 'Tomás', coquena: 'Coquena', apu: 'Apu' },
    charlas: {
      inicio: [['abuela', 'Killa... está ouvindo? Alguma coisa está chorando lá fora, no curral.'], ['killa', 'Vou ver, vó.']],
      afuera: [['killa', 'Que granizo! Parecem pedras.']],
      corral: [['killa', 'O choro vem de depois do curral.']],
      pichon: [['killa', 'Um filhote! Você está gelado...'], ['killa', 'Vem, eu te levo para dentro.']],
      casa: [['abuela', 'É um filhote de condor. A tempestade o derrubou do ninho.'], ['killa', 'De que ninho?'], ['abuela', 'Lá de cima, do Nevado de Chañi. Os condores fazem ninho onde ninguém chega.'],
        ['abuela', 'Um condor que não volta para a sua montanha não aprende a voar, minha filha.'], ['killa', 'Então eu levo ele.'], ['abuela', 'É muito longe, Killa...'],
        ['abuela', '...Mas a sua mãe teria feito o mesmo.'], ['killa', 'O nome dele vai ser Apu.']],
      rosa: [['rosa', 'Aonde você vai tão cedo, Killa?'], ['killa', 'Levar o Apu para casa, no Nevado.'], ['rosa', 'Nossa, que longe! Siga as apachetas, menina. Em cada uma deixe uma pedra: a Pachamama cuida do seu caminho.'],
        ['rosa', 'E se você vir uma copla pendurada por aí, guarde. Sua avó sabe todas.']],
      rosa2: [['rosa', 'Vai, vai! E manda um abraço para os condores.']],
      piedra: [['killa', 'Essa parede é muito alta... Se eu empurrar a pedra, talvez eu alcance.']],
      mirador: [['killa', 'Olha, Apu. Sete cores. A vó diz que o sol pinta uma de cada vez, bem devagar.'], ['apu', 'Piu!']],
      cuesta: [['killa', 'Lá em cima o mundo fica branco. Vamos, Apu.']],
      ceferino: [['ceferino', 'Opa! Sozinha pelas Salinas?'], ['killa', 'Com o Apu.'], ['ceferino', 'Ah, então está bem acompanhada.'],
        ['ceferino', 'Escuta: quando ventar forte, agache-se ou fique atrás de um bloco de sal. Senão o vento te joga na salmoura.'], ['ceferino', 'E para o oeste passa o trem. Esse sobe até as nuvens.']],
      ceferino2: [['ceferino', 'Agache-se com o vento, menina. Como os juncos.']],
      aleteo: [['killa', 'É largo demais para pular...'], ['apu', 'Piu, piu!'], ['killa', 'Apu! Você bateu as asas! Você me levantou!']],
      estacion: [['killa', 'O trem! Corre, Apu!']],
      arranca: [['killa', 'Partiu! Tenho que chegar lá na frente, na locomotiva.']],
      viaducto: [['killa', 'Estamos acima das nuvens, Apu... Não olhe para baixo.']],
      tunel: [['killa', 'Um túnel! Agache-se ou entre no vagão.']],
      tomas: [['tomas', 'Menina! O que você está fazendo em cima do trem?'], ['killa', 'Vou para o Nevado de Chañi. Tenho que levar o Apu.'], ['tomas', 'E esse aí? É um condor?'], ['killa', 'Ainda não. Mas vai ser.'],
        ['tomas', 'Olha só... Eu também queria ir longe quando tinha a sua idade.'], ['tomas', 'Pegue esta lanterna. À noite, na Puna, faz falta.'], ['tomas', 'O trem para na última estação. De lá, siga a montanha.']],
      tomas2: [['tomas', 'Boa viagem, menina! E segure firme.']],
      planeo: [['killa', 'Não tem por onde descer...'], ['apu', 'Kiiá!'], ['killa', 'Apu, você está me levando! Você está enorme!']],
      llamar: [['killa', 'Uma porteira fechada... A trava está lá em cima.'], ['killa', 'Vai, Apu!']],
      puma: [['killa', 'Um puma! Corre, Apu!']],
      coquena: [['coquena', 'Ninguém caça na minha Puna.'], ['killa', 'Quem é você?'], ['coquena', 'Sou o Coquena. Cuido das vicunhas... e de quem anda à noite.'],
        ['coquena', 'Seu filhote já quase voa, Killa. Amanhã, no cume, você vai ter que soltá-lo.'], ['killa', 'E se ele não quiser ir?'], ['coquena', 'Quem a gente ama não vai embora. Sobe.']],
      coquena2: [['coquena', 'Continue subindo. O Vento Branco não espera ninguém.']],
      tormenta: [['killa', 'Aí vem o Vento Branco! Corre!']],
      escapa: [['killa', 'Passou... Apu? Você está aí?'], ['apu', 'Kiiiá!']],
      cumbre: [['killa', 'Chegamos, Apu. Esta é a sua casa.'], ['killa', 'Tome. Era da mamãe.'], ['killa', 'Dizem que vocês levam as mensagens da terra para o céu.'],
        ['killa', 'Diga a ela que estamos bem. Que a vó ainda canta as coplas dela.'], ['killa', 'Voa, Apu!']],
      epilogo: [['abuela', 'E aí? Ele chegou?'], ['killa', 'Chegou, vó.'], ['abuela', 'Olhe para cima, minha filha.'], ['killa', '...Obrigada, Apu.']],
      final: ['Dizem que o condor leva as mensagens da terra para o céu.', 'Eu sei que é verdade.'],
    },
    coplas: [
      ['Sete cores tem o morro,', 'sete penas tenho eu;', 'cada vez que o sol o pinta,', 'pinta também o peito meu.'],
      ['Pachamama, mãe terra,', 'deixo aqui minha pedrinha;', 'cuide bem do meu caminho,', 'que levo uma alma pequenininha.'],
      ['O cardão lá da quebrada', 'tem espinhos e dá flor;', 'assim é a gente do morro:', 'dura por fora e puro amor.'],
      ['Branco o sal da Puna,', 'branca a lua também;', 'se eu me perder em tanto branco,', 'que me ache o seu bem-querer.'],
      ['O vento das salinas', 'quis me levar voando;', 'eu me agachei como o junco', 'e deixei passar cantando.'],
      ['Salineiro, salineiro,', 'o que você corta com a pá?', '—Corto pedaços de um mar', 'que dormiu na planície de lá.'],
      ['Trem que sobe até as nuvens', 'com fumaça de algodão,', 'me leva até a montanha', 'e me traz de volta ao sol.'],
      ['Pelo viaduto do céu', 'passa o trem e passa o tempo;', 'quem olha lá para baixo', 'fica tonto com o vento.'],
      ['Foguista da locomotiva,', 'que sonho você joga no carvão?', '—O de chegar mais longe,', 'e quem o queima é o coração.'],
      ['À noite a Puna é céu,', 'as estrelas chegam ao pé;', 'se uma cair no chão,', 'eu guardo para depois.'],
      ['Coquena cuida das vicunhas', 'com seu poncho de velo;', 'quem caça sem licença', 'perde o caminho e o sol.'],
      ['Lanterninha da noite,', 'não se apague, por favor,', 'que o puma anda pelo morro', 'e eu tenho temor.'],
      ['O Vento Branco não avisa,', 'desce do morro a procurar;', 'abrace forte os seus,', 'que o tempo vai clarear.'],
      ['No cume do Nevado', 'o sol aparece primeiro;', 'por isso nascem os condores', 'onde se toca o céu.'],
      ['Condor, condor que vai embora', 'voando para o Nevado,', 'leva este recadinho', 'a quem está do outro lado.'],
    ],
    creditos: ['KUNTUR', 'Um jogo de papel, feito à mão', 'História, desenhos, música e código: Claude, para o Nuevo General de Juegos', 'Inspirado em Purmamarca, nas Grandes Salinas, no Trem das Nuvens, na Puna e no Nevado de Chañi (Jujuy e Salta, Argentina)', 'As coplas são inventadas, ao estilo das da Quebrada', 'Obrigado por jogar'],
  },
};
export const IDIOMAS = [['es', 'Español'], ['en', 'English'], ['pt', 'Português']];
let actual = 'es';
export const Idioma = {
  get actual() { return actual; },
  poner(l) { if (TEXTOS[l]) { actual = l; try { localStorage.setItem('kuntur:idioma', l); } catch (_) {} document.documentElement.lang = l; } },
  guardado() { try { return localStorage.getItem('kuntur:idioma'); } catch (_) { return null; } },
  delNavegador() { const n = (navigator.language || 'es').slice(0, 2).toLowerCase(); return TEXTOS[n] ? n : n === 'gl' ? 'es' : 'en'; },
};
export const T = () => TEXTOS[actual] || TEXTOS.es;
export function tr(k, ...a) { const v = (T().ui[k] != null ? T().ui[k] : TEXTOS.es.ui[k]) || k; return a.length ? v.replace(/\{(\d)\}/g, (_, i) => a[+i]) : v; }
