// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.SceneManagement
{
    [System.Serializable]
    public partial struct LoadSceneParameters
    {
        public global::UnityEngine.SceneManagement.LoadSceneMode m_LoadSceneMode;
        public global::UnityEngine.SceneManagement.LocalPhysicsMode m_LocalPhysicsMode;
    }
}
