// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.SceneManagement
{
    public enum LoadSceneMode : int
    {
        Single = 0,
        Additive = 1,
    }
}
