// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.SceneManagement
{
    [System.Flags]
    public enum LocalPhysicsMode : int
    {
        None = 0,
        Physics2D = 1,
        Physics3D = 2,
    }
}
