// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.SceneManagement
{
    public partial class SceneManager
    {
        public static global::UnityEngine.SceneManagement.Scene LoadScene(string sceneName, global::UnityEngine.SceneManagement.LoadSceneParameters parameters) { global::Porteo.Falta.Llamada("UnityEngine.SceneManagement.SceneManager::LoadScene"); return default; }
        public static global::UnityEngine.SceneManagement.Scene LoadScene(int sceneBuildIndex, global::UnityEngine.SceneManagement.LoadSceneParameters parameters) { global::Porteo.Falta.Llamada("UnityEngine.SceneManagement.SceneManager::LoadScene"); return default; }
        public static global::UnityEngine.AsyncOperation LoadSceneAsync(int sceneBuildIndex) { global::Porteo.Falta.Llamada("UnityEngine.SceneManagement.SceneManager::LoadSceneAsync"); return default; }
        public static global::UnityEngine.AsyncOperation LoadSceneAsync(int sceneBuildIndex, global::UnityEngine.SceneManagement.LoadSceneParameters parameters) { global::Porteo.Falta.Llamada("UnityEngine.SceneManagement.SceneManager::LoadSceneAsync"); return default; }
        public static global::UnityEngine.AsyncOperation LoadSceneAsync(string sceneName, global::UnityEngine.SceneManagement.LoadSceneParameters parameters) { global::Porteo.Falta.Llamada("UnityEngine.SceneManagement.SceneManager::LoadSceneAsync"); return default; }
    }
}
