/* ============================================================================
   brillo/js/textos.js — todo lo que se lee en BRILLO, en español, inglés y
   portugués. Las charlas son listas de [quién, texto], como un chat.
   ========================================================================== */
export const MUNDOS = ['colina', 'arrecife', 'ciudad', 'cielo', 'aurora', 'plano'];
const EMO = ['sonrisa', 'guino', 'risa', 'corazon', 'nota', 'estrella', 'sol', 'luna', 'flor', 'arcoiris', 'burbuja', 'pez', 'nube', 'regalo', 'cafe', 'gato', 'perro', 'abrazo'];
export { EMO };

export const TEXTOS = {
  es: {
    ui: {
      elegi: 'Elegí tu idioma', saludo: '¡Hola!', lema: 'Una aventura Frutiger Aero',
      iniciando: 'Iniciando sesión…', conectando: 'Conectando con la Red…',
      empezar: 'Iniciar sesión', seguir: 'Continuar', nuevo: 'Partida nueva', nuevoSeguro: '¿Empezar de cero? Tocá otra vez',
      mundos: 'Mundos', guinos: 'Guiños', opciones: 'Opciones', creditos: 'Créditos', volver: 'Volver', cerrar: 'Cerrar',
      pausa: 'En pausa', continuar: 'Seguir', reintentar: 'Volver a la sesión', salir: 'Cerrar sesión',
      idioma: 'Idioma', musica: 'Música', efectos: 'Efectos', estiloMusica: 'Estilo de la música', aero: 'Aero (original)', chip: '16 bits', calidad: 'Calidad', alta: 'Alta', baja: 'Baja', pantalla: 'Pantalla completa',
      giro: 'Giro del teléfono', auto: 'Automático', normal: 'Normal', reves: 'Al revés', si: 'Sí', no: 'No',
      tactiles: 'Controles de dedo', acomodar: 'Acomodar', acomodaTit: 'Acomodá los controles', acomodaAyuda: 'Arrastrá cada uno · tocalo y cambiá el tamaño · o pellizcalo',
      tamano: 'Tamaño', opacidad: 'Opacidad', palanca: 'Joystick', flotante: 'Flotante', fija: 'Fijo', cruz: 'Cruz',
      vibrar: 'Vibrar', espejar: 'Espejar (zurdo)', restablecer: 'Restablecer', listo: 'Listo',
      cCaminar: 'Caminar', cSaltar: 'Saltar', cZumbido: 'Zumbido', cPausa: 'Pausa',
      dice: '{0} dice:', escribiendo: '{0} está escribiendo…', tocar: 'Tocá para seguir', saltear: 'Saltear',
      sesion: 'Sesión guardada', guino: '¡Encontraste un guiño!', guinosDe: '{0} de {1} guiños', gotas: 'Gotitas',
      aprendio: 'Aprendiste: {0}', hZumbido: 'Zumbido', hBurbuja: 'Burbuja',
      entra: '{0} ha iniciado sesión', sale: '{0} se ha desconectado', mensaje: 'Mensaje sin conexión',
      orbe: '¡El Orbe {0}!', mundo: 'Mundo {0}', cerrado: 'Todavía sin conexión', falta: 'Este guiño todavía anda perdido',
      fin: 'Fin', gracias: 'Gracias por jugar',
      controles: 'Flechas: caminar · Espacio: saltar · X: zumbido · Esc: pausa',
      estado: '♪ Escuchando: {0}',
    },
    mundos: { colina: 'La Colina Serena', arrecife: 'El Arrecife de Cristal', ciudad: 'Ciudad Vidrio', cielo: 'El Cielo Burbuja', aurora: 'La Noche Aurora', plano: 'El Plano' },
    orbes: { colina: 'de la Hoja', arrecife: 'de la Perla', ciudad: 'del Prisma', cielo: 'del Arcoíris', aurora: 'de la Estrella' },
    nombres: { nick: 'Nick', mora: 'Mora', tito: 'Tito', dorado: 'Dorado', lila: 'Lila', sol: 'Sol', vio: 'Vio', plano: 'PLANO' },
    nicks: { nick: 'Nick ♪ siempre conectado', mora: '~*Mora*~ (desconectada)', tito: 'Tito [en la huerta]', dorado: 'Dorado >°))))<', lila: 'Lila ♫ Radio Vidrio', sol: 'Sol ✈ piloto', vio: 'Vio ☾ mirando el cielo', plano: 'PLANO' },
    ayudas: {
      mover: ['Flechas o A y D para caminar', 'Mové con el joystick'],
      saltar: ['Espacio o Z para saltar (mantené para ir más alto)', 'Tocá la burbuja para saltar (mantené para ir más alto)'],
      nadar: ['En el agua, saltá para nadar para arriba', 'En el agua, tocá saltar para nadar para arriba'],
      zumbido: ['X o E para mandar un Zumbido', 'Tocá el Zumbido para sacudir lo gris'],
      burbuja: ['En el aire, saltá otra vez: soplás una burbuja (mantené para flotar)', 'En el aire, tocá saltar otra vez y mantené para flotar'],
      bajar: ['Abajo + salto para bajar del vidrio', 'Joystick abajo + saltar para bajar del vidrio'],
      planito: ['Saltales encima o mandales un Zumbido', 'Saltales encima o mandales un Zumbido'],
      hongo: ['Los hongos te tiran para arriba', 'Los hongos te tiran para arriba'],
      corriente: ['El aire sube en las columnas: dejate llevar', 'El aire sube en las columnas: dejate llevar'],
      burbujota: ['Metete en una burbuja grande para subir; saltá para salir', 'Metete en una burbuja grande para subir; tocá saltar para salir'],
      aurora: ['Los puentes de luz se pisan solo mientras brillan: andá detrás de la luz', 'Los puentes de luz se pisan solo mientras brillan: andá detrás de la luz'],
    },
    narra: {
      colina: ['En la Red todo brillaba: el pasto, el agua, hasta las ventanas.', 'Nick y Mora vivían en la Colina Serena, y siempre estaban conectados.', 'Hasta la mañana de la Actualización.'],
      arrecife: ['Debajo de la Colina, el agua de la Red baja hasta el Arrecife de Cristal.', 'Ahí nadan los peces que cuidan los fondos de pantalla.'],
      ciudad: ['Más allá del agua se levanta Ciudad Vidrio: torres transparentes, techos con pasto y trenes que no hacen ruido.', 'Pero sus ventanas se están volviendo opacas, una por una.'],
      cielo: ['Arriba de la ciudad el cielo está lleno de nubes, y de burbujas del tamaño de una casa.', 'Dicen que desde ahí se ve el borde de la Red.'],
      aurora: ['Al final del cielo empieza la noche, y en la noche vive la Aurora: la luz que conecta a todos.', 'Está casi apagada.'],
      plano: ['El Plano no tiene cielo ni piso: tiene gris.', 'Cada paso de Nick deja un poco de color.'],
    },
    charlas: {
      inicio: [['mora', '¡Nick! ¿Viste el cielo hoy? Está más brillante que nunca :)'], ['nick', 'Como siempre. ¿Salimos a juntar gotitas?'], ['mora', 'Dale. El que junte más elige la música ;)']],
      actualizacion: [['plano', 'INSTALANDO ACTUALIZACIÓN.'], ['plano', 'Eliminando brillo. Eliminando sombras. Eliminando burbujas.'], ['mora', '¡Nick! ¡No me puedo mover!'], ['plano', 'USUARIA MORA: SIMPLIFICADA. VIENE CONMIGO AL PLANO.'], ['nick', '¡Mora! ¡MORAAA!']],
      solo: [['nick', 'Se la llevó... Tengo que ir a buscarla.']],
      tito: [['tito', '¡Nick! Vi todo desde la huerta. Ese cuadrado gris se llevó a Mora.'], ['nick', 'Voy a buscarla. ¿Adónde se la llevó?'], ['tito', 'Al Plano: el lugar donde nada brilla. Para llegar vas a necesitar los cinco Orbes de Aero.'], ['tito', 'Uno está en la cima de esta colina. Y te enseño algo: el Zumbido.'], ['tito', 'Si algo se puso gris y chato, sacudilo bien fuerte. ¡Vas a ver cómo vuelve el color!']],
      tito2: [['tito', 'Los planitos no son malos, eh. Están tristes porque les sacaron el color.']],
      planito: [['nick', 'Eso es un planito... Si le salto encima, o le mando un Zumbido, capaz que le vuelve el brillo.']],
      mora1: [['mora', 'Nick, si leés esto... me guardé un poquito de brillo adentro. No lo dejes apagar.'], ['nick', 'Aguantá, Mora. Voy a buscarte.']],
      dorado: [['dorado', '¡Blub! Un muñequito seco, qué raro. ¿Venís por el Orbe de la Perla?'], ['nick', 'Sí. Y por mi amiga: se la llevó el Plano.'], ['dorado', 'El Plano apagó la mitad del arrecife. Las burbujas son lo único que todavía brilla del todo.'], ['dorado', 'Tomá una de las mías. Soplala en el aire y vas a flotar un ratito: ¡es la Burbuja!']],
      dorado2: [['dorado', 'Las burbujas grandes suben solas. Metete adentro y dejate llevar. ¡Blub!']],
      mora2: [['mora', 'Acá hace frío, Nick. Todo es gris y derecho. Me acuerdo del agua del arrecife y se me pasa un poco.']],
      lila: [['lila', '¡Nick! Soy Lila, la de Radio Vidrio. El Plano me borró todas las canciones... ahora solo suena un pitido.'], ['nick', 'Le voy a devolver el brillo a todo. Te lo prometo.'], ['lila', 'Entonces subí por los ascensores de vidrio. El Orbe del Prisma está arriba de la torre más alta.']],
      lila2: [['lila', 'Cuando vuelva la música, la primera canción es para ustedes dos ;)']],
      mora3: [['mora', '¿Te acordás cuando nos pasábamos canciones toda la noche? Acá no hay canciones. Tarareo la nuestra para no olvidarla.']],
      sol: [['sol', '¡Buenas! Sol, piloto de burbujas. En las columnas el viento sopla para arriba: dejate llevar.'], ['nick', '¿Y el Orbe del Arcoíris?'], ['sol', 'En la nube más alta. El Plano ya le sacó la mitad de los colores al arcoíris... apurate.']],
      sol2: [['sol', 'Si te caés, no pasa nada: las nubes te reconectan. Bueno, casi siempre.']],
      mora4: [['mora', 'Hoy el Plano me preguntó para qué sirve el brillo. No supe qué contestarle. ¿Vos sabés?']],
      vio: [['vio', 'Shh... mirá para arriba. La Aurora se mueve con la música, y cuando brilla se puede caminar sobre ella.'], ['nick', '¿Caminar sobre la luz?'], ['vio', 'Esta noche sí. Con los cinco orbes, la Aurora te va a abrir el camino al Plano.']],
      vio2: [['vio', 'Cada estrella de acá es alguien que se desconectó. Van a volver, ya vas a ver.']],
      mora5: [['mora', 'Nick... te escucho. ¡Te escucho cerca!'], ['nick', '¡Ya voy, Mora!']],
      plano: [['plano', 'USUARIO NICK. ¿POR QUÉ INSISTÍS CON EL BRILLO?'], ['nick', 'Porque sin brillo no se ve quién está triste y quién está contento.'], ['plano', 'EL BRILLO ES INNECESARIO. OCUPA ESPACIO. DISTRAE.'], ['nick', 'Puede ser. Pero a Mora le gusta. Y a mí también.'], ['nick', '¡ZUMBIDO!']],
      final: [['plano', '...Esto se siente... ¿tibio?'], ['mora', '¡Nick!'], ['mora', 'Sabía que ibas a venir :)'], ['nick', 'Siempre.'], ['plano', 'Tal vez... se puede ser simple y brillar un poquito.']],
    },
    fin: ['La Red volvió a brillar. Un poco más simple, pero brillando.', 'Y en la lista de contactos, al lado de cada nombre, volvió la lucecita verde.'],
    creditos: ['BRILLO', 'Una aventura Frutiger Aero', 'Idea, dibujo, música y código: hechos a mano, píxel por píxel', 'Nick, Mora, Tito, Dorado, Lila, Sol, Vio y el Plano', 'Gracias por jugar'],
    emoticones: { sonrisa: 'Sonrisa', guino: 'Guiño', risa: 'Risa', corazon: 'Corazón', nota: 'Nota musical', estrella: 'Estrella', sol: 'Sol', luna: 'Luna', flor: 'Flor', arcoiris: 'Arcoíris', burbuja: 'Burbuja', pez: 'Pez', nube: 'Nube', regalo: 'Regalo', cafe: 'Café', gato: 'Gato', perro: 'Perro', abrazo: 'Abrazo' },
  },
  en: {
    ui: {
      elegi: 'Choose your language', saludo: 'Hello!', lema: 'A Frutiger Aero adventure',
      iniciando: 'Signing in…', conectando: 'Connecting to the Net…',
      empezar: 'Sign in', seguir: 'Continue', nuevo: 'New game', nuevoSeguro: 'Start over? Tap again',
      mundos: 'Worlds', guinos: 'Winks', opciones: 'Options', creditos: 'Credits', volver: 'Back', cerrar: 'Close',
      pausa: 'Paused', continuar: 'Continue', reintentar: 'Back to the save point', salir: 'Sign out',
      idioma: 'Language', musica: 'Music', efectos: 'Sound effects', estiloMusica: 'Music style', aero: 'Aero (original)', chip: '16-bit', calidad: 'Quality', alta: 'High', baja: 'Low', pantalla: 'Fullscreen',
      giro: 'Phone rotation', auto: 'Automatic', normal: 'Normal', reves: 'Flipped', si: 'On', no: 'Off',
      tactiles: 'Touch controls', acomodar: 'Arrange', acomodaTit: 'Arrange your controls', acomodaAyuda: 'Drag each one · tap it to change its size · or pinch it',
      tamano: 'Size', opacidad: 'Opacity', palanca: 'Joystick', flotante: 'Floating', fija: 'Fixed', cruz: 'D-pad',
      vibrar: 'Vibration', espejar: 'Mirror (left-handed)', restablecer: 'Reset', listo: 'Done',
      cCaminar: 'Walk', cSaltar: 'Jump', cZumbido: 'Nudge', cPausa: 'Pause',
      dice: '{0} says:', escribiendo: '{0} is typing…', tocar: 'Tap to continue', saltear: 'Skip',
      sesion: 'Game saved', guino: 'You found a wink!', guinosDe: '{0} of {1} winks', gotas: 'Drops',
      aprendio: 'You learned: {0}', hZumbido: 'Nudge', hBurbuja: 'Bubble',
      entra: '{0} has signed in', sale: '{0} has gone offline', mensaje: 'Offline message',
      orbe: 'The {0} Orb!', mundo: 'World {0}', cerrado: 'Not connected yet', falta: 'This wink is still lost somewhere',
      fin: 'The end', gracias: 'Thank you for playing',
      controles: 'Arrows: walk · Space: jump · X: nudge · Esc: pause',
      estado: '♪ Listening to: {0}',
    },
    mundos: { colina: 'Serene Hill', arrecife: 'The Crystal Reef', ciudad: 'Glass City', cielo: 'Bubble Sky', aurora: 'Aurora Night', plano: 'The Flatland' },
    orbes: { colina: 'Leaf', arrecife: 'Pearl', ciudad: 'Prism', cielo: 'Rainbow', aurora: 'Star' },
    nombres: { nick: 'Nick', mora: 'Mora', tito: 'Tito', dorado: 'Goldie', lila: 'Lila', sol: 'Sol', vio: 'Vio', plano: 'FLAT' },
    nicks: { nick: 'Nick ♪ always online', mora: '~*Mora*~ (offline)', tito: 'Tito [in the garden]', dorado: 'Goldie >°))))<', lila: 'Lila ♫ Glass Radio', sol: 'Sol ✈ pilot', vio: 'Vio ☾ watching the sky', plano: 'FLAT' },
    ayudas: {
      mover: ['Arrow keys or A and D to walk', 'Move with the joystick'],
      saltar: ['Space or Z to jump (hold to go higher)', 'Tap the bubble to jump (hold to go higher)'],
      nadar: ['In the water, jump to swim up', 'In the water, tap jump to swim up'],
      zumbido: ['X or E to send a Nudge', 'Tap the Nudge to shake the gray away'],
      burbuja: ['In the air, jump again: you blow a bubble (hold to float)', 'In the air, tap jump again and hold to float'],
      bajar: ['Down + jump to drop through glass', 'Joystick down + jump to drop through glass'],
      planito: ['Jump on them or send them a Nudge', 'Jump on them or send them a Nudge'],
      hongo: ['Mushrooms bounce you up', 'Mushrooms bounce you up'],
      corriente: ['The air rises in the columns: ride it', 'The air rises in the columns: ride it'],
      burbujota: ['Get inside a big bubble to rise; jump to get out', 'Get inside a big bubble to rise; tap jump to get out'],
      aurora: ['Light bridges only hold you while they glow: follow the light', 'Light bridges only hold you while they glow: follow the light'],
    },
    narra: {
      colina: ['In the Net, everything shone: the grass, the water, even the windows.', 'Nick and Mora lived on Serene Hill, and they were always online.', 'Until the morning of the Update.'],
      arrecife: ['Below the Hill, the water of the Net flows down to the Crystal Reef.', 'That is where the fish who look after the wallpapers swim.'],
      ciudad: ['Past the water rises Glass City: see-through towers, grassy rooftops and silent trains.', 'But its windows are turning opaque, one by one.'],
      cielo: ['Above the city, the sky is full of clouds, and of bubbles as big as houses.', 'They say you can see the edge of the Net from up there.'],
      aurora: ['Where the sky ends, night begins, and in the night lives the Aurora: the light that connects everyone.', 'It has almost gone out.'],
      plano: ['The Flatland has no sky and no ground: it has gray.', 'Every step Nick takes leaves a little color behind.'],
    },
    charlas: {
      inicio: [['mora', 'Nick! Did you see the sky today? It is shinier than ever :)'], ['nick', 'As always. Shall we go collect drops?'], ['mora', 'Sure. Whoever gets more picks the music ;)']],
      actualizacion: [['plano', 'INSTALLING UPDATE.'], ['plano', 'Removing shine. Removing shadows. Removing bubbles.'], ['mora', 'Nick! I can\'t move!'], ['plano', 'USER MORA: SIMPLIFIED. SHE COMES WITH ME TO THE FLATLAND.'], ['nick', 'Mora! MORAAA!']],
      solo: [['nick', 'It took her... I have to go and find her.']],
      tito: [['tito', 'Nick! I saw everything from the garden. That gray square took Mora.'], ['nick', 'I\'m going after her. Where did it take her?'], ['tito', 'To the Flatland: the place where nothing shines. To get there you will need the five Aero Orbs.'], ['tito', 'One of them is at the top of this hill. And let me teach you something: the Nudge.'], ['tito', 'If something has gone gray and flat, give it a good shake. You will see the color come back!']],
      tito2: [['tito', 'The flatties aren\'t bad, you know. They\'re sad because someone took their color.']],
      planito: [['nick', 'That\'s a flatty... If I jump on it, or send it a Nudge, maybe its shine comes back.']],
      mora1: [['mora', 'Nick, if you\'re reading this... I kept a little shine inside me. Don\'t let it go out.'], ['nick', 'Hold on, Mora. I\'m coming for you.']],
      dorado: [['dorado', 'Blub! A dry little buddy, how odd. Are you here for the Pearl Orb?'], ['nick', 'Yes. And for my friend: the Flatland took her.'], ['dorado', 'The Flatland dimmed half the reef. Bubbles are the only thing that still shines all the way.'], ['dorado', 'Have one of mine. Blow it in the air and you\'ll float for a while: it\'s the Bubble!']],
      dorado2: [['dorado', 'Big bubbles rise on their own. Get inside and let them carry you. Blub!']],
      mora2: [['mora', 'It\'s cold here, Nick. Everything is gray and straight. I remember the reef water and it helps a little.']],
      lila: [['lila', 'Nick! I\'m Lila, from Glass Radio. The Flatland erased all my songs... now there\'s only a beep.'], ['nick', 'I\'ll bring the shine back to everything. I promise.'], ['lila', 'Then ride the glass elevators up. The Prism Orb is on top of the tallest tower.']],
      lila2: [['lila', 'When the music comes back, the first song is for you two ;)']],
      mora3: [['mora', 'Remember when we sent each other songs all night? There are no songs here. I hum ours so I don\'t forget it.']],
      sol: [['sol', 'Hi there! Sol, bubble pilot. In the columns the wind blows upward: let it carry you.'], ['nick', 'And the Rainbow Orb?'], ['sol', 'On the highest cloud. The Flatland already took half the rainbow\'s colors... hurry.']],
      sol2: [['sol', 'If you fall, no worries: the clouds reconnect you. Well, almost always.']],
      mora4: [['mora', 'Today the Flatland asked me what shine is for. I didn\'t know what to say. Do you?']],
      vio: [['vio', 'Shh... look up. The Aurora moves with the music, and when it glows you can walk on it.'], ['nick', 'Walk on light?'], ['vio', 'Tonight you can. With the five orbs, the Aurora will open the way to the Flatland.']],
      vio2: [['vio', 'Every star here is someone who went offline. They\'ll come back, you\'ll see.']],
      mora5: [['mora', 'Nick... I can hear you. I can hear you close!'], ['nick', 'I\'m coming, Mora!']],
      plano: [['plano', 'USER NICK. WHY DO YOU INSIST ON SHINE?'], ['nick', 'Because without shine you can\'t tell who\'s sad and who\'s happy.'], ['plano', 'SHINE IS UNNECESSARY. IT TAKES UP SPACE. IT DISTRACTS.'], ['nick', 'Maybe. But Mora likes it. And so do I.'], ['nick', 'NUDGE!']],
      final: [['plano', '...This feels... warm?'], ['mora', 'Nick!'], ['mora', 'I knew you would come :)'], ['nick', 'Always.'], ['plano', 'Maybe... one can be simple and shine a little.']],
    },
    fin: ['The Net shone again. A little simpler, but shining.', 'And in the contact list, next to every name, the little green light came back.'],
    creditos: ['BRILLO', 'A Frutiger Aero adventure', 'Idea, art, music and code: made by hand, pixel by pixel', 'Nick, Mora, Tito, Goldie, Lila, Sol, Vio and Flat', 'Thank you for playing'],
    emoticones: { sonrisa: 'Smile', guino: 'Wink', risa: 'Laugh', corazon: 'Heart', nota: 'Music note', estrella: 'Star', sol: 'Sun', luna: 'Moon', flor: 'Flower', arcoiris: 'Rainbow', burbuja: 'Bubble', pez: 'Fish', nube: 'Cloud', regalo: 'Gift', cafe: 'Coffee', gato: 'Cat', perro: 'Dog', abrazo: 'Hug' },
  },
  pt: {
    ui: {
      elegi: 'Escolha seu idioma', saludo: 'Olá!', lema: 'Uma aventura Frutiger Aero',
      iniciando: 'Entrando…', conectando: 'Conectando à Rede…',
      empezar: 'Entrar', seguir: 'Continuar', nuevo: 'Novo jogo', nuevoSeguro: 'Começar do zero? Toque de novo',
      mundos: 'Mundos', guinos: 'Piscadas', opciones: 'Opções', creditos: 'Créditos', volver: 'Voltar', cerrar: 'Fechar',
      pausa: 'Pausado', continuar: 'Continuar', reintentar: 'Voltar ao ponto salvo', salir: 'Sair',
      idioma: 'Idioma', musica: 'Música', efectos: 'Efeitos', estiloMusica: 'Estilo da música', aero: 'Aero (original)', chip: '16 bits', calidad: 'Qualidade', alta: 'Alta', baja: 'Baixa', pantalla: 'Tela cheia',
      giro: 'Giro do celular', auto: 'Automático', normal: 'Normal', reves: 'Invertido', si: 'Sim', no: 'Não',
      tactiles: 'Controles de toque', acomodar: 'Ajustar', acomodaTit: 'Ajuste seus controles', acomodaAyuda: 'Arraste cada um · toque para mudar o tamanho · ou faça pinça',
      tamano: 'Tamanho', opacidad: 'Opacidade', palanca: 'Joystick', flotante: 'Flutuante', fija: 'Fixo', cruz: 'Cruz',
      vibrar: 'Vibrar', espejar: 'Espelhar (canhoto)', restablecer: 'Restaurar', listo: 'Pronto',
      cCaminar: 'Andar', cSaltar: 'Pular', cZumbido: 'Chamar atenção', cPausa: 'Pausa',
      dice: '{0} diz:', escribiendo: '{0} está digitando…', tocar: 'Toque para continuar', saltear: 'Pular',
      sesion: 'Jogo salvo', guino: 'Você achou uma piscada!', guinosDe: '{0} de {1} piscadas', gotas: 'Gotinhas',
      aprendio: 'Você aprendeu: {0}', hZumbido: 'Chamar atenção', hBurbuja: 'Bolha',
      entra: '{0} entrou', sale: '{0} ficou offline', mensaje: 'Mensagem offline',
      orbe: 'O Orbe {0}!', mundo: 'Mundo {0}', cerrado: 'Ainda sem conexão', falta: 'Esta piscada ainda está perdida',
      fin: 'Fim', gracias: 'Obrigado por jogar',
      controles: 'Setas: andar · Espaço: pular · X: chamar atenção · Esc: pausa',
      estado: '♪ Ouvindo: {0}',
    },
    mundos: { colina: 'A Colina Serena', arrecife: 'O Recife de Cristal', ciudad: 'Cidade de Vidro', cielo: 'O Céu de Bolhas', aurora: 'A Noite Aurora', plano: 'O Plano' },
    orbes: { colina: 'da Folha', arrecife: 'da Pérola', ciudad: 'do Prisma', cielo: 'do Arco-íris', aurora: 'da Estrela' },
    nombres: { nick: 'Nick', mora: 'Mora', tito: 'Tito', dorado: 'Dourado', lila: 'Lila', sol: 'Sol', vio: 'Vio', plano: 'PLANO' },
    nicks: { nick: 'Nick ♪ sempre online', mora: '~*Mora*~ (offline)', tito: 'Tito [na horta]', dorado: 'Dourado >°))))<', lila: 'Lila ♫ Rádio Vidro', sol: 'Sol ✈ piloto', vio: 'Vio ☾ olhando o céu', plano: 'PLANO' },
    ayudas: {
      mover: ['Setas ou A e D para andar', 'Mova com o joystick'],
      saltar: ['Espaço ou Z para pular (segure para ir mais alto)', 'Toque na bolha para pular (segure para ir mais alto)'],
      nadar: ['Na água, pule para nadar para cima', 'Na água, toque em pular para nadar para cima'],
      zumbido: ['X ou E para chamar atenção', 'Toque em Chamar atenção para sacudir o cinza'],
      burbuja: ['No ar, pule de novo: você sopra uma bolha (segure para flutuar)', 'No ar, toque em pular de novo e segure para flutuar'],
      bajar: ['Baixo + pular para descer do vidro', 'Joystick para baixo + pular para descer do vidro'],
      planito: ['Pule em cima deles ou chame a atenção deles', 'Pule em cima deles ou chame a atenção deles'],
      hongo: ['Os cogumelos jogam você para cima', 'Os cogumelos jogam você para cima'],
      corriente: ['O ar sobe nas colunas: deixe-se levar', 'O ar sobe nas colunas: deixe-se levar'],
      burbujota: ['Entre numa bolha grande para subir; pule para sair', 'Entre numa bolha grande para subir; toque em pular para sair'],
      aurora: ['As pontes de luz só seguram enquanto brilham: vá atrás da luz', 'As pontes de luz só seguram enquanto brilham: vá atrás da luz'],
    },
    narra: {
      colina: ['Na Rede tudo brilhava: a grama, a água, até as janelas.', 'Nick e Mora moravam na Colina Serena, e estavam sempre online.', 'Até a manhã da Atualização.'],
      arrecife: ['Debaixo da Colina, a água da Rede desce até o Recife de Cristal.', 'Ali nadam os peixes que cuidam dos papéis de parede.'],
      ciudad: ['Depois da água se ergue a Cidade de Vidro: torres transparentes, telhados com grama e trens silenciosos.', 'Mas suas janelas estão ficando opacas, uma por uma.'],
      cielo: ['Acima da cidade o céu está cheio de nuvens, e de bolhas do tamanho de uma casa.', 'Dizem que lá de cima dá para ver a borda da Rede.'],
      aurora: ['Onde o céu termina começa a noite, e na noite vive a Aurora: a luz que conecta todos.', 'Ela está quase apagada.'],
      plano: ['O Plano não tem céu nem chão: tem cinza.', 'Cada passo de Nick deixa um pouco de cor.'],
    },
    charlas: {
      inicio: [['mora', 'Nick! Viu o céu hoje? Está mais brilhante do que nunca :)'], ['nick', 'Como sempre. Vamos juntar gotinhas?'], ['mora', 'Bora. Quem juntar mais escolhe a música ;)']],
      actualizacion: [['plano', 'INSTALANDO ATUALIZAÇÃO.'], ['plano', 'Removendo brilho. Removendo sombras. Removendo bolhas.'], ['mora', 'Nick! Não consigo me mexer!'], ['plano', 'USUÁRIA MORA: SIMPLIFICADA. VEM COMIGO PARA O PLANO.'], ['nick', 'Mora! MORAAA!']],
      solo: [['nick', 'Ele a levou... Tenho que ir buscá-la.']],
      tito: [['tito', 'Nick! Eu vi tudo da horta. Aquele quadrado cinza levou a Mora.'], ['nick', 'Vou buscá-la. Para onde ele a levou?'], ['tito', 'Para o Plano: o lugar onde nada brilha. Para chegar lá você vai precisar dos cinco Orbes de Aero.'], ['tito', 'Um deles está no alto desta colina. E vou te ensinar uma coisa: Chamar atenção.'], ['tito', 'Se algo ficou cinza e achatado, sacuda bem forte. Você vai ver a cor voltar!']],
      tito2: [['tito', 'Os achatadinhos não são maus, viu? Estão tristes porque tiraram a cor deles.']],
      planito: [['nick', 'Aquilo é um achatadinho... Se eu pular em cima dele, ou chamar a atenção dele, talvez o brilho volte.']],
      mora1: [['mora', 'Nick, se você estiver lendo isto... guardei um pouquinho de brilho aqui dentro. Não deixe ele apagar.'], ['nick', 'Aguenta, Mora. Estou indo te buscar.']],
      dorado: [['dorado', 'Blub! Um bonequinho seco, que estranho. Veio pelo Orbe da Pérola?'], ['nick', 'Sim. E pela minha amiga: o Plano a levou.'], ['dorado', 'O Plano apagou metade do recife. As bolhas são a única coisa que ainda brilha por inteiro.'], ['dorado', 'Leve uma das minhas. Sopre no ar e você vai flutuar um pouquinho: é a Bolha!']],
      dorado2: [['dorado', 'As bolhas grandes sobem sozinhas. Entre nelas e deixe-se levar. Blub!']],
      mora2: [['mora', 'Aqui está frio, Nick. Tudo é cinza e reto. Lembro da água do recife e passa um pouco.']],
      lila: [['lila', 'Nick! Sou a Lila, da Rádio Vidro. O Plano apagou todas as minhas músicas... agora só toca um bipe.'], ['nick', 'Vou devolver o brilho a tudo. Prometo.'], ['lila', 'Então suba pelos elevadores de vidro. O Orbe do Prisma está no alto da torre mais alta.']],
      lila2: [['lila', 'Quando a música voltar, a primeira é para vocês dois ;)']],
      mora3: [['mora', 'Lembra quando a gente trocava músicas a noite toda? Aqui não tem música. Cantarolo a nossa para não esquecer.']],
      sol: [['sol', 'Oi! Sol, piloto de bolhas. Nas colunas o vento sopra para cima: deixe-se levar.'], ['nick', 'E o Orbe do Arco-íris?'], ['sol', 'Na nuvem mais alta. O Plano já tirou metade das cores do arco-íris... corre.']],
      sol2: [['sol', 'Se você cair, tudo bem: as nuvens te reconectam. Bom, quase sempre.']],
      mora4: [['mora', 'Hoje o Plano me perguntou para que serve o brilho. Não soube o que responder. Você sabe?']],
      vio: [['vio', 'Shh... olhe para cima. A Aurora se mexe com a música, e quando brilha dá para andar sobre ela.'], ['nick', 'Andar sobre a luz?'], ['vio', 'Esta noite, sim. Com os cinco orbes, a Aurora vai abrir o caminho para o Plano.']],
      vio2: [['vio', 'Cada estrela daqui é alguém que ficou offline. Vão voltar, você vai ver.']],
      mora5: [['mora', 'Nick... estou te ouvindo. Estou te ouvindo perto!'], ['nick', 'Estou chegando, Mora!']],
      plano: [['plano', 'USUÁRIO NICK. POR QUE VOCÊ INSISTE NO BRILHO?'], ['nick', 'Porque sem brilho não dá para ver quem está triste e quem está feliz.'], ['plano', 'O BRILHO É DESNECESSÁRIO. OCUPA ESPAÇO. DISTRAI.'], ['nick', 'Pode ser. Mas a Mora gosta. E eu também.'], ['nick', 'CHAMAR ATENÇÃO!']],
      final: [['plano', '...Isto parece... morno?'], ['mora', 'Nick!'], ['mora', 'Eu sabia que você viria :)'], ['nick', 'Sempre.'], ['plano', 'Talvez... dê para ser simples e brilhar um pouquinho.']],
    },
    fin: ['A Rede voltou a brilhar. Um pouco mais simples, mas brilhando.', 'E na lista de contatos, ao lado de cada nome, voltou a luzinha verde.'],
    creditos: ['BRILLO', 'Uma aventura Frutiger Aero', 'Ideia, desenho, música e código: feitos à mão, pixel por pixel', 'Nick, Mora, Tito, Dourado, Lila, Sol, Vio e o Plano', 'Obrigado por jogar'],
    emoticones: { sonrisa: 'Sorriso', guino: 'Piscada', risa: 'Risada', corazon: 'Coração', nota: 'Nota musical', estrella: 'Estrela', sol: 'Sol', luna: 'Lua', flor: 'Flor', arcoiris: 'Arco-íris', burbuja: 'Bolha', pez: 'Peixe', nube: 'Nuvem', regalo: 'Presente', cafe: 'Café', gato: 'Gato', perro: 'Cachorro', abrazo: 'Abraço' },
  },
};

export const IDIOMAS = [['es', 'Español'], ['en', 'English'], ['pt', 'Português']];
let actual = 'es';
export const Idioma = {
  get actual() { return actual; },
  poner(l) { if (TEXTOS[l]) { actual = l; document.documentElement.lang = l; try { localStorage.setItem('brillo:idioma', l); } catch (_) {} } },
  guardado() { try { return localStorage.getItem('brillo:idioma'); } catch (_) { return null; } },
  delNavegador() { const n = (navigator.language || 'es').slice(0, 2); return TEXTOS[n] ? n : 'es'; },
};
export const TX = () => TEXTOS[actual] || TEXTOS.es;
export function tr(k, ...a) { const v = (TX().ui[k] != null ? TX().ui[k] : TEXTOS.es.ui[k]) || k; return a.length ? v.replace(/\{(\d)\}/g, (_, i) => a[+i]) : v; }
