// <auto-generated> porteo: generar (el IL pide estos tipos por UnityEngine.UnityAnalyticsModule; están en UnityEngine.CoreModule)</auto-generated>
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Analytics.Analytics))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::UnityEngine.Analytics.AnalyticsResult))]
