// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Analytics
{
    public static partial class Analytics
    {
        public static global::UnityEngine.Analytics.AnalyticsResult CustomEvent(string customEventName) { global::Porteo.Falta.Llamada("UnityEngine.Analytics.Analytics::CustomEvent"); return default; }
        public static global::UnityEngine.Analytics.AnalyticsResult CustomEvent(string customEventName, global::UnityEngine.Vector3 position) { global::Porteo.Falta.Llamada("UnityEngine.Analytics.Analytics::CustomEvent"); return default; }
        public static global::UnityEngine.Analytics.AnalyticsResult CustomEvent(string customEventName, global::System.Collections.Generic.IDictionary<string, object> eventData) { global::Porteo.Falta.Llamada("UnityEngine.Analytics.Analytics::CustomEvent"); return default; }
    }
}
