// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Experimental.Rendering
{
    public partial interface IRenderPipeline : global::System.IDisposable
    {
        bool disposed { get; }
        void Render(global::UnityEngine.Experimental.Rendering.ScriptableRenderContext renderContext, global::UnityEngine.Camera[] cameras);
    }
}
