// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Experimental.Rendering
{
    public abstract partial class RenderPipeline : global::UnityEngine.Experimental.Rendering.IRenderPipeline, global::System.IDisposable
    {
        public bool disposed { get { global::Porteo.Falta.Llamada("UnityEngine.Experimental.Rendering.RenderPipeline::disposed"); return default; } }
        public static event global::System.Action<global::UnityEngine.Camera[]> beginFrameRendering { add { global::Porteo.Falta.Llamada("UnityEngine.Experimental.Rendering.RenderPipeline::beginFrameRendering+"); } remove { } }
        public virtual void Render(global::UnityEngine.Experimental.Rendering.ScriptableRenderContext renderContext, global::UnityEngine.Camera[] cameras) { global::Porteo.Falta.Llamada("UnityEngine.Experimental.Rendering.RenderPipeline::Render"); }
        public virtual void Dispose() { global::Porteo.Falta.Llamada("UnityEngine.Experimental.Rendering.RenderPipeline::Dispose"); }
    }
}
