// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Experimental.Rendering
{
    public partial struct ScriptableRenderContext
    {
        public global::System.IntPtr m_Ptr;
    }
}
