// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Tilemaps
{
    public sealed partial class TilemapRenderer : global::UnityEngine.Renderer
    {
    }
}
