// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Events
{
    public partial class UnityEvent<T0, T1, T2>
    {
        protected override global::System.Reflection.MethodInfo FindMethod_Impl(string name, global::System.Type targetObjType) { global::Porteo.Falta.Llamada("UnityEngine.Events.UnityEvent`3::FindMethod_Impl"); return default; }
    }
}
