// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.Events
{
    public abstract partial class UnityEventBase
    {
        protected abstract global::System.Reflection.MethodInfo FindMethod_Impl(string name, global::System.Type targetObjType);
        public static global::System.Reflection.MethodInfo GetValidMethodInfo(global::System.Type objectType, string functionName, global::System.Type[] argumentTypes) { global::Porteo.Falta.Llamada("UnityEngine.Events.UnityEventBase::GetValidMethodInfo"); return default; }
    }
}
