/* ============================================================================
   luz-mala/js/textos.js — lo que se dice, en español, inglés y portugués
   (de Brasil). En el monte chaqueño, a la luz que va y viene de noche por el
   campo le dicen la luz mala. Esta vez la luz mala es una luciérnaga que baja
   a prender los faroles de un quebracho que se apaga por dentro.
   Las charlas cambian con el avance: 0 al empezar, 1 con el Torito vencido,
   2 con la Viuda vencida. Quién dice cada línea está en QUIEN_HABLA; el texto,
   en cada idioma, en el mismo orden.
   ========================================================================== */

const QUIEN_HABLA = {
  mamboreta: [['mamboreta', 'mamboreta', 'chispa', 'mamboreta', 'mamboreta'], ['mamboreta', 'mamboreta', 'mamboreta'], ['mamboreta', 'mamboreta', 'mamboreta']],
  vaquita: [['vaquita', 'vaquita', 'vaquita'], ['vaquita', 'vaquita'], ['vaquita', 'vaquita']],
  canasto: [['canasto']],
  bolita: [['bolita', 'bolita', 'bolita'], ['bolita'], ['bolita']],
};

const TX_LM = {
  es: {
    ui: {
      continuar: 'Continuar', nueva: 'Nueva partida', nuevaSeguro: '¿Seguro? Se borra la otra', opciones: 'Opciones', creditos: 'Créditos',
      volver: 'Volver', seguir: 'Seguir', mapa: 'Mapa', salirTitulo: 'Volver al título', pausa: 'PAUSA',
      idioma: 'Idioma', musica: 'Música', efectos: 'Efectos', temblor: 'Temblor', velocidad: 'Velocidad', invencible: 'Invencible', si: 'Sí', no: 'No',
      ayudas: 'Velocidad e invencible son ayudas: el quebracho se puede recorrer igual.',
      elegiIdioma: 'Elegí tu idioma', lema1: 'Una luciérnaga, un quebracho', lema2: 'y la luz que se apagó',
      hablar: 'Hablar', descansar: 'Descansar', descansaste: 'Descansaste · la partida se guardó', recuperaste: 'Recuperaste {0} de ámbar',
      pistaP1: 'Arriba para hablar con los del pueblo', pistaR1: 'Golpear junta luz · mantené curar para curarte',
      teApagaste: 'TE APAGASTE', tuLuz: 'Tu luz quedó donde caíste',
      tenes: 'Tenés {0} de ámbar', yaEsTuyo: 'Ya es tuyo', chau: 'Chau, don', noAlcanza: 'No te alcanza el ámbar', tienda: 'El canasto',
      elQuebracho: 'EL QUEBRACHO', leyendaMapa: 'Celeste: hongo · rojo: jefe', fin: 'FIN', tiempoAmbar: 'Tiempo {0} · ámbar {1}', tocaVolver: 'Tocá para volver',
      pausaTxt: '{0} · ámbar {1} · {2}', habilidades: 'Lo que llevás', nada: 'Todavía nada',
      teclado: 'Teclado: flechas o WASD · Z salta · X golpea · C aleteo · V (mantener) cura · M mapa · Esc pausa',
      mando: 'Mando: A salta · X golpea · B aleteo · Y (mantener) cura · Select mapa',
      toque: 'Toque: el pulgar izquierdo mueve · a la derecha salto, golpe, aleteo y curar · arriba habla y descansa',
      seguir2: 'Tocá o apretá para seguir',
    },
    intro: [
      'En el monte chaqueño hay un quebracho tan viejo que adentro tiene un pueblo.',
      'Los bichos del quebracho vivían de tres faroles: uno en las raíces, uno en la telaraña y uno en el corazón.',
      'Una noche se apagaron los tres. Y en la oscuridad empezó a verse una luz sola, que iba y venía.',
      'La llamaron la luz mala.',
      'Esa luz era yo.',
    ],
    nombres: { chispa: 'Chispa', mamboreta: 'El Mamboretá', vaquita: 'Vaquita', canasto: 'Don Canasto', bolita: 'Bolita' },
    charlas: {
      mamboreta: [
        ['No te acerques tanto, nena. Dicen que la luz mala trae desgracia.', '...Aunque de cerca parecés una luciérnaga nomás.', 'Me llamo Chispa. Vengo a prender los faroles.',
          'Se apagaron cuando la Reina de la Marabunta se metió en el corazón del quebracho. Sin faroles, el árbol se seca.',
          'El primero está abajo, en las raíces. Lo cuida el Torito. Cuando baja la cabeza, embiste: saltalo.'],
        ['Se prendió el farol de las raíces. Lo vi desde acá: el hongal volvió a brillar.',
          'Te quedó el aleteo del Torito en las alas. Con eso se cruza el túnel de las espinas, abajo a la derecha del hongal.',
          'Más abajo está la telaraña. La Viuda no deja pasar a nadie.'],
        ['Dos faroles. En el pueblo ya no te dicen luz mala: te dicen Chispa.', 'La resina de la Viuda se te pegó en las patas. Ahora te podés agarrar de las paredes.',
          'Queda el corazón. La Reina no lo va a soltar fácil. Cuando apague la luz, la tuya alcanza.'],
      ],
      vaquita: [
        ['¿Vos sos la luz mala? Mi abuela dice que si te veo tengo que rezar.', 'Pero sos chiquita. ¿Me dejás tocar tu luz?', '...Está tibia.'],
        ['¡Te vi volver! Les dije a todos que la luz mala era buena.', 'Nadie me creyó. Pero el farol se prendió igual.'],
        ['Mi abuela ahora te deja un platito de rocío en la puerta.', 'Cuando sea grande quiero brillar como vos.'],
      ],
      canasto: [['Pase, pase. En el canasto tengo de todo... si trae ámbar.']],
      bolita: [
        ['Yo me hago bolita cuando tengo miedo. Últimamente vivo hecho bolita.', 'Si te perdés, en la pausa está el mapa. Yo lo voy dibujando por donde vas.',
          'Los hongos que brillan son para descansar: sentate y tu luz se acuerda de ahí.'],
        ['En el hongal hay una pared que suena a hueco, arriba a la izquierda. Yo la escuché, pero me dio miedo.'],
        ['En los hilos, a la izquierda de todo, brilla algo. Se llega desde el tablón chiquito.'],
      ],
    },
    jefes: {
      torito: { nombre: 'EL TORITO', sub: 'Guardián de las raíces' },
      viuda: { nombre: 'LA VIUDA', sub: 'La que teje en la oscuridad' },
      reina: { nombre: 'LA REINA DE LA MARABUNTA', sub: 'La que apagó el corazón' },
    },
    hallazgos: {
      aleteo: ['ALETEO', 'Con las alas salís disparada para adelante. En el aire, una vez por salto.'],
      resina: ['RESINA', 'Cayendo contra una pared te deslizás despacio. Saltá para rebotar y subir.'],
      chispaExtra: ['UNA CHISPA MÁS', 'Una luz de más: aguantás un golpe más.'],
      farol_raices: ['SE PRENDIÓ EL FAROL', 'Las raíces vuelven a tener luz.'],
      farol_tela: ['SE PRENDIÓ EL FAROL', 'La telaraña vuelve a tener luz.'],
      farol_hormiguero: ['SE PRENDIÓ EL FAROL MADRE', 'El corazón del quebracho vuelve a tener luz.'],
    },
    tienda: {
      iman: ['Pelusa de cardo', 'El ámbar suelto viene solo desde más lejos.'],
      cura: ['Rocío de la mañana', 'Te curás más rápido.'],
      espina: ['Espina de quebracho', 'Más dura que la de vinal: pega más fuerte.'],
      corazon: ['Corazón de ámbar', 'Una chispa más de vida.'],
    },
    zonas: { pueblo: 'EL PUEBLO', raices: 'LAS RAÍCES', tela: 'LA TELARAÑA', hormiguero: 'EL HORMIGUERO' },
    salas: { P1: 'La plaza', R1: 'La bajada', R2: 'El hongal', A1: 'La cueva del Torito', T1: 'Los hilos', A2: 'La tela de la Viuda', H1: 'El pique', H2: 'El río de ámbar', A3: 'El corazón del quebracho' },
    final: ['El corazón del quebracho volvió a latir.', 'Esa noche, en el pueblo, nadie se escondió de la luz.',
      'Desde entonces, en el monte, cuando alguien ve una luz que va y viene, no se persigna.', 'La saluda.'],
    creditos: ['Un juego hecho con código: cada píxel está dibujado y cada nota está sintetizada. No hay una sola imagen ni un solo archivo de audio.',
      'El quebracho se comprobó con un resolvedor que usa la misma física del juego: se puede recorrer entero y lo cerrado está cerrado.',
      'Para los bichos del monte chaqueño.'],
  },

  en: {
    ui: {
      continuar: 'Continue', nueva: 'New game', nuevaSeguro: 'Sure? The other one gets erased', opciones: 'Options', creditos: 'Credits',
      volver: 'Back', seguir: 'Resume', mapa: 'Map', salirTitulo: 'Back to title', pausa: 'PAUSED',
      idioma: 'Language', musica: 'Music', efectos: 'Sound', temblor: 'Shake', velocidad: 'Speed', invencible: 'Invincible', si: 'Yes', no: 'No',
      ayudas: 'Speed and invincible are assists: the whole tree can still be explored.',
      elegiIdioma: 'Choose your language', lema1: 'A firefly, a quebracho tree', lema2: 'and the light that went out',
      hablar: 'Talk', descansar: 'Rest', descansaste: 'You rested · the game was saved', recuperaste: 'You recovered {0} amber',
      pistaP1: 'Press up to talk to the villagers', pistaR1: 'Striking gathers light · hold heal to heal',
      teApagaste: 'YOUR LIGHT WENT OUT', tuLuz: 'Your light stayed where you fell',
      tenes: 'You have {0} amber', yaEsTuyo: 'Already yours', chau: 'Goodbye', noAlcanza: 'Not enough amber', tienda: 'The basket',
      elQuebracho: 'THE QUEBRACHO', leyendaMapa: 'Cyan: mushroom · red: boss', fin: 'THE END', tiempoAmbar: 'Time {0} · amber {1}', tocaVolver: 'Tap to return',
      pausaTxt: '{0} · amber {1} · {2}', habilidades: 'What you carry', nada: 'Nothing yet',
      teclado: 'Keyboard: arrows or WASD · Z jumps · X strikes · C flutter · V (hold) heals · M map · Esc pause',
      mando: 'Gamepad: A jumps · X strikes · B flutter · Y (hold) heals · Select map',
      toque: 'Touch: the left thumb moves · on the right, jump, strike, flutter and heal · up talks and rests',
      seguir2: 'Tap or press to continue',
    },
    intro: [
      'In the Chaco forest there is a quebracho tree so old that a whole village lives inside it.',
      'The bugs of the quebracho lived by three lanterns: one in the roots, one in the web and one in the heart.',
      'One night all three went out. And in the dark a lone light began to appear, drifting back and forth.',
      'They called it the luz mala, the evil light.',
      'That light was me.',
    ],
    nombres: { chispa: 'Chispa', mamboreta: 'The Mamboretá', vaquita: 'Vaquita', canasto: 'Don Canasto', bolita: 'Bolita' },
    charlas: {
      mamboreta: [
        ["Don't come so close, child. They say the luz mala brings bad luck.", '...Although up close you just look like a firefly.', "My name is Chispa. I've come to light the lanterns.",
          'They went out when the Marabunta Queen crept into the heart of the quebracho. Without lanterns, the tree dries up.',
          'The first one is down below, in the roots. The Torito guards it. When he lowers his head, he charges: jump over him.'],
        ['The lantern in the roots is lit. I saw it from here: the mushroom grove is glowing again.',
          "The Torito's flutter stayed in your wings. With it you can cross the tunnel of thorns, down to the right of the mushroom grove.",
          "Further down is the web. The Widow doesn't let anyone through."],
        ["Two lanterns. In the village they don't call you luz mala anymore: they call you Chispa.", "The Widow's resin stuck to your legs. Now you can cling to the walls.",
          "The heart remains. The Queen won't let go of it easily. When she puts out the light, yours will be enough."],
      ],
      vaquita: [
        ['Are you the luz mala? My grandma says if I see you I have to pray.', "But you're tiny. Can I touch your light?", "...It's warm."],
        ['I saw you come back! I told everyone the luz mala was good.', 'Nobody believed me. But the lantern lit up anyway.'],
        ['Now my grandma leaves a little dish of dew by the door for you.', 'When I grow up I want to shine like you.'],
      ],
      canasto: [['Come in, come in. I have everything in my basket... if you bring amber.']],
      bolita: [
        ['I curl up into a ball when I get scared. Lately I live curled up.', 'If you get lost, the map is in the pause menu. I draw it wherever you go.',
          'The glowing mushrooms are for resting: sit down and your light will remember that spot.'],
        ["In the mushroom grove there's a wall that sounds hollow, up on the left. I heard it, but I got scared."],
        ['In the threads, all the way to the left, something is shining. You can reach it from the little plank.'],
      ],
    },
    jefes: {
      torito: { nombre: 'THE TORITO', sub: 'Guardian of the roots' },
      viuda: { nombre: 'THE WIDOW', sub: 'She who weaves in the dark' },
      reina: { nombre: 'THE MARABUNTA QUEEN', sub: 'She who put out the heart' },
    },
    hallazgos: {
      aleteo: ['FLUTTER', 'Your wings launch you forward. In the air, once per jump.'],
      resina: ['RESIN', 'Falling against a wall, you slide down slowly. Jump to bounce off and climb.'],
      chispaExtra: ['ONE MORE SPARK', 'An extra light: you can take one more hit.'],
      farol_raices: ['THE LANTERN IS LIT', 'The roots have light again.'],
      farol_tela: ['THE LANTERN IS LIT', 'The web has light again.'],
      farol_hormiguero: ['THE MOTHER LANTERN IS LIT', 'The heart of the quebracho has light again.'],
    },
    tienda: {
      iman: ['Thistledown', 'Loose amber comes to you from farther away.'],
      cura: ['Morning dew', 'You heal faster.'],
      espina: ['Quebracho thorn', 'Harder than vinal: it strikes harder.'],
      corazon: ['Amber heart', 'One more spark of life.'],
    },
    zonas: { pueblo: 'THE VILLAGE', raices: 'THE ROOTS', tela: 'THE WEB', hormiguero: 'THE ANTHILL' },
    salas: { P1: 'The square', R1: 'The descent', R2: 'The mushroom grove', A1: "The Torito's cave", T1: 'The threads', A2: "The Widow's web", H1: 'The shaft', H2: 'The amber river', A3: 'The heart of the quebracho' },
    final: ['The heart of the quebracho began to beat again.', 'That night, in the village, nobody hid from the light.',
      'Ever since, in the forest, when someone sees a light drifting back and forth, they do not cross themselves.', 'They wave to it.'],
    creditos: ['A game made of code: every pixel is drawn and every note is synthesized. There is not a single image or audio file.',
      'The quebracho was checked by a solver that uses the same physics as the game: it can be explored end to end, and what is locked stays locked.',
      'For the bugs of the Chaco forest.'],
  },

  pt: {
    ui: {
      continuar: 'Continuar', nueva: 'Novo jogo', nuevaSeguro: 'Certeza? O outro será apagado', opciones: 'Opções', creditos: 'Créditos',
      volver: 'Voltar', seguir: 'Continuar', mapa: 'Mapa', salirTitulo: 'Voltar ao título', pausa: 'PAUSA',
      idioma: 'Idioma', musica: 'Música', efectos: 'Efeitos', temblor: 'Tremor', velocidad: 'Velocidade', invencible: 'Invencível', si: 'Sim', no: 'Não',
      ayudas: 'Velocidade e invencível são ajudas: dá para percorrer a árvore mesmo assim.',
      elegiIdioma: 'Escolha seu idioma', lema1: 'Um vaga-lume, um quebracho', lema2: 'e a luz que se apagou',
      hablar: 'Falar', descansar: 'Descansar', descansaste: 'Você descansou · o jogo foi salvo', recuperaste: 'Você recuperou {0} de âmbar',
      pistaP1: 'Para cima para falar com o povo', pistaR1: 'Golpear junta luz · segure curar para se curar',
      teApagaste: 'SUA LUZ SE APAGOU', tuLuz: 'Sua luz ficou onde você caiu',
      tenes: 'Você tem {0} de âmbar', yaEsTuyo: 'Já é seu', chau: 'Tchau', noAlcanza: 'Âmbar insuficiente', tienda: 'O cesto',
      elQuebracho: 'O QUEBRACHO', leyendaMapa: 'Ciano: cogumelo · vermelho: chefe', fin: 'FIM', tiempoAmbar: 'Tempo {0} · âmbar {1}', tocaVolver: 'Toque para voltar',
      pausaTxt: '{0} · âmbar {1} · {2}', habilidades: 'O que você leva', nada: 'Nada ainda',
      teclado: 'Teclado: setas ou WASD · Z pula · X golpeia · C adejo · V (segurar) cura · M mapa · Esc pausa',
      mando: 'Controle: A pula · X golpeia · B adejo · Y (segurar) cura · Select mapa',
      toque: 'Toque: o polegar esquerdo move · à direita, pulo, golpe, adejo e curar · para cima fala e descansa',
      seguir2: 'Toque ou aperte para seguir',
    },
    intro: [
      'No mato do Chaco existe um quebracho tão velho que dentro dele vive um povoado.',
      'Os bichos do quebracho viviam de três lanternas: uma nas raízes, uma na teia e uma no coração.',
      'Uma noite, as três se apagaram. E na escuridão começou a aparecer uma luz sozinha, que ia e vinha.',
      'Chamaram essa luz de luz mala, a luz maldita.',
      'Essa luz era eu.',
    ],
    nombres: { chispa: 'Chispa', mamboreta: 'O Mamboretá', vaquita: 'Vaquita', canasto: 'Don Canasto', bolita: 'Bolita' },
    charlas: {
      mamboreta: [
        ['Não chegue tão perto, menina. Dizem que a luz mala traz desgraça.', '...Mas de perto você parece só um vaga-lume.', 'Meu nome é Chispa. Vim acender as lanternas.',
          'Elas se apagaram quando a Rainha da Marabunta se meteu no coração do quebracho. Sem lanternas, a árvore seca.',
          'A primeira fica lá embaixo, nas raízes. O Torito cuida dela. Quando ele abaixa a cabeça, investe: pule por cima.'],
        ['A lanterna das raízes acendeu. Eu vi daqui: o cogumelal voltou a brilhar.',
          'O adejo do Torito ficou nas suas asas. Com ele dá para atravessar o túnel dos espinhos, lá embaixo à direita do cogumelal.',
          'Mais abaixo fica a teia. A Viúva não deixa ninguém passar.'],
        ['Duas lanternas. No povoado ninguém mais te chama de luz mala: te chamam de Chispa.', 'A resina da Viúva grudou nas suas patas. Agora você consegue se agarrar nas paredes.',
          'Falta o coração. A Rainha não vai soltá-lo fácil. Quando ela apagar a luz, a sua vai bastar.'],
      ],
      vaquita: [
        ['Você é a luz mala? Minha avó diz que, se eu te vir, tenho que rezar.', 'Mas você é pequenininha. Posso tocar na sua luz?', '...Está morninha.'],
        ['Eu te vi voltar! Falei pra todo mundo que a luz mala era boa.', 'Ninguém acreditou. Mas a lanterna acendeu mesmo assim.'],
        ['Agora minha avó deixa um pratinho de orvalho na porta pra você.', 'Quando eu crescer, quero brilhar como você.'],
      ],
      canasto: [['Entre, entre. No meu cesto tem de tudo... se você trouxer âmbar.']],
      bolita: [
        ['Eu viro bolinha quando fico com medo. Ultimamente vivo virado em bolinha.', 'Se você se perder, o mapa está na pausa. Eu vou desenhando por onde você passa.',
          'Os cogumelos que brilham são para descansar: sente-se e sua luz vai se lembrar dali.'],
        ['No cogumelal tem uma parede que soa oca, lá em cima à esquerda. Eu ouvi, mas fiquei com medo.'],
        ['Nos fios, lá na ponta esquerda, tem algo brilhando. Dá para chegar pela tabuinha pequena.'],
      ],
    },
    jefes: {
      torito: { nombre: 'O TORITO', sub: 'Guardião das raízes' },
      viuda: { nombre: 'A VIÚVA', sub: 'A que tece no escuro' },
      reina: { nombre: 'A RAINHA DA MARABUNTA', sub: 'A que apagou o coração' },
    },
    hallazgos: {
      aleteo: ['ADEJO', 'Com as asas você dispara para a frente. No ar, uma vez por pulo.'],
      resina: ['RESINA', 'Caindo contra uma parede, você desliza devagar. Pule para quicar e subir.'],
      chispaExtra: ['MAIS UMA FAÍSCA', 'Uma luz a mais: você aguenta mais um golpe.'],
      farol_raices: ['A LANTERNA ACENDEU', 'As raízes voltam a ter luz.'],
      farol_tela: ['A LANTERNA ACENDEU', 'A teia volta a ter luz.'],
      farol_hormiguero: ['A LANTERNA MÃE ACENDEU', 'O coração do quebracho volta a ter luz.'],
    },
    tienda: {
      iman: ['Penugem de cardo', 'O âmbar solto vem sozinho de mais longe.'],
      cura: ['Orvalho da manhã', 'Você se cura mais rápido.'],
      espina: ['Espinho de quebracho', 'Mais duro que o de vinal: bate mais forte.'],
      corazon: ['Coração de âmbar', 'Mais uma faísca de vida.'],
    },
    zonas: { pueblo: 'O POVOADO', raices: 'AS RAÍZES', tela: 'A TEIA', hormiguero: 'O FORMIGUEIRO' },
    salas: { P1: 'A praça', R1: 'A descida', R2: 'O cogumelal', A1: 'A caverna do Torito', T1: 'Os fios', A2: 'A teia da Viúva', H1: 'O poço', H2: 'O rio de âmbar', A3: 'O coração do quebracho' },
    final: ['O coração do quebracho voltou a bater.', 'Naquela noite, no povoado, ninguém se escondeu da luz.',
      'Desde então, no mato, quando alguém vê uma luz que vai e vem, não faz o sinal da cruz.', 'Acena para ela.'],
    creditos: ['Um jogo feito de código: cada pixel é desenhado e cada nota é sintetizada. Não há uma única imagem nem um único arquivo de áudio.',
      'O quebracho foi verificado por um solucionador que usa a mesma física do jogo: dá para percorrê-lo inteiro, e o que está fechado continua fechado.',
      'Para os bichos do mato chaquenho.'],
  },
};
const TX = () => TX_LM[Idioma.actual] || TX_LM.es;
const PRECIOS = { iman: 40, cura: 70, espina: 110, corazon: 140 };
const ORDEN_TIENDA = ['iman', 'cura', 'espina', 'corazon'];
