// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore
{
    public partial struct FaceInfo
    {
        public int m_FaceIndex;
        public string m_FamilyName;
        public string m_StyleName;
        public int m_PointSize;
        public float m_Scale;
        public int m_UnitsPerEM;
        public float m_LineHeight;
        public float m_AscentLine;
        public float m_CapLine;
        public float m_MeanLine;
        public float m_Baseline;
        public float m_DescentLine;
        public float m_SuperscriptOffset;
        public float m_SuperscriptSize;
        public float m_SubscriptOffset;
        public float m_SubscriptSize;
        public float m_UnderlineOffset;
        public float m_UnderlineThickness;
        public float m_StrikethroughOffset;
        public float m_StrikethroughThickness;
        public float m_TabWidth;
        public string familyName { set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::familyName="); } }
        public string styleName { set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::styleName="); } }
        public int pointSize { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::pointSize"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::pointSize="); } }
        public float scale { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::scale"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::scale="); } }
        public float lineHeight { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::lineHeight"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::lineHeight="); } }
        public float ascentLine { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::ascentLine"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::ascentLine="); } }
        public float capLine { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::capLine"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::capLine="); } }
        public float meanLine { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::meanLine"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::meanLine="); } }
        public float baseline { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::baseline"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::baseline="); } }
        public float descentLine { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::descentLine"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::descentLine="); } }
        public float superscriptOffset { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::superscriptOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::superscriptOffset="); } }
        public float superscriptSize { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::superscriptSize"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::superscriptSize="); } }
        public float subscriptOffset { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::subscriptOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::subscriptOffset="); } }
        public float subscriptSize { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::subscriptSize"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::subscriptSize="); } }
        public float underlineOffset { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::underlineOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::underlineOffset="); } }
        public float underlineThickness { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::underlineThickness"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::underlineThickness="); } }
        public float strikethroughOffset { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::strikethroughOffset"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::strikethroughOffset="); } }
        public float strikethroughThickness { set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::strikethroughThickness="); } }
        public float tabWidth { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::tabWidth"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.FaceInfo::tabWidth="); } }
    }
}
