// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore
{
    public partial struct GlyphRect : global::System.IEquatable<global::UnityEngine.TextCore.GlyphRect>
    {
        public int m_X;
        public int m_Y;
        public int m_Width;
        public int m_Height;
        public int x { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphRect::x"); return default; } }
        public int y { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphRect::y"); return default; } }
        public int width { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphRect::width"); return default; } }
        public int height { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphRect::height"); return default; } }
        public static global::UnityEngine.TextCore.GlyphRect zero { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphRect::zero"); return default; } }
        public GlyphRect(int x, int y, int width, int height) { this = default; }
        public bool Equals(global::UnityEngine.TextCore.GlyphRect other) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphRect::Equals"); return default; }
    }
}
