// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore
{
    public partial class Glyph
    {
        public uint index { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::index"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::index="); } }
        public global::UnityEngine.TextCore.GlyphMetrics metrics { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::metrics"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::metrics="); } }
        public global::UnityEngine.TextCore.GlyphRect glyphRect { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::glyphRect"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::glyphRect="); } }
        public float scale { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::scale"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::scale="); } }
        public int atlasIndex { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::atlasIndex"); return default; } set { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::atlasIndex="); } }
        public Glyph() { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::.ctor"); }
        public Glyph(uint index, global::UnityEngine.TextCore.GlyphMetrics metrics, global::UnityEngine.TextCore.GlyphRect glyphRect, float scale, int atlasIndex) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.Glyph::.ctor"); }
    }
}
