// <auto-generated> porteo: generar (esqueleto de la API de Unity que usa el juego)</auto-generated>
#pragma warning disable
namespace UnityEngine.TextCore
{
    public partial struct GlyphMetrics : global::System.IEquatable<global::UnityEngine.TextCore.GlyphMetrics>
    {
        public float m_Width;
        public float m_Height;
        public float m_HorizontalBearingX;
        public float m_HorizontalBearingY;
        public float m_HorizontalAdvance;
        public float width { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphMetrics::width"); return default; } }
        public float height { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphMetrics::height"); return default; } }
        public float horizontalBearingX { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphMetrics::horizontalBearingX"); return default; } }
        public float horizontalBearingY { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphMetrics::horizontalBearingY"); return default; } }
        public float horizontalAdvance { get { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphMetrics::horizontalAdvance"); return default; } }
        public GlyphMetrics(float width, float height, float bearingX, float bearingY, float advance) { this = default; }
        public bool Equals(global::UnityEngine.TextCore.GlyphMetrics other) { global::Porteo.Falta.Llamada("UnityEngine.TextCore.GlyphMetrics::Equals"); return default; }
    }
}
